QtTreePropertyBrowser Class Reference
The QtTreePropertyBrowser class provides QTreeWidget based property browser.
#include <qttreepropertybrowser.h>
Public Types
enum ResizeMode { Interactive,
Stretch,
Fixed,
ResizeToContents
 }
Signals
void collapsed (QtBrowserItem *item)
void expanded (QtBrowserItem *item)
Public Member Functions
QtTreePropertyBrowser (QWidget *parent=0)
~QtTreePropertyBrowser ()
int indentation () const
void setIndentation (int i)
bool rootIsDecorated () const
void setRootIsDecorated (bool show)
bool alternatingRowColors () const
void setAlternatingRowColors (bool enable)
bool isHeaderVisible () const
void setHeaderVisible (bool visible)
ResizeMode resizeMode () const
void setResizeMode (ResizeMode mode)
int splitterPosition () const
void setSplitterPosition (int position)
void setExpanded (QtBrowserItem *item, bool expanded)
bool isExpanded (QtBrowserItem *item) const
bool isItemVisible (QtBrowserItem *item) const
void setItemVisible (QtBrowserItem *item, bool visible)
void setBackgroundColor (QtBrowserItem *item, const QColor &color)
QColor backgroundColor (QtBrowserItem *item) const
QColor calculatedBackgroundColor (QtBrowserItem *item) const
void setPropertiesWithoutValueMarked (bool mark)
bool propertiesWithoutValueMarked () const
void editItem (QtBrowserItem *item)
Protected Member Functions
virtual void itemInserted (QtBrowserItem *item, QtBrowserItem *afterItem)
virtual void itemRemoved (QtBrowserItem *item)
virtual void itemChanged (QtBrowserItem *item)
Properties
int indentation
indentation of the items in the tree view.
bool rootIsDecorated
whether to show controls for expanding and collapsing root items.
bool alternatingRowColors
whether to draw the background using alternating colors. By default this property is set to true.
bool headerVisible
whether to show the header.
ResizeMode resizeMode
the resize mode of setions in the header.
int splitterPosition
the position of the splitter between the colunms.
bool propertiesWithoutValueMarked
whether to enable or disable marking properties without value.
Additional Inherited Members
Detailed Description
A property browser is a widget that enables the user to edit a given set of properties. Each property is represented by a label specifying the property's name, and an editing widget (e.g. a line edit or a combobox) holding its value. A property can have zero or more subproperties.
QtTreePropertyBrowser provides a tree based view for all nested properties, i.e. properties that have subproperties can be in an expanded (subproperties are visible) or collapsed (subproperties are hidden) state. For example:
Use the QtAbstractPropertyBrowser API to add, insert and remove properties from an instance of the QtTreePropertyBrowser class. The properties themselves are created and managed by implementations of the QtAbstractPropertyManager class.
See also
QtGroupBoxPropertyBrowser, QtAbstractPropertyBrowser
Member Enumeration Documentation
enum QtTreePropertyBrowser::ResizeMode
The resize mode specifies the behavior of the header sections.
Interactive The user can resize the sections. The sections can also be resized programmatically using setSplitterPosition().
Fixed The user cannot resize the section. The section can only be resized programmatically using setSplitterPosition().
Stretch QHeaderView will automatically resize the section to fill the available space. The size cannot be changed by the user or programmatically.
ResizeToContents QHeaderView will automatically resize the section to its optimal size based on the contents of the entire column. The size cannot be changed by the user or programmatically.
See also
setResizeMode()
Enumerator
Interactive
Stretch
Fixed
ResizeToContents
Constructor & Destructor Documentation
QtTreePropertyBrowser::QtTreePropertyBrowser (QWidget * parent = 0)
Creates a property browser with the given parent.
References QtAbstractPropertyBrowser::currentItemChanged(), and QtTreePropertyBrowserPrivate::init().
QtTreePropertyBrowser::~QtTreePropertyBrowser ()
Destroys this property browser.
Note that the properties that were inserted into this browser are not destroyed since they may still be used in other browsers. The properties are owned by the manager that created them.
See also
QtProperty, QtAbstractPropertyManager
References indentation().
Member Function Documentation
bool QtTreePropertyBrowser::alternatingRowColors () const
Referenced by setRootIsDecorated().
QColor QtTreePropertyBrowser::backgroundColor (QtBrowserItem * item) const
Returns the item's color. If there is no color set for item it returns invalid color.
See also
calculatedBackgroundColor(), setBackgroundColor()
QColor QtTreePropertyBrowser::calculatedBackgroundColor (QtBrowserItem * item) const
Returns the item's color. If there is no color set for item it returns parent item's color (if there is no color set for parent it returns grandparent's color and so on). In case the color is not set for item and it's top level item it returns invalid color.
See also
backgroundColor(), setBackgroundColor()
References QtTreePropertyBrowserPrivate::calculatedBackgroundColor().
void QtTreePropertyBrowser::collapsed (QtBrowserItem * item) [signal]
This signal is emitted when the item is collapsed.
See also
expanded(), setExpanded()
Referenced by QtTreePropertyBrowserPrivate::slotCollapsed().
void QtTreePropertyBrowser::editItem (QtBrowserItem * item)
Sets the current item to item and opens the relevant editor for it.
References QtTreePropertyBrowserPrivate::editItem().
void QtTreePropertyBrowser::expanded (QtBrowserItem * item) [signal]
This signal is emitted when the item is expanded.
See also
collapsed(), setExpanded()
Referenced by QtTreePropertyBrowserPrivate::slotExpanded().
int QtTreePropertyBrowser::indentation () const
Referenced by ~QtTreePropertyBrowser().
bool QtTreePropertyBrowser::isExpanded (QtBrowserItem * item) const
Returns true if the item is expanded; otherwise returns false.
See also
setExpanded()
bool QtTreePropertyBrowser::isHeaderVisible () const
bool QtTreePropertyBrowser::isItemVisible (QtBrowserItem * item) const
Returns true if the item is visible; otherwise returns false.
See also
setItemVisible()
Since
4.5
void QtTreePropertyBrowser::itemChanged (QtBrowserItem * item) [protected], [virtual]
Implements QtAbstractPropertyBrowser .
References QtTreePropertyBrowserPrivate::propertyChanged().
void QtTreePropertyBrowser::itemInserted (QtBrowserItem * item, QtBrowserItem * afterItem) [protected], [virtual]
Implements QtAbstractPropertyBrowser .
References QtTreePropertyBrowserPrivate::propertyInserted().
void QtTreePropertyBrowser::itemRemoved (QtBrowserItem * item) [protected], [virtual]
Implements QtAbstractPropertyBrowser .
References QtTreePropertyBrowserPrivate::propertyRemoved().
bool QtTreePropertyBrowser::propertiesWithoutValueMarked () const
Referenced by setPropertiesWithoutValueMarked().
ResizeMode QtTreePropertyBrowser::resizeMode () const
Referenced by setHeaderVisible().
bool QtTreePropertyBrowser::rootIsDecorated () const
Referenced by setIndentation().
void QtTreePropertyBrowser::setAlternatingRowColors (bool enable)
void QtTreePropertyBrowser::setBackgroundColor (QtBrowserItem * item, const QColor & color)
Sets the item's background color to color. Note that while item's background is rendered every second row is being drawn with alternate color (which is a bit lighter than items color)
See also
backgroundColor(), calculatedBackgroundColor()
void QtTreePropertyBrowser::setExpanded (QtBrowserItem * item, bool expanded)
Sets the item to either collapse or expanded, depending on the value of expanded.
See also
isExpanded(), expanded(), collapsed()
Referenced by AxisConfWidget::addConfigurableObjects().
void QtTreePropertyBrowser::setHeaderVisible (bool visible)
References resizeMode().
void QtTreePropertyBrowser::setIndentation (int i)
References rootIsDecorated().
void QtTreePropertyBrowser::setItemVisible (QtBrowserItem * item, bool visible)
Sets the item to be visible, depending on the value of visible.
See also
isItemVisible()
Since
4.5
void QtTreePropertyBrowser::setPropertiesWithoutValueMarked (bool mark)
References propertiesWithoutValueMarked().
void QtTreePropertyBrowser::setResizeMode (QtTreePropertyBrowser::ResizeMode mode)
References Fixed, Interactive, ResizeToContents, splitterPosition(), and Stretch.
void QtTreePropertyBrowser::setRootIsDecorated (bool show)
References alternatingRowColors().
void QtTreePropertyBrowser::setSplitterPosition (int position)
int QtTreePropertyBrowser::splitterPosition () const
Referenced by setResizeMode().
Property Documentation
bool QtTreePropertyBrowser::alternatingRowColors [read], [write]
QtTreePropertyBrowser::headerVisible [read], [write]
int QtTreePropertyBrowser::indentation [read], [write]
bool QtTreePropertyBrowser::propertiesWithoutValueMarked [read], [write]
When marking is enabled the item's background is rendered in dark color and item's foreground is rendered with light color.
See also
propertiesWithoutValueMarked()
QtTreePropertyBrowser::ResizeMode QtTreePropertyBrowser::resizeMode [read], [write]
bool QtTreePropertyBrowser::rootIsDecorated [read], [write]
int QtTreePropertyBrowser::splitterPosition [read], [write]
The documentation for this class was generated from the following files:
qttreepropertybrowser.h
qttreepropertybrowser.cpp