QtCursorPropertyManager Class Reference
The QtCursorPropertyManager provides and manages QCursor properties.
#include <qtpropertymanager.h>
Public Slots
void setValue (QtProperty *property, const QCursor &val)
Signals
void valueChanged (QtProperty *property, const QCursor &val)
Public Member Functions
QtCursorPropertyManager (QObject *parent=0)
~QtCursorPropertyManager ()
QCursor value (const QtProperty *property) const
Protected Member Functions
QString valueText (const QtProperty *property) const
QIcon valueIcon (const QtProperty *property) const
virtual void initializeProperty (QtProperty *property)
virtual void uninitializeProperty (QtProperty *property)
Detailed Description
A cursor property has a current value which can be retrieved using the value() function, and set using the setValue() slot. In addition, QtCursorPropertyManager provides the valueChanged() signal which is emitted whenever a property created by this manager changes.
See also
QtAbstractPropertyManager
Constructor & Destructor Documentation
QtCursorPropertyManager::QtCursorPropertyManager (QObject * parent = 0)
Creates a manager with the given parent.
QtCursorPropertyManager::~QtCursorPropertyManager ()
Destroys this manager, and all the properties it has created.
References QtAbstractPropertyManager::clear().
Member Function Documentation
void QtCursorPropertyManager::initializeProperty (QtProperty * property) [protected], [virtual]
Implements QtAbstractPropertyManager .
References QtCursorPropertyManagerPrivate::m_values.
void QtCursorPropertyManager::setValue (QtProperty * property, const QCursor & value) [slot]
Sets the value of the given property to value.
See also
value(), valueChanged()
References QtCursorPropertyManagerPrivate::m_values, QtAbstractPropertyManager::propertyChanged(), value(), and valueChanged().
Referenced by QtCursorEditorFactoryPrivate::slotEnumChanged().
void QtCursorPropertyManager::uninitializeProperty (QtProperty * property) [protected], [virtual]
Reimplemented from QtAbstractPropertyManager .
References QtCursorPropertyManagerPrivate::m_values.
QCursor QtCursorPropertyManager::value (const QtProperty * property) const
Returns the given property's value.
If the given property is not managed by this manager, this function returns a default QCursor object.
See also
setValue()
References QtCursorPropertyManagerPrivate::m_values.
Referenced by QtCursorEditorFactory::createEditor(), and setValue().
void QtCursorPropertyManager::valueChanged (QtProperty * property, const QCursor & value) [signal]
This signal is emitted whenever a property created by this manager changes its value, passing a pointer to the property and the new value as parameters.
See also
setValue()
Referenced by setValue().
QIcon QtCursorPropertyManager::valueIcon (const QtProperty * property) const [protected], [virtual]
Reimplemented from QtAbstractPropertyManager .
References QtCursorPropertyManagerPrivate::m_values.
QString QtCursorPropertyManager::valueText (const QtProperty * property) const [protected], [virtual]
Reimplemented from QtAbstractPropertyManager .
References QtCursorPropertyManagerPrivate::m_values.
The documentation for this class was generated from the following files:
qtpropertymanager.h
qtpropertymanager.cpp