QtDatePropertyManager Class Reference
The QtDatePropertyManager provides and manages QDate properties.
#include <qtpropertymanager.h>
Public Slots
void setValue (QtProperty *property, const QDate &val)
void setMinimum (QtProperty *property, const QDate &minVal)
void setMaximum (QtProperty *property, const QDate &maxVal)
void setRange (QtProperty *property, const QDate &minVal, const QDate &maxVal)
Signals
void valueChanged (QtProperty *property, const QDate &val)
void rangeChanged (QtProperty *property, const QDate &minVal, const QDate &maxVal)
Public Member Functions
QtDatePropertyManager (QObject *parent=0)
~QtDatePropertyManager ()
QDate value (const QtProperty *property) const
QDate minimum (const QtProperty *property) const
QDate maximum (const QtProperty *property) const
Protected Member Functions
QString valueText (const QtProperty *property) const
virtual void initializeProperty (QtProperty *property)
virtual void uninitializeProperty (QtProperty *property)
Detailed Description
A date property has a current value, and a range specifying the valid dates. The range is defined by a minimum and a maximum value.
The property's values can be retrieved using the minimum(), maximum() and value() functions, and can be set using the setMinimum(), setMaximum() and setValue() slots. Alternatively, the range can be defined in one go using the setRange() slot.
In addition, QtDatePropertyManager provides the valueChanged() signal which is emitted whenever a property created by this manager changes, and the rangeChanged() signal which is emitted whenever such a property changes its range of valid dates.
See also
QtAbstractPropertyManager, QtDateEditFactory, QtDateTimePropertyManager
Constructor & Destructor Documentation
QtDatePropertyManager::QtDatePropertyManager (QObject * parent = 0)
Creates a manager with the given parent.
References QtDatePropertyManagerPrivate::m_format.
QtDatePropertyManager::~QtDatePropertyManager ()
Destroys this manager, and all the properties it has created.
References QtAbstractPropertyManager::clear().
Member Function Documentation
void QtDatePropertyManager::initializeProperty (QtProperty * property) [protected], [virtual]
Implements QtAbstractPropertyManager .
References QtDatePropertyManagerPrivate::m_values.
QDate QtDatePropertyManager::maximum (const QtProperty * property) const
Returns the given property's maximum date.
See also
minimum(), setRange()
References QtDatePropertyManagerPrivate::m_values.
Referenced by QtDateEditFactory::createEditor().
QDate QtDatePropertyManager::minimum (const QtProperty * property) const
Returns the given property's minimum date.
See also
maximum(), setRange()
References QtDatePropertyManagerPrivate::m_values.
Referenced by QtDateEditFactory::createEditor().
void QtDatePropertyManager::rangeChanged (QtProperty * property, const QDate & minimum, const QDate & maximum) [signal]
This signal is emitted whenever a property created by this manager changes its range of valid dates, passing a pointer to the property and the new minimum and maximum dates.
See also
setRange()
Referenced by setMaximum(), setMinimum(), and setRange().
void QtDatePropertyManager::setMaximum (QtProperty * property, const QDate & maxVal) [slot]
Sets the maximum value for the given property to maxVal.
When setting the maximum value, the minimum and current values are adjusted if necessary (ensuring that the range remains valid and that the current value is within in the range).
See also
maximum(), setRange()
References QtAbstractPropertyManager::propertyChanged(), rangeChanged(), and valueChanged().
void QtDatePropertyManager::setMinimum (QtProperty * property, const QDate & minVal) [slot]
Sets the minimum value for the given property to minVal.
When setting the minimum value, the maximum and current values are adjusted if necessary (ensuring that the range remains valid and that the current value is within in the range).
See also
minimum(), setRange()
References QtAbstractPropertyManager::propertyChanged(), rangeChanged(), and valueChanged().
void QtDatePropertyManager::setRange (QtProperty * property, const QDate & minimum, const QDate & maximum) [slot]
Sets the range of valid dates.
This is a convenience function defining the range of valid dates in one go; setting the minimum and maximum values for the given property with a single function call.
When setting a new date range, the current value is adjusted if necessary (ensuring that the value remains in date range).
See also
setMinimum(), setMaximum(), rangeChanged()
References QtAbstractPropertyManager::propertyChanged(), rangeChanged(), and valueChanged().
void QtDatePropertyManager::setValue (QtProperty * property, const QDate & value) [slot]
Sets the value of the given property to value.
If the specified value is not a valid date according to the given property's range, the value is adjusted to the nearest valid value within the range.
See also
value(), setRange(), valueChanged()
References QtAbstractPropertyManager::propertyChanged(), and valueChanged().
Referenced by QtDateEditFactoryPrivate::slotSetValue().
void QtDatePropertyManager::uninitializeProperty (QtProperty * property) [protected], [virtual]
Reimplemented from QtAbstractPropertyManager .
References QtDatePropertyManagerPrivate::m_values.
QDate QtDatePropertyManager::value (const QtProperty * property) const
Returns the given property's value.
If the given property is not managed by this manager, this function returns an invalid date.
See also
setValue()
References QtDatePropertyManagerPrivate::m_values.
Referenced by QtDateEditFactory::createEditor(), and QtDateEditFactoryPrivate::slotRangeChanged().
void QtDatePropertyManager::valueChanged (QtProperty * property, const QDate & value) [signal]
This signal is emitted whenever a property created by this manager changes its value, passing a pointer to the property and the new value as parameters.
See also
setValue()
Referenced by setMaximum(), setMinimum(), setRange(), and setValue().
QString QtDatePropertyManager::valueText (const QtProperty * property) const [protected], [virtual]
Reimplemented from QtAbstractPropertyManager .
References QtDatePropertyManagerPrivate::m_format, and QtDatePropertyManagerPrivate::m_values.
The documentation for this class was generated from the following files:
qtpropertymanager.h
qtpropertymanager.cpp