Data Class Reference
#include <data.h>
Public Member Functions
 Data ()
virtual ~Data ()
bool dataUnchanged () const
void cacheData ()
 Point point (int index) const
double xpos (int index)
double ypos (int index)
void remove (int index)
void calculateXBounds ()
void calculateYBounds ()
void calculateBounds ()
void markLastXDataValid (int lastValidPos)
sets the x data valid so that subsequent calls can use cached values for the position in scene coordinates.
void markLastYDataValid (bool lastValidPos)
sets the y data valid so that subsequent calls can use cached values for the position in scene coordinates.
int size () const
void setData (const QVector< double > & xData, const QVector< double > & yData)
void setData (const QVector< double > & yData)
void addPoint (double x, double y)
void addPoints (const QVector< double > & xData, const QVector< double > & yData)
QVector< double > invalidDataPoints () const
Returns a vector of double containing the abscissa values whose Y values are NaN.
void resetMaxMin ()
Public Attributes
double xMin
double xMax
double yMin
double yMax
bool xMinMaxUnset
bool yMinMaxUnset
bool scalarMode
bool xDataOrdered
bool yDataOrdered
QVector< double > xData
QVector< double > yData
Constructor & Destructor Documentation
Data()
Data::Data ()
~Data()
Data::~Data () [virtual]
Member Function Documentation
addPoint()
void Data::addPoint (double x, double y)
addPoints()
void Data::addPoints (const QVector< double > & xData, const QVector< double > & yData)
cacheData()
void Data::cacheData ()
calculateBounds()
void Data::calculateBounds ()
calculateXBounds()
void Data::calculateXBounds ()
calculateYBounds()
void Data::calculateYBounds ()
dataUnchanged()
bool Data::dataUnchanged () const
invalidDataPoints()
QVector< double > Data::invalidDataPoints () const
Returns
a vector of double with the x values associated to a NaN Y value
Referenced by DotsPainter::draw(), LinePainter::draw(), and StepsPainter::draw().
markLastXDataValid()
void Data::markLastXDataValid (int lastValidPos) [inline]
Parameters
valid true the cached data is marked as valid
valid false the cached data is marked as invalid
If data is marked as valid xpos will return the cached value of the position in scene coordinates. Otherwise, it will calculate it again using the plot rect, the axis upper and lower bound and the index of the data whose position has to be calculated.
markLastYDataValid()
void Data::markLastYDataValid (bool lastValidPos) [inline]
Parameters
valid true the cached data is marked as valid
valid false the cached data is marked as invalid
If data is marked as valid ypos will return the cached value of the position in scene coordinates. Otherwise, it will calculate it again using the plot rect, the axis upper and lower bound and the index of the data whose position has to be calculated.
point()
 Point Data::point (int index) const
remove()
void Data::remove (int index)
resetMaxMin()
void Data::resetMaxMin ()
setData() [1/2]
void Data::setData (const QVector< double > & xData, const QVector< double > & yData)
setData() [2/2]
void Data::setData (const QVector< double > & yData)
size()
int Data::size () const
Referenced by PlotSceneWidget::getClosest(), CurveItem::itemAboutToBeRemoved(), CurveItem::itemAdded(), and SceneCurve::points().
xpos()
double Data::xpos (int index)
printf(`--- using pos in index %d for X\n`, index);
else
printf(`--- must recalc X pos cuz idx %d lastValidX %d\n`, index, lastValidXPos);
References perr.
ypos()
double Data::ypos (int index)
printf(`--- using pos in index %d for Y\n`, index);
else
printf(`--- must recalc Y pos cuz idx %d lastValidX %d\n`, index, lastValidXPos);
References perr.
Member Data Documentation
scalarMode
bool Data::scalarMode
xData
QVector<double> Data::xData
Referenced by PlotSceneWidget::getClosest(), CurveItem::itemAboutToBeRemoved(), CurveItem::itemAdded(), MarkerItem::paint(), and PlotSceneWidgetSaver::save().
xDataOrdered
bool Data::xDataOrdered
xMax
double Data::xMax
Referenced by ScaleItem::setBoundsFromCurves().
xMin
double Data::xMin
Referenced by ScaleItem::setBoundsFromCurves().
xMinMaxUnset
bool Data::xMinMaxUnset
yData
QVector<double> Data::yData
Referenced by PlotSceneWidget::getClosest(), CurveItem::itemAboutToBeRemoved(), CurveItem::itemAdded(), MarkerItem::paint(), and PlotSceneWidgetSaver::save().
yDataOrdered
bool Data::yDataOrdered
yMax
double Data::yMax
Referenced by ScaleItem::setBoundsFromCurves().
yMin
double Data::yMin
Referenced by ScaleItem::setBoundsFromCurves().
yMinMaxUnset
bool Data::yMinMaxUnset
The documentation for this class was generated from the following files:
 data.h
 data.cpp
 data__bk.cpp