ScaleWidget Class Reference
A widget to configure and draw a scale external to a PlotSceneWidget or any other scroll area whose contents need a scale.
#include <scalewidget.h>
Public Types
enum Position { Left,
Right,
Top,
Bottom
 }
Public Slots
void setAutoscale (bool autoscale)
void setAutoscaleMargin (double spanPercent)
void setUpperBound (double ub)
void setLowerBound (double lb)
void setLowerBoundDateTime (const QDateTime &t)
Sets the lower bound according to a given QDateTime timestamp.
void setUpperBoundDateTime (const QDateTime &t)
Sets the upper bound according to a given QDateTime timestamp.
void setBounds (double lowerBound, double upperBound)
void setBoundsWithMargin (double lowerBound, double upperBound)
void adjustScaleBounds (double newMin, double newMax)
void scrollChanged (int value)
void scrollRangeChanged (int min, int max)
void areaChanged (const QSizeF &size)
void setInverted (bool)
void setTickLen (int len)
void setLabelDistFromTick (int d)
void setTickStepLen (double tickStepLen)
void setNumTicks (int nt)
void setAlignment (Qt::Alignment alignment)
void setMargin (double margin)
void setOriginPercentage (double percent)
void setScaleFactor (double)
void setHorizontal (bool h)
void setFormat (const QString &fmt)
void setTickDrawingInverted (bool inverted)
void setLabelRotation (double r)
QPen pen () const
void setPen (const QPen &p)
void itemAdded (const Point &pt)
void itemAboutToBeRemoved (const Point &pt)
void itemRemoved (const Point &pt)
void fullVectorUpdate ()
void minMaxChanged (ScaleOrientation::Type orientation)
void affectingBoundsPointsRemoved ()
Public Member Functions
ScaleWidget (QWidget *parent, ScaleOrientation::Type o=ScaleOrientation::Horizontal)
ScaleOrientation::Type orientation () const
Position position () const
void setPosition (Position pos)
void setOrientation (ScaleOrientation::Type o)
void setId (int id)
int id () const
double lowerBound () const
double upperBound () const
bool autoscale () const
double autoscaleMargin () const
double margin () const
bool isInverted () const
bool horizontal () const
int tickLen () const
int labelDistFromTick () const
double tickStepLen () const
double actualTickStepLen () const
int numTicks () const
double calculateNumTicks () const
double originPercentage () const
double scaleFactor () const
double labelRotation () const
virtual void canvasRectChanged (const QRectF &newRect)
virtual void plotRectChanged (const QRectF &newRect)
does nothing. We are not actually interested in the plot rect
virtual void plotAreaChanged (const QSizeF &area)
pure virtual method that needs to be reimplemented in order to be notified when the plot area changes.
virtual void scrollBarChanged (Qt::Orientation orientation, int value)
pure virtual method that needs to be reimplemented in order to be notified when the value of one of the two scrollbars changes.
virtual void plotZoomLevelChanged (int)
QString format () const
Qt::Alignment alignment () const
bool tickDrawingInverted () const
void installScaleLabelInterface (ScaleLabelInterface *)
When the scale is drawn, the value (in double format) is passed to the installed implementation of ScaleLabelInterface. The returned QString is used to draw the label corresponding to the value.
void removeScaleLabelInterface ()
void attachCurve (SceneCurve *c)
void detachCurve (SceneCurve *c)
bool isAttached (SceneCurve *c)
QList< SceneCurve * > attachedCurves () const
QString orientationShortString () const
void installScaleChangeListener (ScaleChangeListener *l)
void removeScaleChangeListener (ScaleChangeListener *l)
QDateTime lowerBoundDateTime () const
QDateTime upperBoundDateTime () const
QDateTime doubleToDateTime (double d) const
double updateStepLen ()
unused
Protected Member Functions
void paintEvent (QPaintEvent *)
virtual QSize minimumSizeHint () const
returns the minimum size hint.
int mCalculateLongestLabelWidth () const
void mNotifyBoundsChanged ()
Properties
double upperBound
double lowerBound
QDateTime lowerBoundDateTime
returns the lower bound as a QDateTime object
QDateTime upperBoundDateTime
returns the upper bound as a QDateTime object
bool autoscale
double tickStepLen
double originPercentage
double scaleFactor
double labelRotation
int tickLen
int labelDistFromTick
bool isInverted
bool horizontal
bool tickDrawingInverted
QString format
double margin
Detailed Description
Structure
The ExternalScaleWidget is a QWidget that draws a scale with ticks and numeric values. It can be horizontal or vertical. Implements AxisChangeListener in order to receive notifications when the maximum and minimum values of the scale change and PlotEventListener in order to be notified when the PlotSceneWidget area changes, for instance when the user scales the view to magnify a portion of the scene. Nonetheless, it is not essential to install an ExternalScaleWidget if you intend to use this class without a PlotSceneWidget. Actually, there are slots equivalent to the methods implemented from the AxisChangeListener and PlotEventListener interfaces. These slots are areaChanged and scrollChanged. The ExternalScaleWidget needs to know when the area of the QScrollArea contents changes and when the value of the scrollbars change, so that it can recalculate the values to display in the correct points.
Note
You can use the HorizontalScaleWidget and VerticalScaleWidget convenience classes to directly instantiate horizontal and vertical scales respectively. The Qt Desiger plugin uses those classes.
Align scales with the PlotSceneWidget or other scrolling areas
It is very important that the height of a vertical scale is equal to the height of the widget it is associated to, and that the width of a horizontal scale is equal to the widget's width. Using the Qt4 designer, just place and align the widgets, and then use a grid layout. The QGridLayout will ensure that the widgets are all scaled together.
Example
Suppose you have an image from a camera and you want to use an external scale to identify pixel positions inside the image. In this case the ExternalScaleWidget is not used in association with a PlotSceneWidget and thus we use signal/slot connections to tell the scale that the image area or the values of the scroll bars have changed.
// define the orientation of each scale widget
ui.xScale->setOrientation(ScaleOrientation::Horizontal);
ui.yScale->setOrientation(ScaleOrientation::Vertical);
//
// set the scroll area associated to each scale
// ui.image_ScrollArea is a QScrollArea (or QAbstractScrollArea)
// ui.xScale and ui.yScale are the two ExternalScaleWidget
//
connect(ui.image_ScrollArea->horizontalScrollBar(), SIGNAL(valueChanged(int)), ui.xScale,
      SLOT(scrollChanged(int)));
connect(ui.image_ScrollArea->verticalScrollBar(), SIGNAL(valueChanged(int)), ui.yScale,
      SLOT(scrollChanged(int)));
// if the size of the contents of the QScrollArea changes, then each scale must be
// notified
//
connect(myImage, SIGNAL(imageSizeChanged(QSizeF)), ui.xScale, SLOT(areaChanged(QSizeF)));
connect(myImage, SIGNAL(imageSizeChanged(QSizeF)), ui.yScale, SLOT(areaChanged(QSizeF)));
Inverted scales
The maximum must always be greater than the minimum, but if you want the scale to draw the values starting with the minimum on the rigth (for a horizontal scale) or the top (for a vertical scale), just call setInverted on the ExternalScaleWidget.
Tick drawing inverted
If a vertical scale is placed on the right of the display area, then you may want to call setTickDrawingInverted in order to place ticks before numeric values. The same goes for top placed horizontal scales.
Labels format
The format of the labels is not automatically calculated as in the ScaleItem. It is %.1f by default, and you must call the setFormat or use the format option in order to change it.
Origin position percentage
A property called originPercentage is introduced in order to tune the scale positioning. A value of 0.5 for instance tells the scale that its center of gravity should be in the middle of its length. A tick is guaranteed to be positioned at the half of the length of the scale and, according to the number of ticks, some extra empty space at the beginning or end of the scales might appear, without ticks. Actually, if used in conjunction with a PlotSceneWidget, the origin of its axes is normally placed at the center of the plot. To align the ExternalScaleWidget with the grid of the PlotSceneWidget, you should tune the originPercentage property so that its value is 0.5. The PlotSceneWidget itself has a property to change the axis origin position percentage: on the ExternalScaleWidget an equal value should be set with setOriginPercentage.
Orientation
The horizontal property is a shortcut for setOrientation. It switches a scale from the horizontal to the vertical layout, being the parameter true or false respectively.
Tick length
The tickLen property assigns a length (in pixel coordinates) to the scale ticks.
Tick step length
The tick step length is used to calculate the number of ticks on the scale and where the ticks have to be placed. The value is expressed in scale coordinates. For instance, if your scale spans from 0 to 100 and you specify a tickStepLen of 10, you will have ten ticks with ten values drawn on the widget.
Label Rotation
The labelRotation property is able to rotate the labels on the scale. Up to now, it is only possible to rotate x axis labels.
Notes on widget geometry.
Whenever one of the minimum, maximum, labelRotation, format or tickLen properties changes, the minimumSizeHint for the widget changes, and the updateGeometry() is internally called by the setter methods. In this way you can safely insert the widgets into a QLayout without worrying about geometry changes (resizes, changes in tick len or format...). The minimumSizeHint takes into account the font in use, naturally.
Example
This example shows how to use two ExternalScaleWidget scales with a PlotSceneWidget. As said before, ExternalScaleWidget implements two interfaces aimed at receive PlotSceneWidget notifications in matter of geometry change and ScaleItem notifications in matter of minimum and maximum value changes. All you need to to is to install each ExternalScaleWidget on the plot and on the scale items of the plots as in the example below.
// In this example we have a PlotSceneWidget called horProfile and a couple
// of ExternalScaleWidget scales called xScale and yScale
// take each of the ScaleItem of the PlotSceneWidget and install the scale
// as AxisChangeListener.
//
horProfile->xScaleItem()->installAxisChangeListener(xScale);
horProfile->yScaleItem()->installAxisChangeListener(yScale);
// Install the scale as PlotChangeListener into the PlotSceneWidget (horProfile)
//
horProfile->installPlotChangeListener(xScale);
horProfile->installPlotChangeListener(yScale);
// You may want to have the same tickStepLen on the plot and on the external scale.
// Supposing the plot has a tickStepLen of 50 on the x axis and 500 on the y axis,
// then:
//
xScale->setTickStepLen(50.0);
yScale->setTickStepLen(500.0);
// The PlotSceneWidget center its axes (and grid) at the center of the plot so, if
// you do not change this position, you have to tune the position of the scales
// as follows:
//
 yScale->setOriginPercentage(0.5);
 xScale->setOriginPercentage(0.5);
// For the same reason as above, if the size of the plot is less than the view size,
// the scales must be kept correctly centered:
//
xScale->setAlignment(Qt::AlignHCenter);
yScale->setAlignment(Qt::AlignVCenter);
Sample code
An example can be found inside the directory examples/externalscales directory.
See also
HorizontalScaleWidget
VerticalScaleWidget
PlotSceneWidget
ScaleItem
Personalized labels
You can implement a ScaleLabelInterface and install it on an ExternalScaleWidget. The ExternalScaleWidget will call the ScaleLabelInterface::label implementation with the value corresponding to the tick being drawn. Your ScaleLabelInterface::label implementation has to convert the raw value passed by the ExternalScaleWidget into a convenient label according to your needs. For instance, a TimeScaleLabel can be used to convert unix timestamps into a date/time string.
Member Enumeration Documentation
enum ScaleWidget::Position
Enumerator
Left
Right
Top
Bottom
Constructor & Destructor Documentation
ScaleWidget::ScaleWidget (QWidget * parent, ScaleOrientation::Type o = ScaleOrientation::Horizontal) [explicit]
References ScalePrivate::actualTickStepLen, ScalePrivate::alignment, ScalePrivate::autoscale, ScalePrivate::autoscaleMargin, Elettra::black, Bottom, ScaleOrientation::Horizontal, ScalePrivate::inverted, ScalePrivate::labelDistFromTick, ScalePrivate::labelRotation, Left, ScalePrivate::len, ScalePrivate::longestLabelWidth, ScalePrivate::margin, ScalePrivate::minMaxUnset, ScalePrivate::numTicks, ScalePrivate::offset, ScalePrivate::orientation, orientation(), ScalePrivate::originOffset, ScalePrivate::originPercentage, ScalePrivate::pen, ScalePrivate::pos, ScalePrivate::position, ScalePrivate::scaleFactor, ScalePrivate::scaleLabelInterface, setBounds(), ScalePrivate::syncAxisLabelsWithPlot, ScalePrivate::syncAxisTicksWithPlot, ScalePrivate::tickDrawingInverted, ScalePrivate::tickLen, ScalePrivate::tickStepLen, updateStepLen(), and ScaleOrientation::Vertical.
Member Function Documentation
double ScaleWidget::actualTickStepLen () const
References ScalePrivate::actualTickStepLen.
void ScaleWidget::adjustScaleBounds (double newMin, double newMax) [slot]
References ScalePrivate::autoscale, autoscale(), ScalePrivate::lowerBound, ScalePrivate::minMaxUnset, setBounds(), and ScalePrivate::upperBound.
Referenced by plotZoomLevelChanged().
void ScaleWidget::affectingBoundsPointsRemoved () [inline], [slot]
References mCalculateLongestLabelWidth(), minimumSizeHint(), mNotifyBoundsChanged(), and paintEvent().
Qt::Alignment ScaleWidget::alignment () const
References ScalePrivate::alignment, ScalePrivate::inverted, and isInverted().
Referenced by plotZoomLevelChanged(), and setAlignment().
void ScaleWidget::areaChanged (const QSizeF & size) [slot]
References ScaleOrientation::Horizontal, ScalePrivate::len, ScalePrivate::orientation, and ScaleOrientation::Vertical.
Referenced by plotAreaChanged(), and plotZoomLevelChanged().
void ScaleWidget::attachCurve (SceneCurve * c)
References ScalePrivate::curves, and installScaleChangeListener().
Referenced by ExtScalePlotSceneWidget::onDataMinMaxChanged(), and plotZoomLevelChanged().
QList< SceneCurve * > ScaleWidget::attachedCurves () const
References ScalePrivate::curves.
Referenced by ExtScalePlotSceneWidget::onDataMinMaxChanged(), plotZoomLevelChanged(), and ExtScalePlotSceneWidget::removeScale().
bool ScaleWidget::autoscale () const
Referenced by adjustScaleBounds(), and setAutoscale().
double ScaleWidget::autoscaleMargin () const
References ScalePrivate::autoscaleMargin.
double ScaleWidget::calculateNumTicks () const
References ScalePrivate::actualTickStepLen, ScalePrivate::lowerBound, ScalePrivate::numTicks, and ScalePrivate::upperBound.
Referenced by ExtScalePlotSceneWidget::onDataMinMaxChanged(), and paintEvent().
void ScaleWidget::canvasRectChanged (const QRectF & newRect) [virtual]
void ScaleWidget::detachCurve (SceneCurve * c)
References ScalePrivate::curves, and removeScaleChangeListener().
Referenced by ExtScalePlotSceneWidget::onDataMinMaxChanged(), and plotZoomLevelChanged().
QDateTime ScaleWidget::doubleToDateTime (double d) const
References ScalePrivate::lowerBound, lowerBoundDateTime(), ScalePrivate::upperBound, and upperBoundDateTime().
Referenced by plotZoomLevelChanged().
QString ScaleWidget::format () const
Referenced by mCalculateLongestLabelWidth(), paintEvent(), plotZoomLevelChanged(), and setFormat().
void ScaleWidget::fullVectorUpdate () [inline], [slot]
References minMaxChanged().
bool ScaleWidget::horizontal () const
Referenced by orientationShortString(), and setHorizontal().
int ScaleWidget::id () const
References ScalePrivate::id.
Referenced by setId().
void ScaleWidget::installScaleChangeListener (ScaleChangeListener * l)
References ScalePrivate::actualTickStepLen, ScalePrivate::autoscale, ScalePrivate::format, ScaleOrientation::Horizontal, ScalePrivate::lowerBound, orientation(), ScaleChangeListener::scaleAutoscaleChanged(), ScalePrivate::scaleChangeListeners, ScaleChangeListener::scaleLabelsFormatChanged(), ScaleChangeListener::scaleTickStepLenChanged(), ScalePrivate::upperBound, ScaleChangeListener::xScaleBoundsChanged(), and ScaleChangeListener::yScaleBoundsChanged().
Referenced by attachCurve(), and plotZoomLevelChanged().
void ScaleWidget::installScaleLabelInterface (ScaleLabelInterface * iface)
When the scale is drawn, the value (in double format) is passed to the installed implementation of ScaleLabelInterface. The returned QString is used to draw the label corresponding to the value.
Parameters
iface an implementation instance of the ScaleLabelInterface
See also
TimeScaleLabel
References ScalePrivate::scaleLabelInterface.
Referenced by plotZoomLevelChanged().
bool ScaleWidget::isAttached (SceneCurve * c)
References ScalePrivate::curves.
Referenced by ExtScalePlotSceneWidget::onDataMinMaxChanged(), and plotZoomLevelChanged().
bool ScaleWidget::isInverted () const
Referenced by alignment().
void ScaleWidget::itemAboutToBeRemoved (const Point & pt) [inline], [slot]
void ScaleWidget::itemAdded (const Point & pt) [inline], [slot]
void ScaleWidget::itemRemoved (const Point & pt) [inline], [slot]
int ScaleWidget::labelDistFromTick () const
Referenced by setMargin().
double ScaleWidget::labelRotation () const
Referenced by setLabelRotation().
double ScaleWidget::lowerBound () const
Referenced by setAutoscaleMargin(), setBounds(), and setBoundsWithMargin().
QDateTime ScaleWidget::lowerBoundDateTime () const
Referenced by doubleToDateTime(), and plotZoomLevelChanged().
double ScaleWidget::margin () const
Referenced by setLabelDistFromTick(), and setMargin().
int ScaleWidget::mCalculateLongestLabelWidth () const [protected]
References ScalePrivate::format, format(), ScaleLabelInterface::longestLabel(), ScalePrivate::lowerBound, qstoc, ScalePrivate::scaleLabelInterface, and ScalePrivate::upperBound.
Referenced by affectingBoundsPointsRemoved(), minimumSizeHint(), setBounds(), and setFormat().
QSize ScaleWidget::minimumSizeHint () const [protected], [virtual]
Must be recalculated when the min and max change or the format changes.
References ScaleOrientation::Horizontal, ScalePrivate::labelDistFromTick, ScalePrivate::labelRotation, mCalculateLongestLabelWidth(), ScalePrivate::orientation, ScalePrivate::tickLen, and ScaleOrientation::Vertical.
Referenced by affectingBoundsPointsRemoved().
void ScaleWidget::minMaxChanged (ScaleOrientation::Type orientation) [slot]
References ScalePrivate::autoscale, and ScalePrivate::orientation.
Referenced by fullVectorUpdate().
void ScaleWidget::mNotifyBoundsChanged () [protected]
References ScalePrivate::lowerBound, ScalePrivate::orientation, ScalePrivate::scaleChangeListeners, ScalePrivate::upperBound, ScaleOrientation::Vertical, ScaleChangeListener::xScaleBoundsChanged(), and ScaleChangeListener::yScaleBoundsChanged().
Referenced by affectingBoundsPointsRemoved(), setBounds(), setLowerBound(), and setUpperBound().
int ScaleWidget::numTicks () const
References ScalePrivate::numTicks.
ScaleOrientation::Type ScaleWidget::orientation () const
References ScalePrivate::orientation.
Referenced by ExtScalePlotSceneWidget::addScale(), ExtScalePlotSceneWidget::axesCount(), ExtScalePlotSceneWidget::findScales(), installScaleChangeListener(), ExtScalePlotSceneWidget::onDataMinMaxChanged(), ScaleWidget(), and setAutoscale().
QString ScaleWidget::orientationShortString () const
This method returns the orientation as `X` or `Y`
Returns
`X` if the scale is horizontal, `Y` otherwise
References horizontal().
Referenced by plotZoomLevelChanged(), and ExtScalePlotSceneWidget::removeScale().
double ScaleWidget::originPercentage () const
Referenced by setOriginPercentage().
void ScaleWidget::paintEvent (QPaintEvent * e) [protected]
References ScalePrivate::actualTickStepLen, ScalePrivate::alignment, calculateNumTicks(), ScalePrivate::curves, ScalePrivate::format, format(), ScaleOrientation::Horizontal, ScalePrivate::inverted, ScaleLabelInterface::label(), ScalePrivate::labelDistFromTick, ScalePrivate::labelRotation, ScalePrivate::len, ScalePrivate::longestLabelWidth, ScalePrivate::lowerBound, ScalePrivate::margin, ScalePrivate::offset, ScalePrivate::orientation, ScalePrivate::originPercentage, ScalePrivate::pen, qstoc, ScalePrivate::scaleFactor, ScalePrivate::scaleLabelInterface, ScalePrivate::tickDrawingInverted, ScalePrivate::tickLen, and ScalePrivate::upperBound.
Referenced by affectingBoundsPointsRemoved().
QPen ScaleWidget::pen () const [slot]
References ScalePrivate::pen.
Referenced by plotZoomLevelChanged().
void ScaleWidget::plotAreaChanged (const QSizeF & area) [virtual]
Note
The area takes into account the scaling factors currently applied to the view, i.e. m11() and m22() of the current transformation obtained by transform().
Implements PlotGeometryEventListener .
References areaChanged().
void ScaleWidget::plotRectChanged (const QRectF & r) [virtual]
Implements PlotGeometryEventListener .
virtual void ScaleWidget::plotZoomLevelChanged (int) [inline], [virtual]
Implements PlotGeometryEventListener .
References adjustScaleBounds(), alignment(), areaChanged(), attachCurve(), attachedCurves(), detachCurve(), doubleToDateTime(), format(), installScaleChangeListener(), installScaleLabelInterface(), isAttached(), lowerBoundDateTime(), orientationShortString(), pen(), removeScaleChangeListener(), removeScaleLabelInterface(), scrollChanged(), scrollRangeChanged(), setAlignment(), setAutoscale(), setAutoscaleMargin(), setBounds(), setBoundsWithMargin(), setFormat(), setHorizontal(), setInverted(), setLabelDistFromTick(), setLabelRotation(), setLowerBound(), setLowerBoundDateTime(), setMargin(), setNumTicks(), setOriginPercentage(), setPen(), setScaleFactor(), setTickDrawingInverted(), setTickLen(), setTickStepLen(), setUpperBound(), setUpperBoundDateTime(), tickDrawingInverted(), updateStepLen(), and upperBoundDateTime().
ScaleWidget::Position ScaleWidget::position () const
References ScalePrivate::position.
void ScaleWidget::removeScaleChangeListener (ScaleChangeListener * l)
References ScalePrivate::scaleChangeListeners.
Referenced by detachCurve(), and plotZoomLevelChanged().
void ScaleWidget::removeScaleLabelInterface ()
References ScalePrivate::scaleLabelInterface.
Referenced by plotZoomLevelChanged().
double ScaleWidget::scaleFactor () const
Referenced by setScaleFactor().
void ScaleWidget::scrollBarChanged (Qt::Orientation orientation, int value) [virtual]
Parameters
orientation one of the two possible Qt::Orientation values: Qt::Horizontal or Qt::Vertical
value the value of the scrollbar
Implements PlotGeometryEventListener .
References ScaleOrientation::Horizontal, ScalePrivate::orientation, scrollChanged(), and ScaleOrientation::Vertical.
void ScaleWidget::scrollChanged (int value) [slot]
References ScalePrivate::offset.
Referenced by plotZoomLevelChanged(), and scrollBarChanged().
void ScaleWidget::scrollRangeChanged (int min, int max) [slot]
Referenced by plotZoomLevelChanged().
void ScaleWidget::setAlignment (Qt::Alignment alignment) [slot]
References ScalePrivate::alignment, and alignment().
Referenced by ExtScalePlotSceneWidget::addScale(), and plotZoomLevelChanged().
void ScaleWidget::setAutoscale (bool autoscale) [slot]
References ScalePrivate::autoscale, autoscale(), orientation(), ScaleChangeListener::scaleAutoscaleChanged(), and ScalePrivate::scaleChangeListeners.
Referenced by ExtScalePlotSceneWidget::addScale(), and plotZoomLevelChanged().
void ScaleWidget::setAutoscaleMargin (double spanPercent) [slot]
References ScalePrivate::autoscaleMargin, ScalePrivate::lowerBound, lowerBound(), ScalePrivate::upperBound, and upperBound().
Referenced by plotZoomLevelChanged().
void ScaleWidget::setBounds (double lowerBound, double upperBound) [slot]
References ScalePrivate::autoscale, ScalePrivate::longestLabelWidth, ScalePrivate::lowerBound, lowerBound(), mCalculateLongestLabelWidth(), mNotifyBoundsChanged(), ScalePrivate::orientation, ScaleChangeListener::scaleAutoscaleChanged(), ScalePrivate::scaleChangeListeners, updateStepLen(), ScalePrivate::upperBound, and upperBound().
Referenced by adjustScaleBounds(), plotZoomLevelChanged(), ScaleWidget(), and setBoundsWithMargin().
void ScaleWidget::setBoundsWithMargin (double lowerBound, double upperBound) [slot]
References ScalePrivate::autoscaleMargin, lowerBound(), and setBounds().
Referenced by ExtScalePlotSceneWidget::onDataMinMaxChanged(), and plotZoomLevelChanged().
void ScaleWidget::setFormat (const QString & fmt) [slot]
References ScalePrivate::format, format(), ScalePrivate::longestLabelWidth, and mCalculateLongestLabelWidth().
Referenced by plotZoomLevelChanged().
void ScaleWidget::setHorizontal (bool h) [slot]
References ScaleOrientation::Horizontal, horizontal(), ScalePrivate::orientation, setOrientation(), and ScaleOrientation::Vertical.
Referenced by plotZoomLevelChanged().
void ScaleWidget::setId (int id)
References ScalePrivate::id, and id().
void ScaleWidget::setInverted (bool inv) [slot]
References ScalePrivate::inverted.
Referenced by plotZoomLevelChanged().
void ScaleWidget::setLabelDistFromTick (int d) [slot]
References ScalePrivate::labelDistFromTick, ScalePrivate::margin, and margin().
Referenced by plotZoomLevelChanged().
void ScaleWidget::setLabelRotation (double r) [slot]
References ScalePrivate::labelRotation, and labelRotation().
Referenced by ExtScalePlotSceneWidget::initPlot(), and plotZoomLevelChanged().
void ScaleWidget::setLowerBound (double lb) [slot]
References ScalePrivate::autoscale, ScalePrivate::lowerBound, mNotifyBoundsChanged(), ScalePrivate::orientation, ScaleChangeListener::scaleAutoscaleChanged(), ScalePrivate::scaleChangeListeners, and updateStepLen().
Referenced by plotZoomLevelChanged(), and setLowerBoundDateTime().
void ScaleWidget::setLowerBoundDateTime (const QDateTime & t) [slot]
Sets the lower bound according to a given QDateTime timestamp.
Parameters
t a QDateTime representing the lower bound of the scale.
Note
the QDateTime is converted into a double with the millisecond precision: t.toTime_t() + 0.001 * t.time().msec()
This method is useful when your scale is a time scale.
See also
TimeScaleLabel
setUpperBoundDateTime
lowerBoundDateTime
References setLowerBound().
Referenced by plotZoomLevelChanged().
void ScaleWidget::setMargin (double margin) [slot]
References ScalePrivate::labelDistFromTick, labelDistFromTick(), ScalePrivate::margin, and margin().
Referenced by ExtScalePlotSceneWidget::addScale(), and plotZoomLevelChanged().
void ScaleWidget::setNumTicks (int nt) [slot]
References ScalePrivate::numTicks.
Referenced by ExtScalePlotSceneWidget::onDataMinMaxChanged(), and plotZoomLevelChanged().
void ScaleWidget::setOrientation (ScaleOrientation::Type o)
References ScalePrivate::orientation.
Referenced by setHorizontal().
void ScaleWidget::setOriginPercentage (double percent) [slot]
References ScalePrivate::originPercentage, and originPercentage().
Referenced by plotZoomLevelChanged().
void ScaleWidget::setPen (const QPen & p) [slot]
References ScalePrivate::pen.
Referenced by plotZoomLevelChanged().
void ScaleWidget::setPosition (ScaleWidget::Position pos)
References ScalePrivate::position.
Referenced by ExtScalePlotSceneWidget::addScale().
void ScaleWidget::setScaleFactor (double f) [slot]
References ScalePrivate::scaleFactor, and scaleFactor().
Referenced by plotZoomLevelChanged().
void ScaleWidget::setTickDrawingInverted (bool inverted) [slot]
References ScalePrivate::tickDrawingInverted, and tickDrawingInverted().
Referenced by ExtScalePlotSceneWidget::addScale(), and plotZoomLevelChanged().
void ScaleWidget::setTickLen (int len) [slot]
References ScalePrivate::tickLen, tickLen(), ScalePrivate::tickStepLen, and tickStepLen().
Referenced by plotZoomLevelChanged().
void ScaleWidget::setTickStepLen (double tickStepLen) [slot]
References ScalePrivate::actualTickStepLen, ScalePrivate::tickStepLen, tickStepLen(), and updateStepLen().
Referenced by plotZoomLevelChanged().
void ScaleWidget::setUpperBound (double ub) [slot]
References ScalePrivate::autoscale, mNotifyBoundsChanged(), ScalePrivate::orientation, ScaleChangeListener::scaleAutoscaleChanged(), ScalePrivate::scaleChangeListeners, updateStepLen(), and ScalePrivate::upperBound.
Referenced by plotZoomLevelChanged(), and setUpperBoundDateTime().
void ScaleWidget::setUpperBoundDateTime (const QDateTime & t) [slot]
Sets the upper bound according to a given QDateTime timestamp.
Note
This method is useful when your scale is a time scale.
See also
setLowerBoundDateTime
lowerBoundDateTime
TimeScaleLabel
References setUpperBound().
Referenced by plotZoomLevelChanged().
bool ScaleWidget::tickDrawingInverted () const
Referenced by plotZoomLevelChanged(), and setTickDrawingInverted().
int ScaleWidget::tickLen () const
Referenced by setTickLen().
double ScaleWidget::tickStepLen () const
Referenced by setTickLen(), and setTickStepLen().
double ScaleWidget::updateStepLen ()
References ScalePrivate::actualTickStepLen, ScalePrivate::lowerBound, ScalePrivate::scaleChangeListeners, ScaleChangeListener::scaleTickStepLenChanged(), ScalePrivate::tickStepLen, and ScalePrivate::upperBound.
Referenced by plotZoomLevelChanged(), ScaleWidget(), setBounds(), setLowerBound(), setTickStepLen(), and setUpperBound().
double ScaleWidget::upperBound () const
Referenced by setAutoscaleMargin(), and setBounds().
QDateTime ScaleWidget::upperBoundDateTime () const
Referenced by doubleToDateTime(), and plotZoomLevelChanged().
Property Documentation
bool ScaleWidget::autoscale [read], [write]
QString ScaleWidget::format [read], [write]
bool ScaleWidget::horizontal [read], [write]
bool ScaleWidget::isInverted [read], [write]
int ScaleWidget::labelDistFromTick [read], [write]
double ScaleWidget::labelRotation [read], [write]
double ScaleWidget::lowerBound [read], [write]
QDateTime ScaleWidget::lowerBoundDateTime [read], [write]
Returns
the lower bound as a QDateTime object
Conversion
The decimal part of the double value representing the axis bound is used to set the milliseconds, the integer part is interpreted as a unix timestamp, i.e. the number of seconds that have passed since 1970-01-01T00:00:00, Coordinated Universal Time.
See also
setUpperBoundDateTime
setLowerBoundDateTime
upperBoundDateTime
TimeScaleLabel
double ScaleWidget::margin [read], [write]
double ScaleWidget::originPercentage [read], [write]
double ScaleWidget::scaleFactor [read], [write]
bool ScaleWidget::tickDrawingInverted [read], [write]
int ScaleWidget::tickLen [read], [write]
double ScaleWidget::tickStepLen [read], [write]
double ScaleWidget::upperBound [read], [write]
QDateTime ScaleWidget::upperBoundDateTime [read], [write]
Returns
the upper bound as a QDateTime object
See also
lowerBoundDateTime
The documentation for this class was generated from the following files:
scalewidget.h
scalewidget.cpp