QtAbstractEditorFactory< PropertyManager > Class Template Reference
The QtAbstractEditorFactory is the base template class for editor factories.
#include <qtpropertybrowser.h>
Public Member Functions
QtAbstractEditorFactory (QObject *parent)
QWidget * createEditor (QtProperty *property, QWidget *parent)
void addPropertyManager (PropertyManager *manager)
void removePropertyManager (PropertyManager *manager)
QSet< PropertyManager * > propertyManagers () const
PropertyManager * propertyManager (QtProperty *property) const
Protected Member Functions
virtual void connectPropertyManager (PropertyManager *manager)=0
virtual QWidget * createEditor (PropertyManager *manager, QtProperty *property, QWidget *parent)=0
virtual void disconnectPropertyManager (PropertyManager *manager)=0
void managerDestroyed (QObject *manager)
Friends
class QtAbstractPropertyEditor
Additional Inherited Members
Detailed Description
template<class PropertyManager>
*
class QtAbstractEditorFactory< PropertyManager >
An editor factory is a class that is able to create an editing widget of a specified type (e.g. line edits or comboboxes) for a given QtProperty object, and it is used in conjunction with the QtAbstractPropertyManager and QtAbstractPropertyBrowser classes.
Note that the QtAbstractEditorFactory functions are using the PropertyManager template argument class which can be any QtAbstractPropertyManager subclass. For example:
QtSpinBoxFactory *factory;
QSet<QtIntPropertyManager *> managers = factory->propertyManagers();
Note that QtSpinBoxFactory by definition creates editing widgets only for properties created by QtIntPropertyManager.
When using a property browser widget, the properties are created and managed by implementations of the QtAbstractPropertyManager class. To ensure that the properties' values will be displayed using suitable editing widgets, the managers are associated with objects of QtAbstractEditorFactory subclasses. The property browser will use these associations to determine which factories it should use to create the preferred editing widgets.
A QtAbstractEditorFactory object is capable of producing editors for several property managers at the same time. To create an association between this factory and a given manager, use the addPropertyManager() function. Use the removePropertyManager() function to make this factory stop producing editors for a given property manager. Use the propertyManagers() function to retrieve the set of managers currently associated with this factory.
Several ready-made implementations of the QtAbstractEditorFactory class are available:
QtCheckBoxFactory QtDateEditFactory QtDateTimeEditFactory QtDoubleSpinBoxFactory QtEnumEditorFactory QtLineEditFactory QtScrollBarFactory QtSliderFactory QtSpinBoxFactory QtTimeEditFactory QtVariantEditorFactory
When deriving from the QtAbstractEditorFactory class, several pure virtual functions must be implemented: the connectPropertyManager() function is used by the factory to connect to the given manager's signals, the createEditor() function is supposed to create an editor for the given property controlled by the given manager, and finally the disconnectPropertyManager() function is used by the factory to disconnect from the specified manager's signals.
See also
QtAbstractEditorFactoryBase, QtAbstractPropertyManager
Constructor & Destructor Documentation
template<class PropertyManager> QtAbstractEditorFactory< PropertyManager >::QtAbstractEditorFactory (QObject * parent = 0) [inline], [explicit]
Creates an editor factory with the given parent.
See also
addPropertyManager()
Member Function Documentation
template<class PropertyManager> void QtAbstractEditorFactory< PropertyManager >::addPropertyManager (PropertyManager * manager) [inline]
Adds the given manager to this factory's set of managers, making this factory produce editing widgets for properties created by the given manager.
The PropertyManager type is a template argument class, and represents the chosen QtAbstractPropertyManager subclass.
See also
propertyManagers(), removePropertyManager()
Referenced by QtVariantEditorFactory::connectPropertyManager(), QtCursorEditorFactory::QtCursorEditorFactory(), and QtAbstractPropertyBrowser::setFactoryForManager().
template<class PropertyManager> void QtAbstractEditorFactory< PropertyManager >::connectPropertyManager (PropertyManager * manager) [protected], [pure virtual]
Connects this factory to the given manager's signals. The PropertyManager type is a template argument class, and represents the chosen QtAbstractPropertyManager subclass.
This function is used internally by the addPropertyManager() function, and makes it possible to update an editing widget when the associated property's data changes. This is typically done in custom slots responding to the signals emitted by the property's manager, e.g. QtIntPropertyManager::valueChanged() and QtIntPropertyManager::rangeChanged().
See also
propertyManagers(), disconnectPropertyManager()
Implemented in QtFontEditorFactory , QtColorEditorFactory , QtCursorEditorFactory , QtEnumEditorFactory , QtCharEditorFactory , QtKeySequenceEditorFactory , QtDateTimeEditFactory , QtTimeEditFactory , QtDateEditFactory , QtLineEditFactory , QtVariantEditorFactory , QtDoubleSpinBoxFactory , QtCheckBoxFactory , QtScrollBarFactory , QtSliderFactory , and QtSpinBoxFactory .
template<class PropertyManager> QWidget * QtAbstractEditorFactory< PropertyManager >::createEditor (QtProperty * property, QWidget * parent) [inline], [virtual]
Creates an editing widget (with the given parent) for the given property.
Implements QtAbstractEditorFactoryBase .
Referenced by QtVariantEditorFactory::createEditor().
template<class PropertyManager> QWidget * QtAbstractEditorFactory< PropertyManager >::createEditor (PropertyManager * manager, QtProperty * property, QWidget * parent) [protected], [pure virtual]
Creates an editing widget with the given parent for the specified property created by the given manager. The PropertyManager type is a template argument class, and represents the chosen QtAbstractPropertyManager subclass.
This function must be implemented in derived classes: It is recommended to store a pointer to the widget and map it to the given property, since the widget must be updated whenever the associated property's data changes. This is typically done in custom slots responding to the signals emitted by the property's manager, e.g. QtIntPropertyManager::valueChanged() and QtIntPropertyManager::rangeChanged().
See also
connectPropertyManager()
Implemented in QtFontEditorFactory , QtColorEditorFactory , QtCursorEditorFactory , QtEnumEditorFactory , QtCharEditorFactory , QtKeySequenceEditorFactory , QtDateTimeEditFactory , QtTimeEditFactory , QtDateEditFactory , QtLineEditFactory , QtVariantEditorFactory , QtDoubleSpinBoxFactory , QtCheckBoxFactory , QtScrollBarFactory , QtSliderFactory , and QtSpinBoxFactory .
template<class PropertyManager> void QtAbstractEditorFactory< PropertyManager >::disconnectPropertyManager (PropertyManager * manager) [protected], [pure virtual]
Disconnects this factory from the given manager's signals. The PropertyManager type is a template argument class, and represents the chosen QtAbstractPropertyManager subclass.
This function is used internally by the removePropertyManager() function.
See also
propertyManagers(), connectPropertyManager()
Implemented in QtFontEditorFactory , QtColorEditorFactory , QtCursorEditorFactory , QtEnumEditorFactory , QtCharEditorFactory , QtKeySequenceEditorFactory , QtDateTimeEditFactory , QtTimeEditFactory , QtDateEditFactory , QtLineEditFactory , QtVariantEditorFactory , QtDoubleSpinBoxFactory , QtCheckBoxFactory , QtScrollBarFactory , QtSliderFactory , and QtSpinBoxFactory .
template<class PropertyManager> void QtAbstractEditorFactory< PropertyManager >::managerDestroyed (QObject * manager) [inline], [protected], [virtual]
Implements QtAbstractEditorFactoryBase .
template<class PropertyManager> PropertyManager * QtAbstractEditorFactory< PropertyManager >::propertyManager (QtProperty * property) const [inline]
Returns the property manager for the given property, or 0 if the given property doesn't belong to any of this factory's registered managers.
The PropertyManager type is a template argument class, and represents the chosen QtAbstractPropertyManager subclass.
See also
propertyManagers()
Referenced by QtCursorEditorFactoryPrivate::slotEnumChanged(), QtColorEditorFactoryPrivate::slotSetValue(), and QtFontEditorFactoryPrivate::slotSetValue().
template<class PropertyManager> QSet< PropertyManager * > QtAbstractEditorFactory< PropertyManager >::propertyManagers () const [inline]
Returns the factory's set of associated managers. The PropertyManager type is a template argument class, and represents the chosen QtAbstractPropertyManager subclass.
See also
addPropertyManager(), removePropertyManager()
template<class PropertyManager> void QtAbstractEditorFactory< PropertyManager >::removePropertyManager (PropertyManager * manager) [inline]
Removes the given manager from this factory's set of managers. The PropertyManager type is a template argument class, and may be any QtAbstractPropertyManager subclass.
See also
propertyManagers(), addPropertyManager()
Referenced by QtVariantEditorFactory::disconnectPropertyManager().
Friends And Related Function Documentation
template<class PropertyManager> friend class QtAbstractPropertyEditor [friend]
The documentation for this class was generated from the following files:
qtpropertybrowser.h
qtpropertybrowser.cpp