QtPropertyEditorView Class Reference
Public Member Functions
QtPropertyEditorView (QWidget *parent=0)
void setEditorPrivate (QtTreePropertyBrowserPrivate *editorPrivate)
QTreeWidgetItem * indexToItem (const QModelIndex &index) const
Protected Member Functions
void keyPressEvent (QKeyEvent *event)
void mousePressEvent (QMouseEvent *event)
void drawRow (QPainter *painter, const QStyleOptionViewItem &option, const QModelIndex &index) const
Constructor & Destructor Documentation
QtPropertyEditorView::QtPropertyEditorView (QWidget * parent = 0)
Member Function Documentation
void QtPropertyEditorView::drawRow (QPainter * painter, const QStyleOptionViewItem & option, const QModelIndex & index) const [protected]
References QtTreePropertyBrowserPrivate::calculatedBackgroundColor(), QtProperty::hasValue(), QtTreePropertyBrowserPrivate::indexToBrowserItem(), QtTreePropertyBrowserPrivate::indexToProperty(), and QtTreePropertyBrowserPrivate::markPropertiesWithoutValue().
QTreeWidgetItem* QtPropertyEditorView::indexToItem (const QModelIndex & index) const [inline]
Referenced by QtTreePropertyBrowserPrivate::indexToBrowserItem(), QtTreePropertyBrowserPrivate::indexToItem(), and QtTreePropertyBrowserPrivate::indexToProperty().
void QtPropertyEditorView::keyPressEvent (QKeyEvent * event) [protected]
References QtTreePropertyBrowserPrivate::editedItem().
void QtPropertyEditorView::mousePressEvent (QMouseEvent * event) [protected]
References QtTreePropertyBrowserPrivate::editedItem(), QtTreePropertyBrowserPrivate::hasValue(), and QtTreePropertyBrowserPrivate::markPropertiesWithoutValue().
void QtPropertyEditorView::setEditorPrivate (QtTreePropertyBrowserPrivate * editorPrivate) [inline]
Referenced by QtTreePropertyBrowserPrivate::init().
The documentation for this class was generated from the following file:
qttreepropertybrowser.cpp