QtCheckBoxFactoryPrivate Class Reference
Public Member Functions
void slotPropertyChanged (QtProperty *property, bool value)
void slotSetValue (bool value)
Additional Inherited Members
Member Function Documentation
void QtCheckBoxFactoryPrivate::slotPropertyChanged (QtProperty * property, bool value)
References QtBoolEdit::blockCheckBoxSignals(), and QtBoolEdit::setChecked().
void QtCheckBoxFactoryPrivate::slotSetValue (bool value)
References QtBoolPropertyManager::setValue().
The documentation for this class was generated from the following file:
qteditorfactory.cpp