CurveBoundsManager Class Reference
#include <curveboundsmanager.h>
Public Member Functions
CurveBoundsManager ()
void updateMinMax (const QString &curveName, ScaleOrientation::Type orientation, double min, double max)
void getXBounds (double *min, double *max, const QStringList &curveSet) const
void getYBounds (double *min, double *max, const QStringList &curveSet) const
Constructor & Destructor Documentation
CurveBoundsManager::CurveBoundsManager ()
Member Function Documentation
void CurveBoundsManager::getXBounds (double * min, double * max, const QStringList & curveSet) const
Referenced by ExtScalePlotSceneWidget::onDataMinMaxChanged().
void CurveBoundsManager::getYBounds (double * min, double * max, const QStringList & curveSet) const
Referenced by ExtScalePlotSceneWidget::onDataMinMaxChanged().
void CurveBoundsManager::updateMinMax (const QString & curveName, ScaleOrientation::Type orientation, double min, double max)
References ScaleOrientation::Horizontal.
Referenced by ExtScalePlotSceneWidget::onDataMinMaxChanged().
The documentation for this class was generated from the following files:
curveboundsmanager.h
curveboundsmanager.cpp