ScaleChangeListener Class Reference
#include <scalechangelistener.h>
Public Member Functions
ScaleChangeListener ()
virtual void xScaleBoundsChanged (double lower, double upper)=0
x axis bounds notification
virtual void yScaleBoundsChanged (double lower, double upper)=0
y axis bounds notification
virtual void scaleAutoscaleChanged (ScaleOrientation::Type o, bool autoscale)=0
x axis auto scale property change notification
virtual void scaleTickStepLenChanged (double value)=0
notifies listeners about tick step len changes.
virtual void scaleLabelsFormatChanged (const QString &newFormat)=0
when the labels format changes, labelsFormatChanged is used
Constructor & Destructor Documentation
ScaleChangeListener::ScaleChangeListener ()
Member Function Documentation
virtual void ScaleChangeListener::scaleAutoscaleChanged (ScaleOrientation::Type o, bool autoscale) [pure virtual]
Parameters
o the ScaleOrientation::Type property that helps you find out which axis (x or y) has changed its property.
autoscale true autoscale is enabled.
autoscale false autoscale is disabled.
Implemented in SceneCurve , and TargetItem .
Referenced by ScaleWidget::installScaleChangeListener(), ScaleWidget::setAutoscale(), ScaleWidget::setBounds(), ScaleWidget::setLowerBound(), and ScaleWidget::setUpperBound().
virtual void ScaleChangeListener::scaleLabelsFormatChanged (const QString & newFormat) [pure virtual]
See also
ScaleItem
Implemented in SceneCurve , and TargetItem .
Referenced by ScaleWidget::installScaleChangeListener().
virtual void ScaleChangeListener::scaleTickStepLenChanged (double value) [pure virtual]
The tick step len can be tuned by a property in a ScaleItem or let it be automatically calculated by ScaleItem.
See also
ScaleItem
Implemented in SceneCurve , and TargetItem .
Referenced by ScaleWidget::installScaleChangeListener(), and ScaleWidget::updateStepLen().
virtual void ScaleChangeListener::xScaleBoundsChanged (double lower, double upper) [pure virtual]
Parameters
lower the new lower bound
upper the new upper bound
Implemented in SceneCurve , and TargetItem .
Referenced by ScaleWidget::installScaleChangeListener(), and ScaleWidget::mNotifyBoundsChanged().
virtual void ScaleChangeListener::yScaleBoundsChanged (double lower, double upper) [pure virtual]
Parameters
lower the new lower bound
upper the new upper bound
Implemented in SceneCurve , and TargetItem .
Referenced by ScaleWidget::installScaleChangeListener(), and ScaleWidget::mNotifyBoundsChanged().
The documentation for this class was generated from the following files:
scalechangelistener.h
scalechangelistener.cpp