PropertyDialog Class Reference
#include <propertydialog.h>
Public Slots
void show ()
Public Member Functions
 PropertyDialog (PlotSceneWidget *sceneWidget)
virtual ~PropertyDialog ()
void configureTabs (const QMap< QString, QObject * > objectsMap)
void setSettingsKey (const QString &key)
Constructor & Destructor Documentation
PropertyDialog()
PropertyDialog::PropertyDialog (PlotSceneWidget * sceneWidget) [explicit]
~PropertyDialog()
PropertyDialog::~PropertyDialog () [virtual]
Member Function Documentation
configureTabs()
void PropertyDialog::configureTabs (const QMap< QString, QObject * > objectsMap) [inline]
Referenced by PlotSceneWidget::executePropertyDialog().
setSettingsKey()
void PropertyDialog::setSettingsKey (const QString & key) [inline]
Referenced by PlotSceneWidget::executePropertyDialog().
show
void PropertyDialog::show () [slot]
not working yet...
References qstoc.
Referenced by PlotSceneWidget::executePropertyDialog().
The documentation for this class was generated from the following files:
 propertydialog.h
 propertydialog.cpp