ColorListEditor Class Reference
#include <itemdelegates.h>
Public Member Functions
ColorListEditor (QWidget *widget=0)
QColor color () const
void setColor (QColor c)
Properties
QColor color
Constructor & Destructor Documentation
ColorListEditor::ColorListEditor (QWidget * widget = 0)
References color().
Member Function Documentation
QColor ColorListEditor::color () const
Referenced by ColorListEditor(), and setColor().
void ColorListEditor::setColor (QColor c)
References color().
Referenced by ComboColorDelegate::createEditor().
Property Documentation
QColor ColorListEditor::color [read], [write]
Referenced by ComboColorDelegate::setModelData().
The documentation for this class was generated from the following files:
itemdelegates.h
itemdelegates.cpp