QtBrowserItem Class Reference
The QtBrowserItem class represents a property in a property browser instance.
#include <qtpropertybrowser.h>
Public Member Functions
QtProperty * property () const
QtBrowserItem * parent () const
QList< QtBrowserItem * > children () const
QtAbstractPropertyBrowser * browser () const
Friends
class QtAbstractPropertyBrowserPrivate
Detailed Description
Browser items are created whenever a QtProperty is inserted to the property browser. A QtBrowserItem uniquely identifies a browser's item. Thus, if the same QtProperty is inserted multiple times, each occurrence gets its own unique QtBrowserItem. The items are owned by QtAbstractPropertyBrowser and automatically deleted when they are removed from the browser.
You can traverse a browser's properties by calling parent() and children(). The property and the browser associated with an item are available as property() and browser().
See also
QtAbstractPropertyBrowser, QtProperty
Member Function Documentation
QtAbstractPropertyBrowser * QtBrowserItem::browser () const
Returns the property browser which owns this item.
QList< QtBrowserItem * > QtBrowserItem::children () const
Returns the children items of this item. The properties reproduced from children items are always the same as reproduced from associated property' children, for example:
QtBrowserItem *item;
QList<QtBrowserItem *> childrenItems = item->children();
QList<QtProperty *> childrenProperties = item->property()->subProperties();
The childrenItems list represents the same list as childrenProperties.
Referenced by QtAbstractPropertyBrowserPrivate::clearIndex(), and QtAbstractPropertyBrowserPrivate::removeBrowserIndex().
QtBrowserItem * QtBrowserItem::parent () const
Returns the parent item of this item. Returns 0 if this item is associated with top-level property in item's property browser.
See also
children()
Referenced by QtTreePropertyBrowserPrivate::calculatedBackgroundColor(), QtAbstractPropertyBrowserPrivate::createBrowserIndexes(), QtGroupBoxPropertyBrowserPrivate::propertyInserted(), QtButtonPropertyBrowserPrivate::propertyInserted(), QtTreePropertyBrowserPrivate::propertyInserted(), QtAbstractPropertyBrowserPrivate::removeBrowserIndex(), and QtAbstractPropertyBrowserPrivate::removeBrowserIndexes().
QtProperty * QtBrowserItem::property () const
Returns the property which is accosiated with this item. Note that several items can be associated with the same property instance in the same property browser.
See also
QtAbstractPropertyBrowser::items()
Referenced by QtAbstractPropertyBrowserPrivate::createBrowserIndexes(), QtTreePropertyBrowserPrivate::hasValue(), QtTreePropertyBrowserPrivate::indexToProperty(), QtGroupBoxPropertyBrowserPrivate::propertyInserted(), QtButtonPropertyBrowserPrivate::propertyInserted(), QtAbstractPropertyBrowserPrivate::removeBrowserIndex(), and QtAbstractPropertyBrowserPrivate::removeBrowserIndexes().
Friends And Related Function Documentation
friend class QtAbstractPropertyBrowserPrivate [friend]
The documentation for this class was generated from the following files:
qtpropertybrowser.h
qtpropertybrowser.cpp