Point Class Reference
a point item that calculates its position in the view and simply draws a cross centered at x,y and the represented x and y values.
#include <point.h>
Public Member Functions
 Point (const PointData &data, ScaleItem *xAxis, ScaleItem *yAxis)
 Point (double x, double y)
virtual ~Point ()
double updateXPos (PlotSceneWidget *view)
double updateYPos (PlotSceneWidget *view)
QPointF updatePosition (PlotSceneWidget *view)
calculates the position in scene coordinates according to the view geometry.
QPointF pos () const
returns the position of the point in scene coordinates
const PointData & pointDataR () const
 PointData pointData () const
void setPointData (const PointData &pd)
sets the PointData associated to the XYItem.
void setPos (const QPointF & pos)
void setPos (qreal x, qreal y)
Public Attributes
double x
double y
double xpos
double ypos
Friends
class SceneCurve
Detailed Description
You must inherit from this class or install a custom ItemPainterInterface to change its drawing behaviour.
Constructor & Destructor Documentation
Point() [1/2]
Point::Point (const PointData & data, ScaleItem * xAxis, ScaleItem * yAxis) [explicit]
Point() [2/2]
Point::Point (double x, double y)
References x, and y.
~Point()
Point::~Point () [virtual]
Member Function Documentation
pointData()
 PointData Point::pointData () const
pointDataR()
const PointData & Point::pointDataR () const
pos()
QPointF Point::pos () const
Returns
the QPointF representing the item position inside the scene, in scene coordinates.
Referenced by setPos().
setPointData()
void Point::setPointData (const PointData & pd)
Sets or updates the PointData associated to the item. Remember to call calculatePosition after this call if you need to reposition the item after its data has changed.
setPos() [1/2]
void Point::setPos (const QPointF & pos)
References pos().
Referenced by updateXPos(), and updateYPos().
setPos() [2/2]
void Point::setPos (qreal x, qreal y)
References ItemPositionChangeListener::onItemPositionChanged(), x, and y.
updatePosition()
QPointF Point::updatePosition (PlotSceneWidget * view)
Updates the internal position available through the pos call.
References ItemPositionChangeListener::onItemPositionChanged(), PlotSceneWidget::plotRect(), x, and y.
updateXPos()
double Point::updateXPos (PlotSceneWidget * view)
References PlotSceneWidget::plotRect(), setPos(), and x.
updateYPos()
double Point::updateYPos (PlotSceneWidget * view)
References PlotSceneWidget::plotRect(), setPos(), and y.
Friends And Related Function Documentation
SceneCurve
friend class SceneCurve [friend]
Member Data Documentation
x
double Point::x
Referenced by Point(), setPos(), updatePosition(), and updateXPos().
xpos
double Point::xpos
y
double Point::y
Referenced by Point(), setPos(), updatePosition(), and updateYPos().
ypos
double Point::ypos
The documentation for this class was generated from the following files:
 point.h
 point.cpp