QtDoublePropertyManager Class Reference
The QtDoublePropertyManager provides and manages double properties.
#include <qtpropertymanager.h>
Public Slots
void setValue (QtProperty *property, double val)
void setMinimum (QtProperty *property, double minVal)
void setMaximum (QtProperty *property, double maxVal)
void setRange (QtProperty *property, double minVal, double maxVal)
void setSingleStep (QtProperty *property, double step)
void setDecimals (QtProperty *property, int prec)
Signals
void valueChanged (QtProperty *property, double val)
void rangeChanged (QtProperty *property, double minVal, double maxVal)
void singleStepChanged (QtProperty *property, double step)
void decimalsChanged (QtProperty *property, int prec)
Public Member Functions
QtDoublePropertyManager (QObject *parent=0)
~QtDoublePropertyManager ()
double value (const QtProperty *property) const
double minimum (const QtProperty *property) const
double maximum (const QtProperty *property) const
double singleStep (const QtProperty *property) const
int decimals (const QtProperty *property) const
Protected Member Functions
QString valueText (const QtProperty *property) const
virtual void initializeProperty (QtProperty *property)
virtual void uninitializeProperty (QtProperty *property)
Detailed Description
A double property has a current value, and a range specifying the valid values. The range is defined by a minimum and a maximum value.
The property's value and range can be retrieved using the value(), minimum() and maximum() functions, and can be set using the setValue(), setMinimum() and setMaximum() slots. Alternatively, the range can be defined in one go using the setRange() slot.
In addition, QtDoublePropertyManager provides the valueChanged() signal which is emitted whenever a property created by this manager changes, and the rangeChanged() signal which is emitted whenever such a property changes its range of valid values.
See also
QtAbstractPropertyManager, QtDoubleSpinBoxFactory
Constructor & Destructor Documentation
QtDoublePropertyManager::QtDoublePropertyManager (QObject * parent = 0)
Creates a manager with the given parent.
QtDoublePropertyManager::~QtDoublePropertyManager ()
Destroys this manager, and all the properties it has created.
References QtAbstractPropertyManager::clear().
Member Function Documentation
int QtDoublePropertyManager::decimals (const QtProperty * property) const
Returns the given property's precision, in decimals.
See also
setDecimals()
References QtDoublePropertyManagerPrivate::Data::decimals, and QtDoublePropertyManagerPrivate::m_values.
Referenced by QtDoubleSpinBoxFactory::createEditor().
void QtDoublePropertyManager::decimalsChanged (QtProperty * property, int prec) [signal]
This signal is emitted whenever a property created by this manager changes its precision of value, passing a pointer to the property and the new prec value
See also
setDecimals()
Referenced by setDecimals().
void QtDoublePropertyManager::initializeProperty (QtProperty * property) [protected], [virtual]
Implements QtAbstractPropertyManager .
References QtDoublePropertyManagerPrivate::m_values.
double QtDoublePropertyManager::maximum (const QtProperty * property) const
Returns the given property's maximum value.
See also
minimum(), setRange()
References QtDoublePropertyManagerPrivate::m_values.
Referenced by QtDoubleSpinBoxFactory::createEditor().
double QtDoublePropertyManager::minimum (const QtProperty * property) const
Returns the given property's minimum value.
See also
maximum(), setRange()
References QtDoublePropertyManagerPrivate::m_values.
Referenced by QtDoubleSpinBoxFactory::createEditor().
void QtDoublePropertyManager::rangeChanged (QtProperty * property, double minimum, double maximum) [signal]
This signal is emitted whenever a property created by this manager changes its range of valid values, passing a pointer to the property and the new minimum and maximum values
See also
setRange()
Referenced by setMaximum(), setMinimum(), and setRange().
void QtDoublePropertyManager::setDecimals (QtProperty * property, int prec) [slot]
Sets the precision of the given property to prec.
The valid decimal range is 0-13. The default is 2.
See also
decimals()
References QtDoublePropertyManagerPrivate::Data::decimals, decimalsChanged(), and QtDoublePropertyManagerPrivate::m_values.
Referenced by QtPointFPropertyManager::initializeProperty(), QtSizeFPropertyManager::initializeProperty(), QtRectFPropertyManager::initializeProperty(), QtPointFPropertyManager::setDecimals(), QtSizeFPropertyManager::setDecimals(), and QtRectFPropertyManager::setDecimals().
void QtDoublePropertyManager::setMaximum (QtProperty * property, double maxVal) [slot]
Sets the maximum value for the given property to maxVal.
When setting the maximum value, the minimum and current values are adjusted if necessary (ensuring that the range remains valid and that the current value is within in the range).
See also
maximum(), setRange(), rangeChanged()
References QtAbstractPropertyManager::propertyChanged(), rangeChanged(), and valueChanged().
void QtDoublePropertyManager::setMinimum (QtProperty * property, double minVal) [slot]
Sets the minimum value for the given property to minVal.
When setting the minimum value, the maximum and current values are adjusted if necessary (ensuring that the range remains valid and that the current value is within in the range).
See also
minimum(), setRange(), rangeChanged()
References QtAbstractPropertyManager::propertyChanged(), rangeChanged(), and valueChanged().
Referenced by QtSizeFPropertyManager::initializeProperty(), and QtRectFPropertyManager::initializeProperty().
void QtDoublePropertyManager::setRange (QtProperty * property, double minimum, double maximum) [slot]
Sets the range of valid values.
This is a convenience function defining the range of valid values in one go; setting the minimum and maximum values for the given property with a single function call.
When setting a new range, the current value is adjusted if necessary (ensuring that the value remains within range).
See also
setMinimum(), setMaximum(), rangeChanged()
References QtAbstractPropertyManager::propertyChanged(), rangeChanged(), and valueChanged().
void QtDoublePropertyManager::setSingleStep (QtProperty * property, double step) [slot]
Sets the step value for the given property to step.
The step is typically used to increment or decrement a property value while pressing an arrow key.
See also
singleStep()
References QtDoublePropertyManagerPrivate::m_values, QtDoublePropertyManagerPrivate::Data::singleStep, and singleStepChanged().
void QtDoublePropertyManager::setValue (QtProperty * property, double value) [slot]
Sets the value of the given property to value.
If the specified value is not valid according to the given property's range, the value is adjusted to the nearest valid value within the range.
See also
value(), setRange(), valueChanged()
References QtAbstractPropertyManager::propertyChanged(), and valueChanged().
Referenced by QtPointFPropertyManager::initializeProperty(), QtSizeFPropertyManager::initializeProperty(), QtRectFPropertyManager::initializeProperty(), QtPointFPropertyManager::setValue(), QtRectFPropertyManager::setValue(), and QtDoubleSpinBoxFactoryPrivate::slotSetValue().
double QtDoublePropertyManager::singleStep (const QtProperty * property) const
Returns the given property's step value.
The step is typically used to increment or decrement a property value while pressing an arrow key.
See also
setSingleStep()
References QtDoublePropertyManagerPrivate::m_values, and QtDoublePropertyManagerPrivate::Data::singleStep.
Referenced by QtDoubleSpinBoxFactory::createEditor().
void QtDoublePropertyManager::singleStepChanged (QtProperty * property, double step) [signal]
This signal is emitted whenever a property created by this manager changes its single step property, passing a pointer to the property and the new step value
See also
setSingleStep()
Referenced by setSingleStep().
void QtDoublePropertyManager::uninitializeProperty (QtProperty * property) [protected], [virtual]
Reimplemented from QtAbstractPropertyManager .
References QtDoublePropertyManagerPrivate::m_values.
double QtDoublePropertyManager::value (const QtProperty * property) const
Returns the given property's value.
If the given property is not managed by this manager, this function returns 0.
See also
setValue()
References QtDoublePropertyManagerPrivate::m_values.
Referenced by QtDoubleSpinBoxFactory::createEditor(), QtDoubleSpinBoxFactoryPrivate::slotDecimalsChanged(), and QtDoubleSpinBoxFactoryPrivate::slotRangeChanged().
void QtDoublePropertyManager::valueChanged (QtProperty * property, double value) [signal]
This signal is emitted whenever a property created by this manager changes its value, passing a pointer to the property and the new value as parameters.
See also
setValue()
Referenced by setMaximum(), setMinimum(), setRange(), and setValue().
QString QtDoublePropertyManager::valueText (const QtProperty * property) const [protected], [virtual]
Reimplemented from QtAbstractPropertyManager .
References QtDoublePropertyManagerPrivate::m_values.
The documentation for this class was generated from the following files:
qtpropertymanager.h
qtpropertymanager.cpp