QtEnumPropertyManager Class Reference
The QtEnumPropertyManager provides and manages enum properties.
#include <qtpropertymanager.h>
Public Slots
void setValue (QtProperty *property, int val)
void setEnumNames (QtProperty *property, const QStringList &names)
void setEnumIcons (QtProperty *property, const QMap< int, QIcon > &icons)
Signals
void valueChanged (QtProperty *property, int val)
void enumNamesChanged (QtProperty *property, const QStringList &names)
void enumIconsChanged (QtProperty *property, const QMap< int, QIcon > &icons)
Public Member Functions
QtEnumPropertyManager (QObject *parent=0)
~QtEnumPropertyManager ()
int value (const QtProperty *property) const
QStringList enumNames (const QtProperty *property) const
QMap< int, QIcon > enumIcons (const QtProperty *property) const
Protected Member Functions
QString valueText (const QtProperty *property) const
QIcon valueIcon (const QtProperty *property) const
virtual void initializeProperty (QtProperty *property)
virtual void uninitializeProperty (QtProperty *property)
Detailed Description
Each enum property has an associated list of enum names which can be retrieved using the enumNames() function, and set using the corresponding setEnumNames() function. An enum property's value is represented by an index in this list, and can be retrieved and set using the value() and setValue() slots respectively.
Each enum value can also have an associated icon. The mapping from values to icons can be set using the setEnumIcons() function and queried with the enumIcons() function.
In addition, QtEnumPropertyManager provides the valueChanged() signal which is emitted whenever a property created by this manager changes. The enumNamesChanged() or enumIconsChanged() signal is emitted whenever the list of enum names or icons is altered.
See also
QtAbstractPropertyManager, QtEnumEditorFactory
Constructor & Destructor Documentation
QtEnumPropertyManager::QtEnumPropertyManager (QObject * parent = 0)
Creates a manager with the given parent.
QtEnumPropertyManager::~QtEnumPropertyManager ()
Destroys this manager, and all the properties it has created.
References QtAbstractPropertyManager::clear().
Member Function Documentation
QMap< int, QIcon > QtEnumPropertyManager::enumIcons (const QtProperty * property) const
Returns the given property's map of enum values to their icons.
See also
value(), setEnumIcons()
References QtEnumPropertyManagerPrivate::Data::enumIcons, and QtEnumPropertyManagerPrivate::m_values.
Referenced by QtEnumEditorFactory::createEditor(), setEnumIcons(), and QtEnumEditorFactoryPrivate::slotEnumNamesChanged().
void QtEnumPropertyManager::enumIconsChanged (QtProperty * property, const QMap< int, QIcon > & icons) [signal]
This signal is emitted whenever a property created by this manager changes its enum icons, passing a pointer to the property and the new mapping of values to icons as parameters.
See also
setEnumIcons()
Referenced by setEnumIcons().
QStringList QtEnumPropertyManager::enumNames (const QtProperty * property) const
Returns the given property's list of enum names.
See also
value(), setEnumNames()
References QtEnumPropertyManagerPrivate::Data::enumNames, and QtEnumPropertyManagerPrivate::m_values.
Referenced by QtEnumEditorFactory::createEditor(), setEnumNames(), and QtEnumEditorFactoryPrivate::slotEnumIconsChanged().
void QtEnumPropertyManager::enumNamesChanged (QtProperty * property, const QStringList & names) [signal]
This signal is emitted whenever a property created by this manager changes its enum names, passing a pointer to the property and the new names as parameters.
See also
setEnumNames()
Referenced by setEnumNames().
void QtEnumPropertyManager::initializeProperty (QtProperty * property) [protected], [virtual]
Implements QtAbstractPropertyManager .
References QtEnumPropertyManagerPrivate::m_values.
void QtEnumPropertyManager::setEnumIcons (QtProperty * property, const QMap< int, QIcon > & enumIcons) [slot]
Sets the given property's map of enum values to their icons to enumIcons.
Each enum value can have associated icon. This association is represented with passed enumIcons map.
See also
enumNames(), enumNamesChanged()
References enumIcons(), enumIconsChanged(), QtEnumPropertyManagerPrivate::m_values, and QtAbstractPropertyManager::propertyChanged().
Referenced by QtCursorEditorFactory::createEditor().
void QtEnumPropertyManager::setEnumNames (QtProperty * property, const QStringList & enumNames) [slot]
Sets the given property's list of enum names to enumNames. The property's current value is reset to 0 indicating the first item of the list.
If the specified enumNames list is empty, the property's current value is set to -1.
See also
enumNames(), enumNamesChanged()
References enumNames(), QtEnumPropertyManagerPrivate::Data::enumNames, enumNamesChanged(), QtEnumPropertyManagerPrivate::m_values, QtAbstractPropertyManager::propertyChanged(), QtEnumPropertyManagerPrivate::Data::val, and valueChanged().
Referenced by QtCursorEditorFactory::createEditor(), QtLocalePropertyManager::initializeProperty(), QtSizePolicyPropertyManager::initializeProperty(), QtFontPropertyManager::initializeProperty(), QtLocalePropertyManager::setValue(), and QtFontPropertyManagerPrivate::slotFontDatabaseDelayedChange().
void QtEnumPropertyManager::setValue (QtProperty * property, int value) [slot]
Sets the value of the given property to value.
The specified value must be less than the size of the given property's enumNames() list, and larger than (or equal to) 0.
See also
value(), valueChanged()
References QtEnumPropertyManagerPrivate::Data::enumNames, QtEnumPropertyManagerPrivate::m_values, QtAbstractPropertyManager::propertyChanged(), QtEnumPropertyManagerPrivate::Data::val, and valueChanged().
Referenced by QtCursorEditorFactory::createEditor(), QtLocalePropertyManager::initializeProperty(), QtSizePolicyPropertyManager::initializeProperty(), QtFontPropertyManager::initializeProperty(), QtLocalePropertyManager::setValue(), QtSizePolicyPropertyManager::setValue(), QtFontPropertyManager::setValue(), QtFontPropertyManagerPrivate::slotFontDatabaseDelayedChange(), QtCursorEditorFactoryPrivate::slotPropertyChanged(), and QtEnumEditorFactoryPrivate::slotSetValue().
void QtEnumPropertyManager::uninitializeProperty (QtProperty * property) [protected], [virtual]
Reimplemented from QtAbstractPropertyManager .
References QtEnumPropertyManagerPrivate::m_values.
int QtEnumPropertyManager::value (const QtProperty * property) const
Returns the given property's value which is an index in the list returned by enumNames()
If the given property is not managed by this manager, this function returns -1.
See also
enumNames(), setValue()
References QtEnumPropertyManagerPrivate::m_values.
Referenced by QtEnumEditorFactory::createEditor(), QtEnumEditorFactoryPrivate::slotEnumIconsChanged(), QtEnumEditorFactoryPrivate::slotEnumNamesChanged(), and QtFontPropertyManagerPrivate::slotFontDatabaseDelayedChange().
void QtEnumPropertyManager::valueChanged (QtProperty * property, int value) [signal]
This signal is emitted whenever a property created by this manager changes its value, passing a pointer to the property and the new value as parameters.
See also
setValue()
Referenced by setEnumNames(), and setValue().
QIcon QtEnumPropertyManager::valueIcon (const QtProperty * property) const [protected], [virtual]
Reimplemented from QtAbstractPropertyManager .
References QtEnumPropertyManagerPrivate::Data::enumIcons, QtEnumPropertyManagerPrivate::m_values, and QtEnumPropertyManagerPrivate::Data::val.
QString QtEnumPropertyManager::valueText (const QtProperty * property) const [protected], [virtual]
Reimplemented from QtAbstractPropertyManager .
References QtEnumPropertyManagerPrivate::Data::enumNames, QtEnumPropertyManagerPrivate::m_values, and QtEnumPropertyManagerPrivate::Data::val.
The documentation for this class was generated from the following files:
qtpropertymanager.h
qtpropertymanager.cpp