QtGroupBoxPropertyBrowserPrivate Class Reference
Classes
struct WidgetItem
Public Member Functions
void init (QWidget *parent)
void propertyInserted (QtBrowserItem *index, QtBrowserItem *afterIndex)
void propertyRemoved (QtBrowserItem *index)
void propertyChanged (QtBrowserItem *index)
QWidget * createEditor (QtProperty *property, QWidget *parent) const
void slotEditorDestroyed ()
void slotUpdate ()
Member Function Documentation
QWidget* QtGroupBoxPropertyBrowserPrivate::createEditor (QtProperty * property, QWidget * parent) const [inline]
References QtAbstractPropertyBrowser::createEditor(), slotEditorDestroyed(), and slotUpdate().
Referenced by propertyInserted().
void QtGroupBoxPropertyBrowserPrivate::init (QWidget * parent)
Referenced by QtGroupBoxPropertyBrowser::QtGroupBoxPropertyBrowser().
void QtGroupBoxPropertyBrowserPrivate::propertyChanged (QtBrowserItem * index)
References QtGroupBoxPropertyBrowserPrivate::WidgetItem::groupBox, QtGroupBoxPropertyBrowserPrivate::WidgetItem::label, QtGroupBoxPropertyBrowserPrivate::WidgetItem::widget, and QtGroupBoxPropertyBrowserPrivate::WidgetItem::widgetLabel.
Referenced by QtGroupBoxPropertyBrowser::itemChanged().
void QtGroupBoxPropertyBrowserPrivate::propertyInserted (QtBrowserItem * index, QtBrowserItem * afterIndex)
References QtGroupBoxPropertyBrowserPrivate::WidgetItem::children, createEditor(), QtGroupBoxPropertyBrowserPrivate::WidgetItem::groupBox, QtGroupBoxPropertyBrowserPrivate::WidgetItem::label, QtGroupBoxPropertyBrowserPrivate::WidgetItem::layout, QtGroupBoxPropertyBrowserPrivate::WidgetItem::line, QtGroupBoxPropertyBrowserPrivate::WidgetItem::parent, QtBrowserItem::parent(), QtBrowserItem::property(), slotEditorDestroyed(), QtGroupBoxPropertyBrowserPrivate::WidgetItem::widget, QtGroupBoxPropertyBrowserPrivate::WidgetItem::WidgetItem(), and QtGroupBoxPropertyBrowserPrivate::WidgetItem::widgetLabel.
Referenced by QtGroupBoxPropertyBrowser::itemInserted().
void QtGroupBoxPropertyBrowserPrivate::propertyRemoved (QtBrowserItem * index)
References QtGroupBoxPropertyBrowserPrivate::WidgetItem::children, QtGroupBoxPropertyBrowserPrivate::WidgetItem::groupBox, QtGroupBoxPropertyBrowserPrivate::WidgetItem::label, QtGroupBoxPropertyBrowserPrivate::WidgetItem::layout, QtGroupBoxPropertyBrowserPrivate::WidgetItem::line, QtGroupBoxPropertyBrowserPrivate::WidgetItem::parent, QtGroupBoxPropertyBrowserPrivate::WidgetItem::widget, and QtGroupBoxPropertyBrowserPrivate::WidgetItem::widgetLabel.
Referenced by QtGroupBoxPropertyBrowser::itemRemoved().
void QtGroupBoxPropertyBrowserPrivate::slotEditorDestroyed ()
Referenced by createEditor(), and propertyInserted().
void QtGroupBoxPropertyBrowserPrivate::slotUpdate ()
References QtGroupBoxPropertyBrowserPrivate::WidgetItem::children, QtGroupBoxPropertyBrowserPrivate::WidgetItem::groupBox, QtGroupBoxPropertyBrowserPrivate::WidgetItem::label, QtGroupBoxPropertyBrowserPrivate::WidgetItem::layout, QtGroupBoxPropertyBrowserPrivate::WidgetItem::parent, QtGroupBoxPropertyBrowserPrivate::WidgetItem::widget, and QtGroupBoxPropertyBrowserPrivate::WidgetItem::widgetLabel.
Referenced by createEditor().
The documentation for this class was generated from the following file:
qtgroupboxpropertybrowser.cpp