QtTimePropertyManager Class Reference
The QtTimePropertyManager provides and manages QTime properties.
#include <qtpropertymanager.h>
Public Slots
void setValue (QtProperty *property, const QTime &val)
Signals
void valueChanged (QtProperty *property, const QTime &val)
Public Member Functions
QtTimePropertyManager (QObject *parent=0)
~QtTimePropertyManager ()
QTime value (const QtProperty *property) const
Protected Member Functions
QString valueText (const QtProperty *property) const
virtual void initializeProperty (QtProperty *property)
virtual void uninitializeProperty (QtProperty *property)
Detailed Description
A time property's value can be retrieved using the value() function, and set using the setValue() slot.
In addition, QtTimePropertyManager provides the valueChanged() signal which is emitted whenever a property created by this manager changes.
See also
QtAbstractPropertyManager, QtTimeEditFactory
Constructor & Destructor Documentation
QtTimePropertyManager::QtTimePropertyManager (QObject * parent = 0)
Creates a manager with the given parent.
References QtTimePropertyManagerPrivate::m_format.
QtTimePropertyManager::~QtTimePropertyManager ()
Destroys this manager, and all the properties it has created.
References QtAbstractPropertyManager::clear().
Member Function Documentation
void QtTimePropertyManager::initializeProperty (QtProperty * property) [protected], [virtual]
Implements QtAbstractPropertyManager .
References QtTimePropertyManagerPrivate::m_values.
void QtTimePropertyManager::setValue (QtProperty * property, const QTime & value) [slot]
Sets the value of the given property to value.
See also
value(), valueChanged()
References QtTimePropertyManagerPrivate::m_values, QtAbstractPropertyManager::propertyChanged(), and valueChanged().
Referenced by QtTimeEditFactoryPrivate::slotSetValue().
void QtTimePropertyManager::uninitializeProperty (QtProperty * property) [protected], [virtual]
Reimplemented from QtAbstractPropertyManager .
References QtTimePropertyManagerPrivate::m_values.
QTime QtTimePropertyManager::value (const QtProperty * property) const
Returns the given property's value.
If the given property is not managed by this manager, this function returns an invalid time object.
See also
setValue()
References QtTimePropertyManagerPrivate::m_values.
Referenced by QtTimeEditFactory::createEditor().
void QtTimePropertyManager::valueChanged (QtProperty * property, const QTime & value) [signal]
This signal is emitted whenever a property created by this manager changes its value, passing a pointer to the property and the new value as parameters.
See also
setValue()
Referenced by setValue().
QString QtTimePropertyManager::valueText (const QtProperty * property) const [protected], [virtual]
Reimplemented from QtAbstractPropertyManager .
References QtTimePropertyManagerPrivate::m_format, and QtTimePropertyManagerPrivate::m_values.
The documentation for this class was generated from the following files:
qtpropertymanager.h
qtpropertymanager.cpp