QtAbstractPropertyBrowserPrivate Class Reference
Public Member Functions
QtAbstractPropertyBrowserPrivate ()
void insertSubTree (QtProperty *property, QtProperty *parentProperty)
void removeSubTree (QtProperty *property, QtProperty *parentProperty)
void createBrowserIndexes (QtProperty *property, QtProperty *parentProperty, QtProperty *afterProperty)
void removeBrowserIndexes (QtProperty *property, QtProperty *parentProperty)
QtBrowserItem * createBrowserIndex (QtProperty *property, QtBrowserItem *parentIndex, QtBrowserItem *afterIndex)
void removeBrowserIndex (QtBrowserItem *index)
void clearIndex (QtBrowserItem *index)
void slotPropertyInserted (QtProperty *property, QtProperty *parentProperty, QtProperty *afterProperty)
void slotPropertyRemoved (QtProperty *property, QtProperty *parentProperty)
void slotPropertyDestroyed (QtProperty *property)
void slotPropertyDataChanged (QtProperty *property)
Public Attributes
QList< QtProperty * > m_subItems
QMap< QtAbstractPropertyManager *, QList< QtProperty * > > m_managerToProperties
QMap< QtProperty *, QList< QtProperty * > > m_propertyToParents
QMap< QtProperty *, QtBrowserItem * > m_topLevelPropertyToIndex
QList< QtBrowserItem * > m_topLevelIndexes
QMap< QtProperty *, QList< QtBrowserItem * > > m_propertyToIndexes
QtBrowserItem * m_currentItem
Constructor & Destructor Documentation
QtAbstractPropertyBrowserPrivate::QtAbstractPropertyBrowserPrivate ()
Member Function Documentation
void QtAbstractPropertyBrowserPrivate::clearIndex (QtBrowserItem * index)
References QtBrowserItem::children().
Referenced by QtAbstractPropertyBrowser::~QtAbstractPropertyBrowser().
QtBrowserItem * QtAbstractPropertyBrowserPrivate::createBrowserIndex (QtProperty * property, QtBrowserItem * parentIndex, QtBrowserItem * afterIndex)
References QtBrowserItemPrivate::addChild(), QtAbstractPropertyBrowser::itemInserted(), m_propertyToIndexes, m_topLevelIndexes, and m_topLevelPropertyToIndex.
Referenced by createBrowserIndexes().
void QtAbstractPropertyBrowserPrivate::createBrowserIndexes (QtProperty * property, QtProperty * parentProperty, QtProperty * afterProperty)
References createBrowserIndex(), m_propertyToIndexes, QtBrowserItem::parent(), and QtBrowserItem::property().
Referenced by QtAbstractPropertyBrowser::insertProperty(), and slotPropertyInserted().
void QtAbstractPropertyBrowserPrivate::insertSubTree (QtProperty * property, QtProperty * parentProperty)
References m_managerToProperties, m_propertyToParents, slotPropertyDataChanged(), slotPropertyDestroyed(), slotPropertyInserted(), and slotPropertyRemoved().
Referenced by QtAbstractPropertyBrowser::insertProperty(), and slotPropertyInserted().
void QtAbstractPropertyBrowserPrivate::removeBrowserIndex (QtBrowserItem * index)
References QtBrowserItem::children(), QtAbstractPropertyBrowser::itemRemoved(), m_propertyToIndexes, m_topLevelIndexes, m_topLevelPropertyToIndex, QtBrowserItem::parent(), QtBrowserItem::property(), and QtBrowserItemPrivate::removeChild().
Referenced by removeBrowserIndexes().
void QtAbstractPropertyBrowserPrivate::removeBrowserIndexes (QtProperty * property, QtProperty * parentProperty)
References m_propertyToIndexes, QtBrowserItem::parent(), QtBrowserItem::property(), and removeBrowserIndex().
Referenced by QtAbstractPropertyBrowser::removeProperty(), and slotPropertyRemoved().
void QtAbstractPropertyBrowserPrivate::removeSubTree (QtProperty * property, QtProperty * parentProperty)
References m_managerToProperties, m_propertyToParents, slotPropertyDataChanged(), slotPropertyDestroyed(), slotPropertyInserted(), and slotPropertyRemoved().
Referenced by QtAbstractPropertyBrowser::removeProperty(), and slotPropertyRemoved().
void QtAbstractPropertyBrowserPrivate::slotPropertyDataChanged (QtProperty * property)
References QtAbstractPropertyBrowser::itemChanged(), m_propertyToIndexes, and m_propertyToParents.
Referenced by insertSubTree(), and removeSubTree().
void QtAbstractPropertyBrowserPrivate::slotPropertyDestroyed (QtProperty * property)
References m_subItems, and QtAbstractPropertyBrowser::removeProperty().
Referenced by insertSubTree(), and removeSubTree().
void QtAbstractPropertyBrowserPrivate::slotPropertyInserted (QtProperty * property, QtProperty * parentProperty, QtProperty * afterProperty)
References createBrowserIndexes(), insertSubTree(), and m_propertyToParents.
Referenced by insertSubTree(), and removeSubTree().
void QtAbstractPropertyBrowserPrivate::slotPropertyRemoved (QtProperty * property, QtProperty * parentProperty)
References m_propertyToParents, removeBrowserIndexes(), and removeSubTree().
Referenced by insertSubTree(), and removeSubTree().
Member Data Documentation
QtBrowserItem* QtAbstractPropertyBrowserPrivate::m_currentItem
Referenced by QtAbstractPropertyBrowser::currentItem(), and QtAbstractPropertyBrowser::setCurrentItem().
QMap<QtAbstractPropertyManager *, QList<QtProperty *> > QtAbstractPropertyBrowserPrivate::m_managerToProperties
Referenced by insertSubTree(), and removeSubTree().
QMap<QtProperty *, QList<QtBrowserItem *> > QtAbstractPropertyBrowserPrivate::m_propertyToIndexes
Referenced by createBrowserIndex(), createBrowserIndexes(), QtAbstractPropertyBrowser::items(), removeBrowserIndex(), removeBrowserIndexes(), and slotPropertyDataChanged().
QMap<QtProperty *, QList<QtProperty *> > QtAbstractPropertyBrowserPrivate::m_propertyToParents
Referenced by insertSubTree(), removeSubTree(), slotPropertyDataChanged(), slotPropertyInserted(), and slotPropertyRemoved().
QList<QtProperty *> QtAbstractPropertyBrowserPrivate::m_subItems
Referenced by QtAbstractPropertyBrowser::addProperty(), QtAbstractPropertyBrowser::insertProperty(), QtAbstractPropertyBrowser::properties(), QtAbstractPropertyBrowser::removeProperty(), and slotPropertyDestroyed().
QList<QtBrowserItem *> QtAbstractPropertyBrowserPrivate::m_topLevelIndexes
Referenced by createBrowserIndex(), removeBrowserIndex(), and QtAbstractPropertyBrowser::topLevelItems().
QMap<QtProperty *, QtBrowserItem *> QtAbstractPropertyBrowserPrivate::m_topLevelPropertyToIndex
Referenced by createBrowserIndex(), removeBrowserIndex(), and QtAbstractPropertyBrowser::topLevelItem().
The documentation for this class was generated from the following file:
qtpropertybrowser.cpp