LinePainter Class Reference
#include <linepainter.h>
Public Slots
void setLineColor (const QColor &c)
changes the color of the lines
void setLineWidth (double w)
changes the width of the lines
void setLinePen (const QPen &p)
changes the color of the lines
Public Member Functions
 LinePainter (CurveItem * curveItem)
virtual ~LinePainter ()
virtual void draw (SceneCurve *curve, PlotSceneWidget *plot, QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget=0)
the drawing method.
virtual CurveItem * curveItem () const
virtual QSizeF elementSize () const
the size of each drawn element
virtual int type () const
QColor lineColor () const
returns the colour used for the lines that form the curve
double lineWidth () const
returns the line width
QPen linePen () const
returns the pen used to draw the lines
QPen pen () const
Implements the pen method of the ItemPainterInterface.
Properties
QColor lineColor
double lineWidth
QPen linePen
Additional Inherited Members
Constructor & Destructor Documentation
LinePainter()
LinePainter::LinePainter (CurveItem * curveItem)
References curveItem(), and CurveItem::installItemPainterInterface().
~LinePainter()
LinePainter::~LinePainter () [virtual]
Member Function Documentation
curveItem()
 CurveItem * LinePainter::curveItem () const [virtual]
Implements ItemPainterInterface .
Referenced by LinePainter().
draw()
void LinePainter::draw (SceneCurve * curve, PlotSceneWidget * plot, QPainter * painter, const QStyleOptionGraphicsItem * option, QWidget * widget = 0) [virtual]
This method is invoked by CurveItem inside paint method. You can obtain the points of the curve in scene coordinates by calling curve->points and the size of the points by means of curve->dataSize. It may be necessary to call painter->save() and painter->restore() at the beginning and end of the drawing. Each draw method of each installed ItemPainterInterface is actually invoked in sequence without saving and restoring the painter state for you.
See also
CurveItem
LinePainter
DotsPainter
Implements ItemPainterInterface .
References ScaleItem::axisId(), SceneCurve::data(), SceneCurve::dataSize(), SceneCurve::getXAxis(), Data::invalidDataPoints(), SceneCurve::points(), Elettra::red, PlotSceneWidget::scaleItem(), and PlotSceneWidget::transform().
elementSize()
QSizeF LinePainter::elementSize () const [virtual]
This size is used by the classes that use ItemPainterInterface to know how much extra space is needed in order to calculate the bounding rect of the CurveItem or other geometrical properties.
For instance, if you are drawing circles, then this method should return the radius of the circle, so that CurveItem knows how much space has to be added to the curve bounds in order to correcly draw the items.
If you are drawing lines, then this size can be 0x0 since the connecting lines do not require extra space to be calculated. If you use a particular pen width, then you may want to return its width in order to be sure that CurveItem takes care of this space.
See also
CurveItem
Implements ItemPainterInterface .
lineColor()
QColor LinePainter::lineColor () const
Returns
the color of the lines
See also
setLineColor
setLineWidth
linePen()
QPen LinePainter::linePen () const
Returns
the pen used to draw the lines.
lineWidth()
double LinePainter::lineWidth () const
Returns
the width of the line used to draw the lines.
See also
setLineColor
setLineWidth
pen()
QPen LinePainter::pen () const [virtual]
Returns
the line pen as returned by linePen()
Implements ItemPainterInterface .
setLineColor
void LinePainter::setLineColor (const QColor & c) [slot]
The default colour is Qt::black
See also
lineColor
Referenced by ExtScalePlotSceneWidget::addCurve(), PlotSceneWidget::addLineCurve(), and XYSceneTest::XYSceneTest().
setLinePen
void LinePainter::setLinePen (const QPen & p) [slot]
See also
linePen
setLineWidth
void LinePainter::setLineWidth (double w) [slot]
The default is 0.0
See also
lineWidth
type()
int LinePainter::type () const [virtual]
Implements ItemPainterInterface .
References ItemPainterInterface::Line.
Property Documentation
lineColor
QColor LinePainter::lineColor [read], [write]
linePen
QPen LinePainter::linePen [read], [write]
lineWidth
double LinePainter::lineWidth [read], [write]
The documentation for this class was generated from the following files:
 linepainter.h
 linepainter.cpp