PlotSceneWidgetSaver Class Reference
#include <plotscenewidgetsaver.h>
Public Member Functions
 PlotSceneWidgetSaver ()
bool save (const QList< SceneCurve * >curves, bool timeScale)
QString errorMessage ()
QString fileName ()
Constructor & Destructor Documentation
PlotSceneWidgetSaver()
PlotSceneWidgetSaver::PlotSceneWidgetSaver ()
Member Function Documentation
errorMessage()
QString PlotSceneWidgetSaver::errorMessage () [inline]
Referenced by PlotSceneWidget::saveData().
fileName()
QString PlotSceneWidgetSaver::fileName () [inline]
Referenced by PlotSceneWidget::saveData().
save()
bool PlotSceneWidgetSaver::save (const QList< SceneCurve * > curves, bool timeScale)
References SceneCurve::data(), SceneCurve::dataSize(), OptionsDialog::dateTimeFormat(), SceneCurve::name(), pinfo, qstoc, OptionsDialog::timestampToDateTimeString(), Data::xData, OptionsDialog::xFormat(), Data::yData, and OptionsDialog::yFormat().
Referenced by PlotSceneWidget::saveData().
The documentation for this class was generated from the following files:
 plotscenewidgetsaver.h
 plotscenewidgetsaver.cpp