QtRectPropertyManager Class Reference
The QtRectPropertyManager provides and manages QRect properties.
#include <qtpropertymanager.h>
Public Slots
void setValue (QtProperty *property, const QRect &val)
void setConstraint (QtProperty *property, const QRect &constraint)
Signals
void valueChanged (QtProperty *property, const QRect &val)
void constraintChanged (QtProperty *property, const QRect &constraint)
Public Member Functions
QtRectPropertyManager (QObject *parent=0)
~QtRectPropertyManager ()
QtIntPropertyManager * subIntPropertyManager () const
QRect value (const QtProperty *property) const
QRect constraint (const QtProperty *property) const
Protected Member Functions
QString valueText (const QtProperty *property) const
virtual void initializeProperty (QtProperty *property)
virtual void uninitializeProperty (QtProperty *property)
Detailed Description
A rectangle property has nested x, y, width and height subproperties. The top-level property's value can be retrieved using the value() function, and set using the setValue() slot.
The subproperties are created by a QtIntPropertyManager object. This manager can be retrieved using the subIntPropertyManager() function. In order to provide editing widgets for the subproperties in a property browser widget, this manager must be associated with an editor factory.
A rectangle property also has a constraint rectangle which can be retrieved using the constraint() function, and set using the setConstraint() slot.
In addition, QtRectPropertyManager provides the valueChanged() signal which is emitted whenever a property created by this manager changes, and the constraintChanged() signal which is emitted whenever such a property changes its constraint rectangle.
See also
QtAbstractPropertyManager, QtIntPropertyManager, QtRectFPropertyManager
Constructor & Destructor Documentation
QtRectPropertyManager::QtRectPropertyManager (QObject * parent = 0)
Creates a manager with the given parent.
References QtRectPropertyManagerPrivate::m_intPropertyManager, QtAbstractPropertyManager::propertyDestroyed(), and valueChanged().
QtRectPropertyManager::~QtRectPropertyManager ()
Destroys this manager, and all the properties it has created.
References QtAbstractPropertyManager::clear().
Member Function Documentation
QRect QtRectPropertyManager::constraint (const QtProperty * property) const
Returns the given property's constraining rectangle. If returned value is null QRect it means there is no constraint applied.
See also
value(), setConstraint()
References QtRectPropertyManagerPrivate::Data::constraint, and QtRectPropertyManagerPrivate::m_values.
void QtRectPropertyManager::constraintChanged (QtProperty * property, const QRect & constraint) [signal]
This signal is emitted whenever property changes its constraint rectangle, passing a pointer to the property and the new constraint rectangle as parameters.
See also
setConstraint()
Referenced by setConstraint().
void QtRectPropertyManager::initializeProperty (QtProperty * property) [protected], [virtual]
Implements QtAbstractPropertyManager .
References QtAbstractPropertyManager::addProperty(), QtProperty::addSubProperty(), QtRectPropertyManagerPrivate::m_hToProperty, QtRectPropertyManagerPrivate::m_intPropertyManager, QtRectPropertyManagerPrivate::m_propertyToH, QtRectPropertyManagerPrivate::m_propertyToW, QtRectPropertyManagerPrivate::m_propertyToX, QtRectPropertyManagerPrivate::m_propertyToY, QtRectPropertyManagerPrivate::m_values, QtRectPropertyManagerPrivate::m_wToProperty, QtRectPropertyManagerPrivate::m_xToProperty, QtRectPropertyManagerPrivate::m_yToProperty, QtIntPropertyManager::setMinimum(), QtProperty::setPropertyName(), and QtIntPropertyManager::setValue().
void QtRectPropertyManager::setConstraint (QtProperty * property, const QRect & constraint) [slot]
Sets the given property's constraining rectangle to constraint.
When setting the constraint, the current value is adjusted if necessary (ensuring that the current rectangle value is inside the constraint). In order to reset the constraint pass a null QRect value.
See also
setValue(), constraint(), constraintChanged()
References QtRectPropertyManagerPrivate::Data::constraint, constraintChanged(), QtRectPropertyManagerPrivate::m_values, QtAbstractPropertyManager::propertyChanged(), QtRectPropertyManagerPrivate::setConstraint(), QtRectPropertyManagerPrivate::Data::val, and valueChanged().
void QtRectPropertyManager::setValue (QtProperty * property, const QRect & value) [slot]
Sets the value of the given property to value. Nested properties are updated automatically.
If the specified value is not inside the given property's constraining rectangle, the value is adjusted accordingly to fit within the constraint.
See also
value(), setConstraint(), valueChanged()
References QtRectPropertyManagerPrivate::Data::constraint, QtRectPropertyManagerPrivate::m_intPropertyManager, QtRectPropertyManagerPrivate::m_propertyToH, QtRectPropertyManagerPrivate::m_propertyToW, QtRectPropertyManagerPrivate::m_propertyToX, QtRectPropertyManagerPrivate::m_propertyToY, QtRectPropertyManagerPrivate::m_values, QtAbstractPropertyManager::propertyChanged(), QtIntPropertyManager::setValue(), QtRectPropertyManagerPrivate::Data::val, and valueChanged().
QtIntPropertyManager * QtRectPropertyManager::subIntPropertyManager () const
Returns the manager that creates the nested x, y, width and height subproperties.
In order to provide editing widgets for the mentioned subproperties in a property browser widget, this manager must be associated with an editor factory.
See also
QtAbstractPropertyBrowser::setFactoryForManager()
References QtRectPropertyManagerPrivate::m_intPropertyManager.
Referenced by QtVariantPropertyManager::QtVariantPropertyManager().
void QtRectPropertyManager::uninitializeProperty (QtProperty * property) [protected], [virtual]
Reimplemented from QtAbstractPropertyManager .
References QtRectPropertyManagerPrivate::m_hToProperty, QtRectPropertyManagerPrivate::m_propertyToH, QtRectPropertyManagerPrivate::m_propertyToW, QtRectPropertyManagerPrivate::m_propertyToX, QtRectPropertyManagerPrivate::m_propertyToY, QtRectPropertyManagerPrivate::m_values, QtRectPropertyManagerPrivate::m_wToProperty, QtRectPropertyManagerPrivate::m_xToProperty, and QtRectPropertyManagerPrivate::m_yToProperty.
QRect QtRectPropertyManager::value (const QtProperty * property) const
Returns the given property's value.
If the given property is not managed by this manager, this function returns an invalid rectangle.
See also
setValue(), constraint()
References QtRectPropertyManagerPrivate::m_values.
void QtRectPropertyManager::valueChanged (QtProperty * property, const QRect & value) [signal]
This signal is emitted whenever a property created by this manager changes its value, passing a pointer to the property and the new value as parameters.
See also
setValue()
Referenced by QtRectPropertyManager(), setConstraint(), and setValue().
QString QtRectPropertyManager::valueText (const QtProperty * property) const [protected], [virtual]
Reimplemented from QtAbstractPropertyManager .
References QtRectPropertyManagerPrivate::m_values.
The documentation for this class was generated from the following files:
qtpropertymanager.h
qtpropertymanager.cpp