AxesManager Class Reference
Manages the axes of a PlotSceneWidget.
#include <axesmanager.h>
Public Member Functions
 AxesManager ()
The constructor. It takes no parameters.
void addCouple (const AxisCouple &c)
void removeCouple (const AxisCouple &c)
void removeDuplicateCouples ()
 ScaleItem * getAxis (ScaleItem::Id axisId) const
returns the ScaleItem with the axis id passed as parameter
QList< AxisCouple > & getAxisCouples ()
returns the list of axis couples in the plot.
QList< ScaleItem * > getAllAxes () const
returns a list of all the axes in the PlotSceneWidget
QList< ScaleItem * > getAxes (bool all, ScaleItem::Orientation o) const
Returns a list of axes with the specified orientation, or all axes is all is true.
void clearAxes (bool all, ScaleItem::Orientation o)
 ScaleItem * getAssociatedAxis (ScaleItem::Id otherAxis)
Given an axis, identified by its Id, this method finds and returns the first axis associated to the otherAxis axis.
QPair< double, double > getOriginPosPercentage (ScaleItem::Id oneAxisId, ScaleItem::Id otherAxisId, bool *ok)
given two axes, this method looks for the couple inside the AxisCouple list and returns the associated origin.
 AxisCouple * findIncompleteCouple (ScaleItem *item)
Returns true if an incomplete couple has been found, false otherwise.
int count () const
Public Attributes
QList< AxisCouple > axes
Constructor & Destructor Documentation
AxesManager()
AxesManager::AxesManager ()
Constructed and used by PlotSceneWidget. You can retrieve a reference by calling PlotSceneWidget::axesManager.
See also
PlotSceneWidget
Member Function Documentation
addCouple()
void AxesManager::addCouple (const AxisCouple & c) [inline]
References axes.
clearAxes()
void AxesManager::clearAxes (bool all, ScaleItem::Orientation o)
References axes, ScaleItem::Horizontal, removeDuplicateCouples(), ScaleItem::Vertical, AxisCouple::xAxis, and AxisCouple::yAxis.
count()
int AxesManager::count () const
References axes.
findIncompleteCouple()
 AxisCouple * AxesManager::findIncompleteCouple (ScaleItem * item)
An incomplete couple is an AxisCouple that has just one of the two axis not NULL.
References axes, AxisCouple::xAxis, and AxisCouple::yAxis.
getAllAxes()
QList< ScaleItem * > AxesManager::getAllAxes () const
For each AxisCouple in the PlotSceneWidget, it returns its x and y ScaleItem references.
References axes, AxisCouple::xAxis, and AxisCouple::yAxis.
Referenced by getAxes().
getAssociatedAxis()
 ScaleItem * AxesManager::getAssociatedAxis (ScaleItem::Id otherAxisId)
given an axis with otherAxisId as id, this method returns the associated axis
Note
If one axis is shared through different couples, (for instance an x axis common between two distinct y axes), then the associated axis in the first couple in the list is returned.
Returns
the axis associated to the axis identified by otherAxisId.
Axes are coupled in two. This method returns the one coupled with otherAxisId
References axes, ScaleItem::axisId(), AxisCouple::xAxis, and AxisCouple::yAxis.
getAxes()
QList< ScaleItem * > AxesManager::getAxes (bool all, ScaleItem::Orientation o) const
References getAllAxes(), and ScaleItem::orientation().
getAxis()
 ScaleItem * AxesManager::getAxis (ScaleItem::Id axisId) const
Parameters
axisId the id of the axis you want to retrieve
Returns
the ScaleItem with the specified axisId.
NULL if no ScaleItem was found with the specified axisId
References axes, ScaleItem::axisId(), AxisCouple::xAxis, and AxisCouple::yAxis.
getAxisCouples()
QList< AxisCouple>& AxesManager::getAxisCouples () [inline]
Returns
the list of axis couples in the plot.
References axes.
getOriginPosPercentage()
QPair< double, double > AxesManager::getOriginPosPercentage (ScaleItem::Id oneAxisId, ScaleItem::Id otherAxisId, bool * ok)
Given the axis id of two axes, it returns a pair of double representing the position, given in terms of percentage, of the x and y axis with respect to the scene.
Parameters
oneAxisId one of the axis id to look for
otherAxisId the other axis id to look for (the order is irrelevant)
a compulsory parameter used to test whether the two axes are associated and the origin is defined.
Returns
the point representing the origin between the axes xA and yA, if they belong to the same couple. Returns NULL if the two axes do not belong to the same couple.
See also
getAssociatedAxis
References axes, ScaleItem::axisId(), AxisCouple::xAxis, AxisCouple::xOriginPosPercentage, AxisCouple::yAxis, and AxisCouple::yOriginPosPercentage.
removeCouple()
void AxesManager::removeCouple (const AxisCouple & c) [inline]
References axes.
removeDuplicateCouples()
void AxesManager::removeDuplicateCouples ()
References axes.
Referenced by clearAxes().
Member Data Documentation
axes
QList< AxisCouple> AxesManager::axes
Referenced by addCouple(), clearAxes(), count(), findIncompleteCouple(), getAllAxes(), getAssociatedAxis(), getAxis(), getAxisCouples(), getOriginPosPercentage(), removeCouple(), and removeDuplicateCouples().
The documentation for this class was generated from the following files:
 axesmanager.h
 axesmanager.cpp