QtGroupBoxPropertyBrowser Class Reference
The QtGroupBoxPropertyBrowser class provides a QGroupBox based property browser.
#include <qtgroupboxpropertybrowser.h>
Public Member Functions
QtGroupBoxPropertyBrowser (QWidget *parent=0)
~QtGroupBoxPropertyBrowser ()
Protected Member Functions
virtual void itemInserted (QtBrowserItem *item, QtBrowserItem *afterItem)
virtual void itemRemoved (QtBrowserItem *item)
virtual void itemChanged (QtBrowserItem *item)
Additional Inherited Members
Detailed Description
A property browser is a widget that enables the user to edit a given set of properties. Each property is represented by a label specifying the property's name, and an editing widget (e.g. a line edit or a combobox) holding its value. A property can have zero or more subproperties.
QtGroupBoxPropertyBrowser provides group boxes for all nested properties, i.e. subproperties are enclosed by a group box with the parent property's name as its title. For example:
Use the QtAbstractPropertyBrowser API to add, insert and remove properties from an instance of the QtGroupBoxPropertyBrowser class. The properties themselves are created and managed by implementations of the QtAbstractPropertyManager class.
See also
QtTreePropertyBrowser, QtAbstractPropertyBrowser
Constructor & Destructor Documentation
QtGroupBoxPropertyBrowser::QtGroupBoxPropertyBrowser (QWidget * parent = 0)
Creates a property browser with the given parent.
References QtGroupBoxPropertyBrowserPrivate::init().
QtGroupBoxPropertyBrowser::~QtGroupBoxPropertyBrowser ()
Destroys this property browser.
Note that the properties that were inserted into this browser are not destroyed since they may still be used in other browsers. The properties are owned by the manager that created them.
See also
QtProperty, QtAbstractPropertyManager
Member Function Documentation
void QtGroupBoxPropertyBrowser::itemChanged (QtBrowserItem * item) [protected], [virtual]
Implements QtAbstractPropertyBrowser .
References QtGroupBoxPropertyBrowserPrivate::propertyChanged().
void QtGroupBoxPropertyBrowser::itemInserted (QtBrowserItem * item, QtBrowserItem * afterItem) [protected], [virtual]
Implements QtAbstractPropertyBrowser .
References QtGroupBoxPropertyBrowserPrivate::propertyInserted().
void QtGroupBoxPropertyBrowser::itemRemoved (QtBrowserItem * item) [protected], [virtual]
Implements QtAbstractPropertyBrowser .
References QtGroupBoxPropertyBrowserPrivate::propertyRemoved().
The documentation for this class was generated from the following files:
qtgroupboxpropertybrowser.h
qtgroupboxpropertybrowser.cpp