QtKeySequenceEdit Class Reference
#include <qtpropertybrowserutils_p.h>
Public Slots
void setKeySequence (const QKeySequence &sequence)
Signals
void keySequenceChanged (const QKeySequence &sequence)
Public Member Functions
QtKeySequenceEdit (QWidget *parent=0)
QKeySequence keySequence () const
bool eventFilter (QObject *o, QEvent *e)
Protected Member Functions
void focusInEvent (QFocusEvent *e)
void focusOutEvent (QFocusEvent *e)
void keyPressEvent (QKeyEvent *e)
void keyReleaseEvent (QKeyEvent *e)
void paintEvent (QPaintEvent *)
bool event (QEvent *e)
Constructor & Destructor Documentation
QtKeySequenceEdit::QtKeySequenceEdit (QWidget * parent = 0)
Member Function Documentation
bool QtKeySequenceEdit::event (QEvent * e) [protected]
bool QtKeySequenceEdit::eventFilter (QObject * o, QEvent * e)
References keySequenceChanged(), and setKeySequence().
void QtKeySequenceEdit::focusInEvent (QFocusEvent * e) [protected]
void QtKeySequenceEdit::focusOutEvent (QFocusEvent * e) [protected]
void QtKeySequenceEdit::keyPressEvent (QKeyEvent * e) [protected]
void QtKeySequenceEdit::keyReleaseEvent (QKeyEvent * e) [protected]
QKeySequence QtKeySequenceEdit::keySequence () const
void QtKeySequenceEdit::keySequenceChanged (const QKeySequence & sequence) [signal]
Referenced by eventFilter().
void QtKeySequenceEdit::paintEvent (QPaintEvent *) [protected]
void QtKeySequenceEdit::setKeySequence (const QKeySequence & sequence) [slot]
Referenced by QtKeySequenceEditorFactory::createEditor(), eventFilter(), and QtKeySequenceEditorFactoryPrivate::slotPropertyChanged().
The documentation for this class was generated from the following files:
qtpropertybrowserutils_p.h
qtpropertybrowserutils.cpp