QtButtonPropertyBrowserPrivate Class Reference
Classes
struct WidgetItem
Public Member Functions
void init (QWidget *parent)
void propertyInserted (QtBrowserItem *index, QtBrowserItem *afterIndex)
void propertyRemoved (QtBrowserItem *index)
void propertyChanged (QtBrowserItem *index)
QWidget * createEditor (QtProperty *property, QWidget *parent) const
void slotEditorDestroyed ()
void slotUpdate ()
void slotToggled (bool checked)
Member Function Documentation
QWidget* QtButtonPropertyBrowserPrivate::createEditor (QtProperty * property, QWidget * parent) const [inline]
References QtAbstractPropertyBrowser::createEditor(), slotEditorDestroyed(), slotToggled(), and slotUpdate().
Referenced by propertyInserted().
void QtButtonPropertyBrowserPrivate::init (QWidget * parent)
Referenced by QtButtonPropertyBrowser::QtButtonPropertyBrowser().
void QtButtonPropertyBrowserPrivate::propertyChanged (QtBrowserItem * index)
References QtButtonPropertyBrowserPrivate::WidgetItem::button, QtButtonPropertyBrowserPrivate::WidgetItem::label, QtButtonPropertyBrowserPrivate::WidgetItem::widget, and QtButtonPropertyBrowserPrivate::WidgetItem::widgetLabel.
Referenced by QtButtonPropertyBrowser::itemChanged().
void QtButtonPropertyBrowserPrivate::propertyInserted (QtBrowserItem * index, QtBrowserItem * afterIndex)
References QtButtonPropertyBrowserPrivate::WidgetItem::button, QtButtonPropertyBrowserPrivate::WidgetItem::children, QtButtonPropertyBrowserPrivate::WidgetItem::container, createEditor(), QtProperty::hasValue(), QtButtonPropertyBrowserPrivate::WidgetItem::label, QtButtonPropertyBrowserPrivate::WidgetItem::layout, QtButtonPropertyBrowserPrivate::WidgetItem::parent, QtBrowserItem::parent(), QtBrowserItem::property(), slotEditorDestroyed(), slotToggled(), QtButtonPropertyBrowserPrivate::WidgetItem::widget, QtButtonPropertyBrowserPrivate::WidgetItem::WidgetItem(), and QtButtonPropertyBrowserPrivate::WidgetItem::widgetLabel.
Referenced by QtButtonPropertyBrowser::itemInserted().
void QtButtonPropertyBrowserPrivate::propertyRemoved (QtBrowserItem * index)
References QtButtonPropertyBrowserPrivate::WidgetItem::button, QtButtonPropertyBrowserPrivate::WidgetItem::children, QtButtonPropertyBrowserPrivate::WidgetItem::container, QtButtonPropertyBrowserPrivate::WidgetItem::label, QtButtonPropertyBrowserPrivate::WidgetItem::layout, QtButtonPropertyBrowserPrivate::WidgetItem::parent, QtButtonPropertyBrowserPrivate::WidgetItem::widget, and QtButtonPropertyBrowserPrivate::WidgetItem::widgetLabel.
Referenced by QtButtonPropertyBrowser::itemRemoved().
void QtButtonPropertyBrowserPrivate::slotEditorDestroyed ()
Referenced by createEditor(), and propertyInserted().
void QtButtonPropertyBrowserPrivate::slotToggled (bool checked)
References slotUpdate().
Referenced by createEditor(), and propertyInserted().
void QtButtonPropertyBrowserPrivate::slotUpdate ()
References QtButtonPropertyBrowserPrivate::WidgetItem::button, QtButtonPropertyBrowserPrivate::WidgetItem::container, QtButtonPropertyBrowserPrivate::WidgetItem::expanded, QtButtonPropertyBrowserPrivate::WidgetItem::label, QtButtonPropertyBrowserPrivate::WidgetItem::layout, QtButtonPropertyBrowserPrivate::WidgetItem::parent, QtButtonPropertyBrowserPrivate::WidgetItem::widget, and QtButtonPropertyBrowserPrivate::WidgetItem::widgetLabel.
Referenced by createEditor(), and slotToggled().
The documentation for this class was generated from the following file:
qtbuttonpropertybrowser.cpp