QtPointPropertyManager Class Reference
The QtPointPropertyManager provides and manages QPoint properties.
#include <qtpropertymanager.h>
Public Slots
void setValue (QtProperty *property, const QPoint &val)
Signals
void valueChanged (QtProperty *property, const QPoint &val)
Public Member Functions
QtPointPropertyManager (QObject *parent=0)
~QtPointPropertyManager ()
QtIntPropertyManager * subIntPropertyManager () const
QPoint value (const QtProperty *property) const
Protected Member Functions
QString valueText (const QtProperty *property) const
virtual void initializeProperty (QtProperty *property)
virtual void uninitializeProperty (QtProperty *property)
Detailed Description
A point property has nested x and y subproperties. The top-level property's value can be retrieved using the value() function, and set using the setValue() slot.
The subproperties are created by a QtIntPropertyManager object. This manager can be retrieved using the subIntPropertyManager() function. In order to provide editing widgets for the subproperties in a property browser widget, this manager must be associated with an editor factory.
In addition, QtPointPropertyManager provides the valueChanged() signal which is emitted whenever a property created by this manager changes.
See also
QtAbstractPropertyManager, QtIntPropertyManager, QtPointFPropertyManager
Constructor & Destructor Documentation
QtPointPropertyManager::QtPointPropertyManager (QObject * parent = 0)
Creates a manager with the given parent.
References QtPointPropertyManagerPrivate::m_intPropertyManager, QtAbstractPropertyManager::propertyDestroyed(), and valueChanged().
QtPointPropertyManager::~QtPointPropertyManager ()
Destroys this manager, and all the properties it has created.
References QtAbstractPropertyManager::clear().
Member Function Documentation
void QtPointPropertyManager::initializeProperty (QtProperty * property) [protected], [virtual]
Implements QtAbstractPropertyManager .
References QtAbstractPropertyManager::addProperty(), QtProperty::addSubProperty(), QtPointPropertyManagerPrivate::m_intPropertyManager, QtPointPropertyManagerPrivate::m_propertyToX, QtPointPropertyManagerPrivate::m_propertyToY, QtPointPropertyManagerPrivate::m_values, QtPointPropertyManagerPrivate::m_xToProperty, QtPointPropertyManagerPrivate::m_yToProperty, QtProperty::setPropertyName(), and QtIntPropertyManager::setValue().
void QtPointPropertyManager::setValue (QtProperty * property, const QPoint & value) [slot]
Sets the value of the given property to value. Nested properties are updated automatically.
See also
value(), valueChanged()
References QtPointPropertyManagerPrivate::m_intPropertyManager, QtPointPropertyManagerPrivate::m_propertyToX, QtPointPropertyManagerPrivate::m_propertyToY, QtPointPropertyManagerPrivate::m_values, QtAbstractPropertyManager::propertyChanged(), QtIntPropertyManager::setValue(), and valueChanged().
QtIntPropertyManager * QtPointPropertyManager::subIntPropertyManager () const
Returns the manager that creates the nested x and y subproperties.
In order to provide editing widgets for the subproperties in a property browser widget, this manager must be associated with an editor factory.
See also
QtAbstractPropertyBrowser::setFactoryForManager()
References QtPointPropertyManagerPrivate::m_intPropertyManager.
Referenced by QtVariantPropertyManager::QtVariantPropertyManager().
void QtPointPropertyManager::uninitializeProperty (QtProperty * property) [protected], [virtual]
Reimplemented from QtAbstractPropertyManager .
References QtPointPropertyManagerPrivate::m_propertyToX, QtPointPropertyManagerPrivate::m_propertyToY, QtPointPropertyManagerPrivate::m_values, QtPointPropertyManagerPrivate::m_xToProperty, and QtPointPropertyManagerPrivate::m_yToProperty.
QPoint QtPointPropertyManager::value (const QtProperty * property) const
Returns the given property's value.
If the given property is not managed by this manager, this function returns a point with coordinates (0, 0).
See also
setValue()
References QtPointPropertyManagerPrivate::m_values.
void QtPointPropertyManager::valueChanged (QtProperty * property, const QPoint & value) [signal]
This signal is emitted whenever a property created by this manager changes its value, passing a pointer to the property and the new value as parameters.
See also
setValue()
Referenced by QtPointPropertyManager(), and setValue().
QString QtPointPropertyManager::valueText (const QtProperty * property) const [protected], [virtual]
Reimplemented from QtAbstractPropertyManager .
References QtPointPropertyManagerPrivate::m_values.
The documentation for this class was generated from the following files:
qtpropertymanager.h
qtpropertymanager.cpp