CircleItemSet Class Reference
#include <circleitemset.h>
Public Slots
void setMaxRadius (double r)
void setNumDifferentRadius (int nr)
void setBufferSize (int bSize)
void setColorList (const QList< QColor > &colors)
void setAlphaChannel (int alpha)
void setRadiusScaleDivider (double factor)
void setMaxRadius (double r)
void setNumDifferentRadius (int nr)
void setBufferSize (int bSize)
void setColorList (const QList< QColor > &colors)
void setAlphaChannel (int alpha)
Public Member Functions
 CircleItemSet (CurveItem * curveItem, int bufferSize, qreal maxRadius=50, int numDifferentRadius=10)
QList< QColor > colorList () const
int bufferSize () const
int numDifferentRadius () const
double maxRadius () const
int alphaChannel () const
void setGradientEnabled (bool en)
bool gradientEnabled () const
void setBorderEnabled (bool en)
bool borderEnabled () const
virtual void bufferSizeChanged (int newSize)
virtual void draw (SceneCurve *curve, PlotSceneWidget *plot, QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget=0)
the drawing method.
virtual CurveItem * curveItem () const
virtual QSizeF elementSize () const
the size of each drawn element
 CircleItemSet (CurveItem * curveItem, int bufferSize, qreal maxRadius=30, int numDifferentRadius=10)
virtual ~CircleItemSet ()
virtual int type () const
QList< QColor > colorList () const
int bufferSize () const
int numDifferentRadius () const
double maxRadius () const
double radiusScaleDivider () const
int alphaChannel () const
void setGradientEnabled (bool en)
bool gradientEnabled () const
void setBorderEnabled (bool en)
bool borderEnabled () const
virtual void bufferSizeChanged (int newSize)
virtual void draw (SceneCurve *curve, PlotSceneWidget *plot, QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget=0)
the drawing method.
virtual CurveItem * curveItem () const
virtual QSizeF elementSize () const
the size of each drawn element
Protected Member Functions
QColor mCalculateColor (int idx, int nMax, int nStepsPerInterval) const
Properties
int numDifferentRadius
double maxRadius
int alphaChannel
bool gradientEnabled
bool borderEnabled
Additional Inherited Members
Constructor & Destructor Documentation
CircleItemSet() [1/2]
CircleItemSet::CircleItemSet (CurveItem * curveItem, int bufferSize, qreal maxRadius = 50, int numDifferentRadius = 10)
test
References Elettra::black, bufferSize(), KLIGHTGRAY, maxRadius, numDifferentRadius, and setColorList().
CircleItemSet() [2/2]
CircleItemSet::CircleItemSet (CurveItem * curveItem, int bufferSize, qreal maxRadius = 30, int numDifferentRadius = 10)
~CircleItemSet()
CircleItemSet::~CircleItemSet () [virtual]
References CurveItem::removeItemPainterInterface().
Member Function Documentation
alphaChannel() [1/2]
int CircleItemSet::alphaChannel () const [inline]
alphaChannel() [2/2]
int CircleItemSet::alphaChannel () const [inline]
borderEnabled() [1/2]
bool CircleItemSet::borderEnabled () const
borderEnabled() [2/2]
bool CircleItemSet::borderEnabled () const
bufferSize() [1/2]
int CircleItemSet::bufferSize () const [inline]
Referenced by CircleItemSet().
bufferSize() [2/2]
int CircleItemSet::bufferSize () const [inline]
bufferSizeChanged() [1/2]
void CircleItemSet::bufferSizeChanged (int newSize) [virtual]
bufferSizeChanged() [2/2]
virtual void CircleItemSet::bufferSizeChanged (int newSize) [virtual]
colorList() [1/2]
QList<QColor> CircleItemSet::colorList () const [inline]
colorList() [2/2]
QList<QColor> CircleItemSet::colorList () const [inline]
curveItem() [1/2]
 CurveItem * CircleItemSet::curveItem () const [virtual]
Implements ItemPainterInterface .
curveItem() [2/2]
virtual CurveItem* CircleItemSet::curveItem () const [virtual]
Implements ItemPainterInterface .
draw() [1/2]
void CircleItemSet::draw (SceneCurve * curve, PlotSceneWidget * plot, QPainter * painter, const QStyleOptionGraphicsItem * option, QWidget * widget = 0) [virtual]
This method is invoked by CurveItem inside paint method. You can obtain the points of the curve in scene coordinates by calling curve->points and the size of the points by means of curve->dataSize. It may be necessary to call painter->save() and painter->restore() at the beginning and end of the drawing. Each draw method of each installed ItemPainterInterface is actually invoked in sequence without saving and restoring the painter state for you.
See also
CurveItem
LinePainter
DotsPainter
Implements ItemPainterInterface .
References SceneCurve::dataSize(), and SceneCurve::points().
draw() [2/2]
virtual void CircleItemSet::draw (SceneCurve * curve, PlotSceneWidget * plot, QPainter * painter, const QStyleOptionGraphicsItem * option, QWidget * widget = 0) [virtual]
This method is invoked by CurveItem inside paint method. You can obtain the points of the curve in scene coordinates by calling curve->points and the size of the points by means of curve->dataSize. It may be necessary to call painter->save() and painter->restore() at the beginning and end of the drawing. Each draw method of each installed ItemPainterInterface is actually invoked in sequence without saving and restoring the painter state for you.
See also
CurveItem
LinePainter
DotsPainter
Implements ItemPainterInterface .
elementSize() [1/2]
QSizeF CircleItemSet::elementSize () const [virtual]
This size is used by the classes that use ItemPainterInterface to know how much extra space is needed in order to calculate the bounding rect of the CurveItem or other geometrical properties.
For instance, if you are drawing circles, then this method should return the radius of the circle, so that CurveItem knows how much space has to be added to the curve bounds in order to correcly draw the items.
If you are drawing lines, then this size can be 0x0 since the connecting lines do not require extra space to be calculated. If you use a particular pen width, then you may want to return its width in order to be sure that CurveItem takes care of this space.
See also
CurveItem
Implements ItemPainterInterface .
elementSize() [2/2]
virtual QSizeF CircleItemSet::elementSize () const [virtual]
This size is used by the classes that use ItemPainterInterface to know how much extra space is needed in order to calculate the bounding rect of the CurveItem or other geometrical properties.
For instance, if you are drawing circles, then this method should return the radius of the circle, so that CurveItem knows how much space has to be added to the curve bounds in order to correcly draw the items.
If you are drawing lines, then this size can be 0x0 since the connecting lines do not require extra space to be calculated. If you use a particular pen width, then you may want to return its width in order to be sure that CurveItem takes care of this space.
See also
CurveItem
Implements ItemPainterInterface .
gradientEnabled() [1/2]
bool CircleItemSet::gradientEnabled () const
gradientEnabled() [2/2]
bool CircleItemSet::gradientEnabled () const
maxRadius() [1/2]
double CircleItemSet::maxRadius () const [inline]
maxRadius() [2/2]
double CircleItemSet::maxRadius () const [inline]
mCalculateColor()
QColor CircleItemSet::mCalculateColor (int idx, int nMax, int nStepsPerInterval) const [protected]
numDifferentRadius() [1/2]
int CircleItemSet::numDifferentRadius () const [inline]
numDifferentRadius() [2/2]
int CircleItemSet::numDifferentRadius () const [inline]
radiusScaleDivider()
double CircleItemSet::radiusScaleDivider () const [inline]
setAlphaChannel [1/2]
void CircleItemSet::setAlphaChannel (int alpha) [inline], [slot]
setAlphaChannel [2/2]
void CircleItemSet::setAlphaChannel (int alpha) [inline], [slot]
setBorderEnabled() [1/2]
void CircleItemSet::setBorderEnabled (bool en)
setBorderEnabled() [2/2]
void CircleItemSet::setBorderEnabled (bool en)
setBufferSize [1/2]
void CircleItemSet::setBufferSize (int bSize) [inline], [slot]
setBufferSize [2/2]
void CircleItemSet::setBufferSize (int bSize) [inline], [slot]
setColorList [1/2]
void CircleItemSet::setColorList (const QList< QColor > & colors) [inline], [slot]
Referenced by AgingCircles::AgingCircles(), and CircleItemSet().
setColorList [2/2]
void CircleItemSet::setColorList (const QList< QColor > & colors) [inline], [slot]
setGradientEnabled() [1/2]
void CircleItemSet::setGradientEnabled (bool en)
setGradientEnabled() [2/2]
void CircleItemSet::setGradientEnabled (bool en)
setMaxRadius [1/2]
void CircleItemSet::setMaxRadius (double r) [inline], [slot]
setMaxRadius [2/2]
void CircleItemSet::setMaxRadius (double r) [inline], [slot]
setNumDifferentRadius [1/2]
void CircleItemSet::setNumDifferentRadius (int nr) [inline], [slot]
setNumDifferentRadius [2/2]
void CircleItemSet::setNumDifferentRadius (int nr) [inline], [slot]
setRadiusScaleDivider
void CircleItemSet::setRadiusScaleDivider (double factor) [inline], [slot]
type()
int CircleItemSet::type () const [virtual]
Implements ItemPainterInterface .
References ItemPainterInterface::CircleItemSet.
Property Documentation
alphaChannel
int CircleItemSet::alphaChannel [read], [write]
borderEnabled
bool CircleItemSet::borderEnabled [read], [write]
gradientEnabled
bool CircleItemSet::gradientEnabled [read], [write]
maxRadius
double CircleItemSet::maxRadius [read], [write]
Referenced by CircleItemSet().
numDifferentRadius
int CircleItemSet::numDifferentRadius [read], [write]
Referenced by CircleItemSet().
The documentation for this class was generated from the following files:
 circles/circleitemset.h
 circles/circleitemset.cpp