QtPropertyBrowserUtils Class Reference
#include <qtpropertybrowserutils_p.h>
Static Public Member Functions
static QPixmap brushValuePixmap (const QBrush &b)
static QIcon brushValueIcon (const QBrush &b)
static QString colorValueText (const QColor &c)
static QPixmap fontValuePixmap (const QFont &f)
static QIcon fontValueIcon (const QFont &f)
static QString fontValueText (const QFont &f)
Member Function Documentation
QIcon QtPropertyBrowserUtils::brushValueIcon (const QBrush & b) [static]
Referenced by QtColorPropertyManager::valueIcon().
QPixmap QtPropertyBrowserUtils::brushValuePixmap (const QBrush & b) [static]
Referenced by QtColorEditWidget::QtColorEditWidget(), and QtColorEditWidget::setValue().
QString QtPropertyBrowserUtils::colorValueText (const QColor & c) [static]
Referenced by QtColorEditWidget::QtColorEditWidget(), QtColorEditWidget::setValue(), and QtColorPropertyManager::valueText().
QIcon QtPropertyBrowserUtils::fontValueIcon (const QFont & f) [static]
Referenced by QtFontPropertyManager::valueIcon().
QPixmap QtPropertyBrowserUtils::fontValuePixmap (const QFont & f) [static]
Referenced by QtFontEditWidget::QtFontEditWidget(), and QtFontEditWidget::setValue().
QString QtPropertyBrowserUtils::fontValueText (const QFont & f) [static]
Referenced by QtFontEditWidget::QtFontEditWidget(), QtFontEditWidget::setValue(), and QtFontPropertyManager::valueText().
The documentation for this class was generated from the following files:
qtpropertybrowserutils_p.h
qtpropertybrowserutils.cpp