QtButtonPropertyBrowser Class Reference
The QtButtonPropertyBrowser class provides a drop down QToolButton based property browser.
#include <qtbuttonpropertybrowser.h>
Signals
void collapsed (QtBrowserItem *item)
void expanded (QtBrowserItem *item)
Public Member Functions
QtButtonPropertyBrowser (QWidget *parent=0)
~QtButtonPropertyBrowser ()
void setExpanded (QtBrowserItem *item, bool expanded)
bool isExpanded (QtBrowserItem *item) const
Protected Member Functions
virtual void itemInserted (QtBrowserItem *item, QtBrowserItem *afterItem)
virtual void itemRemoved (QtBrowserItem *item)
virtual void itemChanged (QtBrowserItem *item)
Additional Inherited Members
Detailed Description
A property browser is a widget that enables the user to edit a given set of properties. Each property is represented by a label specifying the property's name, and an editing widget (e.g. a line edit or a combobox) holding its value. A property can have zero or more subproperties.
QtButtonPropertyBrowser provides drop down button for all nested properties, i.e. subproperties are enclosed by a container associated with the drop down button. The parent property's name is displayed as button text. For example:
Use the QtAbstractPropertyBrowser API to add, insert and remove properties from an instance of the QtButtonPropertyBrowser class. The properties themselves are created and managed by implementations of the QtAbstractPropertyManager class.
See also
QtTreePropertyBrowser, QtAbstractPropertyBrowser
Constructor & Destructor Documentation
QtButtonPropertyBrowser::QtButtonPropertyBrowser (QWidget * parent = 0)
Creates a property browser with the given parent.
References QtButtonPropertyBrowserPrivate::init().
QtButtonPropertyBrowser::~QtButtonPropertyBrowser ()
Destroys this property browser.
Note that the properties that were inserted into this browser are not destroyed since they may still be used in other browsers. The properties are owned by the manager that created them.
See also
QtProperty, QtAbstractPropertyManager
Member Function Documentation
void QtButtonPropertyBrowser::collapsed (QtBrowserItem * item) [signal]
This signal is emitted when the item is collapsed.
See also
expanded(), setExpanded()
void QtButtonPropertyBrowser::expanded (QtBrowserItem * item) [signal]
This signal is emitted when the item is expanded.
See also
collapsed(), setExpanded()
bool QtButtonPropertyBrowser::isExpanded (QtBrowserItem * item) const
Returns true if the item is expanded; otherwise returns false.
See also
setExpanded()
References QtButtonPropertyBrowserPrivate::WidgetItem::expanded.
void QtButtonPropertyBrowser::itemChanged (QtBrowserItem * item) [protected], [virtual]
Implements QtAbstractPropertyBrowser .
References QtButtonPropertyBrowserPrivate::propertyChanged().
void QtButtonPropertyBrowser::itemInserted (QtBrowserItem * item, QtBrowserItem * afterItem) [protected], [virtual]
Implements QtAbstractPropertyBrowser .
References QtButtonPropertyBrowserPrivate::propertyInserted().
void QtButtonPropertyBrowser::itemRemoved (QtBrowserItem * item) [protected], [virtual]
Implements QtAbstractPropertyBrowser .
References QtButtonPropertyBrowserPrivate::propertyRemoved().
void QtButtonPropertyBrowser::setExpanded (QtBrowserItem * item, bool expanded)
Sets the item to either collapse or expanded, depending on the value of expanded.
See also
isExpanded(), expanded(), collapsed()
The documentation for this class was generated from the following files:
qtbuttonpropertybrowser.h
qtbuttonpropertybrowser.cpp