QtStringPropertyManager Class Reference
The QtStringPropertyManager provides and manages QString properties.
#include <qtpropertymanager.h>
Public Slots
void setValue (QtProperty *property, const QString &val)
void setRegExp (QtProperty *property, const QRegExp &regExp)
Signals
void valueChanged (QtProperty *property, const QString &val)
void regExpChanged (QtProperty *property, const QRegExp &regExp)
Public Member Functions
QtStringPropertyManager (QObject *parent=0)
~QtStringPropertyManager ()
QString value (const QtProperty *property) const
QRegExp regExp (const QtProperty *property) const
Protected Member Functions
QString valueText (const QtProperty *property) const
virtual void initializeProperty (QtProperty *property)
virtual void uninitializeProperty (QtProperty *property)
Detailed Description
A string property's value can be retrieved using the value() function, and set using the setValue() slot.
The current value can be checked against a regular expression. To set the regular expression use the setRegExp() slot, use the regExp() function to retrieve the currently set expression.
In addition, QtStringPropertyManager provides the valueChanged() signal which is emitted whenever a property created by this manager changes, and the regExpChanged() signal which is emitted whenever such a property changes its currently set regular expression.
See also
QtAbstractPropertyManager, QtLineEditFactory
Constructor & Destructor Documentation
QtStringPropertyManager::QtStringPropertyManager (QObject * parent = 0)
Creates a manager with the given parent.
QtStringPropertyManager::~QtStringPropertyManager ()
Destroys this manager, and all the properties it has created.
References QtAbstractPropertyManager::clear().
Member Function Documentation
void QtStringPropertyManager::initializeProperty (QtProperty * property) [protected], [virtual]
Implements QtAbstractPropertyManager .
References QtStringPropertyManagerPrivate::m_values.
QRegExp QtStringPropertyManager::regExp (const QtProperty * property) const
Returns the given property's currently set regular expression.
If the given property is not managed by this manager, this function returns an empty expression.
See also
setRegExp()
References QtStringPropertyManagerPrivate::m_values, and QtStringPropertyManagerPrivate::Data::regExp.
Referenced by QtLineEditFactory::createEditor(), and setRegExp().
void QtStringPropertyManager::regExpChanged (QtProperty * property, const QRegExp & regExp) [signal]
This signal is emitted whenever a property created by this manager changes its currenlty set regular expression, passing a pointer to the property and the new regExp as parameters.
See also
setRegExp()
Referenced by setRegExp().
void QtStringPropertyManager::setRegExp (QtProperty * property, const QRegExp & regExp) [slot]
Sets the regular expression of the given property to regExp.
See also
regExp(), setValue(), regExpChanged()
References QtStringPropertyManagerPrivate::m_values, regExp(), QtStringPropertyManagerPrivate::Data::regExp, and regExpChanged().
void QtStringPropertyManager::setValue (QtProperty * property, const QString & value) [slot]
Sets the value of the given property to value.
If the specified value doesn't match the given property's regular expression, this function does nothing.
See also
value(), setRegExp(), valueChanged()
References QtStringPropertyManagerPrivate::m_values, QtAbstractPropertyManager::propertyChanged(), QtStringPropertyManagerPrivate::Data::regExp, QtStringPropertyManagerPrivate::Data::val, and valueChanged().
Referenced by QtLineEditFactoryPrivate::slotSetValue().
void QtStringPropertyManager::uninitializeProperty (QtProperty * property) [protected], [virtual]
Reimplemented from QtAbstractPropertyManager .
References QtStringPropertyManagerPrivate::m_values.
QString QtStringPropertyManager::value (const QtProperty * property) const
Returns the given property's value.
If the given property is not managed by this manager, this function returns an empty string.
See also
setValue()
References QtStringPropertyManagerPrivate::m_values.
Referenced by QtLineEditFactory::createEditor().
void QtStringPropertyManager::valueChanged (QtProperty * property, const QString & value) [signal]
This signal is emitted whenever a property created by this manager changes its value, passing a pointer to the property and the new value as parameters.
See also
setValue()
Referenced by setValue().
QString QtStringPropertyManager::valueText (const QtProperty * property) const [protected], [virtual]
Reimplemented from QtAbstractPropertyManager .
References QtStringPropertyManagerPrivate::m_values.
The documentation for this class was generated from the following files:
qtpropertymanager.h
qtpropertymanager.cpp