QtPropertyEditorDelegate Class Reference
Public Member Functions
QtPropertyEditorDelegate (QObject *parent=0)
void setEditorPrivate (QtTreePropertyBrowserPrivate *editorPrivate)
QWidget * createEditor (QWidget *parent, const QStyleOptionViewItem &option, const QModelIndex &index) const
void updateEditorGeometry (QWidget *editor, const QStyleOptionViewItem &option, const QModelIndex &index) const
void paint (QPainter *painter, const QStyleOptionViewItem &option, const QModelIndex &index) const
QSize sizeHint (const QStyleOptionViewItem &option, const QModelIndex &index) const
void setModelData (QWidget *, QAbstractItemModel *, const QModelIndex &) const
void setEditorData (QWidget *, const QModelIndex &) const
bool eventFilter (QObject *object, QEvent *event)
void closeEditor (QtProperty *property)
QTreeWidgetItem * editedItem () const
Protected Member Functions
void drawDecoration (QPainter *painter, const QStyleOptionViewItem &option, const QRect &rect, const QPixmap &pixmap) const
void drawDisplay (QPainter *painter, const QStyleOptionViewItem &option, const QRect &rect, const QString &text) const
Constructor & Destructor Documentation
QtPropertyEditorDelegate::QtPropertyEditorDelegate (QObject * parent = 0) [inline]
Member Function Documentation
void QtPropertyEditorDelegate::closeEditor (QtProperty * property)
Referenced by QtTreePropertyBrowserPrivate::disableItem().
QWidget * QtPropertyEditorDelegate::createEditor (QWidget * parent, const QStyleOptionViewItem & option, const QModelIndex & index) const
void QtPropertyEditorDelegate::drawDecoration (QPainter * painter, const QStyleOptionViewItem & option, const QRect & rect, const QPixmap & pixmap) const [protected]
void QtPropertyEditorDelegate::drawDisplay (QPainter * painter, const QStyleOptionViewItem & option, const QRect & rect, const QString & text) const [protected]
QTreeWidgetItem* QtPropertyEditorDelegate::editedItem () const [inline]
Referenced by QtTreePropertyBrowserPrivate::editedItem().
bool QtPropertyEditorDelegate::eventFilter (QObject * object, QEvent * event)
void QtPropertyEditorDelegate::paint (QPainter * painter, const QStyleOptionViewItem & option, const QModelIndex & index) const
References QtProperty::hasValue().
void QtPropertyEditorDelegate::setEditorData (QWidget * , const QModelIndex &) const [inline]
void QtPropertyEditorDelegate::setEditorPrivate (QtTreePropertyBrowserPrivate * editorPrivate) [inline]
Referenced by QtTreePropertyBrowserPrivate::init().
void QtPropertyEditorDelegate::setModelData (QWidget * , QAbstractItemModel * , const QModelIndex &) const [inline]
QSize QtPropertyEditorDelegate::sizeHint (const QStyleOptionViewItem & option, const QModelIndex & index) const
void QtPropertyEditorDelegate::updateEditorGeometry (QWidget * editor, const QStyleOptionViewItem & option, const QModelIndex & index) const
The documentation for this class was generated from the following file:
qttreepropertybrowser.cpp