QtKeySequenceEditorFactory Class Reference
The QtKeySequenceEditorFactory class provides editor widgets for properties created by QtKeySequencePropertyManager objects.
#include <qteditorfactory.h>
Public Member Functions
QtKeySequenceEditorFactory (QObject *parent=0)
~QtKeySequenceEditorFactory ()
Protected Member Functions
void connectPropertyManager (QtKeySequencePropertyManager *manager)
QWidget * createEditor (QtKeySequencePropertyManager *manager, QtProperty *property, QWidget *parent)
void disconnectPropertyManager (QtKeySequencePropertyManager *manager)
Additional Inherited Members
Detailed Description
See also
QtAbstractEditorFactory
Constructor & Destructor Documentation
QtKeySequenceEditorFactory::QtKeySequenceEditorFactory (QObject * parent = 0)
Creates a factory with the given parent.
QtKeySequenceEditorFactory::~QtKeySequenceEditorFactory ()
Destroys this factory, and all the widgets it has created.
References EditorFactoryPrivate< Editor >::m_editorToProperty.
Member Function Documentation
void QtKeySequenceEditorFactory::connectPropertyManager (QtKeySequencePropertyManager * manager) [protected], [virtual]
Connects this factory to the given manager's signals. The PropertyManager type is a template argument class, and represents the chosen QtAbstractPropertyManager subclass.
This function is used internally by the addPropertyManager() function, and makes it possible to update an editing widget when the associated property's data changes. This is typically done in custom slots responding to the signals emitted by the property's manager, e.g. QtIntPropertyManager::valueChanged() and QtIntPropertyManager::rangeChanged().
See also
propertyManagers(), disconnectPropertyManager()
Implements QtAbstractEditorFactory< QtKeySequencePropertyManager > .
QWidget * QtKeySequenceEditorFactory::createEditor (QtKeySequencePropertyManager * manager, QtProperty * property, QWidget * parent) [protected], [virtual]
Creates an editing widget with the given parent for the specified property created by the given manager. The PropertyManager type is a template argument class, and represents the chosen QtAbstractPropertyManager subclass.
This function must be implemented in derived classes: It is recommended to store a pointer to the widget and map it to the given property, since the widget must be updated whenever the associated property's data changes. This is typically done in custom slots responding to the signals emitted by the property's manager, e.g. QtIntPropertyManager::valueChanged() and QtIntPropertyManager::rangeChanged().
See also
connectPropertyManager()
Implements QtAbstractEditorFactory< QtKeySequencePropertyManager > .
References EditorFactoryPrivate< Editor >::createEditor(), QtKeySequenceEdit::setKeySequence(), and QtKeySequencePropertyManager::value().
void QtKeySequenceEditorFactory::disconnectPropertyManager (QtKeySequencePropertyManager * manager) [protected], [virtual]
Disconnects this factory from the given manager's signals. The PropertyManager type is a template argument class, and represents the chosen QtAbstractPropertyManager subclass.
This function is used internally by the removePropertyManager() function.
See also
propertyManagers(), connectPropertyManager()
Implements QtAbstractEditorFactory< QtKeySequencePropertyManager > .
The documentation for this class was generated from the following files:
qteditorfactory.h
qteditorfactory.cpp