QtCharPropertyManager Class Reference
The QtCharPropertyManager provides and manages QChar properties.
#include <qtpropertymanager.h>
Public Slots
void setValue (QtProperty *property, const QChar &val)
Signals
void valueChanged (QtProperty *property, const QChar &val)
Public Member Functions
QtCharPropertyManager (QObject *parent=0)
~QtCharPropertyManager ()
QChar value (const QtProperty *property) const
Protected Member Functions
QString valueText (const QtProperty *property) const
virtual void initializeProperty (QtProperty *property)
virtual void uninitializeProperty (QtProperty *property)
Detailed Description
A char's value can be retrieved using the value() function, and set using the setValue() slot.
In addition, QtCharPropertyManager provides the valueChanged() signal which is emitted whenever a property created by this manager changes.
See also
QtAbstractPropertyManager
Constructor & Destructor Documentation
QtCharPropertyManager::QtCharPropertyManager (QObject * parent = 0)
Creates a manager with the given parent.
QtCharPropertyManager::~QtCharPropertyManager ()
Destroys this manager, and all the properties it has created.
References QtAbstractPropertyManager::clear().
Member Function Documentation
void QtCharPropertyManager::initializeProperty (QtProperty * property) [protected], [virtual]
Implements QtAbstractPropertyManager .
References QtCharPropertyManagerPrivate::m_values.
void QtCharPropertyManager::setValue (QtProperty * property, const QChar & value) [slot]
Sets the value of the given property to value.
See also
value(), valueChanged()
References QtCharPropertyManagerPrivate::m_values, QtAbstractPropertyManager::propertyChanged(), and valueChanged().
Referenced by QtCharEditorFactoryPrivate::slotSetValue().
void QtCharPropertyManager::uninitializeProperty (QtProperty * property) [protected], [virtual]
Reimplemented from QtAbstractPropertyManager .
References QtCharPropertyManagerPrivate::m_values.
QChar QtCharPropertyManager::value (const QtProperty * property) const
Returns the given property's value.
If the given property is not managed by this manager, this function returns an null QChar object.
See also
setValue()
References QtCharPropertyManagerPrivate::m_values.
Referenced by QtCharEditorFactory::createEditor().
void QtCharPropertyManager::valueChanged (QtProperty * property, const QChar & value) [signal]
This signal is emitted whenever a property created by this manager changes its value, passing a pointer to the property and the new value as parameters.
Referenced by setValue().
QString QtCharPropertyManager::valueText (const QtProperty * property) const [protected], [virtual]
Reimplemented from QtAbstractPropertyManager .
References QtCharPropertyManagerPrivate::m_values.
The documentation for this class was generated from the following files:
qtpropertymanager.h
qtpropertymanager.cpp