QtScrollBarFactory Class Reference
The QtScrollBarFactory class provides QScrollBar widgets for properties created by QtIntPropertyManager objects.
#include <qteditorfactory.h>
Public Member Functions
QtScrollBarFactory (QObject *parent=0)
~QtScrollBarFactory ()
Protected Member Functions
void connectPropertyManager (QtIntPropertyManager *manager)
QWidget * createEditor (QtIntPropertyManager *manager, QtProperty *property, QWidget *parent)
void disconnectPropertyManager (QtIntPropertyManager *manager)
Additional Inherited Members
Detailed Description
See also
QtAbstractEditorFactory, QtIntPropertyManager
Constructor & Destructor Documentation
QtScrollBarFactory::QtScrollBarFactory (QObject * parent = 0)
Creates a factory with the given parent.
QtScrollBarFactory::~QtScrollBarFactory ()
Destroys this factory, and all the widgets it has created.
References EditorFactoryPrivate< Editor >::m_editorToProperty.
Member Function Documentation
void QtScrollBarFactory::connectPropertyManager (QtIntPropertyManager * manager) [protected], [virtual]
Connects this factory to the given manager's signals. The PropertyManager type is a template argument class, and represents the chosen QtAbstractPropertyManager subclass.
This function is used internally by the addPropertyManager() function, and makes it possible to update an editing widget when the associated property's data changes. This is typically done in custom slots responding to the signals emitted by the property's manager, e.g. QtIntPropertyManager::valueChanged() and QtIntPropertyManager::rangeChanged().
See also
propertyManagers(), disconnectPropertyManager()
Implements QtAbstractEditorFactory< QtIntPropertyManager > .
QWidget * QtScrollBarFactory::createEditor (QtIntPropertyManager * manager, QtProperty * property, QWidget * parent) [protected], [virtual]
Creates an editing widget with the given parent for the specified property created by the given manager. The PropertyManager type is a template argument class, and represents the chosen QtAbstractPropertyManager subclass.
This function must be implemented in derived classes: It is recommended to store a pointer to the widget and map it to the given property, since the widget must be updated whenever the associated property's data changes. This is typically done in custom slots responding to the signals emitted by the property's manager, e.g. QtIntPropertyManager::valueChanged() and QtIntPropertyManager::rangeChanged().
See also
connectPropertyManager()
Implements QtAbstractEditorFactory< QtIntPropertyManager > .
References EditorFactoryPrivate< Editor >::initializeEditor(), QtIntPropertyManager::maximum(), QtIntPropertyManager::minimum(), QtIntPropertyManager::singleStep(), and QtIntPropertyManager::value().
void QtScrollBarFactory::disconnectPropertyManager (QtIntPropertyManager * manager) [protected], [virtual]
Disconnects this factory from the given manager's signals. The PropertyManager type is a template argument class, and represents the chosen QtAbstractPropertyManager subclass.
This function is used internally by the removePropertyManager() function.
See also
propertyManagers(), connectPropertyManager()
Implements QtAbstractEditorFactory< QtIntPropertyManager > .
The documentation for this class was generated from the following files:
qteditorfactory.h
qteditorfactory.cpp