QtVariantPropertyManagerPrivate Class Reference
Public Member Functions
QtVariantPropertyManagerPrivate ()
void slotValueChanged (QtProperty *property, int val)
void slotRangeChanged (QtProperty *property, int min, int max)
void slotSingleStepChanged (QtProperty *property, int step)
void slotValueChanged (QtProperty *property, double val)
void slotRangeChanged (QtProperty *property, double min, double max)
void slotSingleStepChanged (QtProperty *property, double step)
void slotDecimalsChanged (QtProperty *property, int prec)
void slotValueChanged (QtProperty *property, bool val)
void slotValueChanged (QtProperty *property, const QString &val)
void slotRegExpChanged (QtProperty *property, const QRegExp &regExp)
void slotValueChanged (QtProperty *property, const QDate &val)
void slotRangeChanged (QtProperty *property, const QDate &min, const QDate &max)
void slotValueChanged (QtProperty *property, const QTime &val)
void slotValueChanged (QtProperty *property, const QDateTime &val)
void slotValueChanged (QtProperty *property, const QKeySequence &val)
void slotValueChanged (QtProperty *property, const QChar &val)
void slotValueChanged (QtProperty *property, const QLocale &val)
void slotValueChanged (QtProperty *property, const QPoint &val)
void slotValueChanged (QtProperty *property, const QPointF &val)
void slotValueChanged (QtProperty *property, const QSize &val)
void slotRangeChanged (QtProperty *property, const QSize &min, const QSize &max)
void slotValueChanged (QtProperty *property, const QSizeF &val)
void slotRangeChanged (QtProperty *property, const QSizeF &min, const QSizeF &max)
void slotValueChanged (QtProperty *property, const QRect &val)
void slotConstraintChanged (QtProperty *property, const QRect &val)
void slotValueChanged (QtProperty *property, const QRectF &val)
void slotConstraintChanged (QtProperty *property, const QRectF &val)
void slotValueChanged (QtProperty *property, const QColor &val)
void slotEnumChanged (QtProperty *property, int val)
void slotEnumNamesChanged (QtProperty *property, const QStringList &enumNames)
void slotEnumIconsChanged (QtProperty *property, const QMap< int, QIcon > &enumIcons)
void slotValueChanged (QtProperty *property, const QSizePolicy &val)
void slotValueChanged (QtProperty *property, const QFont &val)
void slotValueChanged (QtProperty *property, const QCursor &val)
void slotFlagChanged (QtProperty *property, int val)
void slotFlagNamesChanged (QtProperty *property, const QStringList &flagNames)
void slotPropertyInserted (QtProperty *property, QtProperty *parent, QtProperty *after)
void slotPropertyRemoved (QtProperty *property, QtProperty *parent)
void valueChanged (QtProperty *property, const QVariant &val)
int internalPropertyToType (QtProperty *property) const
QtVariantProperty * createSubProperty (QtVariantProperty *parent, QtVariantProperty *after, QtProperty *internal)
void removeSubProperty (QtVariantProperty *property)
Public Attributes
bool m_creatingProperty
bool m_creatingSubProperties
bool m_destroyingSubProperties
int m_propertyType
QMap< int, QtAbstractPropertyManager * > m_typeToPropertyManager
QMap< int, QMap< QString, int > > m_typeToAttributeToAttributeType
QMap< const QtProperty *, QPair< QtVariantProperty *, int > > m_propertyToType
QMap< int, int > m_typeToValueType
QMap< QtProperty *, QtVariantProperty * > m_internalToProperty
const QString m_constraintAttribute
const QString m_singleStepAttribute
const QString m_decimalsAttribute
const QString m_enumIconsAttribute
const QString m_enumNamesAttribute
const QString m_flagNamesAttribute
const QString m_maximumAttribute
const QString m_minimumAttribute
const QString m_regExpAttribute
Constructor & Destructor Documentation
QtVariantPropertyManagerPrivate::QtVariantPropertyManagerPrivate ()
Member Function Documentation
QtVariantProperty * QtVariantPropertyManagerPrivate::createSubProperty (QtVariantProperty * parent, QtVariantProperty * after, QtProperty * internal)
References QtVariantPropertyManager::addProperty(), QtProperty::insertSubProperty(), internalPropertyToType(), m_creatingSubProperties, m_internalToProperty, QtProperty::setPropertyName(), QtProperty::setStatusTip(), QtProperty::setToolTip(), and QtProperty::setWhatsThis().
Referenced by QtVariantPropertyManager::initializeProperty(), and slotPropertyInserted().
int QtVariantPropertyManagerPrivate::internalPropertyToType (QtProperty * property) const
References QtVariantPropertyManager::enumTypeId().
Referenced by createSubProperty().
void QtVariantPropertyManagerPrivate::removeSubProperty (QtVariantProperty * property)
References m_destroyingSubProperties, m_internalToProperty, and wrappedProperty().
Referenced by slotPropertyRemoved().
void QtVariantPropertyManagerPrivate::slotConstraintChanged (QtProperty * property, const QRect & val)
References QtVariantPropertyManager::attributeChanged(), m_constraintAttribute, and m_internalToProperty.
void QtVariantPropertyManagerPrivate::slotConstraintChanged (QtProperty * property, const QRectF & val)
References QtVariantPropertyManager::attributeChanged(), m_constraintAttribute, and m_internalToProperty.
void QtVariantPropertyManagerPrivate::slotDecimalsChanged (QtProperty * property, int prec)
References QtVariantPropertyManager::attributeChanged(), m_decimalsAttribute, and m_internalToProperty.
void QtVariantPropertyManagerPrivate::slotEnumChanged (QtProperty * property, int val)
void QtVariantPropertyManagerPrivate::slotEnumIconsChanged (QtProperty * property, const QMap< int, QIcon > & enumIcons)
References QtVariantPropertyManager::attributeChanged(), m_enumIconsAttribute, and m_internalToProperty.
void QtVariantPropertyManagerPrivate::slotEnumNamesChanged (QtProperty * property, const QStringList & enumNames)
References QtVariantPropertyManager::attributeChanged(), m_enumNamesAttribute, and m_internalToProperty.
void QtVariantPropertyManagerPrivate::slotFlagChanged (QtProperty * property, int val)
void QtVariantPropertyManagerPrivate::slotFlagNamesChanged (QtProperty * property, const QStringList & flagNames)
References QtVariantPropertyManager::attributeChanged(), m_flagNamesAttribute, and m_internalToProperty.
void QtVariantPropertyManagerPrivate::slotPropertyInserted (QtProperty * property, QtProperty * parent, QtProperty * after)
References createSubProperty(), m_creatingProperty, and m_internalToProperty.
void QtVariantPropertyManagerPrivate::slotPropertyRemoved (QtProperty * property, QtProperty * parent)
References m_internalToProperty, and removeSubProperty().
void QtVariantPropertyManagerPrivate::slotRangeChanged (QtProperty * property, int min, int max)
References QtVariantPropertyManager::attributeChanged(), m_internalToProperty, m_maximumAttribute, and m_minimumAttribute.
void QtVariantPropertyManagerPrivate::slotRangeChanged (QtProperty * property, double min, double max)
References QtVariantPropertyManager::attributeChanged(), m_internalToProperty, m_maximumAttribute, and m_minimumAttribute.
void QtVariantPropertyManagerPrivate::slotRangeChanged (QtProperty * property, const QDate & min, const QDate & max)
References QtVariantPropertyManager::attributeChanged(), m_internalToProperty, m_maximumAttribute, and m_minimumAttribute.
void QtVariantPropertyManagerPrivate::slotRangeChanged (QtProperty * property, const QSize & min, const QSize & max)
References QtVariantPropertyManager::attributeChanged(), m_internalToProperty, m_maximumAttribute, and m_minimumAttribute.
void QtVariantPropertyManagerPrivate::slotRangeChanged (QtProperty * property, const QSizeF & min, const QSizeF & max)
References QtVariantPropertyManager::attributeChanged(), m_internalToProperty, m_maximumAttribute, and m_minimumAttribute.
void QtVariantPropertyManagerPrivate::slotRegExpChanged (QtProperty * property, const QRegExp & regExp)
References QtVariantPropertyManager::attributeChanged(), m_internalToProperty, and m_regExpAttribute.
void QtVariantPropertyManagerPrivate::slotSingleStepChanged (QtProperty * property, int step)
References QtVariantPropertyManager::attributeChanged(), m_internalToProperty, and m_singleStepAttribute.
void QtVariantPropertyManagerPrivate::slotSingleStepChanged (QtProperty * property, double step)
References QtVariantPropertyManager::attributeChanged(), m_internalToProperty, and m_singleStepAttribute.
void QtVariantPropertyManagerPrivate::slotValueChanged (QtProperty * property, int val)
References valueChanged().
void QtVariantPropertyManagerPrivate::slotValueChanged (QtProperty * property, double val)
References valueChanged().
void QtVariantPropertyManagerPrivate::slotValueChanged (QtProperty * property, bool val)
References valueChanged().
void QtVariantPropertyManagerPrivate::slotValueChanged (QtProperty * property, const QString & val)
References valueChanged().
void QtVariantPropertyManagerPrivate::slotValueChanged (QtProperty * property, const QDate & val)
References valueChanged().
void QtVariantPropertyManagerPrivate::slotValueChanged (QtProperty * property, const QTime & val)
References valueChanged().
void QtVariantPropertyManagerPrivate::slotValueChanged (QtProperty * property, const QDateTime & val)
References valueChanged().
void QtVariantPropertyManagerPrivate::slotValueChanged (QtProperty * property, const QKeySequence & val)
References valueChanged().
void QtVariantPropertyManagerPrivate::slotValueChanged (QtProperty * property, const QChar & val)
References valueChanged().
void QtVariantPropertyManagerPrivate::slotValueChanged (QtProperty * property, const QLocale & val)
References valueChanged().
void QtVariantPropertyManagerPrivate::slotValueChanged (QtProperty * property, const QPoint & val)
References valueChanged().
void QtVariantPropertyManagerPrivate::slotValueChanged (QtProperty * property, const QPointF & val)
References valueChanged().
void QtVariantPropertyManagerPrivate::slotValueChanged (QtProperty * property, const QSize & val)
References valueChanged().
void QtVariantPropertyManagerPrivate::slotValueChanged (QtProperty * property, const QSizeF & val)
References valueChanged().
void QtVariantPropertyManagerPrivate::slotValueChanged (QtProperty * property, const QRect & val)
References valueChanged().
void QtVariantPropertyManagerPrivate::slotValueChanged (QtProperty * property, const QRectF & val)
References valueChanged().
void QtVariantPropertyManagerPrivate::slotValueChanged (QtProperty * property, const QColor & val)
References valueChanged().
void QtVariantPropertyManagerPrivate::slotValueChanged (QtProperty * property, const QSizePolicy & val)
References valueChanged().
void QtVariantPropertyManagerPrivate::slotValueChanged (QtProperty * property, const QFont & val)
References valueChanged().
void QtVariantPropertyManagerPrivate::slotValueChanged (QtProperty * property, const QCursor & val)
References valueChanged().
void QtVariantPropertyManagerPrivate::valueChanged (QtProperty * property, const QVariant & val)
References m_internalToProperty, QtAbstractPropertyManager::propertyChanged(), and QtVariantPropertyManager::valueChanged().
Referenced by slotValueChanged().
Member Data Documentation
const QString QtVariantPropertyManagerPrivate::m_constraintAttribute
Referenced by QtVariantPropertyManager::attributeValue(), QtVariantPropertyManager::QtVariantPropertyManager(), QtVariantPropertyManager::setAttribute(), and slotConstraintChanged().
bool QtVariantPropertyManagerPrivate::m_creatingProperty
Referenced by QtVariantPropertyManager::addProperty(), QtVariantPropertyManager::createProperty(), QtVariantPropertyManager::QtVariantPropertyManager(), and slotPropertyInserted().
bool QtVariantPropertyManagerPrivate::m_creatingSubProperties
Referenced by createSubProperty(), QtVariantPropertyManager::initializeProperty(), and QtVariantPropertyManager::QtVariantPropertyManager().
const QString QtVariantPropertyManagerPrivate::m_decimalsAttribute
Referenced by QtVariantPropertyManager::attributeValue(), QtVariantPropertyManager::QtVariantPropertyManager(), QtVariantPropertyManager::setAttribute(), and slotDecimalsChanged().
bool QtVariantPropertyManagerPrivate::m_destroyingSubProperties
Referenced by QtVariantPropertyManager::QtVariantPropertyManager(), removeSubProperty(), and QtVariantPropertyManager::uninitializeProperty().
const QString QtVariantPropertyManagerPrivate::m_enumIconsAttribute
Referenced by QtVariantPropertyManager::attributeValue(), QtVariantPropertyManager::QtVariantPropertyManager(), QtVariantPropertyManager::setAttribute(), and slotEnumIconsChanged().
const QString QtVariantPropertyManagerPrivate::m_enumNamesAttribute
Referenced by QtVariantPropertyManager::attributeValue(), QtVariantPropertyManager::QtVariantPropertyManager(), QtVariantPropertyManager::setAttribute(), and slotEnumNamesChanged().
const QString QtVariantPropertyManagerPrivate::m_flagNamesAttribute
Referenced by QtVariantPropertyManager::attributeValue(), QtVariantPropertyManager::QtVariantPropertyManager(), QtVariantPropertyManager::setAttribute(), and slotFlagNamesChanged().
QMap<QtProperty *, QtVariantProperty *> QtVariantPropertyManagerPrivate::m_internalToProperty
Referenced by createSubProperty(), QtVariantPropertyManager::initializeProperty(), removeSubProperty(), slotConstraintChanged(), slotDecimalsChanged(), slotEnumIconsChanged(), slotEnumNamesChanged(), slotFlagNamesChanged(), slotPropertyInserted(), slotPropertyRemoved(), slotRangeChanged(), slotRegExpChanged(), slotSingleStepChanged(), QtVariantPropertyManager::uninitializeProperty(), and valueChanged().
const QString QtVariantPropertyManagerPrivate::m_maximumAttribute
Referenced by QtVariantPropertyManager::attributeValue(), QtVariantPropertyManager::QtVariantPropertyManager(), QtVariantPropertyManager::setAttribute(), and slotRangeChanged().
const QString QtVariantPropertyManagerPrivate::m_minimumAttribute
Referenced by QtVariantPropertyManager::attributeValue(), QtVariantPropertyManager::QtVariantPropertyManager(), QtVariantPropertyManager::setAttribute(), and slotRangeChanged().
QMap<const QtProperty *, QPair<QtVariantProperty *, int> > QtVariantPropertyManagerPrivate::m_propertyToType
Referenced by QtVariantPropertyManager::createProperty(), QtVariantPropertyManager::propertyType(), QtVariantPropertyManager::uninitializeProperty(), and QtVariantPropertyManager::variantProperty().
int QtVariantPropertyManagerPrivate::m_propertyType
Referenced by QtVariantPropertyManager::addProperty(), QtVariantPropertyManager::createProperty(), QtVariantPropertyManager::initializeProperty(), and QtVariantPropertyManager::QtVariantPropertyManager().
const QString QtVariantPropertyManagerPrivate::m_regExpAttribute
Referenced by QtVariantPropertyManager::attributeValue(), QtVariantPropertyManager::QtVariantPropertyManager(), QtVariantPropertyManager::setAttribute(), and slotRegExpChanged().
const QString QtVariantPropertyManagerPrivate::m_singleStepAttribute
Referenced by QtVariantPropertyManager::attributeValue(), QtVariantPropertyManager::QtVariantPropertyManager(), QtVariantPropertyManager::setAttribute(), and slotSingleStepChanged().
QMap<int, QMap<QString, int> > QtVariantPropertyManagerPrivate::m_typeToAttributeToAttributeType
Referenced by QtVariantPropertyManager::attributes(), QtVariantPropertyManager::attributeType(), QtVariantPropertyManager::attributeValue(), and QtVariantPropertyManager::QtVariantPropertyManager().
QMap<int, QtAbstractPropertyManager *> QtVariantPropertyManagerPrivate::m_typeToPropertyManager
Referenced by QtVariantPropertyManager::initializeProperty(), and QtVariantPropertyManager::QtVariantPropertyManager().
QMap<int, int> QtVariantPropertyManagerPrivate::m_typeToValueType
Referenced by QtVariantPropertyManager::isPropertyTypeSupported(), QtVariantPropertyManager::QtVariantPropertyManager(), and QtVariantPropertyManager::valueType().
The documentation for this class was generated from the following file:
qtvariantproperty.cpp