MouseEventListener Class Reference
an abstract class that can be used to be notified when a mouse event takes place
#include <mouseeventlistener.h>
Public Member Functions
 MouseEventListener ()
virtual void mousePressEvent (PlotSceneWidget *, QMouseEvent *)
virtual void mouseReleaseEvent (PlotSceneWidget *, QMouseEvent *)
virtual void mouseMoveEvent (PlotSceneWidget *, QMouseEvent *)
virtual void mouseClickEvent (PlotSceneWidget *, const QPointF &)
virtual void mouseDoubleClickEvent (PlotSceneWidget *, QMouseEvent *)
Detailed Description
Mouse press, move, release and click event can be intercepted. In each method, a reference to the PlotSceneWidget that received the event is passed.
Constructor & Destructor Documentation
MouseEventListener()
MouseEventListener::MouseEventListener () [inline]
Member Function Documentation
mouseClickEvent()
virtual void MouseEventListener::mouseClickEvent (PlotSceneWidget * , const QPointF &) [inline], [virtual]
Reimplemented in MarkerItem .
Referenced by PlotSceneWidget::mouseReleaseEvent().
mouseDoubleClickEvent()
virtual void MouseEventListener::mouseDoubleClickEvent (PlotSceneWidget * , QMouseEvent *) [inline], [virtual]
Reimplemented in MarkerItem .
Referenced by PlotSceneWidget::mouseDoubleClickEvent().
mouseMoveEvent()
virtual void MouseEventListener::mouseMoveEvent (PlotSceneWidget * , QMouseEvent *) [inline], [virtual]
Referenced by PlotSceneWidget::mouseMoveEvent().
mousePressEvent()
virtual void MouseEventListener::mousePressEvent (PlotSceneWidget * , QMouseEvent *) [inline], [virtual]
Referenced by PlotSceneWidget::mousePressEvent().
mouseReleaseEvent()
virtual void MouseEventListener::mouseReleaseEvent (PlotSceneWidget * , QMouseEvent *) [inline], [virtual]
Reimplemented in MarkerItem .
Referenced by PlotSceneWidget::mouseReleaseEvent().
The documentation for this class was generated from the following file:
 mouseeventlistener.h