QtBoolEdit Class Reference
#include <qtpropertybrowserutils_p.h>
Signals
void toggled (bool)
Public Member Functions
QtBoolEdit (QWidget *parent=0)
bool textVisible () const
void setTextVisible (bool textVisible)
Qt::CheckState checkState () const
void setCheckState (Qt::CheckState state)
bool isChecked () const
void setChecked (bool c)
bool blockCheckBoxSignals (bool block)
Protected Member Functions
void mousePressEvent (QMouseEvent *event)
void paintEvent (QPaintEvent *)
Constructor & Destructor Documentation
QtBoolEdit::QtBoolEdit (QWidget * parent = 0)
References toggled().
Member Function Documentation
bool QtBoolEdit::blockCheckBoxSignals (bool block)
Referenced by QtCheckBoxFactoryPrivate::slotPropertyChanged().
Qt::CheckState QtBoolEdit::checkState () const
bool QtBoolEdit::isChecked () const
Referenced by setChecked(), and setTextVisible().
void QtBoolEdit::mousePressEvent (QMouseEvent * event) [protected]
void QtBoolEdit::paintEvent (QPaintEvent *) [protected]
void QtBoolEdit::setChecked (bool c)
References isChecked().
Referenced by QtCheckBoxFactory::createEditor(), and QtCheckBoxFactoryPrivate::slotPropertyChanged().
void QtBoolEdit::setCheckState (Qt::CheckState state)
void QtBoolEdit::setTextVisible (bool textVisible)
References isChecked(), and textVisible().
bool QtBoolEdit::textVisible () const [inline]
Referenced by setTextVisible().
void QtBoolEdit::toggled (bool) [signal]
Referenced by QtBoolEdit().
The documentation for this class was generated from the following files:
qtpropertybrowserutils_p.h
qtpropertybrowserutils.cpp