ExternalScaleWidget Class Reference
A widget to configure and draw a scale external to a PlotSceneWidget or any other scroll area whose contents need a scale.
#include <externalscalewidget.h>
Public Slots
void setMinimum (double min)
void setMaximum (double max)
void scrollChanged (int value)
void scrollRangeChanged (int min, int max)
void areaChanged (const QSizeF &size)
void setInverted (bool)
void setTickLen (int len)
void setLabelDistFromTick (int d)
void setTickStepLen (double tickStepLen)
void setAlignment (Qt::Alignment alignment)
void setMargin (double margin)
void setOriginPercentage (double percent)
void setScaleFactor (double)
void setHorizontal (bool h)
void setFormat (const QString &fmt)
void setTickDrawingInverted (bool inverted)
void setLabelRotation (double r)
void setSyncAxisTicksWithPlot (bool sync)
void setSyncAxisLabelsWithPlot (bool sync)
QPen pen () const
void setPen (const QPen &p)
Public Member Functions
 ExternalScaleWidget (QWidget *parent, ScaleItem::Orientation o= ScaleItem::Horizontal)
 ScaleItem::Orientation orientation () const
void setOrientation (ScaleItem::Orientation o)
double minimum () const
double maximum () const
double margin () const
bool isInverted () const
bool horizontal () const
int tickLen () const
int labelDistFromTick () const
double tickStepLen () const
double originPercentage () const
double scaleFactor () const
double labelRotation () const
bool syncAxisTicksWithPlot () const
bool syncAxisLabelsWithPlot () const
virtual void xAxisBoundsChanged (double lower, double upper)
x axis bounds notification
virtual void yAxisBoundsChanged (double lower, double upper)
y axis bounds notification
virtual void axisAutoscaleChanged (ScaleItem::Orientation o, bool autoscale)
x axis auto scale property change notification
virtual void canvasRectChanged (const QRectF &newRect)
notifies when the canvas area changes.
virtual void tickStepLenChanged (double len)
notifies listeners about tick step len changes.
virtual void labelsFormatChanged (const QString & format)
when the labels format changes, labelsFormatChanged is used
virtual void plotRectChanged (const QRectF &newRect)
does nothing. We are not actually interested in the plot rect
virtual void plotAreaChanged (const QSizeF &area)
pure virtual method that needs to be reimplemented in order to be notified when the plot area changes.
virtual void scrollBarChanged (Qt::Orientation orientation, int value)
pure virtual method that needs to be reimplemented in order to be notified when the value of one of the two scrollbars changes.
virtual void plotZoomLevelChanged (int)
QString format () const
Qt::Alignment alignment () const
bool tickDrawingInverted () const
void installScaleLabelInterface (ScaleLabelInterface *)
When the scale is drawn, the value (in double format) is passed to the installed implementation of ScaleLabelInterface. The returned QString is used to draw the label corresponding to the value.
void removeScaleLabelInterface ()
Protected Member Functions
void paintEvent (QPaintEvent *)
virtual QSize minimumSizeHint () const
returns the minimum size hint.
int mCalculateLongestLabelWidth () const
Properties
double minimum
double maximum
double tickStepLen
double originPercentage
double scaleFactor
double labelRotation
int tickLen
int labelDistFromTick
bool isInverted
bool horizontal
bool tickDrawingInverted
QString format
bool syncAxisTicksWithPlot
bool syncAxisLabelsWithPlot
double margin
Detailed Description
Structure
The ExternalScaleWidget is a QWidget that draws a scale with ticks and numeric values. It can be horizontal or vertical. Implements AxisChangeListener in order to receive notifications when the maximum and minimum values of the scale change and PlotEventListener in order to be notified when the PlotSceneWidget area changes, for instance when the user scales the view to magnify a portion of the scene. Nonetheless, it is not essential to install an ExternalScaleWidget if you intend to use this class without a PlotSceneWidget. Actually, there are slots equivalent to the methods implemented from the AxisChangeListener and PlotEventListener interfaces. These slots are areaChanged and scrollChanged. The ExternalScaleWidget needs to know when the area of the QScrollArea contents changes and when the value of the scrollbars change, so that it can recalculate the values to display in the correct points.
Note
You can use the HorizontalScaleWidget and VerticalScaleWidget convenience classes to directly instantiate horizontal and vertical scales respectively. The Qt Desiger plugin uses those classes.
Align scales with the PlotSceneWidget or other scrolling areas
It is very important that the height of a vertical scale is equal to the height of the widget it is associated to, and that the width of a horizontal scale is equal to the widget's width. Using the Qt4 designer, just place and align the widgets, and then use a grid layout. The QGridLayout will ensure that the widgets are all scaled together.
Example
Suppose you have an image from a camera and you want to use an external scale to identify pixel positions inside the image. In this case the ExternalScaleWidget is not used in association with a PlotSceneWidget and thus we use signal/slot connections to tell the scale that the image area or the values of the scroll bars have changed.
// define the orientation of each scale widget
ui.xScale->setOrientation(ScaleItem::Horizontal);
ui.yScale->setOrientation(ScaleItem::Vertical);
//
// set the scroll area associated to each scale
// ui.image_ScrollArea is a QScrollArea (or QAbstractScrollArea)
// ui.xScale and ui.yScale are the two ExternalScaleWidget
//
connect(ui.image_ScrollArea->horizontalScrollBar(), SIGNAL(valueChanged(int)), ui.xScale,
      SLOT(scrollChanged(int)));
connect(ui.image_ScrollArea->verticalScrollBar(), SIGNAL(valueChanged(int)), ui.yScale,
      SLOT(scrollChanged(int)));
// if the size of the contents of the QScrollArea changes, then each scale must be
// notified
//
connect(myImage, SIGNAL(imageSizeChanged(QSizeF)), ui.xScale, SLOT(areaChanged(QSizeF)));
connect(myImage, SIGNAL(imageSizeChanged(QSizeF)), ui.yScale, SLOT(areaChanged(QSizeF)));
Inverted scales
The maximum must always be greater than the minimum, but if you want the scale to draw the values starting with the minimum on the rigth (for a horizontal scale) or the top (for a vertical scale), just call setInverted on the ExternalScaleWidget.
Tick drawing inverted
If a vertical scale is placed on the right of the display area, then you may want to call setTickDrawingInverted in order to place ticks before numeric values. The same goes for top placed horizontal scales.
Labels format
The format of the labels is not automatically calculated as in the ScaleItem. It is %.1f by default, and you must call the setFormat or use the format option in order to change it.
Origin position percentage
A property called originPercentage is introduced in order to tune the scale positioning. A value of 0.5 for instance tells the scale that its center of gravity should be in the middle of its length. A tick is guaranteed to be positioned at the half of the length of the scale and, according to the number of ticks, some extra empty space at the beginning or end of the scales might appear, without ticks. Actually, if used in conjunction with a PlotSceneWidget, the origin of its axes is normally placed at the center of the plot. To align the ExternalScaleWidget with the grid of the PlotSceneWidget, you should tune the originPercentage property so that its value is 0.5. The PlotSceneWidget itself has a property to change the axis origin position percentage: on the ExternalScaleWidget an equal value should be set with setOriginPercentage.
Orientation
The horizontal property is a shortcut for setOrientation. It switches a scale from the horizontal to the vertical layout, being the parameter true or false respectively.
Tick length
The tickLen property assigns a length (in pixel coordinates) to the scale ticks.
Tick step length
The tick step length is used to calculate the number of ticks on the scale and where the ticks have to be placed. The value is expressed in scale coordinates. For instance, if your scale spans from 0 to 100 and you specify a tickStepLen of 10, you will have ten ticks with ten values drawn on the widget.
Label Rotation
The labelRotation property is able to rotate the labels on the scale. Up to now, it is only possible to rotate x axis labels.
Notes on widget geometry.
Whenever one of the minimum, maximum, labelRotation, format or tickLen properties changes, the minimumSizeHint for the widget changes, and the updateGeometry() is internally called by the setter methods. In this way you can safely insert the widgets into a QLayout without worrying about geometry changes (resizes, changes in tick len or format...). The minimumSizeHint takes into account the font in use, naturally.
Example
This example shows how to use two ExternalScaleWidget scales with a PlotSceneWidget. As said before, ExternalScaleWidget implements two interfaces aimed at receive PlotSceneWidget notifications in matter of geometry change and ScaleItem notifications in matter of minimum and maximum value changes. All you need to to is to install each ExternalScaleWidget on the plot and on the scale items of the plots as in the example below.
// In this example we have a PlotSceneWidget called horProfile and a couple
// of ExternalScaleWidget scales called xScale and yScale
// take each of the ScaleItem of the PlotSceneWidget and install the scale
// as AxisChangeListener.
//
horProfile->xScaleItem()->installAxisChangeListener(xScale);
horProfile->yScaleItem()->installAxisChangeListener(yScale);
// Install the scale as PlotChangeListener into the PlotSceneWidget (horProfile)
//
horProfile->installPlotChangeListener(xScale);
horProfile->installPlotChangeListener(yScale);
// You may want to have the same tickStepLen on the plot and on the external scale.
// Supposing the plot has a tickStepLen of 50 on the x axis and 500 on the y axis,
// then:
//
xScale->setTickStepLen(50.0);
yScale->setTickStepLen(500.0);
// The PlotSceneWidget center its axes (and grid) at the center of the plot so, if
// you do not change this position, you have to tune the position of the scales
// as follows:
//
 yScale->setOriginPercentage(0.5);
 xScale->setOriginPercentage(0.5);
// For the same reason as above, if the size of the plot is less than the view size,
// the scales must be kept correctly centered:
//
xScale->setAlignment(Qt::AlignHCenter);
yScale->setAlignment(Qt::AlignVCenter);
Sample code
An example can be found inside the directory examples/externalscales directory.
See also
HorizontalScaleWidget
VerticalScaleWidget
PlotSceneWidget
ScaleItem
Personalized labels
You can implement a ScaleLabelInterface and install it on an ExternalScaleWidget. The ExternalScaleWidget will call the ScaleLabelInterface::label implementation with the value corresponding to the tick being drawn. Your ScaleLabelInterface::label implementation has to convert the raw value passed by the ExternalScaleWidget into a convenient label according to your needs. For instance, a TimeScaleLabel can be used to convert unix timestamps into a date/time string.
Constructor & Destructor Documentation
ExternalScaleWidget()
ExternalScaleWidget::ExternalScaleWidget (QWidget * parent, ScaleItem::Orientation o = ScaleItem::Horizontal) [explicit]
References ScalePrivate::alignment, Elettra::black, ScaleItem::Horizontal, ScalePrivate::inverted, ScalePrivate::labelDistFromTick, ScalePrivate::labelRotation, ScalePrivate::len, ScalePrivate::longestLabelWidth, ScalePrivate::margin, ScalePrivate::max, ScalePrivate::min, ScalePrivate::offset, ScalePrivate::orientation, orientation(), ScalePrivate::originOffset, ScalePrivate::originPercentage, ScalePrivate::pen, ScalePrivate::pos, ScalePrivate::scaleFactor, ScalePrivate::scaleLabelInterface, ScalePrivate::syncAxisLabelsWithPlot, ScalePrivate::syncAxisTicksWithPlot, ScalePrivate::tickDrawingInverted, ScalePrivate::tickLen, and ScalePrivate::tickStepLen.
Member Function Documentation
alignment()
Qt::Alignment ExternalScaleWidget::alignment () const
References ScalePrivate::alignment.
Referenced by setAlignment().
areaChanged
void ExternalScaleWidget::areaChanged (const QSizeF & size) [slot]
References ScaleItem::Horizontal, ScalePrivate::len, ScalePrivate::orientation, and ScaleItem::Vertical.
Referenced by plotAreaChanged().
axisAutoscaleChanged()
void ExternalScaleWidget::axisAutoscaleChanged (ScaleItem::Orientation o, bool autoscale) [virtual]
Parameters
o the ScaleItem::Orientation property that helps you find out which axis (x or y) has changed its property.
autoscale true autoscale is enabled.
autoscale false autoscale is disabled.
Implements AxisChangeListener .
canvasRectChanged()
void ExternalScaleWidget::canvasRectChanged (const QRectF & newRect) [virtual]
In some cases, when the axis is placed on the right or at the bottom of the plot, the labels might require more space, and the plot area must be reduced.
Parameters
newRect the new rectangle
Implements AxisChangeListener .
format()
QString ExternalScaleWidget::format () const
References ScalePrivate::format.
horizontal()
bool ExternalScaleWidget::horizontal () const
References ScaleItem::Horizontal, and ScalePrivate::orientation.
installScaleLabelInterface()
void ExternalScaleWidget::installScaleLabelInterface (ScaleLabelInterface * iface)
When the scale is drawn, the value (in double format) is passed to the installed implementation of ScaleLabelInterface. The returned QString is used to draw the label corresponding to the value.
Parameters
iface an implementation instance of the ScaleLabelInterface
See also
TimeScaleLabel
References ScalePrivate::scaleLabelInterface.
Referenced by ExtScalePlotSceneWidget::ExtScalePlotSceneWidget().
isInverted()
bool ExternalScaleWidget::isInverted () const
References ScalePrivate::inverted.
labelDistFromTick()
int ExternalScaleWidget::labelDistFromTick () const
References ScalePrivate::labelDistFromTick.
labelRotation()
double ExternalScaleWidget::labelRotation () const
References ScalePrivate::labelRotation.
labelsFormatChanged()
void ExternalScaleWidget::labelsFormatChanged (const QString & newFormat) [virtual]
See also
ScaleItem
Implements AxisChangeListener .
References format, setFormat(), and ScalePrivate::syncAxisLabelsWithPlot.
margin()
double ExternalScaleWidget::margin () const
References ScalePrivate::margin.
maximum()
double ExternalScaleWidget::maximum () const
References ScalePrivate::max.
mCalculateLongestLabelWidth()
int ExternalScaleWidget::mCalculateLongestLabelWidth () const [protected]
References ScalePrivate::format, format, ScaleLabelInterface::longestLabel(), ScalePrivate::max, ScalePrivate::min, qstoc, and ScalePrivate::scaleLabelInterface.
Referenced by minimumSizeHint(), setFormat(), xAxisBoundsChanged(), and yAxisBoundsChanged().
minimum()
double ExternalScaleWidget::minimum () const
References ScalePrivate::min.
minimumSizeHint()
QSize ExternalScaleWidget::minimumSizeHint () const [protected], [virtual]
Must be recalculated when the min and max change or the format changes.
References ScaleItem::Horizontal, ScalePrivate::labelDistFromTick, ScalePrivate::labelRotation, mCalculateLongestLabelWidth(), ScalePrivate::orientation, ScalePrivate::tickLen, and ScaleItem::Vertical.
orientation()
 ScaleItem::Orientation ExternalScaleWidget::orientation () const
References ScalePrivate::orientation.
Referenced by ExternalScaleWidget(), and scrollBarChanged().
originPercentage()
double ExternalScaleWidget::originPercentage () const
References ScalePrivate::originPercentage.
paintEvent()
void ExternalScaleWidget::paintEvent (QPaintEvent *) [protected]
version with originPercentage
References ScalePrivate::alignment, ScalePrivate::format, format, ScaleItem::Horizontal, ScalePrivate::inverted, ScaleLabelInterface::label(), ScalePrivate::labelDistFromTick, ScalePrivate::labelRotation, ScalePrivate::len, ScalePrivate::longestLabelWidth, ScalePrivate::margin, ScalePrivate::max, ScalePrivate::min, ScalePrivate::offset, ScalePrivate::orientation, ScalePrivate::originPercentage, ScalePrivate::pen, qstoc, ScalePrivate::scaleFactor, ScalePrivate::scaleLabelInterface, ScalePrivate::tickDrawingInverted, ScalePrivate::tickLen, and ScalePrivate::tickStepLen.
pen
QPen ExternalScaleWidget::pen () const [slot]
References ScalePrivate::pen.
plotAreaChanged()
void ExternalScaleWidget::plotAreaChanged (const QSizeF & area) [virtual]
Note
The area takes into account the scaling factors currently applied to the view, i.e. m11() and m22() of the current transformation obtained by transform().
Implements PlotGeometryEventListener .
References areaChanged().
plotRectChanged()
void ExternalScaleWidget::plotRectChanged (const QRectF & newRect) [virtual]
Implements PlotGeometryEventListener .
plotZoomLevelChanged()
virtual void ExternalScaleWidget::plotZoomLevelChanged (int) [inline], [virtual]
Implements PlotGeometryEventListener .
removeScaleLabelInterface()
void ExternalScaleWidget::removeScaleLabelInterface ()
References ScalePrivate::scaleLabelInterface.
scaleFactor()
double ExternalScaleWidget::scaleFactor () const
References ScalePrivate::scaleFactor.
scrollBarChanged()
void ExternalScaleWidget::scrollBarChanged (Qt::Orientation orientation, int value) [virtual]
Parameters
orientation one of the two possible Qt::Orientation values: Qt::Horizontal or Qt::Vertical
value the value of the scrollbar
Implements PlotGeometryEventListener .
References ScaleItem::Horizontal, ScalePrivate::orientation, orientation(), scrollChanged(), and ScaleItem::Vertical.
scrollChanged
void ExternalScaleWidget::scrollChanged (int value) [slot]
References ScalePrivate::offset.
Referenced by scrollBarChanged().
scrollRangeChanged
void ExternalScaleWidget::scrollRangeChanged (int min, int max) [slot]
setAlignment
void ExternalScaleWidget::setAlignment (Qt::Alignment alignment) [slot]
References ScalePrivate::alignment, and alignment().
Referenced by ExtScalePlotSceneWidget::addExternalScale(), and ExtScalePlotSceneWidget::ExtScalePlotSceneWidget().
setFormat
void ExternalScaleWidget::setFormat (const QString & fmt) [slot]
References ScalePrivate::format, ScalePrivate::longestLabelWidth, and mCalculateLongestLabelWidth().
Referenced by labelsFormatChanged().
setHorizontal
void ExternalScaleWidget::setHorizontal (bool h) [slot]
References ScaleItem::Horizontal, setOrientation(), and ScaleItem::Vertical.
setInverted
void ExternalScaleWidget::setInverted (bool inv) [slot]
References ScalePrivate::inverted.
setLabelDistFromTick
void ExternalScaleWidget::setLabelDistFromTick (int d) [slot]
References ScalePrivate::labelDistFromTick.
Referenced by VerticalScaleWidget::VerticalScaleWidget().
setLabelRotation
void ExternalScaleWidget::setLabelRotation (double r) [slot]
References ScalePrivate::labelRotation.
Referenced by ExtScalePlotSceneWidget::ExtScalePlotSceneWidget().
setMargin
void ExternalScaleWidget::setMargin (double margin) [slot]
References ScalePrivate::margin, and margin.
Referenced by ExtScalePlotSceneWidget::addExternalScale(), and ExtScalePlotSceneWidget::ExtScalePlotSceneWidget().
setMaximum
void ExternalScaleWidget::setMaximum (double max) [slot]
References ScalePrivate::max.
setMinimum
void ExternalScaleWidget::setMinimum (double min) [slot]
References ScalePrivate::min.
setOrientation()
void ExternalScaleWidget::setOrientation (ScaleItem::Orientation o)
References ScalePrivate::orientation.
Referenced by setHorizontal().
setOriginPercentage
void ExternalScaleWidget::setOriginPercentage (double percent) [slot]
References ScalePrivate::originPercentage.
Referenced by ExtScalePlotSceneWidget::addExternalScale(), and ExtScalePlotSceneWidget::ExtScalePlotSceneWidget().
setPen
void ExternalScaleWidget::setPen (const QPen & p) [slot]
References ScalePrivate::pen.
Referenced by ExtScalePlotSceneWidget::addExternalScale().
setScaleFactor
void ExternalScaleWidget::setScaleFactor (double f) [slot]
References ScalePrivate::scaleFactor.
setSyncAxisLabelsWithPlot
void ExternalScaleWidget::setSyncAxisLabelsWithPlot (bool sync) [slot]
References ScalePrivate::syncAxisLabelsWithPlot.
setSyncAxisTicksWithPlot
void ExternalScaleWidget::setSyncAxisTicksWithPlot (bool sync) [slot]
References ScalePrivate::syncAxisTicksWithPlot.
setTickDrawingInverted
void ExternalScaleWidget::setTickDrawingInverted (bool inverted) [slot]
References ScalePrivate::tickDrawingInverted.
Referenced by ExtScalePlotSceneWidget::addExternalScale().
setTickLen
void ExternalScaleWidget::setTickLen (int len) [slot]
References ScalePrivate::tickLen.
setTickStepLen
void ExternalScaleWidget::setTickStepLen (double tickStepLen) [slot]
References perr, ScalePrivate::tickStepLen, and tickStepLen.
Referenced by ExtScalePlotSceneWidget::addExternalScale(), ExtScalePlotSceneWidget::ExtScalePlotSceneWidget(), and tickStepLenChanged().
syncAxisLabelsWithPlot()
bool ExternalScaleWidget::syncAxisLabelsWithPlot () const
References ScalePrivate::syncAxisLabelsWithPlot.
syncAxisTicksWithPlot()
bool ExternalScaleWidget::syncAxisTicksWithPlot () const
References ScalePrivate::syncAxisTicksWithPlot.
tickDrawingInverted()
bool ExternalScaleWidget::tickDrawingInverted () const
References ScalePrivate::tickDrawingInverted.
tickLen()
int ExternalScaleWidget::tickLen () const
References ScalePrivate::tickLen.
tickStepLen()
double ExternalScaleWidget::tickStepLen () const
References ScalePrivate::tickStepLen.
tickStepLenChanged()
void ExternalScaleWidget::tickStepLenChanged (double value) [virtual]
The tick step len can be tuned by a property in a ScaleItem or let it be automatically calculated by ScaleItem.
See also
ScaleItem
Implements AxisChangeListener .
References setTickStepLen(), and ScalePrivate::syncAxisTicksWithPlot.
xAxisBoundsChanged()
void ExternalScaleWidget::xAxisBoundsChanged (double lower, double upper) [virtual]
Parameters
lower the new lower bound
upper the new upper bound
Implements AxisChangeListener .
References ScaleItem::Horizontal, ScalePrivate::longestLabelWidth, ScalePrivate::max, mCalculateLongestLabelWidth(), ScalePrivate::min, and ScalePrivate::orientation.
yAxisBoundsChanged()
void ExternalScaleWidget::yAxisBoundsChanged (double lower, double upper) [virtual]
Parameters
lower the new lower bound
upper the new upper bound
Implements AxisChangeListener .
References ScalePrivate::longestLabelWidth, ScalePrivate::max, mCalculateLongestLabelWidth(), ScalePrivate::min, ScalePrivate::orientation, and ScaleItem::Vertical.
Property Documentation
format
QString ExternalScaleWidget::format [read], [write]
Referenced by labelsFormatChanged(), mCalculateLongestLabelWidth(), and paintEvent().
horizontal
bool ExternalScaleWidget::horizontal [read], [write]
isInverted
bool ExternalScaleWidget::isInverted [read], [write]
labelDistFromTick
int ExternalScaleWidget::labelDistFromTick [read], [write]
labelRotation
double ExternalScaleWidget::labelRotation [read], [write]
margin
double ExternalScaleWidget::margin [read], [write]
Referenced by setMargin().
maximum
double ExternalScaleWidget::maximum [read], [write]
minimum
double ExternalScaleWidget::minimum [read], [write]
originPercentage
double ExternalScaleWidget::originPercentage [read], [write]
scaleFactor
double ExternalScaleWidget::scaleFactor [read], [write]
syncAxisLabelsWithPlot
bool ExternalScaleWidget::syncAxisLabelsWithPlot [read], [write]
syncAxisTicksWithPlot
bool ExternalScaleWidget::syncAxisTicksWithPlot [read], [write]
tickDrawingInverted
bool ExternalScaleWidget::tickDrawingInverted [read], [write]
tickLen
int ExternalScaleWidget::tickLen [read], [write]
tickStepLen
double ExternalScaleWidget::tickStepLen [read], [write]
Referenced by setTickStepLen().
The documentation for this class was generated from the following files:
 externalscalewidget.h
 externalscalewidget.cpp