QtAbstractEditorFactoryBase Class Reference
The QtAbstractEditorFactoryBase provides an interface for editor factories.
#include <qtpropertybrowser.h>
Public Member Functions
virtual QWidget * createEditor (QtProperty *property, QWidget *parent)=0
Protected Slots
virtual void managerDestroyed (QObject *manager)=0
Protected Member Functions
QtAbstractEditorFactoryBase (QObject *parent=0)
virtual void breakConnection (QtAbstractPropertyManager *manager)=0
Friends
class QtAbstractPropertyBrowser
Detailed Description
An editor factory is a class that is able to create an editing widget of a specified type (e.g. line edits or comboboxes) for a given QtProperty object, and it is used in conjunction with the QtAbstractPropertyManager and QtAbstractPropertyBrowser classes.
When using a property browser widget, the properties are created and managed by implementations of the QtAbstractPropertyManager class. To ensure that the properties' values will be displayed using suitable editing widgets, the managers are associated with objects of QtAbstractEditorFactory subclasses. The property browser will use these associations to determine which factories it should use to create the preferred editing widgets.
Typically, an editor factory is created by subclassing the QtAbstractEditorFactory template class which inherits QtAbstractEditorFactoryBase. But note that several ready-made implementations are available:
QtCheckBoxFactory QtDateEditFactory QtDateTimeEditFactory QtDoubleSpinBoxFactory QtEnumEditorFactory QtLineEditFactory QtScrollBarFactory QtSliderFactory QtSpinBoxFactory QtTimeEditFactory QtVariantEditorFactory
See also
QtAbstractPropertyManager, QtAbstractPropertyBrowser
Constructor & Destructor Documentation
QtAbstractEditorFactoryBase::QtAbstractEditorFactoryBase (QObject * parent = 0) [inline], [explicit], [protected]
Creates an abstract editor factory with the given parent.
Member Function Documentation
void QtAbstractEditorFactoryBase::breakConnection (QtAbstractPropertyManager * manager) [protected], [pure virtual]
Referenced by QtAbstractPropertyBrowser::unsetFactoryForManager().
QWidget * QtAbstractEditorFactoryBase::createEditor (QtProperty * property, QWidget * parent) [pure virtual]
Creates an editing widget (with the given parent) for the given property.
This function is reimplemented in QtAbstractEditorFactory template class which also provides a pure virtual convenience overload of this function enabling access to the property's manager.
See also
QtAbstractEditorFactory::createEditor()
Implemented in QtVariantEditorFactory , QtAbstractEditorFactory< PropertyManager > , QtAbstractEditorFactory< QtCharPropertyManager > , QtAbstractEditorFactory< QtDatePropertyManager > , QtAbstractEditorFactory< QtBoolPropertyManager > , QtAbstractEditorFactory< QtColorPropertyManager > , QtAbstractEditorFactory< QtKeySequencePropertyManager > , QtAbstractEditorFactory< QtDateTimePropertyManager > , QtAbstractEditorFactory< QtDoublePropertyManager > , QtAbstractEditorFactory< QtTimePropertyManager > , QtAbstractEditorFactory< QtVariantPropertyManager > , QtAbstractEditorFactory< QtCursorPropertyManager > , QtAbstractEditorFactory< QtEnumPropertyManager > , QtAbstractEditorFactory< QtIntPropertyManager > , QtAbstractEditorFactory< QtFontPropertyManager > , and QtAbstractEditorFactory< QtStringPropertyManager > .
Referenced by QtVariantEditorFactory::createEditor(), QtAbstractPropertyBrowser::createEditor(), and QtCursorEditorFactory::createEditor().
void QtAbstractEditorFactoryBase::managerDestroyed (QObject * manager) [protected], [pure virtual], [slot]
Implemented in QtAbstractEditorFactory< PropertyManager > , QtAbstractEditorFactory< QtCharPropertyManager > , QtAbstractEditorFactory< QtDatePropertyManager > , QtAbstractEditorFactory< QtBoolPropertyManager > , QtAbstractEditorFactory< QtColorPropertyManager > , QtAbstractEditorFactory< QtKeySequencePropertyManager > , QtAbstractEditorFactory< QtDateTimePropertyManager > , QtAbstractEditorFactory< QtDoublePropertyManager > , QtAbstractEditorFactory< QtTimePropertyManager > , QtAbstractEditorFactory< QtVariantPropertyManager > , QtAbstractEditorFactory< QtCursorPropertyManager > , QtAbstractEditorFactory< QtEnumPropertyManager > , QtAbstractEditorFactory< QtIntPropertyManager > , QtAbstractEditorFactory< QtFontPropertyManager > , and QtAbstractEditorFactory< QtStringPropertyManager > .
Friends And Related Function Documentation
friend class QtAbstractPropertyBrowser [friend]
The documentation for this class was generated from the following files:
qtpropertybrowser.h
qtpropertybrowser.cpp