QtColorEditWidget Class Reference
Public Slots
void setValue (const QColor &value)
Signals
void valueChanged (const QColor &value)
Public Member Functions
QtColorEditWidget (QWidget *parent)
bool eventFilter (QObject *obj, QEvent *ev)
Protected Member Functions
void paintEvent (QPaintEvent *)
Constructor & Destructor Documentation
QtColorEditWidget::QtColorEditWidget (QWidget * parent)
References QtPropertyBrowserUtils::brushValuePixmap(), QtPropertyBrowserUtils::colorValueText(), and setupTreeViewEditorMargin().
Member Function Documentation
bool QtColorEditWidget::eventFilter (QObject * obj, QEvent * ev)
void QtColorEditWidget::paintEvent (QPaintEvent *) [protected]
void QtColorEditWidget::setValue (const QColor & value) [slot]
References QtPropertyBrowserUtils::brushValuePixmap(), QtPropertyBrowserUtils::colorValueText(), and valueChanged().
Referenced by QtColorEditorFactory::createEditor().
void QtColorEditWidget::valueChanged (const QColor & value) [signal]
Referenced by setValue().
The documentation for this class was generated from the following file:
qteditorfactory.cpp