QtSizeFPropertyManager Class Reference
The QtSizeFPropertyManager provides and manages QSizeF properties.
#include <qtpropertymanager.h>
Public Slots
void setValue (QtProperty *property, const QSizeF &val)
void setMinimum (QtProperty *property, const QSizeF &minVal)
void setMaximum (QtProperty *property, const QSizeF &maxVal)
void setRange (QtProperty *property, const QSizeF &minVal, const QSizeF &maxVal)
void setDecimals (QtProperty *property, int prec)
Signals
void valueChanged (QtProperty *property, const QSizeF &val)
void rangeChanged (QtProperty *property, const QSizeF &minVal, const QSizeF &maxVal)
void decimalsChanged (QtProperty *property, int prec)
Public Member Functions
QtSizeFPropertyManager (QObject *parent=0)
~QtSizeFPropertyManager ()
QtDoublePropertyManager * subDoublePropertyManager () const
QSizeF value (const QtProperty *property) const
QSizeF minimum (const QtProperty *property) const
QSizeF maximum (const QtProperty *property) const
int decimals (const QtProperty *property) const
Protected Member Functions
QString valueText (const QtProperty *property) const
virtual void initializeProperty (QtProperty *property)
virtual void uninitializeProperty (QtProperty *property)
Detailed Description
A size property has nested width and height subproperties. The top-level property's value can be retrieved using the value() function, and set using the setValue() slot.
The subproperties are created by a QtDoublePropertyManager object. This manager can be retrieved using the subDoublePropertyManager() function. In order to provide editing widgets for the subproperties in a property browser widget, this manager must be associated with an editor factory.
A size property also has a range of valid values defined by a minimum size and a maximum size. These sizes can be retrieved using the minimum() and the maximum() functions, and set using the setMinimum() and setMaximum() slots. Alternatively, the range can be defined in one go using the setRange() slot.
In addition, QtSizeFPropertyManager provides the valueChanged() signal which is emitted whenever a property created by this manager changes, and the rangeChanged() signal which is emitted whenever such a property changes its range of valid sizes.
See also
QtAbstractPropertyManager, QtDoublePropertyManager, QtSizePropertyManager
Constructor & Destructor Documentation
QtSizeFPropertyManager::QtSizeFPropertyManager (QObject * parent = 0)
Creates a manager with the given parent.
References QtSizeFPropertyManagerPrivate::m_doublePropertyManager, QtAbstractPropertyManager::propertyDestroyed(), and valueChanged().
QtSizeFPropertyManager::~QtSizeFPropertyManager ()
Destroys this manager, and all the properties it has created.
References QtAbstractPropertyManager::clear().
Member Function Documentation
int QtSizeFPropertyManager::decimals (const QtProperty * property) const
Returns the given property's precision, in decimals.
See also
setDecimals()
References QtSizeFPropertyManagerPrivate::Data::decimals, and QtSizeFPropertyManagerPrivate::m_values.
Referenced by initializeProperty().
void QtSizeFPropertyManager::decimalsChanged (QtProperty * property, int prec) [signal]
This signal is emitted whenever a property created by this manager changes its precision of value, passing a pointer to the property and the new prec value
See also
setDecimals()
Referenced by setDecimals().
void QtSizeFPropertyManager::initializeProperty (QtProperty * property) [protected], [virtual]
Implements QtAbstractPropertyManager .
References QtAbstractPropertyManager::addProperty(), QtProperty::addSubProperty(), decimals(), QtSizeFPropertyManagerPrivate::m_doublePropertyManager, QtSizeFPropertyManagerPrivate::m_hToProperty, QtSizeFPropertyManagerPrivate::m_propertyToH, QtSizeFPropertyManagerPrivate::m_propertyToW, QtSizeFPropertyManagerPrivate::m_values, QtSizeFPropertyManagerPrivate::m_wToProperty, QtDoublePropertyManager::setDecimals(), QtDoublePropertyManager::setMinimum(), QtProperty::setPropertyName(), and QtDoublePropertyManager::setValue().
QSizeF QtSizeFPropertyManager::maximum (const QtProperty * property) const
Returns the given property's maximum size value.
See also
setMaximum(), minimum(), setRange()
References QtSizeFPropertyManagerPrivate::m_values.
QSizeF QtSizeFPropertyManager::minimum (const QtProperty * property) const
Returns the given property's minimum size value.
See also
setMinimum(), maximum(), setRange()
References QtSizeFPropertyManagerPrivate::m_values.
void QtSizeFPropertyManager::rangeChanged (QtProperty * property, const QSizeF & minimum, const QSizeF & maximum) [signal]
This signal is emitted whenever a property created by this manager changes its range of valid sizes, passing a pointer to the property and the new minimum and maximum sizes.
See also
setRange()
Referenced by setMaximum(), setMinimum(), and setRange().
void QtSizeFPropertyManager::setDecimals (QtProperty * property, int prec) [slot]
Sets the precision of the given property to prec.
The valid decimal range is 0-13. The default is 2.
See also
decimals()
References QtSizeFPropertyManagerPrivate::Data::decimals, decimalsChanged(), QtSizeFPropertyManagerPrivate::m_doublePropertyManager, QtSizeFPropertyManagerPrivate::m_propertyToH, QtSizeFPropertyManagerPrivate::m_propertyToW, QtSizeFPropertyManagerPrivate::m_values, and QtDoublePropertyManager::setDecimals().
void QtSizeFPropertyManager::setMaximum (QtProperty * property, const QSizeF & maxVal) [slot]
Sets the maximum size value for the given property to maxVal.
When setting the maximum size value, the minimum and current values are adjusted if necessary (ensuring that the size range remains valid and that the current value is within the range).
See also
maximum(), setRange(), rangeChanged()
References QtSizeFPropertyManagerPrivate::Data::maximumValue(), QtAbstractPropertyManager::propertyChanged(), rangeChanged(), QtSizeFPropertyManagerPrivate::Data::setMaximumValue(), QtSizeFPropertyManagerPrivate::setRange(), and valueChanged().
void QtSizeFPropertyManager::setMinimum (QtProperty * property, const QSizeF & minVal) [slot]
Sets the minimum size value for the given property to minVal.
When setting the minimum size value, the maximum and current values are adjusted if necessary (ensuring that the size range remains valid and that the current value is within the range).
See also
minimum(), setRange(), rangeChanged()
References QtSizeFPropertyManagerPrivate::Data::minimumValue(), QtAbstractPropertyManager::propertyChanged(), rangeChanged(), QtSizeFPropertyManagerPrivate::Data::setMinimumValue(), QtSizeFPropertyManagerPrivate::setRange(), and valueChanged().
void QtSizeFPropertyManager::setRange (QtProperty * property, const QSizeF & minimum, const QSizeF & maximum) [slot]
Sets the range of valid values.
This is a convenience function defining the range of valid values in one go; setting the minimum and maximum values for the given property with a single function call.
When setting a new range, the current value is adjusted if necessary (ensuring that the value remains within the range).
See also
setMinimum(), setMaximum(), rangeChanged()
References QtAbstractPropertyManager::propertyChanged(), rangeChanged(), QtSizeFPropertyManagerPrivate::setRange(), and valueChanged().
void QtSizeFPropertyManager::setValue (QtProperty * property, const QSizeF & value) [slot]
Sets the value of the given property to value.
If the specified value is not valid according to the given property's size range, the value is adjusted to the nearest valid value within the size range.
See also
value(), setRange(), valueChanged()
References QtAbstractPropertyManager::propertyChanged(), QtSizeFPropertyManagerPrivate::setValue(), and valueChanged().
QtDoublePropertyManager * QtSizeFPropertyManager::subDoublePropertyManager () const
Returns the manager that creates the nested width and height subproperties.
In order to provide editing widgets for the width and height properties in a property browser widget, this manager must be associated with an editor factory.
See also
QtAbstractPropertyBrowser::setFactoryForManager()
References QtSizeFPropertyManagerPrivate::m_doublePropertyManager.
Referenced by QtVariantPropertyManager::QtVariantPropertyManager().
void QtSizeFPropertyManager::uninitializeProperty (QtProperty * property) [protected], [virtual]
Reimplemented from QtAbstractPropertyManager .
References QtSizeFPropertyManagerPrivate::m_hToProperty, QtSizeFPropertyManagerPrivate::m_propertyToH, QtSizeFPropertyManagerPrivate::m_propertyToW, QtSizeFPropertyManagerPrivate::m_values, and QtSizeFPropertyManagerPrivate::m_wToProperty.
QSizeF QtSizeFPropertyManager::value (const QtProperty * property) const
Returns the given property's value.
If the given property is not managed by this manager, this function returns an invalid size
See also
setValue()
References QtSizeFPropertyManagerPrivate::m_values.
void QtSizeFPropertyManager::valueChanged (QtProperty * property, const QSizeF & value) [signal]
This signal is emitted whenever a property created by this manager changes its value, passing a pointer to the property and the new value as parameters.
See also
setValue()
Referenced by QtSizeFPropertyManager(), setMaximum(), setMinimum(), setRange(), and setValue().
QString QtSizeFPropertyManager::valueText (const QtProperty * property) const [protected], [virtual]
Reimplemented from QtAbstractPropertyManager .
References QtSizeFPropertyManagerPrivate::m_values.
The documentation for this class was generated from the following files:
qtpropertymanager.h
qtpropertymanager.cpp