QtSizePolicyPropertyManager Class Reference
The QtSizePolicyPropertyManager provides and manages QSizePolicy properties.
#include <qtpropertymanager.h>
Public Slots
void setValue (QtProperty *property, const QSizePolicy &val)
Signals
void valueChanged (QtProperty *property, const QSizePolicy &val)
Public Member Functions
QtSizePolicyPropertyManager (QObject *parent=0)
~QtSizePolicyPropertyManager ()
QtIntPropertyManager * subIntPropertyManager () const
QtEnumPropertyManager * subEnumPropertyManager () const
QSizePolicy value (const QtProperty *property) const
Protected Member Functions
QString valueText (const QtProperty *property) const
virtual void initializeProperty (QtProperty *property)
virtual void uninitializeProperty (QtProperty *property)
Detailed Description
A size policy property has nested horizontalPolicy, verticalPolicy, horizontalStretch and verticalStretch subproperties. The top-level property's value can be retrieved using the value() function, and set using the setValue() slot.
The subproperties are created by QtIntPropertyManager and QtEnumPropertyManager objects. These managers can be retrieved using the subIntPropertyManager() and subEnumPropertyManager() functions respectively. In order to provide editing widgets for the subproperties in a property browser widget, these managers must be associated with editor factories.
In addition, QtSizePolicyPropertyManager provides the valueChanged() signal which is emitted whenever a property created by this manager changes.
See also
QtAbstractPropertyManager, QtIntPropertyManager, QtEnumPropertyManager
Constructor & Destructor Documentation
QtSizePolicyPropertyManager::QtSizePolicyPropertyManager (QObject * parent = 0)
Creates a manager with the given parent.
References QtSizePolicyPropertyManagerPrivate::m_enumPropertyManager, QtSizePolicyPropertyManagerPrivate::m_intPropertyManager, QtAbstractPropertyManager::propertyDestroyed(), and valueChanged().
QtSizePolicyPropertyManager::~QtSizePolicyPropertyManager ()
Destroys this manager, and all the properties it has created.
References QtAbstractPropertyManager::clear().
Member Function Documentation
void QtSizePolicyPropertyManager::initializeProperty (QtProperty * property) [protected], [virtual]
Implements QtAbstractPropertyManager .
References QtAbstractPropertyManager::addProperty(), QtProperty::addSubProperty(), QtSizePolicyPropertyManagerPrivate::m_enumPropertyManager, QtSizePolicyPropertyManagerPrivate::m_hPolicyToProperty, QtSizePolicyPropertyManagerPrivate::m_hStretchToProperty, QtSizePolicyPropertyManagerPrivate::m_intPropertyManager, QtSizePolicyPropertyManagerPrivate::m_propertyToHPolicy, QtSizePolicyPropertyManagerPrivate::m_propertyToHStretch, QtSizePolicyPropertyManagerPrivate::m_propertyToVPolicy, QtSizePolicyPropertyManagerPrivate::m_propertyToVStretch, QtSizePolicyPropertyManagerPrivate::m_values, QtSizePolicyPropertyManagerPrivate::m_vPolicyToProperty, QtSizePolicyPropertyManagerPrivate::m_vStretchToProperty, QtEnumPropertyManager::setEnumNames(), QtProperty::setPropertyName(), QtIntPropertyManager::setRange(), QtIntPropertyManager::setValue(), and QtEnumPropertyManager::setValue().
void QtSizePolicyPropertyManager::setValue (QtProperty * property, const QSizePolicy & value) [slot]
Sets the value of the given property to value. Nested properties are updated automatically.
See also
value(), valueChanged()
References QtSizePolicyPropertyManagerPrivate::m_enumPropertyManager, QtSizePolicyPropertyManagerPrivate::m_intPropertyManager, QtSizePolicyPropertyManagerPrivate::m_propertyToHPolicy, QtSizePolicyPropertyManagerPrivate::m_propertyToHStretch, QtSizePolicyPropertyManagerPrivate::m_propertyToVPolicy, QtSizePolicyPropertyManagerPrivate::m_propertyToVStretch, QtSizePolicyPropertyManagerPrivate::m_values, QtAbstractPropertyManager::propertyChanged(), QtIntPropertyManager::setValue(), QtEnumPropertyManager::setValue(), and valueChanged().
QtEnumPropertyManager * QtSizePolicyPropertyManager::subEnumPropertyManager () const
Returns the manager that creates the nested horizontalPolicy and verticalPolicy subproperties.
In order to provide editing widgets for the mentioned subproperties in a property browser widget, this manager must be associated with an editor factory.
See also
QtAbstractPropertyBrowser::setFactoryForManager()
References QtSizePolicyPropertyManagerPrivate::m_enumPropertyManager.
Referenced by QtVariantEditorFactory::connectPropertyManager(), QtVariantEditorFactory::disconnectPropertyManager(), and QtVariantPropertyManager::QtVariantPropertyManager().
QtIntPropertyManager * QtSizePolicyPropertyManager::subIntPropertyManager () const
Returns the manager that creates the nested horizontalStretch and verticalStretch subproperties.
In order to provide editing widgets for the mentioned subproperties in a property browser widget, this manager must be associated with an editor factory.
See also
QtAbstractPropertyBrowser::setFactoryForManager()
References QtSizePolicyPropertyManagerPrivate::m_intPropertyManager.
Referenced by QtVariantEditorFactory::connectPropertyManager(), QtVariantEditorFactory::disconnectPropertyManager(), and QtVariantPropertyManager::QtVariantPropertyManager().
void QtSizePolicyPropertyManager::uninitializeProperty (QtProperty * property) [protected], [virtual]
Reimplemented from QtAbstractPropertyManager .
References QtSizePolicyPropertyManagerPrivate::m_hPolicyToProperty, QtSizePolicyPropertyManagerPrivate::m_hStretchToProperty, QtSizePolicyPropertyManagerPrivate::m_propertyToHPolicy, QtSizePolicyPropertyManagerPrivate::m_propertyToHStretch, QtSizePolicyPropertyManagerPrivate::m_propertyToVPolicy, QtSizePolicyPropertyManagerPrivate::m_propertyToVStretch, QtSizePolicyPropertyManagerPrivate::m_values, QtSizePolicyPropertyManagerPrivate::m_vPolicyToProperty, and QtSizePolicyPropertyManagerPrivate::m_vStretchToProperty.
QSizePolicy QtSizePolicyPropertyManager::value (const QtProperty * property) const
Returns the given property's value.
If the given property is not managed by this manager, this function returns the default size policy.
See also
setValue()
References QtSizePolicyPropertyManagerPrivate::m_values.
void QtSizePolicyPropertyManager::valueChanged (QtProperty * property, const QSizePolicy & value) [signal]
This signal is emitted whenever a property created by this manager changes its value, passing a pointer to the property and the new value as parameters.
See also
setValue()
Referenced by QtSizePolicyPropertyManager(), and setValue().
QString QtSizePolicyPropertyManager::valueText (const QtProperty * property) const [protected], [virtual]
Unknown size policy on reading invalid uic3 files
Reimplemented from QtAbstractPropertyManager .
References QtSizePolicyPropertyManagerPrivate::m_values, QtMetaEnumProvider::policyEnumNames(), and QtMetaEnumProvider::sizePolicyToIndex().
The documentation for this class was generated from the following files:
qtpropertymanager.h
qtpropertymanager.cpp