EditorFactoryPrivate< Editor > Class Template Reference
Public Types
typedef QList< Editor * > EditorList
typedef QMap< QtProperty *, EditorList > PropertyToEditorListMap
typedef QMap< Editor *, QtProperty * > EditorToPropertyMap
Public Member Functions
Editor * createEditor (QtProperty *property, QWidget *parent)
void initializeEditor (QtProperty *property, Editor *e)
void slotEditorDestroyed (QObject *object)
Public Attributes
PropertyToEditorListMap m_createdEditors
EditorToPropertyMap m_editorToProperty
Member Typedef Documentation
template<class Editor> typedef QList<Editor *> EditorFactoryPrivate< Editor >::EditorList
template<class Editor> typedef QMap<Editor *, QtProperty *> EditorFactoryPrivate< Editor >::EditorToPropertyMap
template<class Editor> typedef QMap<QtProperty *, EditorList> EditorFactoryPrivate< Editor >::PropertyToEditorListMap
Member Function Documentation
template<class Editor > Editor * EditorFactoryPrivate< Editor >::createEditor (QtProperty * property, QWidget * parent)
References EditorFactoryPrivate< Editor >::initializeEditor().
Referenced by QtSpinBoxFactory::createEditor(), QtCheckBoxFactory::createEditor(), QtDoubleSpinBoxFactory::createEditor(), QtLineEditFactory::createEditor(), QtDateEditFactory::createEditor(), QtTimeEditFactory::createEditor(), QtDateTimeEditFactory::createEditor(), QtKeySequenceEditorFactory::createEditor(), QtCharEditorFactory::createEditor(), QtEnumEditorFactory::createEditor(), QtColorEditorFactory::createEditor(), and QtFontEditorFactory::createEditor().
template<class Editor> void EditorFactoryPrivate< Editor >::initializeEditor (QtProperty * property, Editor * e)
References EditorFactoryPrivate< Editor >::m_createdEditors, and EditorFactoryPrivate< Editor >::m_editorToProperty.
Referenced by QtSliderFactory::createEditor(), EditorFactoryPrivate< Editor >::createEditor(), and QtScrollBarFactory::createEditor().
template<class Editor > void EditorFactoryPrivate< Editor >::slotEditorDestroyed (QObject * object)
References EditorFactoryPrivate< Editor >::m_createdEditors, and EditorFactoryPrivate< Editor >::m_editorToProperty.
Member Data Documentation
template<class Editor> PropertyToEditorListMap EditorFactoryPrivate< Editor >::m_createdEditors
Referenced by EditorFactoryPrivate< Editor >::initializeEditor(), EditorFactoryPrivate< Editor >::slotEditorDestroyed(), QtSpinBoxFactoryPrivate::slotPropertyChanged(), QtSpinBoxFactoryPrivate::slotRangeChanged(), and QtSpinBoxFactoryPrivate::slotSingleStepChanged().
template<class Editor> EditorToPropertyMap EditorFactoryPrivate< Editor >::m_editorToProperty
Referenced by EditorFactoryPrivate< Editor >::initializeEditor(), EditorFactoryPrivate< Editor >::slotEditorDestroyed(), QtSpinBoxFactoryPrivate::slotSetValue(), QtCharEditorFactory::~QtCharEditorFactory(), QtCheckBoxFactory::~QtCheckBoxFactory(), QtColorEditorFactory::~QtColorEditorFactory(), QtDateEditFactory::~QtDateEditFactory(), QtDateTimeEditFactory::~QtDateTimeEditFactory(), QtDoubleSpinBoxFactory::~QtDoubleSpinBoxFactory(), QtEnumEditorFactory::~QtEnumEditorFactory(), QtFontEditorFactory::~QtFontEditorFactory(), QtKeySequenceEditorFactory::~QtKeySequenceEditorFactory(), QtLineEditFactory::~QtLineEditFactory(), QtScrollBarFactory::~QtScrollBarFactory(), QtSliderFactory::~QtSliderFactory(), QtSpinBoxFactory::~QtSpinBoxFactory(), and QtTimeEditFactory::~QtTimeEditFactory().
The documentation for this class was generated from the following file:
qteditorfactory.cpp