QtDoubleSpinBoxFactoryPrivate Class Reference
Public Member Functions
void slotPropertyChanged (QtProperty *property, double value)
void slotRangeChanged (QtProperty *property, double min, double max)
void slotSingleStepChanged (QtProperty *property, double step)
void slotDecimalsChanged (QtProperty *property, int prec)
void slotSetValue (double value)
Additional Inherited Members
Member Function Documentation
void QtDoubleSpinBoxFactoryPrivate::slotDecimalsChanged (QtProperty * property, int prec)
References QtDoublePropertyManager::value().
void QtDoubleSpinBoxFactoryPrivate::slotPropertyChanged (QtProperty * property, double value)
void QtDoubleSpinBoxFactoryPrivate::slotRangeChanged (QtProperty * property, double min, double max)
References QtDoublePropertyManager::value().
void QtDoubleSpinBoxFactoryPrivate::slotSetValue (double value)
References QtDoublePropertyManager::setValue().
void QtDoubleSpinBoxFactoryPrivate::slotSingleStepChanged (QtProperty * property, double step)
The documentation for this class was generated from the following file:
qteditorfactory.cpp