QtMetaEnumProvider Class Reference
Public Member Functions
QtMetaEnumProvider ()
QStringList policyEnumNames () const
QStringList languageEnumNames () const
QStringList countryEnumNames (QLocale::Language language) const
QSizePolicy::Policy indexToSizePolicy (int index) const
int sizePolicyToIndex (QSizePolicy::Policy policy) const
void indexToLocale (int languageIndex, int countryIndex, QLocale::Language *language, QLocale::Country *country) const
void localeToIndex (QLocale::Language language, QLocale::Country country, int *languageIndex, int *countryIndex) const
Constructor & Destructor Documentation
QtMetaEnumProvider::QtMetaEnumProvider ()
Member Function Documentation
QStringList QtMetaEnumProvider::countryEnumNames (QLocale::Language language) const [inline]
References QtMetaEnumWrapper::policy().
void QtMetaEnumProvider::indexToLocale (int languageIndex, int countryIndex, QLocale::Language * language, QLocale::Country * country) const
QSizePolicy::Policy QtMetaEnumProvider::indexToSizePolicy (int index) const
QStringList QtMetaEnumProvider::languageEnumNames () const [inline]
void QtMetaEnumProvider::localeToIndex (QLocale::Language language, QLocale::Country country, int * languageIndex, int * countryIndex) const
QStringList QtMetaEnumProvider::policyEnumNames () const [inline]
Referenced by QtSizePolicyPropertyManager::valueText().
int QtMetaEnumProvider::sizePolicyToIndex (QSizePolicy::Policy policy) const
Referenced by QtSizePolicyPropertyManager::valueText().
The documentation for this class was generated from the following file:
qtpropertymanager.cpp