QtColorPropertyManager Class Reference
The QtColorPropertyManager provides and manages QColor properties.
#include <qtpropertymanager.h>
Public Slots
void setValue (QtProperty *property, const QColor &val)
Signals
void valueChanged (QtProperty *property, const QColor &val)
Public Member Functions
QtColorPropertyManager (QObject *parent=0)
~QtColorPropertyManager ()
QtIntPropertyManager * subIntPropertyManager () const
QColor value (const QtProperty *property) const
Protected Member Functions
QString valueText (const QtProperty *property) const
QIcon valueIcon (const QtProperty *property) const
virtual void initializeProperty (QtProperty *property)
virtual void uninitializeProperty (QtProperty *property)
Detailed Description
A color property has nested red, green and blue subproperties. The top-level property's value can be retrieved using the value() function, and set using the setValue() slot.
The subproperties are created by a QtIntPropertyManager object. This manager can be retrieved using the subIntPropertyManager() function. In order to provide editing widgets for the subproperties in a property browser widget, this manager must be associated with an editor factory.
In addition, QtColorPropertyManager provides the valueChanged() signal which is emitted whenever a property created by this manager changes.
See also
QtAbstractPropertyManager, QtAbstractPropertyBrowser, QtIntPropertyManager
Constructor & Destructor Documentation
QtColorPropertyManager::QtColorPropertyManager (QObject * parent = 0)
Creates a manager with the given parent.
References QtColorPropertyManagerPrivate::m_intPropertyManager, QtAbstractPropertyManager::propertyDestroyed(), and valueChanged().
QtColorPropertyManager::~QtColorPropertyManager ()
Destroys this manager, and all the properties it has created.
References QtAbstractPropertyManager::clear().
Member Function Documentation
void QtColorPropertyManager::initializeProperty (QtProperty * property) [protected], [virtual]
Implements QtAbstractPropertyManager .
References QtAbstractPropertyManager::addProperty(), QtProperty::addSubProperty(), QtColorPropertyManagerPrivate::m_aToProperty, QtColorPropertyManagerPrivate::m_bToProperty, QtColorPropertyManagerPrivate::m_gToProperty, QtColorPropertyManagerPrivate::m_intPropertyManager, QtColorPropertyManagerPrivate::m_propertyToA, QtColorPropertyManagerPrivate::m_propertyToB, QtColorPropertyManagerPrivate::m_propertyToG, QtColorPropertyManagerPrivate::m_propertyToR, QtColorPropertyManagerPrivate::m_rToProperty, QtColorPropertyManagerPrivate::m_values, QtProperty::setPropertyName(), QtIntPropertyManager::setRange(), and QtIntPropertyManager::setValue().
void QtColorPropertyManager::setValue (QtProperty * property, const QColor & value) [slot]
Sets the value of the given property to value. Nested properties are updated automatically.
See also
value(), valueChanged()
References QtColorPropertyManagerPrivate::m_intPropertyManager, QtColorPropertyManagerPrivate::m_propertyToA, QtColorPropertyManagerPrivate::m_propertyToB, QtColorPropertyManagerPrivate::m_propertyToG, QtColorPropertyManagerPrivate::m_propertyToR, QtColorPropertyManagerPrivate::m_values, QtAbstractPropertyManager::propertyChanged(), QtIntPropertyManager::setValue(), and valueChanged().
Referenced by QtColorEditorFactoryPrivate::slotSetValue().
QtIntPropertyManager * QtColorPropertyManager::subIntPropertyManager () const
Returns the manager that produces the nested red, green and blue subproperties.
In order to provide editing widgets for the subproperties in a property browser widget, this manager must be associated with an editor factory.
See also
QtAbstractPropertyBrowser::setFactoryForManager()
References QtColorPropertyManagerPrivate::m_intPropertyManager.
Referenced by QtVariantEditorFactory::connectPropertyManager(), QtVariantEditorFactory::disconnectPropertyManager(), and QtVariantPropertyManager::QtVariantPropertyManager().
void QtColorPropertyManager::uninitializeProperty (QtProperty * property) [protected], [virtual]
Reimplemented from QtAbstractPropertyManager .
References QtColorPropertyManagerPrivate::m_aToProperty, QtColorPropertyManagerPrivate::m_bToProperty, QtColorPropertyManagerPrivate::m_gToProperty, QtColorPropertyManagerPrivate::m_propertyToA, QtColorPropertyManagerPrivate::m_propertyToB, QtColorPropertyManagerPrivate::m_propertyToG, QtColorPropertyManagerPrivate::m_propertyToR, QtColorPropertyManagerPrivate::m_rToProperty, and QtColorPropertyManagerPrivate::m_values.
QColor QtColorPropertyManager::value (const QtProperty * property) const
Returns the given property's value.
If the given property is not managed by this manager, this function returns an invalid color.
See also
setValue()
References QtColorPropertyManagerPrivate::m_values.
Referenced by QtColorEditorFactory::createEditor().
void QtColorPropertyManager::valueChanged (QtProperty * property, const QColor & value) [signal]
This signal is emitted whenever a property created by this manager changes its value, passing a pointer to the property and the new value as parameters.
See also
setValue()
Referenced by QtColorPropertyManager(), and setValue().
QIcon QtColorPropertyManager::valueIcon (const QtProperty * property) const [protected], [virtual]
Reimplemented from QtAbstractPropertyManager .
References QtPropertyBrowserUtils::brushValueIcon(), and QtColorPropertyManagerPrivate::m_values.
QString QtColorPropertyManager::valueText (const QtProperty * property) const [protected], [virtual]
Reimplemented from QtAbstractPropertyManager .
References QtPropertyBrowserUtils::colorValueText(), and QtColorPropertyManagerPrivate::m_values.
The documentation for this class was generated from the following files:
qtpropertymanager.h
qtpropertymanager.cpp