ScaleLabelInterface Class Reference
This interface defines methods to provide custom labels in a ScaleItem.
#include <scalelabelinterface.h>
Public Types
enum Type {
 Undefined = -1,
 TimeScale,
 Position = 1,
 ZPosition,
 XPosition,
 YPosition,
 LabelMap,
 User = 100,
 MaxUser = 1000
 }
Public Member Functions
 ScaleLabelInterface ()
virtual QString label (double value) const =0
This method must be reimplemented in a subclass and must return a QString to be displayed in the ScaleItem in correspondance to the value on the axis.
virtual Type type () const =0
virtual QString longestLabel () const =0
This method returns the longest possible string that may be returned by the implementing scale label interface.
Detailed Description
To customize axis labels, just provide an implementation of this ScaleLabelInterface and install it on a ScaleItem. You must implement the label method, that returns a QString depending on the value of the point in the axis.
Example
A custom implementation may return a string displaying a date/time value represented by a timestamp on the x axis.
Member Enumeration Documentation
Type
enum ScaleLabelInterface::Type
Enumerator
Undefined
TimeScale
Position
ZPosition
XPosition
YPosition
LabelMap
User
MaxUser
Constructor & Destructor Documentation
ScaleLabelInterface()
ScaleLabelInterface::ScaleLabelInterface ()
Member Function Documentation
label()
virtual QString ScaleLabelInterface::label (double value) const [pure virtual]
Parameters
value the value on the ScaleItem, in the ScaleItem coordinates.
Returns
a QString that represents the value passed as parameter.
See also
ScaleItem::installScaleLabelInterface
ScaleItem
Implemented in TimeScaleLabel .
Referenced by ExternalScaleWidget::paintEvent().
longestLabel()
virtual QString ScaleLabelInterface::longestLabel () const [pure virtual]
Note: this method must return the longest possible string independently of the
labels currently displayed as returned by the label method. For instance, if the x axis maps the months of the year, then `September` must be returned.
Note: if the longestLabel changes over time (for instance, the format of the months
switches to the month number instead of the name), then a call to updateGeometry may be required on the scales that use the ScaleLabelInterface, in order to recalculate the size occupied by the labels.
Implemented in TimeScaleLabel .
Referenced by ExternalScaleWidget::mCalculateLongestLabelWidth().
type()
virtual Type ScaleLabelInterface::type () const [pure virtual]
Implemented in TimeScaleLabel .
Referenced by PlotSceneWidget::saveData().
The documentation for this class was generated from the following files:
 scalelabelinterface.h
 scalelabelinterface.cpp