QtSizePropertyManager Class Reference
The QtSizePropertyManager provides and manages QSize properties.
#include <qtpropertymanager.h>
Public Slots
void setValue (QtProperty *property, const QSize &val)
void setMinimum (QtProperty *property, const QSize &minVal)
void setMaximum (QtProperty *property, const QSize &maxVal)
void setRange (QtProperty *property, const QSize &minVal, const QSize &maxVal)
Signals
void valueChanged (QtProperty *property, const QSize &val)
void rangeChanged (QtProperty *property, const QSize &minVal, const QSize &maxVal)
Public Member Functions
QtSizePropertyManager (QObject *parent=0)
~QtSizePropertyManager ()
QtIntPropertyManager * subIntPropertyManager () const
QSize value (const QtProperty *property) const
QSize minimum (const QtProperty *property) const
QSize maximum (const QtProperty *property) const
Protected Member Functions
QString valueText (const QtProperty *property) const
virtual void initializeProperty (QtProperty *property)
virtual void uninitializeProperty (QtProperty *property)
Detailed Description
A size property has nested width and height subproperties. The top-level property's value can be retrieved using the value() function, and set using the setValue() slot.
The subproperties are created by a QtIntPropertyManager object. This manager can be retrieved using the subIntPropertyManager() function. In order to provide editing widgets for the subproperties in a property browser widget, this manager must be associated with an editor factory.
A size property also has a range of valid values defined by a minimum size and a maximum size. These sizes can be retrieved using the minimum() and the maximum() functions, and set using the setMinimum() and setMaximum() slots. Alternatively, the range can be defined in one go using the setRange() slot.
In addition, QtSizePropertyManager provides the valueChanged() signal which is emitted whenever a property created by this manager changes, and the rangeChanged() signal which is emitted whenever such a property changes its range of valid sizes.
See also
QtAbstractPropertyManager, QtIntPropertyManager, QtSizeFPropertyManager
Constructor & Destructor Documentation
QtSizePropertyManager::QtSizePropertyManager (QObject * parent = 0)
Creates a manager with the given parent.
References QtSizePropertyManagerPrivate::m_intPropertyManager, QtAbstractPropertyManager::propertyDestroyed(), and valueChanged().
QtSizePropertyManager::~QtSizePropertyManager ()
Destroys this manager, and all the properties it has created.
References QtAbstractPropertyManager::clear().
Member Function Documentation
void QtSizePropertyManager::initializeProperty (QtProperty * property) [protected], [virtual]
Implements QtAbstractPropertyManager .
References QtAbstractPropertyManager::addProperty(), QtProperty::addSubProperty(), QtSizePropertyManagerPrivate::m_hToProperty, QtSizePropertyManagerPrivate::m_intPropertyManager, QtSizePropertyManagerPrivate::m_propertyToH, QtSizePropertyManagerPrivate::m_propertyToW, QtSizePropertyManagerPrivate::m_values, QtSizePropertyManagerPrivate::m_wToProperty, QtIntPropertyManager::setMinimum(), QtProperty::setPropertyName(), and QtIntPropertyManager::setValue().
QSize QtSizePropertyManager::maximum (const QtProperty * property) const
Returns the given property's maximum size value.
See also
setMaximum(), minimum(), setRange()
References QtSizePropertyManagerPrivate::m_values.
QSize QtSizePropertyManager::minimum (const QtProperty * property) const
Returns the given property's minimum size value.
See also
setMinimum(), maximum(), setRange()
References QtSizePropertyManagerPrivate::m_values.
void QtSizePropertyManager::rangeChanged (QtProperty * property, const QSize & minimum, const QSize & maximum) [signal]
This signal is emitted whenever a property created by this manager changes its range of valid sizes, passing a pointer to the property and the new minimum and maximum sizes.
See also
setRange()
Referenced by setMaximum(), setMinimum(), and setRange().
void QtSizePropertyManager::setMaximum (QtProperty * property, const QSize & maxVal) [slot]
Sets the maximum size value for the given property to maxVal.
When setting the maximum size value, the minimum and current values are adjusted if necessary (ensuring that the size range remains valid and that the current value is within the range).
See also
maximum(), setRange(), rangeChanged()
References QtSizePropertyManagerPrivate::Data::maximumValue(), QtAbstractPropertyManager::propertyChanged(), rangeChanged(), QtSizePropertyManagerPrivate::Data::setMaximumValue(), QtSizePropertyManagerPrivate::setRange(), and valueChanged().
void QtSizePropertyManager::setMinimum (QtProperty * property, const QSize & minVal) [slot]
Sets the minimum size value for the given property to minVal.
When setting the minimum size value, the maximum and current values are adjusted if necessary (ensuring that the size range remains valid and that the current value is within the range).
See also
minimum(), setRange(), rangeChanged()
References QtSizePropertyManagerPrivate::Data::minimumValue(), QtAbstractPropertyManager::propertyChanged(), rangeChanged(), QtSizePropertyManagerPrivate::Data::setMinimumValue(), QtSizePropertyManagerPrivate::setRange(), and valueChanged().
void QtSizePropertyManager::setRange (QtProperty * property, const QSize & minimum, const QSize & maximum) [slot]
Sets the range of valid values.
This is a convenience function defining the range of valid values in one go; setting the minimum and maximum values for the given property with a single function call.
When setting a new range, the current value is adjusted if necessary (ensuring that the value remains within the range).
See also
setMinimum(), setMaximum(), rangeChanged()
References QtAbstractPropertyManager::propertyChanged(), rangeChanged(), QtSizePropertyManagerPrivate::setRange(), and valueChanged().
void QtSizePropertyManager::setValue (QtProperty * property, const QSize & value) [slot]
Sets the value of the given property to value.
If the specified value is not valid according to the given property's size range, the value is adjusted to the nearest valid value within the size range.
See also
value(), setRange(), valueChanged()
References QtAbstractPropertyManager::propertyChanged(), QtSizePropertyManagerPrivate::setValue(), and valueChanged().
QtIntPropertyManager * QtSizePropertyManager::subIntPropertyManager () const
Returns the manager that creates the nested width and height subproperties.
In order to provide editing widgets for the width and height properties in a property browser widget, this manager must be associated with an editor factory.
See also
QtAbstractPropertyBrowser::setFactoryForManager()
References QtSizePropertyManagerPrivate::m_intPropertyManager.
Referenced by QtVariantPropertyManager::QtVariantPropertyManager().
void QtSizePropertyManager::uninitializeProperty (QtProperty * property) [protected], [virtual]
Reimplemented from QtAbstractPropertyManager .
References QtSizePropertyManagerPrivate::m_hToProperty, QtSizePropertyManagerPrivate::m_propertyToH, QtSizePropertyManagerPrivate::m_propertyToW, QtSizePropertyManagerPrivate::m_values, and QtSizePropertyManagerPrivate::m_wToProperty.
QSize QtSizePropertyManager::value (const QtProperty * property) const
Returns the given property's value.
If the given property is not managed by this manager, this function returns an invalid size
See also
setValue()
References QtSizePropertyManagerPrivate::m_values.
void QtSizePropertyManager::valueChanged (QtProperty * property, const QSize & value) [signal]
This signal is emitted whenever a property created by this manager changes its value, passing a pointer to the property and the new value as parameters.
See also
setValue()
Referenced by QtSizePropertyManager(), setMaximum(), setMinimum(), setRange(), and setValue().
QString QtSizePropertyManager::valueText (const QtProperty * property) const [protected], [virtual]
Reimplemented from QtAbstractPropertyManager .
References QtSizePropertyManagerPrivate::m_values.
The documentation for this class was generated from the following files:
qtpropertymanager.h
qtpropertymanager.cpp