TargetItem Class Reference
A QGraphicsObject that can be moved and can be attached to a writer in order to write a value according to the position of the item.
#include <targetitem.h>
Public Types
enum { Type = UserType + 101
 }
Public Slots
void setCircleColor (const QColor &c)
void setPointLabelEnabled (bool en)
void setInnerRadius (double r)
void setOuterRadius (double r)
void setRadiusScaleDivider (double divider)
void setX (double x)
stores the x position in the x scale coordinate.
void setY (double y)
stores the y position in the y scale coordinate.
void updatePosition ()
updates the item position according to the x and y values in scale coordinates
Public Member Functions
virtual int type () const
 TargetItem (ScaleItem *xAxis, ScaleItem *yAxis, PlotSceneWidget *plot)
The TargetItem constructor.
QColor circleColor () const
bool pointLabelEnabled () const
double innerRadius () const
double outerRadius () const
double radiusScaleDivider () const
double x () const
returns the x position in the ScaleItem x coordinate system
double y () const
returns the y position in the ScaleItem y coordinate system
virtual void paint (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget=0)
QRectF boundingRect () const
void installItemMoveListener (ItemMoveListener *l)
Installs an ItemMoveListener implementation.
 ItemMoveListener * itemMoveListener () const
Returns the currently installed item move listener.
void canvasRectChanged (const QRectF &newRect)
This method updates the item position when the plot canvas changes.
virtual void xAxisBoundsChanged (double, double)
This must be implemented from AxisChangeListener interface, but they do nothing.
virtual void yAxisBoundsChanged (double, double)
This is aimed at repositioning the target item.
virtual void axisAutoscaleChanged (ScaleItem::Orientation, bool)
This is aimed at repositioning the target item.
virtual void tickStepLenChanged (double)
notifies listeners about tick step len changes.
virtual void labelsFormatChanged (const QString &)
when the labels format changes, labelsFormatChanged is used
Protected Member Functions
virtual QVariant itemChange (GraphicsItemChange change, const QVariant &value)
void mousePressEvent (QGraphicsSceneMouseEvent *event)
void mouseReleaseEvent (QGraphicsSceneMouseEvent *event)
Detailed Description
A TargetItem must be attached to a couple of ScaleItem axes, and must be constructed passing a reference to a PlotSceneWidget, as you can see in the TargetItem constructor.
See also
TargetItem
In order to receive move events, you have to implement the ItemMoveListener interface and install it by calling installItemMoveListener. Move events are sent only if the mouse button is pressed. setPos does not per se produce a move event.
See also
installItemMoveListener
ItemMoveListener
Automatic repositioning of the TargetItem when the plot geometry changes.
TargetItem implements AxisChangeListener interface. When the PlotSceneWidget plot canvas changes its geometry, the canvasRectChanged method repositions the target item according to the new geometry and the values of x and y axes coordinates of the target items, which are set with setX and setY.
Note
The TargetItem constructor installs the TargetItem on each ScaleItem in order to receive the geometry change events of the PlotSceneWidget and to be able to reposition itself when the canvas rect changes.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
Type
Constructor & Destructor Documentation
TargetItem()
TargetItem::TargetItem (ScaleItem * xAxis, ScaleItem * yAxis, PlotSceneWidget * plot)
Parameters
xAxis a reference to the associated x ScaleItem
yAxis a reference to the associated x ScaleItem
plot the PlotSceneWidget in which to place the TargetItem
Initiates a red TargetItem with an inner radius of 15 and an outer radius of 20. The item is movable, selectable, sends geometry changes and sends scene position changes (QGraphicsItem's item flags).
The position with respect to the x and y scales is set to 0.0 by default. Remember to call setX and setY when you know what the position of the item is. Storing x and y position in axes coordinates is important in order to reposition the item when the canvas rect of the plot changes.
Automatic repositioning of the TargetItem on plot geometry change event.
When the PlotSceneWidget plot canvas changes its geometry, the canvasRectChanged method repositions the target item according to the new geometry and the values of x and y axes coordinates of the target items, which are set with setX and setY The TargetItem constructor installs the TargetItem on each axis, xAxis and yAxis, in order to automatically manage the object repositioning when the canvas plot rect changes.
References KRED.
Member Function Documentation
axisAutoscaleChanged()
virtual void TargetItem::axisAutoscaleChanged (ScaleItem::Orientation , bool) [inline], [virtual]
Implements AxisChangeListener .
boundingRect()
QRectF TargetItem::boundingRect () const
References outerRadius().
canvasRectChanged()
void TargetItem::canvasRectChanged (const QRectF & newRect) [virtual]
Implements AxisChangeListener .
References updatePosition().
circleColor()
QColor TargetItem::circleColor () const
innerRadius()
double TargetItem::innerRadius () const
Referenced by paint().
installItemMoveListener()
void TargetItem::installItemMoveListener (ItemMoveListener * l)
Parameters
l an object implementing the ItemMoveListener interface.
NULL if you want to remove a previously installed listener.
See also
ItemMoveListener
itemMoveListener
itemChange()
QVariant TargetItem::itemChange (GraphicsItemChange change, const QVariant & value) [protected], [virtual]
itemMoveListener()
 ItemMoveListener * TargetItem::itemMoveListener () const
Returns
the currently installed item move listener, NULL if none is installed
labelsFormatChanged()
virtual void TargetItem::labelsFormatChanged (const QString & newFormat) [inline], [virtual]
See also
ScaleItem
Implements AxisChangeListener .
mousePressEvent()
void TargetItem::mousePressEvent (QGraphicsSceneMouseEvent * event) [protected]
mouseReleaseEvent()
void TargetItem::mouseReleaseEvent (QGraphicsSceneMouseEvent * event) [protected]
outerRadius()
double TargetItem::outerRadius () const
Referenced by boundingRect(), and paint().
paint()
void TargetItem::paint (QPainter * painter, const QStyleOptionGraphicsItem * option, QWidget * widget = 0) [virtual]
References Elettra::black, innerRadius(), KDARKGREEN, KRED, outerRadius(), Elettra::white, x(), and y().
pointLabelEnabled()
bool TargetItem::pointLabelEnabled () const
radiusScaleDivider()
double TargetItem::radiusScaleDivider () const
setCircleColor
void TargetItem::setCircleColor (const QColor & c) [slot]
setInnerRadius
void TargetItem::setInnerRadius (double r) [slot]
setOuterRadius
void TargetItem::setOuterRadius (double r) [slot]
setPointLabelEnabled
void TargetItem::setPointLabelEnabled (bool en) [slot]
setRadiusScaleDivider
void TargetItem::setRadiusScaleDivider (double divider) [slot]
setX
void TargetItem::setX (double x) [slot]
Parameters
x the x value, in the ScaleItem coordinates (x axis coordinate)
Storing the x value in the target item allows its position to be automatically updated when the canvas rect of the plot changes.
See also
setY
y
x
References x().
setY
void TargetItem::setY (double y) [slot]
Parameters
y the y value, in the ScaleItem coordinates (y axis coordinate)
Storing the y value in the target item allows its position to be automatically updated when the canvas rect of the plot changes.
See also
setX
y
x
References y().
tickStepLenChanged()
virtual void TargetItem::tickStepLenChanged (double value) [inline], [virtual]
The tick step len can be tuned by a property in a ScaleItem or let it be automatically calculated by ScaleItem.
See also
ScaleItem
Implements AxisChangeListener .
type()
virtual int TargetItem::type () const [inline], [virtual]
References Type.
updatePosition
void TargetItem::updatePosition () [slot]
See also
setX
setY
x
y
Referenced by canvasRectChanged(), xAxisBoundsChanged(), and yAxisBoundsChanged().
x()
double TargetItem::x () const
Returns
the x position in the ScaleItem x coordinate system
Must have previously been set with setX
See also
setX
y
Referenced by paint(), and setX().
xAxisBoundsChanged()
void TargetItem::xAxisBoundsChanged (double , double) [virtual]
Calls updatePosition();
Implements AxisChangeListener .
References updatePosition().
y()
double TargetItem::y () const
Returns
the y position in the ScaleItem y coordinate system
Must have previously been set with setY
See also
setY
x
Referenced by paint(), and setY().
yAxisBoundsChanged()
void TargetItem::yAxisBoundsChanged (double , double) [virtual]
Calls updatePosition();
Implements AxisChangeListener .
References updatePosition().
The documentation for this class was generated from the following files:
 targetitem.h
 targetitem.cpp