QtCursorDatabase Class Reference
#include <qtpropertybrowserutils_p.h>
Public Member Functions
QtCursorDatabase ()
QStringList cursorShapeNames () const
QMap< int, QIcon > cursorShapeIcons () const
QString cursorToShapeName (const QCursor &cursor) const
QIcon cursorToShapeIcon (const QCursor &cursor) const
int cursorToValue (const QCursor &cursor) const
QCursor valueToCursor (int value) const
Constructor & Destructor Documentation
QtCursorDatabase::QtCursorDatabase ()
Member Function Documentation
QMap< int, QIcon > QtCursorDatabase::cursorShapeIcons () const
QStringList QtCursorDatabase::cursorShapeNames () const
QIcon QtCursorDatabase::cursorToShapeIcon (const QCursor & cursor) const
References cursorToValue().
QString QtCursorDatabase::cursorToShapeName (const QCursor & cursor) const
References cursorToValue().
int QtCursorDatabase::cursorToValue (const QCursor & cursor) const
Referenced by cursorToShapeIcon(), and cursorToShapeName().
QCursor QtCursorDatabase::valueToCursor (int value) const
The documentation for this class was generated from the following files:
qtpropertybrowserutils_p.h
qtpropertybrowserutils.cpp