ObjectPropertyManager Class Reference
#include <objectpropertymanager.h>
Public Slots
void slotValueChanged (QtProperty *p, const QVariant &v)
Public Member Functions
ObjectPropertyManager (QtVariantPropertyManager *propMan, QObject *parent)
QList< QtProperty * > setObjects (const QList< QObject * > &o)
void save ()
Constructor & Destructor Documentation
ObjectPropertyManager::ObjectPropertyManager (QtVariantPropertyManager * propMan, QObject * parent)
References ObjectPropertyManagerPrivate::qtVariantManager, and slotValueChanged().
Member Function Documentation
void ObjectPropertyManager::save ()
References ObjectPropertyManagerPrivate::objectsMap.
QList< QtProperty * > ObjectPropertyManager::setObjects (const QList< QObject * > & o)
References QtVariantPropertyManager::addProperty(), QtProperty::addSubProperty(), QtVariantPropertyManager::groupTypeId(), ObjectPropertyManagerPrivate::objectsMap, ObjectPropertyManagerPrivate::qtVariantManager, and QtVariantProperty::setValue().
Referenced by AxisConfWidget::addConfigurableObjects().
void ObjectPropertyManager::slotValueChanged (QtProperty * p, const QVariant & v) [slot]
References ObjectPropertyManagerPrivate::objectsMap, and QtProperty::propertyName().
Referenced by ObjectPropertyManager().
The documentation for this class was generated from the following files:
objectpropertymanager.h
objectpropertymanager.cpp