QtProperty Class Reference
The QtProperty class encapsulates an instance of a property.
#include <qtpropertybrowser.h>
Public Member Functions
virtual ~QtProperty ()
QList< QtProperty * > subProperties () const
QtAbstractPropertyManager * propertyManager () const
QString toolTip () const
QString statusTip () const
QString whatsThis () const
QString propertyName () const
QString propertyId () const
bool isEnabled () const
bool isModified () const
bool hasValue () const
QIcon valueIcon () const
QString valueText () const
virtual bool compare (QtProperty *otherProperty) const
void setToolTip (const QString &text)
void setStatusTip (const QString &text)
void setWhatsThis (const QString &text)
void setPropertyName (const QString &text)
void setPropertyId (const QString &text)
void setEnabled (bool enable)
void setModified (bool modified)
bool isSubProperty () const
void addSubProperty (QtProperty *property)
void insertSubProperty (QtProperty *property, QtProperty *afterProperty)
void removeSubProperty (QtProperty *property)
Protected Member Functions
QtProperty (QtAbstractPropertyManager *manager)
void propertyChanged ()
Friends
class QtAbstractPropertyManager
Detailed Description
Properties are created by objects of QtAbstractPropertyManager subclasses; a manager can create properties of a given type, and is used in conjunction with the QtAbstractPropertyBrowser class. A property is always owned by the manager that created it, which can be retrieved using the propertyManager() function.
QtProperty contains the most common property attributes, and provides functions for retrieving as well as setting their values:
Getter Setter propertyName() setPropertyName() statusTip() setStatusTip() toolTip() setToolTip() whatsThis() setWhatsThis() isEnabled() setEnabled() isModified() setModified() valueText() Nop valueIcon() Nop
It is also possible to nest properties: QtProperty provides the addSubProperty(), insertSubProperty() and removeSubProperty() functions to manipulate the set of subproperties. Use the subProperties() function to retrieve a property's current set of subproperties. Note that nested properties are not owned by the parent property, i.e. each subproperty is owned by the manager that created it.
See also
QtAbstractPropertyManager, QtBrowserItem
Constructor & Destructor Documentation
QtProperty::~QtProperty () [virtual]
Destroys this property.
Note that subproperties are detached but not destroyed, i.e. they can still be used in another context.
See also
QtAbstractPropertyManager::clear()
References QtPropertyPrivate::m_manager, QtPropertyPrivate::m_parentItems, QtPropertyPrivate::m_subItems, and QtAbstractPropertyManagerPrivate::propertyRemoved().
QtProperty::QtProperty (QtAbstractPropertyManager * manager) [explicit], [protected]
Creates a property with the given manager.
This constructor is only useful when creating a custom QtProperty subclass (e.g. QtVariantProperty). To create a regular QtProperty object, use the QtAbstractPropertyManager::addProperty() function instead.
See also
QtAbstractPropertyManager::addProperty()
References QtPropertyPrivate::QtPropertyPrivate().
Member Function Documentation
void QtProperty::addSubProperty (QtProperty * property)
Appends the given property to this property's subproperties.
If the given property already is added, this function does nothing.
See also
insertSubProperty(), removeSubProperty()
Referenced by QtVariantPropertyManager::addProperty(), QtLocalePropertyManager::initializeProperty(), QtPointPropertyManager::initializeProperty(), QtPointFPropertyManager::initializeProperty(), QtSizePropertyManager::initializeProperty(), QtSizeFPropertyManager::initializeProperty(), QtRectPropertyManager::initializeProperty(), QtRectFPropertyManager::initializeProperty(), QtSizePolicyPropertyManager::initializeProperty(), QtFontPropertyManager::initializeProperty(), QtColorPropertyManager::initializeProperty(), and ObjectPropertyManager::setObjects().
bool QtProperty::compare (QtProperty * otherProperty) const [virtual]
Returns True if this property is equal to otherProperty
The list of parent or sub properties are not considered in the comparison.
Reimplemented in QtVariantProperty .
References isEnabled(), isModified(), propertyId(), propertyName(), statusTip(), toolTip(), and whatsThis().
Referenced by QtVariantProperty::compare().
bool QtProperty::hasValue () const
Returns whether the property has a value.
See also
QtAbstractPropertyManager::hasValue()
Referenced by QtPropertyEditorView::drawRow(), QtTreePropertyBrowserPrivate::hasValue(), QtPropertyEditorDelegate::paint(), and QtButtonPropertyBrowserPrivate::propertyInserted().
void QtProperty::insertSubProperty (QtProperty * property, QtProperty * precedingProperty)
Inserts the given property after the specified precedingProperty into this property's list of subproperties. If precedingProperty is 0, the specified property is inserted at the beginning of the list.
If the given property already is inserted, this function does nothing.
See also
addSubProperty(), removeSubProperty()
References QtPropertyPrivate::m_parentItems, and subProperties().
Referenced by QtVariantPropertyManagerPrivate::createSubProperty().
bool QtProperty::isEnabled () const
Returns whether the property is enabled.
See also
setEnabled()
Referenced by QtVariantPropertyManager::addProperty(), and compare().
bool QtProperty::isModified () const
Returns whether the property is modified.
See also
setModified()
Referenced by QtVariantPropertyManager::addProperty(), and compare().
bool QtProperty::isSubProperty () const
Returns whether the property is sub property.
Referenced by QtVariantPropertyManager::setProperties().
void QtProperty::propertyChanged () [protected]
Referenced by QtAbstractPropertyManagerPrivate::propertyChanged().
QString QtProperty::propertyId () const
Returns the property's id.
See also
setPropertyId()
Referenced by QtVariantPropertyManager::addProperty(), compare(), and QtAbstractPropertyManager::qtProperty().
QtAbstractPropertyManager * QtProperty::propertyManager () const
Returns a pointer to the manager that owns this property.
Referenced by QtVariantPropertyManager::attributeValue(), QtAbstractEditorFactory< QtStringPropertyManager >::createEditor(), QtVariantPropertyManager::setAttribute(), QtVariantPropertyManager::setValue(), and QtVariantPropertyManager::value().
QString QtProperty::propertyName () const
Returns the property's name.
See also
setPropertyName()
Referenced by QtVariantPropertyManager::addProperty(), compare(), QtCursorEditorFactory::createEditor(), and ObjectPropertyManager::slotValueChanged().
void QtProperty::removeSubProperty (QtProperty * property)
Removes the given property from the list of subproperties without deleting it.
See also
addSubProperty(), insertSubProperty()
void QtProperty::setEnabled (bool enable)
Enables or disables the property according to the passed enable value.
See also
isEnabled()
void QtProperty::setModified (bool modified)
Sets the property's modified state according to the passed modified value.
See also
isModified()
void QtProperty::setPropertyId (const QString & id)
Sets the property's id to the given id.
See also
propertyId()
void QtProperty::setPropertyName (const QString & name)
Sets the property's name to the given name.
See also
propertyName()
Referenced by QtVariantPropertyManagerPrivate::createSubProperty(), QtLocalePropertyManager::initializeProperty(), QtPointPropertyManager::initializeProperty(), QtPointFPropertyManager::initializeProperty(), QtSizePropertyManager::initializeProperty(), QtSizeFPropertyManager::initializeProperty(), QtRectPropertyManager::initializeProperty(), QtRectFPropertyManager::initializeProperty(), QtSizePolicyPropertyManager::initializeProperty(), QtFontPropertyManager::initializeProperty(), QtColorPropertyManager::initializeProperty(), and QtFlagPropertyManager::setFlagNames().
void QtProperty::setStatusTip (const QString & text)
Sets the property's status tip to the given text.
See also
statusTip()
Referenced by QtVariantPropertyManagerPrivate::createSubProperty().
void QtProperty::setToolTip (const QString & text)
Sets the property's tool tip to the given text.
See also
toolTip()
Referenced by QtVariantPropertyManagerPrivate::createSubProperty().
void QtProperty::setWhatsThis (const QString & text)
Sets the property's `What's This` help text to the given text.
See also
whatsThis()
Referenced by QtVariantPropertyManagerPrivate::createSubProperty().
QString QtProperty::statusTip () const
Returns the property's status tip.
See also
setStatusTip()
Referenced by QtVariantPropertyManager::addProperty(), and compare().
QList< QtProperty * > QtProperty::subProperties () const
Returns the set of subproperties.
Note that subproperties are not owned by this property, but by the manager that created them.
See also
insertSubProperty(), removeSubProperty()
Referenced by QtVariantPropertyManager::addProperty(), QtVariantPropertyManager::initializeProperty(), and insertSubProperty().
QString QtProperty::toolTip () const
Returns the property's tool tip.
See also
setToolTip()
Referenced by compare().
QIcon QtProperty::valueIcon () const
Returns an icon representing the current state of this property.
If the given property type can not generate such an icon, this function returns an invalid icon.
See also
QtAbstractPropertyManager::valueIcon()
Referenced by QtVariantPropertyManager::valueIcon().
QString QtProperty::valueText () const
Returns a string representing the current state of this property.
If the given property type can not generate such a string, this function returns an empty string.
See also
QtAbstractPropertyManager::valueText()
Referenced by QtVariantPropertyManager::valueText().
QString QtProperty::whatsThis () const
Returns the property's `What's This` help text.
See also
setWhatsThis()
Referenced by QtVariantPropertyManager::addProperty(), and compare().
Friends And Related Function Documentation
friend class QtAbstractPropertyManager [friend]
The documentation for this class was generated from the following files:
qtpropertybrowser.h
qtpropertybrowser.cpp