DotsPainter Class Reference
#include <dotspainter.h>
Public Slots
void setDotsColor (const QColor &c)
changes the color of the dots
void setRadius (double w)
changes the width of the dots
void setPen (const QPen &p)
changes the color of the dots
void setBorderColor (const QColor &c)
sets the border color of the dot.
Public Member Functions
 DotsPainter (CurveItem * curveItem)
virtual ~DotsPainter ()
virtual void draw (SceneCurve *curve, PlotSceneWidget *plot, QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget=0)
the drawing method.
virtual CurveItem * curveItem () const
virtual QSizeF elementSize () const
the size of each drawn element
virtual int type () const
QColor borderColor () const
QColor dotsColor () const
returns the colour used for the dots that form the curve
double radius () const
returns the line width
QPen pen () const
returns the pen used to draw the dots
Properties
QColor dotsColor
QColor borderColor
double radius
QPen pen
Additional Inherited Members
Constructor & Destructor Documentation
DotsPainter()
DotsPainter::DotsPainter (CurveItem * curveItem)
References curveItem(), CurveItem::installItemPainterInterface(), KMAROON, and KYELLOW.
~DotsPainter()
DotsPainter::~DotsPainter () [virtual]
Member Function Documentation
borderColor()
QColor DotsPainter::borderColor () const
curveItem()
 CurveItem * DotsPainter::curveItem () const [virtual]
Implements ItemPainterInterface .
Referenced by DotsPainter().
dotsColor()
QColor DotsPainter::dotsColor () const
Returns
the color of the dots
See also
setDotsColor
setRadius
draw()
void DotsPainter::draw (SceneCurve * curve, PlotSceneWidget * plot, QPainter * painter, const QStyleOptionGraphicsItem * option, QWidget * widget = 0) [virtual]
This method is invoked by CurveItem inside paint method. You can obtain the points of the curve in scene coordinates by calling curve->points and the size of the points by means of curve->dataSize. It may be necessary to call painter->save() and painter->restore() at the beginning and end of the drawing. Each draw method of each installed ItemPainterInterface is actually invoked in sequence without saving and restoring the painter state for you.
See also
CurveItem
LinePainter
DotsPainter
Implements ItemPainterInterface .
References SceneCurve::data(), SceneCurve::dataSize(), Data::invalidDataPoints(), SceneCurve::points(), Elettra::red, PlotSceneWidget::transform(), and PlotSceneWidget::xScaleItem().
elementSize()
QSizeF DotsPainter::elementSize () const [virtual]
This size is used by the classes that use ItemPainterInterface to know how much extra space is needed in order to calculate the bounding rect of the CurveItem or other geometrical properties.
For instance, if you are drawing circles, then this method should return the radius of the circle, so that CurveItem knows how much space has to be added to the curve bounds in order to correcly draw the items.
If you are drawing lines, then this size can be 0x0 since the connecting lines do not require extra space to be calculated. If you use a particular pen width, then you may want to return its width in order to be sure that CurveItem takes care of this space.
See also
CurveItem
Implements ItemPainterInterface .
pen()
QPen DotsPainter::pen () const [virtual]
Implements the pen method of the ItemPainterInterface.
Returns
the pen used to draw the dots.
the pen used to draw the circles
Implements ItemPainterInterface .
radius()
double DotsPainter::radius () const
Returns
the width of the line used to draw the dots.
See also
setDotsColor
setRadius
setBorderColor
void DotsPainter::setBorderColor (const QColor & c) [slot]
setDotsColor
void DotsPainter::setDotsColor (const QColor & c) [slot]
The default colour is yellow
See also
lineColor
setPen
void DotsPainter::setPen (const QPen & p) [slot]
See also
linePen
setRadius
void DotsPainter::setRadius (double w) [slot]
The default is 0.0
See also
radius
type()
int DotsPainter::type () const [virtual]
Implements ItemPainterInterface .
References ItemPainterInterface::Dot.
Property Documentation
borderColor
QColor DotsPainter::borderColor [read], [write]
dotsColor
QColor DotsPainter::dotsColor [read], [write]
pen
QPen DotsPainter::pen [read], [write]
radius
double DotsPainter::radius [read], [write]
The documentation for this class was generated from the following files:
 dotspainter.h
 dotspainter.cpp