QGraphicsZoomer Class Reference
#include <qgraphicszoomer.h>
Public Member Functions
 QGraphicsZoomer (PlotSceneWidget *plot)
void addScale (ScaleItem *scale)
void removeScale (ScaleItem *scale)
virtual ~QGraphicsZoomer ()
void zoom (const QRectF &zoomRect)
zoom the axes according to the zoomRect given in view coordinates
bool inZoom () const
void unzoom ()
void clear ()
int stackSize () const
void canvasRectChanged (const QRectF &newRect)
notifies when the canvas area changes.
void xAxisBoundsChanged (double, double)
x axis bounds notification
void yAxisBoundsChanged (double, double)
y axis bounds notification
void axisAutoscaleChanged (ScaleItem::Orientation, bool)
x axis auto scale property change notification
virtual void tickStepLenChanged (double)
notifies listeners about tick step len changes.
virtual void labelsFormatChanged (const QString &)
when the labels format changes, labelsFormatChanged is used
 ScaleItem * xAxis () const
Returns ScaleItem::xBottom if set.
 ScaleItem * yAxis () const
Constructor & Destructor Documentation
QGraphicsZoomer()
QGraphicsZoomer::QGraphicsZoomer (PlotSceneWidget * plot) [explicit]
References QGraphicsZoomerPrivate::inZoom, and QGraphicsZoomerPrivate::plot.
~QGraphicsZoomer()
QGraphicsZoomer::~QGraphicsZoomer () [virtual]
References ScaleItem::removeAxisChangeListener(), and QGraphicsZoomerPrivate::zoomStackMap.
Member Function Documentation
addScale()
void QGraphicsZoomer::addScale (ScaleItem * scale)
References ScaleItem::installAxisChangeListener(), and QGraphicsZoomerPrivate::zoomStackMap.
axisAutoscaleChanged()
void QGraphicsZoomer::axisAutoscaleChanged (ScaleItem::Orientation o, bool autoscale) [inline], [virtual]
Parameters
o the ScaleItem::Orientation property that helps you find out which axis (x or y) has changed its property.
autoscale true autoscale is enabled.
autoscale false autoscale is disabled.
Implements AxisChangeListener .
canvasRectChanged()
void QGraphicsZoomer::canvasRectChanged (const QRectF & newRect) [virtual]
In some cases, when the axis is placed on the right or at the bottom of the plot, the labels might require more space, and the plot area must be reduced.
Parameters
newRect the new rectangle
d_ptr->zoomStack[0] = newRect;
Implements AxisChangeListener .
clear()
void QGraphicsZoomer::clear ()
References QGraphicsZoomerPrivate::inZoom, and unzoom().
inZoom()
bool QGraphicsZoomer::inZoom () const
References QGraphicsZoomerPrivate::inZoom.
labelsFormatChanged()
virtual void QGraphicsZoomer::labelsFormatChanged (const QString & newFormat) [inline], [virtual]
See also
ScaleItem
Implements AxisChangeListener .
removeScale()
void QGraphicsZoomer::removeScale (ScaleItem * scale)
References ScaleItem::removeAxisChangeListener(), and QGraphicsZoomerPrivate::zoomStackMap.
stackSize()
int QGraphicsZoomer::stackSize () const
References QGraphicsZoomerPrivate::zoomStackMap.
Referenced by unzoom().
tickStepLenChanged()
virtual void QGraphicsZoomer::tickStepLenChanged (double value) [inline], [virtual]
The tick step len can be tuned by a property in a ScaleItem or let it be automatically calculated by ScaleItem.
See also
ScaleItem
Implements AxisChangeListener .
unzoom()
void QGraphicsZoomer::unzoom ()
References QGraphicsZoomerPrivate::inZoom, ScaleItem::setBounds(), stackSize(), and QGraphicsZoomerPrivate::zoomStackMap.
Referenced by clear().
xAxis()
 ScaleItem * QGraphicsZoomer::xAxis () const
References ScaleItem::axisId(), ScaleItem::xBottom, and QGraphicsZoomerPrivate::zoomStackMap.
xAxisBoundsChanged()
void QGraphicsZoomer::xAxisBoundsChanged (double lower, double upper) [inline], [virtual]
Parameters
lower the new lower bound
upper the new upper bound
Implements AxisChangeListener .
yAxis()
 ScaleItem * QGraphicsZoomer::yAxis () const
References ScaleItem::axisId(), ScaleItem::yLeft, and QGraphicsZoomerPrivate::zoomStackMap.
yAxisBoundsChanged()
void QGraphicsZoomer::yAxisBoundsChanged (double lower, double upper) [inline], [virtual]
Parameters
lower the new lower bound
upper the new upper bound
Implements AxisChangeListener .
zoom()
void QGraphicsZoomer::zoom (const QRectF & zoomRect)
Parameters
zoomRect rectangle in view coordinates
References ScaleItem::axisId(), ScaleItem::Horizontal, PlotSceneWidget::invTransform(), QGraphicsZoomerPrivate::inZoom, ScaleItem::lowerBound, ScaleItem::orientation(), QGraphicsZoomerPrivate::plot, ScaleItem::setBounds(), ScaleItem::upperBound, and QGraphicsZoomerPrivate::zoomStackMap.
The documentation for this class was generated from the following files:
 qgraphicszoomer.h
 qgraphicszoomer.cpp