QtDateTimePropertyManager Class Reference
The QtDateTimePropertyManager provides and manages QDateTime properties.
#include <qtpropertymanager.h>
Public Slots
void setValue (QtProperty *property, const QDateTime &val)
Signals
void valueChanged (QtProperty *property, const QDateTime &val)
Public Member Functions
QtDateTimePropertyManager (QObject *parent=0)
~QtDateTimePropertyManager ()
QDateTime value (const QtProperty *property) const
Protected Member Functions
QString valueText (const QtProperty *property) const
virtual void initializeProperty (QtProperty *property)
virtual void uninitializeProperty (QtProperty *property)
Detailed Description
A date and time property has a current value which can be retrieved using the value() function, and set using the setValue() slot. In addition, QtDateTimePropertyManager provides the valueChanged() signal which is emitted whenever a property created by this manager changes.
See also
QtAbstractPropertyManager, QtDateTimeEditFactory, QtDatePropertyManager
Constructor & Destructor Documentation
QtDateTimePropertyManager::QtDateTimePropertyManager (QObject * parent = 0)
Creates a manager with the given parent.
References QtDateTimePropertyManagerPrivate::m_format.
QtDateTimePropertyManager::~QtDateTimePropertyManager ()
Destroys this manager, and all the properties it has created.
References QtAbstractPropertyManager::clear().
Member Function Documentation
void QtDateTimePropertyManager::initializeProperty (QtProperty * property) [protected], [virtual]
Implements QtAbstractPropertyManager .
References QtDateTimePropertyManagerPrivate::m_values.
void QtDateTimePropertyManager::setValue (QtProperty * property, const QDateTime & value) [slot]
Sets the value of the given property to value.
See also
value(), valueChanged()
References QtDateTimePropertyManagerPrivate::m_values, QtAbstractPropertyManager::propertyChanged(), and valueChanged().
Referenced by QtDateTimeEditFactoryPrivate::slotSetValue().
void QtDateTimePropertyManager::uninitializeProperty (QtProperty * property) [protected], [virtual]
Reimplemented from QtAbstractPropertyManager .
References QtDateTimePropertyManagerPrivate::m_values.
QDateTime QtDateTimePropertyManager::value (const QtProperty * property) const
Returns the given property's value.
If the given property is not managed by this manager, this function returns an invalid QDateTime object.
See also
setValue()
References QtDateTimePropertyManagerPrivate::m_values.
Referenced by QtDateTimeEditFactory::createEditor().
void QtDateTimePropertyManager::valueChanged (QtProperty * property, const QDateTime & value) [signal]
This signal is emitted whenever a property created by this manager changes its value, passing a pointer to the property and the new value as parameters.
Referenced by setValue().
QString QtDateTimePropertyManager::valueText (const QtProperty * property) const [protected], [virtual]
Reimplemented from QtAbstractPropertyManager .
References QtDateTimePropertyManagerPrivate::m_format, and QtDateTimePropertyManagerPrivate::m_values.
The documentation for this class was generated from the following files:
qtpropertymanager.h
qtpropertymanager.cpp