Zoomer Class Reference
#include <zoomer.h>
Public Member Functions
 Zoomer (PlotSceneWidget *plot)
void zoom (const QRectF &zoomRect)
void setZoomRect (const QRectF &r)
void setBaseScale (double sx, double sy)
bool inZoom () const
void unzoom ()
Constructor & Destructor Documentation
Zoomer()
Zoomer::Zoomer (PlotSceneWidget * plot) [explicit]
References ZoomerPrivate::inZoom, ZoomerPrivate::plot, PlotSceneWidget::plotRect(), ZoomerPrivate::zoomRect, and ZoomerPrivate::zoomStack.
Member Function Documentation
inZoom()
bool Zoomer::inZoom () const
References ZoomerPrivate::inZoom.
setBaseScale()
void Zoomer::setBaseScale (double sx, double sy)
References ZoomerPrivate::zoomStack.
setZoomRect()
void Zoomer::setZoomRect (const QRectF & r)
References ZoomerPrivate::zoomRect.
unzoom()
void Zoomer::unzoom ()
References ZoomerPrivate::inZoom, ZoomerPrivate::plot, PlotSceneWidget::scale(), ZoomerPrivate::zoomRect, and ZoomerPrivate::zoomStack.
zoom()
void Zoomer::zoom (const QRectF & zoomRect)
References ZoomerPrivate::inZoom, ZoomerPrivate::plot, PlotSceneWidget::plotRect(), PlotSceneWidget::scale(), and ZoomerPrivate::zoomStack.
The documentation for this class was generated from the following files:
 zoomer.h
 zoomer.cpp