QtTreePropertyBrowserPrivate Class Reference
Public Member Functions
QtTreePropertyBrowserPrivate ()
void init (QWidget *parent)
void propertyInserted (QtBrowserItem *index, QtBrowserItem *afterIndex)
void propertyRemoved (QtBrowserItem *index)
void propertyChanged (QtBrowserItem *index)
QWidget * createEditor (QtProperty *property, QWidget *parent) const
QtProperty * indexToProperty (const QModelIndex &index) const
QTreeWidgetItem * indexToItem (const QModelIndex &index) const
QtBrowserItem * indexToBrowserItem (const QModelIndex &index) const
bool lastColumn (int column) const
void disableItem (QTreeWidgetItem *item) const
void enableItem (QTreeWidgetItem *item) const
bool hasValue (QTreeWidgetItem *item) const
void slotCollapsed (const QModelIndex &index)
void slotExpanded (const QModelIndex &index)
QColor calculatedBackgroundColor (QtBrowserItem *item) const
QtPropertyEditorView * treeWidget () const
bool markPropertiesWithoutValue () const
QtBrowserItem * currentItem () const
void setCurrentItem (QtBrowserItem *browserItem, bool block)
void editItem (QtBrowserItem *browserItem)
void slotCurrentBrowserItemChanged (QtBrowserItem *item)
void slotCurrentTreeItemChanged (QTreeWidgetItem *newItem, QTreeWidgetItem *)
QTreeWidgetItem * editedItem () const
Constructor & Destructor Documentation
QtTreePropertyBrowserPrivate::QtTreePropertyBrowserPrivate ()
Member Function Documentation
QColor QtTreePropertyBrowserPrivate::calculatedBackgroundColor (QtBrowserItem * item) const
References QtBrowserItem::parent().
Referenced by QtTreePropertyBrowser::calculatedBackgroundColor(), createEditor(), and QtPropertyEditorView::drawRow().
QWidget* QtTreePropertyBrowserPrivate::createEditor (QtProperty * property, QWidget * parent) const [inline]
References calculatedBackgroundColor(), QtAbstractPropertyBrowser::createEditor(), disableItem(), enableItem(), hasValue(), indexToBrowserItem(), indexToItem(), indexToProperty(), lastColumn(), slotCollapsed(), and slotExpanded().
QtBrowserItem * QtTreePropertyBrowserPrivate::currentItem () const
Referenced by markPropertiesWithoutValue(), and slotCurrentBrowserItemChanged().
void QtTreePropertyBrowserPrivate::disableItem (QTreeWidgetItem * item) const
References QtPropertyEditorDelegate::closeEditor().
Referenced by createEditor(), and propertyChanged().
QTreeWidgetItem * QtTreePropertyBrowserPrivate::editedItem () const
References QtPropertyEditorDelegate::editedItem().
Referenced by QtPropertyEditorView::keyPressEvent(), markPropertiesWithoutValue(), and QtPropertyEditorView::mousePressEvent().
void QtTreePropertyBrowserPrivate::editItem (QtBrowserItem * browserItem)
Referenced by QtTreePropertyBrowser::editItem(), and markPropertiesWithoutValue().
void QtTreePropertyBrowserPrivate::enableItem (QTreeWidgetItem * item) const
Referenced by createEditor(), and propertyChanged().
bool QtTreePropertyBrowserPrivate::hasValue (QTreeWidgetItem * item) const
References QtProperty::hasValue(), and QtBrowserItem::property().
Referenced by createEditor(), and QtPropertyEditorView::mousePressEvent().
QtBrowserItem * QtTreePropertyBrowserPrivate::indexToBrowserItem (const QModelIndex & index) const
References QtPropertyEditorView::indexToItem().
Referenced by createEditor(), and QtPropertyEditorView::drawRow().
QTreeWidgetItem * QtTreePropertyBrowserPrivate::indexToItem (const QModelIndex & index) const
References QtPropertyEditorView::indexToItem().
Referenced by createEditor(), slotCollapsed(), and slotExpanded().
QtProperty * QtTreePropertyBrowserPrivate::indexToProperty (const QModelIndex & index) const
References QtPropertyEditorView::indexToItem(), and QtBrowserItem::property().
Referenced by createEditor(), and QtPropertyEditorView::drawRow().
void QtTreePropertyBrowserPrivate::init (QWidget * parent)
References drawIndicatorIcon(), QtPropertyEditorView::setEditorPrivate(), QtPropertyEditorDelegate::setEditorPrivate(), slotCollapsed(), slotCurrentTreeItemChanged(), and slotExpanded().
Referenced by QtTreePropertyBrowser::QtTreePropertyBrowser().
bool QtTreePropertyBrowserPrivate::lastColumn (int column) const
Referenced by createEditor().
bool QtTreePropertyBrowserPrivate::markPropertiesWithoutValue () const [inline]
References currentItem(), editedItem(), editItem(), setCurrentItem(), slotCurrentBrowserItemChanged(), and slotCurrentTreeItemChanged().
Referenced by QtPropertyEditorView::drawRow(), QtPropertyEditorView::mousePressEvent(), and propertyChanged().
void QtTreePropertyBrowserPrivate::propertyChanged (QtBrowserItem * index)
References disableItem(), enableItem(), and markPropertiesWithoutValue().
Referenced by QtTreePropertyBrowser::itemChanged().
void QtTreePropertyBrowserPrivate::propertyInserted (QtBrowserItem * index, QtBrowserItem * afterIndex)
References QtBrowserItem::parent().
Referenced by QtTreePropertyBrowser::itemInserted().
void QtTreePropertyBrowserPrivate::propertyRemoved (QtBrowserItem * index)
Referenced by QtTreePropertyBrowser::itemRemoved().
void QtTreePropertyBrowserPrivate::setCurrentItem (QtBrowserItem * browserItem, bool block)
Referenced by markPropertiesWithoutValue(), and slotCurrentBrowserItemChanged().
void QtTreePropertyBrowserPrivate::slotCollapsed (const QModelIndex & index)
References QtTreePropertyBrowser::collapsed(), and indexToItem().
Referenced by createEditor(), and init().
void QtTreePropertyBrowserPrivate::slotCurrentBrowserItemChanged (QtBrowserItem * item)
References currentItem(), and setCurrentItem().
Referenced by markPropertiesWithoutValue().
void QtTreePropertyBrowserPrivate::slotCurrentTreeItemChanged (QTreeWidgetItem * newItem, QTreeWidgetItem *)
References QtAbstractPropertyBrowser::setCurrentItem().
Referenced by init(), and markPropertiesWithoutValue().
void QtTreePropertyBrowserPrivate::slotExpanded (const QModelIndex & index)
References QtTreePropertyBrowser::expanded(), and indexToItem().
Referenced by createEditor(), and init().
QtPropertyEditorView* QtTreePropertyBrowserPrivate::treeWidget () const [inline]
The documentation for this class was generated from the following file:
qttreepropertybrowser.cpp