QtVariantPropertyManager Class Reference
The QtVariantPropertyManager class provides and manages QVariant based properties.
#include <qtvariantproperty.h>
Public Slots
virtual void setValue (QtProperty *property, const QVariant &val)
virtual void setAttribute (QtProperty *property, const QString &attribute, const QVariant &value)
Signals
void valueChanged (QtProperty *property, const QVariant &val)
void attributeChanged (QtProperty *property, const QString &attribute, const QVariant &val)
Public Member Functions
QtVariantPropertyManager (QObject *parent=0)
~QtVariantPropertyManager ()
virtual QtVariantProperty * addProperty (int propertyType, const QString &name=QString())
void setProperties (QSet< QtProperty * > properties)
int propertyType (const QtProperty *property) const
int valueType (const QtProperty *property) const
QtVariantProperty * variantProperty (const QtProperty *property) const
virtual bool isPropertyTypeSupported (int propertyType) const
virtual int valueType (int propertyType) const
virtual QStringList attributes (int propertyType) const
virtual int attributeType (int propertyType, const QString &attribute) const
virtual QVariant value (const QtProperty *property) const
virtual QVariant attributeValue (const QtProperty *property, const QString &attribute) const
Static Public Member Functions
static int enumTypeId ()
static int flagTypeId ()
static int groupTypeId ()
static int iconMapTypeId ()
Protected Member Functions
virtual bool hasValue (const QtProperty *property) const
QString valueText (const QtProperty *property) const
QIcon valueIcon (const QtProperty *property) const
virtual void initializeProperty (QtProperty *property)
virtual void uninitializeProperty (QtProperty *property)
virtual QtProperty * createProperty ()
Detailed Description
QtVariantPropertyManager provides the addProperty() function which creates QtVariantProperty objects. The QtVariantProperty class is a convenience class handling QVariant based properties inheriting QtProperty. A QtProperty object created by a QtVariantPropertyManager instance can be converted into a QtVariantProperty object using the variantProperty() function.
The property's value can be retrieved using the value(), and set using the setValue() slot. In addition the property's type, and the type of its value, can be retrieved using the propertyType() and valueType() functions respectively.
A property's type is a QVariant::Type enumerator value, and usually a property's type is the same as its value type. But for some properties the types differ, for example for enums, flags and group types in which case QtVariantPropertyManager provides the enumTypeId(), flagTypeId() and groupTypeId() functions, respectively, to identify their property type (the value types are QVariant::Int for the enum and flag types, and QVariant::Invalid for the group type).
Use the isPropertyTypeSupported() function to check if a particular property type is supported. The currently supported property types are:
Property Type Property Type Id int QVariant::Int double QVariant::Double bool QVariant::Bool QString QVariant::String QDate QVariant::Date QTime QVariant::Time QDateTime QVariant::DateTime QKeySequence QVariant::KeySequence QChar QVariant::Char QLocale QVariant::Locale QPoint QVariant::Point QPointF QVariant::PointF QSize QVariant::Size QSizeF QVariant::SizeF QRect QVariant::Rect QRectF QVariant::RectF QColor QVariant::Color QSizePolicy QVariant::SizePolicy QFont QVariant::Font QCursor QVariant::Cursor enum enumTypeId() flag flagTypeId() group groupTypeId()
Each property type can provide additional attributes, e.g. QVariant::Int and QVariant::Double provides minimum and maximum values. The currently supported attributes are:
Property Type Attribute Name Attribute Type int minimum QVariant::Int maximum QVariant::Int singleStep QVariant::Int double minimum QVariant::Double maximum QVariant::Double singleStep QVariant::Double decimals QVariant::Int QString regExp QVariant::RegExp QDate minimum QVariant::Date maximum QVariant::Date QPointF decimals QVariant::Int QSize minimum QVariant::Size maximum QVariant::Size QSizeF minimum QVariant::SizeF maximum QVariant::SizeF decimals QVariant::Int QRect constraint QVariant::Rect QRectF constraint QVariant::RectF decimals QVariant::Int enum enumNames QVariant::StringList enumIcons iconMapTypeId() flag flagNames QVariant::StringList
The attributes for a given property type can be retrieved using the attributes() function. Each attribute has a value type which can be retrieved using the attributeType() function, and a value accessible through the attributeValue() function. In addition, the value can be set using the setAttribute() slot.
QtVariantManager also provides the valueChanged() signal which is emitted whenever a property created by this manager change, and the attributeChanged() signal which is emitted whenever an attribute of such a property changes.
See also
QtVariantProperty, QtVariantEditorFactory
Constructor & Destructor Documentation
QtVariantPropertyManager::QtVariantPropertyManager (QObject * parent = 0)
Creates a manager with the given parent.
References enumTypeId(), flagTypeId(), groupTypeId(), iconMapTypeId(), QtVariantPropertyManagerPrivate::m_constraintAttribute, QtVariantPropertyManagerPrivate::m_creatingProperty, QtVariantPropertyManagerPrivate::m_creatingSubProperties, QtVariantPropertyManagerPrivate::m_decimalsAttribute, QtVariantPropertyManagerPrivate::m_destroyingSubProperties, QtVariantPropertyManagerPrivate::m_enumIconsAttribute, QtVariantPropertyManagerPrivate::m_enumNamesAttribute, QtVariantPropertyManagerPrivate::m_flagNamesAttribute, QtVariantPropertyManagerPrivate::m_maximumAttribute, QtVariantPropertyManagerPrivate::m_minimumAttribute, QtVariantPropertyManagerPrivate::m_propertyType, QtVariantPropertyManagerPrivate::m_regExpAttribute, QtVariantPropertyManagerPrivate::m_singleStepAttribute, QtVariantPropertyManagerPrivate::m_typeToAttributeToAttributeType, QtVariantPropertyManagerPrivate::m_typeToPropertyManager, QtVariantPropertyManagerPrivate::m_typeToValueType, QtAbstractPropertyManager::propertyInserted(), QtAbstractPropertyManager::propertyRemoved(), QtFlagPropertyManager::subBoolPropertyManager(), QtFontPropertyManager::subBoolPropertyManager(), QtPointFPropertyManager::subDoublePropertyManager(), QtSizeFPropertyManager::subDoublePropertyManager(), QtRectFPropertyManager::subDoublePropertyManager(), QtLocalePropertyManager::subEnumPropertyManager(), QtSizePolicyPropertyManager::subEnumPropertyManager(), QtFontPropertyManager::subEnumPropertyManager(), QtPointPropertyManager::subIntPropertyManager(), QtSizePropertyManager::subIntPropertyManager(), QtRectPropertyManager::subIntPropertyManager(), QtSizePolicyPropertyManager::subIntPropertyManager(), QtFontPropertyManager::subIntPropertyManager(), QtColorPropertyManager::subIntPropertyManager(), and valueChanged().
QtVariantPropertyManager::~QtVariantPropertyManager ()
Destroys this manager, and all the properties it has created.
References QtAbstractPropertyManager::clear().
Member Function Documentation
QtVariantProperty * QtVariantPropertyManager::addProperty (int propertyType, const QString & name = QString()) [virtual]
Creates and returns a variant property of the given propertyType with the given name.
If the specified propertyType is not supported by this variant manager, this function returns 0.
Do not use the inherited QtAbstractPropertyManager::addProperty() function to create a variant property (that function will always return 0 since it will not be clear what type the property should have).
See also
isPropertyTypeSupported()
References addProperty(), QtAbstractPropertyManager::addProperty(), QtProperty::addSubProperty(), attributes(), QtVariantProperty::attributeValue(), QtProperty::isEnabled(), QtProperty::isModified(), isPropertyTypeSupported(), QtVariantPropertyManagerPrivate::m_creatingProperty, QtVariantPropertyManagerPrivate::m_propertyType, QtProperty::propertyId(), QtProperty::propertyName(), QtVariantProperty::propertyType(), propertyType(), QtProperty::statusTip(), QtProperty::subProperties(), QtVariantProperty::value(), variantProperty(), and QtProperty::whatsThis().
Referenced by addProperty(), QtVariantPropertyManagerPrivate::createSubProperty(), and ObjectPropertyManager::setObjects().
void QtVariantPropertyManager::attributeChanged (QtProperty * property, const QString & attribute, const QVariant & value) [signal]
This signal is emitted whenever an attribute of a property created by this manager changes its value, passing a pointer to the property, the attribute and the new value as parameters.
See also
setAttribute()
Referenced by QtVariantPropertyManagerPrivate::slotConstraintChanged(), QtVariantPropertyManagerPrivate::slotDecimalsChanged(), QtVariantPropertyManagerPrivate::slotEnumIconsChanged(), QtVariantPropertyManagerPrivate::slotEnumNamesChanged(), QtVariantPropertyManagerPrivate::slotFlagNamesChanged(), QtVariantPropertyManagerPrivate::slotRangeChanged(), QtVariantPropertyManagerPrivate::slotRegExpChanged(), and QtVariantPropertyManagerPrivate::slotSingleStepChanged().
QStringList QtVariantPropertyManager::attributes (int propertyType) const [virtual]
Returns a list of the given propertyType 's attributes.
See also
attributeValue(), attributeType()
References QtVariantPropertyManagerPrivate::m_typeToAttributeToAttributeType.
Referenced by addProperty(), attributeType(), and attributeValue().
int QtVariantPropertyManager::attributeType (int propertyType, const QString & attribute) const [virtual]
Returns the type of the specified attribute of the given propertyType.
If the given propertyType is not supported by this manager, or if the given propertyType does not possess the specified attribute, this function returns QVariant::Invalid.
See also
attributes(), valueType()
References attributes(), and QtVariantPropertyManagerPrivate::m_typeToAttributeToAttributeType.
Referenced by setAttribute().
QVariant QtVariantPropertyManager::attributeValue (const QtProperty * property, const QString & attribute) const [virtual]
Returns the given property's value for the specified attribute
If the given property was not created by this manager, or if the specified attribute does not exist, this function returns an invalid variant.
See also
attributes(), attributeType(), setAttribute()
References attributes(), QtVariantPropertyManagerPrivate::m_constraintAttribute, QtVariantPropertyManagerPrivate::m_decimalsAttribute, QtVariantPropertyManagerPrivate::m_enumIconsAttribute, QtVariantPropertyManagerPrivate::m_enumNamesAttribute, QtVariantPropertyManagerPrivate::m_flagNamesAttribute, QtVariantPropertyManagerPrivate::m_maximumAttribute, QtVariantPropertyManagerPrivate::m_minimumAttribute, QtVariantPropertyManagerPrivate::m_regExpAttribute, QtVariantPropertyManagerPrivate::m_singleStepAttribute, QtVariantPropertyManagerPrivate::m_typeToAttributeToAttributeType, QtProperty::propertyManager(), and propertyType().
Referenced by QtVariantProperty::attributeValue(), and setAttribute().
QtProperty * QtVariantPropertyManager::createProperty () [protected], [virtual]
Reimplemented from QtAbstractPropertyManager .
References QtVariantPropertyManagerPrivate::m_creatingProperty, QtVariantPropertyManagerPrivate::m_propertyToType, and QtVariantPropertyManagerPrivate::m_propertyType.
int QtVariantPropertyManager::enumTypeId () [static]
Returns the type id for an enum property.
Note that the property's value type can be retrieved using the valueType() function (which is QVariant::Int for the enum property type).
See also
propertyType(), valueType()
Referenced by QtVariantPropertyManagerPrivate::internalPropertyToType(), QtVariantEditorFactory::QtVariantEditorFactory(), and QtVariantPropertyManager().
int QtVariantPropertyManager::flagTypeId () [static]
Returns the type id for a flag property.
Note that the property's value type can be retrieved using the valueType() function (which is QVariant::Int for the flag property type).
See also
propertyType(), valueType()
Referenced by QtVariantPropertyManager().
int QtVariantPropertyManager::groupTypeId () [static]
Returns the type id for a group property.
Note that the property's value type can be retrieved using the valueType() function (which is QVariant::Invalid for the group property type, since it doesn't provide any value).
See also
propertyType(), valueType()
Referenced by hasValue(), QtVariantPropertyManager(), and ObjectPropertyManager::setObjects().
bool QtVariantPropertyManager::hasValue (const QtProperty * property) const [protected], [virtual]
Reimplemented from QtAbstractPropertyManager .
References groupTypeId(), and propertyType().
int QtVariantPropertyManager::iconMapTypeId () [static]
Returns the type id for a icon map attribute.
Note that the property's attribute type can be retrieved using the attributeType() function.
See also
attributeType(), QtEnumPropertyManager::enumIcons()
Referenced by QtVariantPropertyManager().
void QtVariantPropertyManager::initializeProperty (QtProperty * property) [protected], [virtual]
Implements QtAbstractPropertyManager .
References QtAbstractPropertyManager::addProperty(), QtVariantPropertyManagerPrivate::createSubProperty(), QtVariantPropertyManagerPrivate::m_creatingSubProperties, QtVariantPropertyManagerPrivate::m_internalToProperty, QtVariantPropertyManagerPrivate::m_propertyType, QtVariantPropertyManagerPrivate::m_typeToPropertyManager, QtProperty::subProperties(), and variantProperty().
bool QtVariantPropertyManager::isPropertyTypeSupported (int propertyType) const [virtual]
Returns true if the given propertyType is supported by this variant manager; otherwise false.
See also
propertyType()
References QtVariantPropertyManagerPrivate::m_typeToValueType.
Referenced by addProperty().
int QtVariantPropertyManager::propertyType (const QtProperty * property) const
Returns the given property's type.
See also
valueType()
References QtVariantPropertyManagerPrivate::m_propertyToType.
Referenced by addProperty(), attributeValue(), QtVariantEditorFactory::createEditor(), hasValue(), QtVariantProperty::propertyType(), setAttribute(), and valueType().
void QtVariantPropertyManager::setAttribute (QtProperty * property, const QString & attribute, const QVariant & value) [virtual], [slot]
Sets the value of the specified attribute of the given property, to value.
The new value's type must be of the type returned by attributeType(), or of a type that can be converted to attributeType() using the QVariant::canConvert() function, otherwise this function does nothing.
See also
attributeValue(), QtVariantProperty::setAttribute(), attributeChanged()
References attributeType(), attributeValue(), QtVariantPropertyManagerPrivate::m_constraintAttribute, QtVariantPropertyManagerPrivate::m_decimalsAttribute, QtVariantPropertyManagerPrivate::m_enumIconsAttribute, QtVariantPropertyManagerPrivate::m_enumNamesAttribute, QtVariantPropertyManagerPrivate::m_flagNamesAttribute, QtVariantPropertyManagerPrivate::m_maximumAttribute, QtVariantPropertyManagerPrivate::m_minimumAttribute, QtVariantPropertyManagerPrivate::m_regExpAttribute, QtVariantPropertyManagerPrivate::m_singleStepAttribute, QtProperty::propertyManager(), and propertyType().
Referenced by QtVariantProperty::setAttribute().
void QtVariantPropertyManager::setProperties (QSet< QtProperty * > properties)
Set properties used by this manager.
See also
properties(), addProperty()
References QtAbstractPropertyManager::clear(), and QtProperty::isSubProperty().
void QtVariantPropertyManager::setValue (QtProperty * property, const QVariant & value) [virtual], [slot]
Sets the value of the given property to value.
The specified value must be of a type returned by valueType(), or of type that can be converted to valueType() using the QVariant::canConvert() function, otherwise this function does nothing.
See also
value(), QtVariantProperty::setValue(), valueChanged()
References QtProperty::propertyManager(), and valueType().
Referenced by QtVariantProperty::setValue().
void QtVariantPropertyManager::uninitializeProperty (QtProperty * property) [protected], [virtual]
Reimplemented from QtAbstractPropertyManager .
References QtVariantPropertyManagerPrivate::m_destroyingSubProperties, QtVariantPropertyManagerPrivate::m_internalToProperty, and QtVariantPropertyManagerPrivate::m_propertyToType.
QVariant QtVariantPropertyManager::value (const QtProperty * property) const [virtual]
Returns the given property's value.
If the given property is not managed by this manager, this function returns an invalid variant.
See also
setValue()
References QtProperty::propertyManager().
Referenced by QtVariantProperty::value().
void QtVariantPropertyManager::valueChanged (QtProperty * property, const QVariant & value) [signal]
This signal is emitted whenever a property created by this manager changes its value, passing a pointer to the property and the new value as parameters.
See also
setValue()
Referenced by QtVariantPropertyManager(), and QtVariantPropertyManagerPrivate::valueChanged().
QIcon QtVariantPropertyManager::valueIcon (const QtProperty * property) const [protected], [virtual]
Reimplemented from QtAbstractPropertyManager .
References QtProperty::valueIcon().
QString QtVariantPropertyManager::valueText (const QtProperty * property) const [protected], [virtual]
Reimplemented from QtAbstractPropertyManager .
References QtProperty::valueText().
int QtVariantPropertyManager::valueType (const QtProperty * property) const
Returns the given property's value type.
See also
propertyType()
References propertyType().
Referenced by setValue(), and QtVariantProperty::valueType().
int QtVariantPropertyManager::valueType (int propertyType) const [virtual]
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Returns the value type associated with the given propertyType.
References QtVariantPropertyManagerPrivate::m_typeToValueType.
QtVariantProperty * QtVariantPropertyManager::variantProperty (const QtProperty * property) const
Returns the given property converted into a QtVariantProperty.
If the property was not created by this variant manager, the function returns 0.
See also
createProperty()
References QtVariantPropertyManagerPrivate::m_propertyToType.
Referenced by addProperty(), and initializeProperty().
The documentation for this class was generated from the following files:
qtvariantproperty.h
qtvariantproperty.cpp