QtRectFPropertyManager Class Reference
The QtRectFPropertyManager provides and manages QRectF properties.
#include <qtpropertymanager.h>
Public Slots
void setValue (QtProperty *property, const QRectF &val)
void setConstraint (QtProperty *property, const QRectF &constraint)
void setDecimals (QtProperty *property, int prec)
Signals
void valueChanged (QtProperty *property, const QRectF &val)
void constraintChanged (QtProperty *property, const QRectF &constraint)
void decimalsChanged (QtProperty *property, int prec)
Public Member Functions
QtRectFPropertyManager (QObject *parent=0)
~QtRectFPropertyManager ()
QtDoublePropertyManager * subDoublePropertyManager () const
QRectF value (const QtProperty *property) const
QRectF constraint (const QtProperty *property) const
int decimals (const QtProperty *property) const
Protected Member Functions
QString valueText (const QtProperty *property) const
virtual void initializeProperty (QtProperty *property)
virtual void uninitializeProperty (QtProperty *property)
Detailed Description
A rectangle property has nested x, y, width and height subproperties. The top-level property's value can be retrieved using the value() function, and set using the setValue() slot.
The subproperties are created by a QtDoublePropertyManager object. This manager can be retrieved using the subDoublePropertyManager() function. In order to provide editing widgets for the subproperties in a property browser widget, this manager must be associated with an editor factory.
A rectangle property also has a constraint rectangle which can be retrieved using the constraint() function, and set using the setConstraint() slot.
In addition, QtRectFPropertyManager provides the valueChanged() signal which is emitted whenever a property created by this manager changes, and the constraintChanged() signal which is emitted whenever such a property changes its constraint rectangle.
See also
QtAbstractPropertyManager, QtDoublePropertyManager, QtRectPropertyManager
Constructor & Destructor Documentation
QtRectFPropertyManager::QtRectFPropertyManager (QObject * parent = 0)
Creates a manager with the given parent.
References QtRectFPropertyManagerPrivate::m_doublePropertyManager, QtAbstractPropertyManager::propertyDestroyed(), and valueChanged().
QtRectFPropertyManager::~QtRectFPropertyManager ()
Destroys this manager, and all the properties it has created.
References QtAbstractPropertyManager::clear().
Member Function Documentation
QRectF QtRectFPropertyManager::constraint (const QtProperty * property) const
Returns the given property's constraining rectangle. If returned value is null QRectF it means there is no constraint applied.
See also
value(), setConstraint()
References QtRectFPropertyManagerPrivate::Data::constraint, and QtRectFPropertyManagerPrivate::m_values.
void QtRectFPropertyManager::constraintChanged (QtProperty * property, const QRectF & constraint) [signal]
This signal is emitted whenever property changes its constraint rectangle, passing a pointer to the property and the new constraint rectangle as parameters.
See also
setConstraint()
Referenced by setConstraint().
int QtRectFPropertyManager::decimals (const QtProperty * property) const
Returns the given property's precision, in decimals.
See also
setDecimals()
References QtRectFPropertyManagerPrivate::Data::decimals, and QtRectFPropertyManagerPrivate::m_values.
Referenced by initializeProperty().
void QtRectFPropertyManager::decimalsChanged (QtProperty * property, int prec) [signal]
This signal is emitted whenever a property created by this manager changes its precision of value, passing a pointer to the property and the new prec value
See also
setDecimals()
Referenced by setDecimals().
void QtRectFPropertyManager::initializeProperty (QtProperty * property) [protected], [virtual]
Implements QtAbstractPropertyManager .
References QtAbstractPropertyManager::addProperty(), QtProperty::addSubProperty(), decimals(), QtRectFPropertyManagerPrivate::m_doublePropertyManager, QtRectFPropertyManagerPrivate::m_hToProperty, QtRectFPropertyManagerPrivate::m_propertyToH, QtRectFPropertyManagerPrivate::m_propertyToW, QtRectFPropertyManagerPrivate::m_propertyToX, QtRectFPropertyManagerPrivate::m_propertyToY, QtRectFPropertyManagerPrivate::m_values, QtRectFPropertyManagerPrivate::m_wToProperty, QtRectFPropertyManagerPrivate::m_xToProperty, QtRectFPropertyManagerPrivate::m_yToProperty, QtDoublePropertyManager::setDecimals(), QtDoublePropertyManager::setMinimum(), QtProperty::setPropertyName(), and QtDoublePropertyManager::setValue().
void QtRectFPropertyManager::setConstraint (QtProperty * property, const QRectF & constraint) [slot]
Sets the given property's constraining rectangle to constraint.
When setting the constraint, the current value is adjusted if necessary (ensuring that the current rectangle value is inside the constraint). In order to reset the constraint pass a null QRectF value.
See also
setValue(), constraint(), constraintChanged()
References QtRectFPropertyManagerPrivate::Data::constraint, constraintChanged(), QtRectFPropertyManagerPrivate::m_values, QtAbstractPropertyManager::propertyChanged(), QtRectFPropertyManagerPrivate::setConstraint(), QtRectFPropertyManagerPrivate::Data::val, and valueChanged().
void QtRectFPropertyManager::setDecimals (QtProperty * property, int prec) [slot]
Sets the precision of the given property to prec.
The valid decimal range is 0-13. The default is 2.
See also
decimals()
References QtRectFPropertyManagerPrivate::Data::decimals, decimalsChanged(), QtRectFPropertyManagerPrivate::m_doublePropertyManager, QtRectFPropertyManagerPrivate::m_propertyToH, QtRectFPropertyManagerPrivate::m_propertyToW, QtRectFPropertyManagerPrivate::m_propertyToX, QtRectFPropertyManagerPrivate::m_propertyToY, QtRectFPropertyManagerPrivate::m_values, and QtDoublePropertyManager::setDecimals().
void QtRectFPropertyManager::setValue (QtProperty * property, const QRectF & value) [slot]
Sets the value of the given property to value. Nested properties are updated automatically.
If the specified value is not inside the given property's constraining rectangle, the value is adjusted accordingly to fit within the constraint.
See also
value(), setConstraint(), valueChanged()
References QtRectFPropertyManagerPrivate::Data::constraint, QtRectFPropertyManagerPrivate::m_doublePropertyManager, QtRectFPropertyManagerPrivate::m_propertyToH, QtRectFPropertyManagerPrivate::m_propertyToW, QtRectFPropertyManagerPrivate::m_propertyToX, QtRectFPropertyManagerPrivate::m_propertyToY, QtRectFPropertyManagerPrivate::m_values, QtAbstractPropertyManager::propertyChanged(), QtDoublePropertyManager::setValue(), QtRectFPropertyManagerPrivate::Data::val, and valueChanged().
QtDoublePropertyManager * QtRectFPropertyManager::subDoublePropertyManager () const
Returns the manager that creates the nested x, y, width and height subproperties.
In order to provide editing widgets for the mentioned subproperties in a property browser widget, this manager must be associated with an editor factory.
See also
QtAbstractPropertyBrowser::setFactoryForManager()
References QtRectFPropertyManagerPrivate::m_doublePropertyManager.
Referenced by QtVariantPropertyManager::QtVariantPropertyManager().
void QtRectFPropertyManager::uninitializeProperty (QtProperty * property) [protected], [virtual]
Reimplemented from QtAbstractPropertyManager .
References QtRectFPropertyManagerPrivate::m_hToProperty, QtRectFPropertyManagerPrivate::m_propertyToH, QtRectFPropertyManagerPrivate::m_propertyToW, QtRectFPropertyManagerPrivate::m_propertyToX, QtRectFPropertyManagerPrivate::m_propertyToY, QtRectFPropertyManagerPrivate::m_values, QtRectFPropertyManagerPrivate::m_wToProperty, QtRectFPropertyManagerPrivate::m_xToProperty, and QtRectFPropertyManagerPrivate::m_yToProperty.
QRectF QtRectFPropertyManager::value (const QtProperty * property) const
Returns the given property's value.
If the given property is not managed by this manager, this function returns an invalid rectangle.
See also
setValue(), constraint()
References QtRectFPropertyManagerPrivate::m_values.
void QtRectFPropertyManager::valueChanged (QtProperty * property, const QRectF & value) [signal]
This signal is emitted whenever a property created by this manager changes its value, passing a pointer to the property and the new value as parameters.
See also
setValue()
Referenced by QtRectFPropertyManager(), setConstraint(), and setValue().
QString QtRectFPropertyManager::valueText (const QtProperty * property) const [protected], [virtual]
Reimplemented from QtAbstractPropertyManager .
References QtRectFPropertyManagerPrivate::m_values.
The documentation for this class was generated from the following files:
qtpropertymanager.h
qtpropertymanager.cpp