QtPointFPropertyManager Class Reference
The QtPointFPropertyManager provides and manages QPointF properties.
#include <qtpropertymanager.h>
Public Slots
void setValue (QtProperty *property, const QPointF &val)
void setDecimals (QtProperty *property, int prec)
Signals
void valueChanged (QtProperty *property, const QPointF &val)
void decimalsChanged (QtProperty *property, int prec)
Public Member Functions
QtPointFPropertyManager (QObject *parent=0)
~QtPointFPropertyManager ()
QtDoublePropertyManager * subDoublePropertyManager () const
QPointF value (const QtProperty *property) const
int decimals (const QtProperty *property) const
Protected Member Functions
QString valueText (const QtProperty *property) const
virtual void initializeProperty (QtProperty *property)
virtual void uninitializeProperty (QtProperty *property)
Detailed Description
A point property has nested x and y subproperties. The top-level property's value can be retrieved using the value() function, and set using the setValue() slot.
The subproperties are created by a QtDoublePropertyManager object. This manager can be retrieved using the subDoublePropertyManager() function. In order to provide editing widgets for the subproperties in a property browser widget, this manager must be associated with an editor factory.
In addition, QtPointFPropertyManager provides the valueChanged() signal which is emitted whenever a property created by this manager changes.
See also
QtAbstractPropertyManager, QtDoublePropertyManager, QtPointPropertyManager
Constructor & Destructor Documentation
QtPointFPropertyManager::QtPointFPropertyManager (QObject * parent = 0)
Creates a manager with the given parent.
References QtPointFPropertyManagerPrivate::m_doublePropertyManager, QtAbstractPropertyManager::propertyDestroyed(), and valueChanged().
QtPointFPropertyManager::~QtPointFPropertyManager ()
Destroys this manager, and all the properties it has created.
References QtAbstractPropertyManager::clear().
Member Function Documentation
int QtPointFPropertyManager::decimals (const QtProperty * property) const
Returns the given property's precision, in decimals.
See also
setDecimals()
References QtPointFPropertyManagerPrivate::Data::decimals, and QtPointFPropertyManagerPrivate::m_values.
Referenced by initializeProperty().
void QtPointFPropertyManager::decimalsChanged (QtProperty * property, int prec) [signal]
This signal is emitted whenever a property created by this manager changes its precision of value, passing a pointer to the property and the new prec value
See also
setDecimals()
Referenced by setDecimals().
void QtPointFPropertyManager::initializeProperty (QtProperty * property) [protected], [virtual]
Implements QtAbstractPropertyManager .
References QtAbstractPropertyManager::addProperty(), QtProperty::addSubProperty(), decimals(), QtPointFPropertyManagerPrivate::m_doublePropertyManager, QtPointFPropertyManagerPrivate::m_propertyToX, QtPointFPropertyManagerPrivate::m_propertyToY, QtPointFPropertyManagerPrivate::m_values, QtPointFPropertyManagerPrivate::m_xToProperty, QtPointFPropertyManagerPrivate::m_yToProperty, QtDoublePropertyManager::setDecimals(), QtProperty::setPropertyName(), and QtDoublePropertyManager::setValue().
void QtPointFPropertyManager::setDecimals (QtProperty * property, int prec) [slot]
Sets the precision of the given property to prec.
The valid decimal range is 0-13. The default is 2.
See also
decimals()
References QtPointFPropertyManagerPrivate::Data::decimals, decimalsChanged(), QtPointFPropertyManagerPrivate::m_doublePropertyManager, QtPointFPropertyManagerPrivate::m_propertyToX, QtPointFPropertyManagerPrivate::m_propertyToY, QtPointFPropertyManagerPrivate::m_values, and QtDoublePropertyManager::setDecimals().
void QtPointFPropertyManager::setValue (QtProperty * property, const QPointF & value) [slot]
Sets the value of the given property to value. Nested properties are updated automatically.
See also
value(), valueChanged()
References QtPointFPropertyManagerPrivate::m_doublePropertyManager, QtPointFPropertyManagerPrivate::m_propertyToX, QtPointFPropertyManagerPrivate::m_propertyToY, QtPointFPropertyManagerPrivate::m_values, QtAbstractPropertyManager::propertyChanged(), QtDoublePropertyManager::setValue(), and valueChanged().
QtDoublePropertyManager * QtPointFPropertyManager::subDoublePropertyManager () const
Returns the manager that creates the nested x and y subproperties.
In order to provide editing widgets for the subproperties in a property browser widget, this manager must be associated with an editor factory.
See also
QtAbstractPropertyBrowser::setFactoryForManager()
References QtPointFPropertyManagerPrivate::m_doublePropertyManager.
Referenced by QtVariantPropertyManager::QtVariantPropertyManager().
void QtPointFPropertyManager::uninitializeProperty (QtProperty * property) [protected], [virtual]
Reimplemented from QtAbstractPropertyManager .
References QtPointFPropertyManagerPrivate::m_propertyToX, QtPointFPropertyManagerPrivate::m_propertyToY, QtPointFPropertyManagerPrivate::m_values, QtPointFPropertyManagerPrivate::m_xToProperty, and QtPointFPropertyManagerPrivate::m_yToProperty.
QPointF QtPointFPropertyManager::value (const QtProperty * property) const
Returns the given property's value.
If the given property is not managed by this manager, this function returns a point with coordinates (0, 0).
See also
setValue()
References QtPointFPropertyManagerPrivate::m_values.
void QtPointFPropertyManager::valueChanged (QtProperty * property, const QPointF & value) [signal]
This signal is emitted whenever a property created by this manager changes its value, passing a pointer to the property and the new value as parameters.
See also
setValue()
Referenced by QtPointFPropertyManager(), and setValue().
QString QtPointFPropertyManager::valueText (const QtProperty * property) const [protected], [virtual]
Reimplemented from QtAbstractPropertyManager .
References QtPointFPropertyManagerPrivate::m_values.
The documentation for this class was generated from the following files:
qtpropertymanager.h
qtpropertymanager.cpp