ExtScalePlotSceneWidget Class Reference
#include <extscaleplotscenewidget.h>
Public Member Functions
 ExtScalePlotSceneWidget (QWidget *parent=0, bool multiScale=false)
 SceneCurve * addCurve (const QString &name, ScaleItem *xScale=NULL, ScaleItem *yScale=NULL, bool addExtScale=false)
 ScaleItem * addAxis (ScaleItem::Orientation o, const QString &axisName)
void addExternalScale (ScaleItem *axis, SceneCurve *curve)
 PlotSceneWidget * getPlot () const
void setMultiscale (bool multiscale)
bool multiscale () const
 ScaleItem * getAxis (ScaleItem::Id)
void removeCurve (const QString &name)
void clear ()
 SceneCurve * addCurve (SceneCurve *curve, bool addExtScale)
Add a pre configured curve to the plot.
void removeAdditionalExternalScales ()
Constructor & Destructor Documentation
ExtScalePlotSceneWidget()
ExtScalePlotSceneWidget::ExtScalePlotSceneWidget (QWidget * parent = 0, bool multiScale = false) [explicit]
References ScaleItem::Horizontal, ExternalScaleWidget::installScaleLabelInterface(), ExternalScaleWidget::setAlignment(), ExternalScaleWidget::setLabelRotation(), ExternalScaleWidget::setMargin(), ExternalScaleWidget::setOriginPercentage(), ExternalScaleWidget::setTickStepLen(), and ScaleItem::xBottom.
Member Function Documentation
addAxis()
 ScaleItem * ExtScalePlotSceneWidget::addAxis (ScaleItem::Orientation o, const QString & axisName)
addCurve() [1/2]
 SceneCurve * ExtScalePlotSceneWidget::addCurve (const QString & name, ScaleItem * xScale = NULL, ScaleItem * yScale = NULL, bool addExtScale = false)
References addExternalScale(), SceneCurve::installCurveChangeListener(), KCAMEL, KDARKBLUE, KDARKCYAN, KDARKPINK, KDARKWATER, KGRAY, KVERYDARKVIOLET, KYELLOW, perr, qstoc, and LinePainter::setLineColor().
addCurve() [2/2]
 SceneCurve * ExtScalePlotSceneWidget::addCurve (SceneCurve * curve, bool addExtScale)
Parameters
curve a previously configured curve to be added to the plot
References addExternalScale(), SceneCurve::getYAxis(), and SceneCurve::name().
addExternalScale()
void ExtScalePlotSceneWidget::addExternalScale (ScaleItem * axis, SceneCurve * curve)
References SceneCurve::curveItem(), ScaleItem::installAxisChangeListener(), CurveItem::itemPainter(), SceneCurve::name(), ItemPainterInterface::pen(), ExternalScaleWidget::setAlignment(), ExternalScaleWidget::setMargin(), ExternalScaleWidget::setOriginPercentage(), ExternalScaleWidget::setPen(), ExternalScaleWidget::setTickDrawingInverted(), ExternalScaleWidget::setTickStepLen(), ScaleItem::tickStepLen, and ScaleItem::Vertical.
Referenced by addCurve().
clear()
void ExtScalePlotSceneWidget::clear ()
References SceneCurve::name(), removeAdditionalExternalScales(), removeCurve(), and ScaleItem::Vertical.
getAxis()
 ScaleItem * ExtScalePlotSceneWidget::getAxis (ScaleItem::Id id)
getPlot()
 PlotSceneWidget * ExtScalePlotSceneWidget::getPlot () const
multiscale()
bool ExtScalePlotSceneWidget::multiscale () const
Referenced by setMultiscale().
removeAdditionalExternalScales()
void ExtScalePlotSceneWidget::removeAdditionalExternalScales ()
Referenced by clear().
removeCurve()
void ExtScalePlotSceneWidget::removeCurve (const QString & name)
Referenced by clear().
setMultiscale()
void ExtScalePlotSceneWidget::setMultiscale (bool multiscale)
References multiscale().
The documentation for this class was generated from the following files:
 extscaleplotscenewidget.h
 extscaleplotscenewidget.cpp
 extscaleplotscenewidget.h.cpp