QtFlagPropertyManager Class Reference
The QtFlagPropertyManager provides and manages flag properties.
#include <qtpropertymanager.h>
Public Slots
void setValue (QtProperty *property, int val)
void setFlagNames (QtProperty *property, const QStringList &names)
Signals
void valueChanged (QtProperty *property, int val)
void flagNamesChanged (QtProperty *property, const QStringList &names)
Public Member Functions
QtFlagPropertyManager (QObject *parent=0)
~QtFlagPropertyManager ()
QtBoolPropertyManager * subBoolPropertyManager () const
int value (const QtProperty *property) const
QStringList flagNames (const QtProperty *property) const
Protected Member Functions
QString valueText (const QtProperty *property) const
virtual void initializeProperty (QtProperty *property)
virtual void uninitializeProperty (QtProperty *property)
Detailed Description
Each flag property has an associated list of flag names which can be retrieved using the flagNames() function, and set using the corresponding setFlagNames() function.
The flag manager provides properties with nested boolean subproperties representing each flag, i.e. a flag property's value is the binary combination of the subproperties' values. A property's value can be retrieved and set using the value() and setValue() slots respectively. The combination of flags is represented by single int value - that's why it's possible to store up to 32 independent flags in one flag property.
The subproperties are created by a QtBoolPropertyManager object. This manager can be retrieved using the subBoolPropertyManager() function. In order to provide editing widgets for the subproperties in a property browser widget, this manager must be associated with an editor factory.
In addition, QtFlagPropertyManager provides the valueChanged() signal which is emitted whenever a property created by this manager changes, and the flagNamesChanged() signal which is emitted whenever the list of flag names is altered.
See also
QtAbstractPropertyManager, QtBoolPropertyManager
Constructor & Destructor Documentation
QtFlagPropertyManager::QtFlagPropertyManager (QObject * parent = 0)
Creates a manager with the given parent.
References QtFlagPropertyManagerPrivate::m_boolPropertyManager, QtAbstractPropertyManager::propertyDestroyed(), and valueChanged().
QtFlagPropertyManager::~QtFlagPropertyManager ()
Destroys this manager, and all the properties it has created.
References QtAbstractPropertyManager::clear().
Member Function Documentation
QStringList QtFlagPropertyManager::flagNames (const QtProperty * property) const
Returns the given property's list of flag names.
See also
value(), setFlagNames()
References QtFlagPropertyManagerPrivate::Data::flagNames, and QtFlagPropertyManagerPrivate::m_values.
Referenced by setFlagNames().
void QtFlagPropertyManager::flagNamesChanged (QtProperty * property, const QStringList & names) [signal]
This signal is emitted whenever a property created by this manager changes its flag names, passing a pointer to the property and the new names as parameters.
See also
setFlagNames()
Referenced by setFlagNames().
void QtFlagPropertyManager::initializeProperty (QtProperty * property) [protected], [virtual]
Implements QtAbstractPropertyManager .
References QtFlagPropertyManagerPrivate::m_propertyToFlags, and QtFlagPropertyManagerPrivate::m_values.
void QtFlagPropertyManager::setFlagNames (QtProperty * property, const QStringList & flagNames) [slot]
Sets the given property's list of flag names to flagNames. The property's current value is reset to 0 indicating the first item of the list.
See also
flagNames(), flagNamesChanged()
References QtAbstractPropertyManager::addProperty(), flagNames(), QtFlagPropertyManagerPrivate::Data::flagNames, flagNamesChanged(), QtFlagPropertyManagerPrivate::m_boolPropertyManager, QtFlagPropertyManagerPrivate::m_flagToProperty, QtFlagPropertyManagerPrivate::m_propertyToFlags, QtFlagPropertyManagerPrivate::m_values, QtAbstractPropertyManager::propertyChanged(), QtProperty::setPropertyName(), QtFlagPropertyManagerPrivate::Data::val, and valueChanged().
void QtFlagPropertyManager::setValue (QtProperty * property, int value) [slot]
Sets the value of the given property to value. Nested properties are updated automatically.
The specified value must be less than the binary combination of the property's flagNames() list size (i.e. less than 2 n, where n is the size of the list) and larger than (or equal to) 0.
See also
value(), valueChanged()
References QtFlagPropertyManagerPrivate::Data::flagNames, QtFlagPropertyManagerPrivate::m_boolPropertyManager, QtFlagPropertyManagerPrivate::m_propertyToFlags, QtFlagPropertyManagerPrivate::m_values, QtAbstractPropertyManager::propertyChanged(), QtBoolPropertyManager::setValue(), QtFlagPropertyManagerPrivate::Data::val, and valueChanged().
QtBoolPropertyManager * QtFlagPropertyManager::subBoolPropertyManager () const
Returns the manager that produces the nested boolean subproperties representing each flag.
In order to provide editing widgets for the subproperties in a property browser widget, this manager must be associated with an editor factory.
See also
QtAbstractPropertyBrowser::setFactoryForManager()
References QtFlagPropertyManagerPrivate::m_boolPropertyManager.
Referenced by QtVariantPropertyManager::QtVariantPropertyManager().
void QtFlagPropertyManager::uninitializeProperty (QtProperty * property) [protected], [virtual]
Reimplemented from QtAbstractPropertyManager .
References QtFlagPropertyManagerPrivate::m_flagToProperty, QtFlagPropertyManagerPrivate::m_propertyToFlags, and QtFlagPropertyManagerPrivate::m_values.
int QtFlagPropertyManager::value (const QtProperty * property) const
Returns the given property's value.
If the given property is not managed by this manager, this function returns 0.
See also
flagNames(), setValue()
References QtFlagPropertyManagerPrivate::m_values.
void QtFlagPropertyManager::valueChanged (QtProperty * property, int value) [signal]
This signal is emitted whenever a property created by this manager changes its value, passing a pointer to the property and the new value as parameters.
See also
setValue()
Referenced by QtFlagPropertyManager(), setFlagNames(), and setValue().
QString QtFlagPropertyManager::valueText (const QtProperty * property) const [protected], [virtual]
Reimplemented from QtAbstractPropertyManager .
References QtFlagPropertyManagerPrivate::Data::flagNames, QtFlagPropertyManagerPrivate::m_values, and QtFlagPropertyManagerPrivate::Data::val.
The documentation for this class was generated from the following files:
qtpropertymanager.h
qtpropertymanager.cpp