OptionsDialog Class Reference
#include <plotscenewidgetsaver.h>
Public Slots
void setDateTimeFormatEnabled (bool en)
Public Member Functions
 OptionsDialog (QWidget *parent, double xSample, double ySample)
QString xFormat () const
QString yFormat () const
bool dateTimeFormat () const
QString timestampToDateTimeString (double timestamp, const QString &format)
Public Attributes
double xSample
double ySample
Protected Slots
void updateXExample (const QString &format)
void updateYExample (const QString &format)
void setDateTimeFormat (bool timeScale)
Constructor & Destructor Documentation
OptionsDialog()
OptionsDialog::OptionsDialog (QWidget * parent, double xSample, double ySample)
References perr, qstoc, setDateTimeFormat(), updateXExample(), updateYExample(), xSample, and ySample.
Member Function Documentation
dateTimeFormat()
bool OptionsDialog::dateTimeFormat () const
Referenced by PlotSceneWidgetSaver::save().
setDateTimeFormat
void OptionsDialog::setDateTimeFormat (bool timeScale) [protected], [slot]
Referenced by OptionsDialog().
setDateTimeFormatEnabled
void OptionsDialog::setDateTimeFormatEnabled (bool en) [slot]
timestampToDateTimeString()
QString OptionsDialog::timestampToDateTimeString (double timestamp, const QString & format)
References qstoc.
Referenced by PlotSceneWidgetSaver::save(), and updateXExample().
updateXExample
void OptionsDialog::updateXExample (const QString & format) [protected], [slot]
References qstoc, timestampToDateTimeString(), and xSample.
Referenced by OptionsDialog().
updateYExample
void OptionsDialog::updateYExample (const QString & format) [protected], [slot]
References qstoc, and ySample.
Referenced by OptionsDialog().
xFormat()
QString OptionsDialog::xFormat () const
Referenced by PlotSceneWidgetSaver::save().
yFormat()
QString OptionsDialog::yFormat () const
Referenced by PlotSceneWidgetSaver::save().
Member Data Documentation
xSample
double OptionsDialog::xSample
Referenced by OptionsDialog(), and updateXExample().
ySample
double OptionsDialog::ySample
Referenced by OptionsDialog(), and updateYExample().
The documentation for this class was generated from the following files:
 plotscenewidgetsaver.h
 plotscenewidgetsaver.cpp