QtLocalePropertyManager Class Reference
The QtLocalePropertyManager provides and manages QLocale properties.
#include <qtpropertymanager.h>
Public Slots
void setValue (QtProperty *property, const QLocale &val)
Signals
void valueChanged (QtProperty *property, const QLocale &val)
Public Member Functions
QtLocalePropertyManager (QObject *parent=0)
~QtLocalePropertyManager ()
QtEnumPropertyManager * subEnumPropertyManager () const
QLocale value (const QtProperty *property) const
Protected Member Functions
QString valueText (const QtProperty *property) const
virtual void initializeProperty (QtProperty *property)
virtual void uninitializeProperty (QtProperty *property)
Detailed Description
A locale property has nested language and country subproperties. The top-level property's value can be retrieved using the value() function, and set using the setValue() slot.
The subproperties are created by QtEnumPropertyManager object. These submanager can be retrieved using the subEnumPropertyManager() function. In order to provide editing widgets for the subproperties in a property browser widget, this manager must be associated with editor factory.
In addition, QtLocalePropertyManager provides the valueChanged() signal which is emitted whenever a property created by this manager changes.
See also
QtAbstractPropertyManager, QtEnumPropertyManager
Constructor & Destructor Documentation
QtLocalePropertyManager::QtLocalePropertyManager (QObject * parent = 0)
Creates a manager with the given parent.
References QtLocalePropertyManagerPrivate::m_enumPropertyManager, QtAbstractPropertyManager::propertyDestroyed(), and valueChanged().
QtLocalePropertyManager::~QtLocalePropertyManager ()
Destroys this manager, and all the properties it has created.
References QtAbstractPropertyManager::clear().
Member Function Documentation
void QtLocalePropertyManager::initializeProperty (QtProperty * property) [protected], [virtual]
Implements QtAbstractPropertyManager .
References QtAbstractPropertyManager::addProperty(), QtProperty::addSubProperty(), QtLocalePropertyManagerPrivate::m_countryToProperty, QtLocalePropertyManagerPrivate::m_enumPropertyManager, QtLocalePropertyManagerPrivate::m_languageToProperty, QtLocalePropertyManagerPrivate::m_propertyToCountry, QtLocalePropertyManagerPrivate::m_propertyToLanguage, QtLocalePropertyManagerPrivate::m_values, QtEnumPropertyManager::setEnumNames(), QtProperty::setPropertyName(), and QtEnumPropertyManager::setValue().
void QtLocalePropertyManager::setValue (QtProperty * property, const QLocale & value) [slot]
Sets the value of the given property to value. Nested properties are updated automatically.
See also
value(), valueChanged()
References QtLocalePropertyManagerPrivate::m_enumPropertyManager, QtLocalePropertyManagerPrivate::m_propertyToCountry, QtLocalePropertyManagerPrivate::m_propertyToLanguage, QtLocalePropertyManagerPrivate::m_values, QtAbstractPropertyManager::propertyChanged(), QtEnumPropertyManager::setEnumNames(), QtEnumPropertyManager::setValue(), and valueChanged().
QtEnumPropertyManager * QtLocalePropertyManager::subEnumPropertyManager () const
Returns the manager that creates the nested language and country subproperties.
In order to provide editing widgets for the mentioned subproperties in a property browser widget, this manager must be associated with an editor factory.
See also
QtAbstractPropertyBrowser::setFactoryForManager()
References QtLocalePropertyManagerPrivate::m_enumPropertyManager.
Referenced by QtVariantPropertyManager::QtVariantPropertyManager().
void QtLocalePropertyManager::uninitializeProperty (QtProperty * property) [protected], [virtual]
Reimplemented from QtAbstractPropertyManager .
References QtLocalePropertyManagerPrivate::m_countryToProperty, QtLocalePropertyManagerPrivate::m_languageToProperty, QtLocalePropertyManagerPrivate::m_propertyToCountry, QtLocalePropertyManagerPrivate::m_propertyToLanguage, and QtLocalePropertyManagerPrivate::m_values.
QLocale QtLocalePropertyManager::value (const QtProperty * property) const
Returns the given property's value.
If the given property is not managed by this manager, this function returns the default locale.
See also
setValue()
References QtLocalePropertyManagerPrivate::m_values.
void QtLocalePropertyManager::valueChanged (QtProperty * property, const QLocale & value) [signal]
This signal is emitted whenever a property created by this manager changes its value, passing a pointer to the property and the new value as parameters.
See also
setValue()
Referenced by QtLocalePropertyManager(), and setValue().
QString QtLocalePropertyManager::valueText (const QtProperty * property) const [protected], [virtual]
Reimplemented from QtAbstractPropertyManager .
References QtLocalePropertyManagerPrivate::m_values.
The documentation for this class was generated from the following files:
qtpropertymanager.h
qtpropertymanager.cpp