QtEnumEditorFactoryPrivate Class Reference
Public Member Functions
void slotPropertyChanged (QtProperty *property, int value)
void slotEnumNamesChanged (QtProperty *property, const QStringList &)
void slotEnumIconsChanged (QtProperty *property, const QMap< int, QIcon > &)
void slotSetValue (int value)
Additional Inherited Members
Member Function Documentation
void QtEnumEditorFactoryPrivate::slotEnumIconsChanged (QtProperty * property, const QMap< int, QIcon > & enumIcons)
References QtEnumPropertyManager::enumNames(), and QtEnumPropertyManager::value().
void QtEnumEditorFactoryPrivate::slotEnumNamesChanged (QtProperty * property, const QStringList & enumNames)
References QtEnumPropertyManager::enumIcons(), and QtEnumPropertyManager::value().
void QtEnumEditorFactoryPrivate::slotPropertyChanged (QtProperty * property, int value)
void QtEnumEditorFactoryPrivate::slotSetValue (int value)
References QtEnumPropertyManager::setValue().
The documentation for this class was generated from the following file:
qteditorfactory.cpp