QtVariantEditorFactory Class Reference
The QtVariantEditorFactory class provides widgets for properties created by QtVariantPropertyManager objects.
#include <qtvariantproperty.h>
Public Member Functions
QtVariantEditorFactory (QObject *parent=0)
~QtVariantEditorFactory ()
Protected Member Functions
void connectPropertyManager (QtVariantPropertyManager *manager)
QWidget * createEditor (QtVariantPropertyManager *manager, QtProperty *property, QWidget *parent)
QWidget * createEditor (QtProperty *property, QWidget *parent)
void disconnectPropertyManager (QtVariantPropertyManager *manager)
Additional Inherited Members
Detailed Description
The variant factory provides the following widgets for the specified property types:
Property Type Widget int QSpinBox double QDoubleSpinBox bool QCheckBox QString QLineEdit QDate QDateEdit QTime QTimeEdit QDateTime QDateTimeEdit QKeySequence customized editor QChar customized editor enum QComboBox QCursor QComboBox
Note that QtVariantPropertyManager supports several additional property types for which the QtVariantEditorFactory class does not provide editing widgets, e.g. QPoint and QSize. To provide widgets for other types using the variant approach, derive from the QtVariantEditorFactory class.
See also
QtAbstractEditorFactory, QtVariantPropertyManager
Constructor & Destructor Documentation
QtVariantEditorFactory::QtVariantEditorFactory (QObject * parent = 0)
Creates a factory with the given parent.
References QtVariantPropertyManager::enumTypeId(), QtVariantEditorFactoryPrivate::m_charEditorFactory, QtVariantEditorFactoryPrivate::m_checkBoxFactory, QtVariantEditorFactoryPrivate::m_colorEditorFactory, QtVariantEditorFactoryPrivate::m_comboBoxFactory, QtVariantEditorFactoryPrivate::m_cursorEditorFactory, QtVariantEditorFactoryPrivate::m_dateEditFactory, QtVariantEditorFactoryPrivate::m_dateTimeEditFactory, QtVariantEditorFactoryPrivate::m_doubleSpinBoxFactory, QtVariantEditorFactoryPrivate::m_factoryToType, QtVariantEditorFactoryPrivate::m_fontEditorFactory, QtVariantEditorFactoryPrivate::m_keySequenceEditorFactory, QtVariantEditorFactoryPrivate::m_lineEditFactory, QtVariantEditorFactoryPrivate::m_spinBoxFactory, QtVariantEditorFactoryPrivate::m_timeEditFactory, and QtVariantEditorFactoryPrivate::m_typeToFactory.
QtVariantEditorFactory::~QtVariantEditorFactory ()
Destroys this factory, and all the widgets it has created.
Member Function Documentation
void QtVariantEditorFactory::connectPropertyManager (QtVariantPropertyManager * manager) [protected], [virtual]
Connects this factory to the given manager's signals. The PropertyManager type is a template argument class, and represents the chosen QtAbstractPropertyManager subclass.
This function is used internally by the addPropertyManager() function, and makes it possible to update an editing widget when the associated property's data changes. This is typically done in custom slots responding to the signals emitted by the property's manager, e.g. QtIntPropertyManager::valueChanged() and QtIntPropertyManager::rangeChanged().
See also
propertyManagers(), disconnectPropertyManager()
Implements QtAbstractEditorFactory< QtVariantPropertyManager > .
References QtAbstractEditorFactory< PropertyManager >::addPropertyManager(), QtVariantEditorFactoryPrivate::m_charEditorFactory, QtVariantEditorFactoryPrivate::m_checkBoxFactory, QtVariantEditorFactoryPrivate::m_colorEditorFactory, QtVariantEditorFactoryPrivate::m_comboBoxFactory, QtVariantEditorFactoryPrivate::m_cursorEditorFactory, QtVariantEditorFactoryPrivate::m_dateEditFactory, QtVariantEditorFactoryPrivate::m_dateTimeEditFactory, QtVariantEditorFactoryPrivate::m_doubleSpinBoxFactory, QtVariantEditorFactoryPrivate::m_fontEditorFactory, QtVariantEditorFactoryPrivate::m_keySequenceEditorFactory, QtVariantEditorFactoryPrivate::m_lineEditFactory, QtVariantEditorFactoryPrivate::m_spinBoxFactory, QtVariantEditorFactoryPrivate::m_timeEditFactory, QtFontPropertyManager::subBoolPropertyManager(), QtSizePolicyPropertyManager::subEnumPropertyManager(), QtFontPropertyManager::subEnumPropertyManager(), QtSizePolicyPropertyManager::subIntPropertyManager(), QtFontPropertyManager::subIntPropertyManager(), and QtColorPropertyManager::subIntPropertyManager().
QWidget * QtVariantEditorFactory::createEditor (QtVariantPropertyManager * manager, QtProperty * property, QWidget * parent) [protected], [virtual]
Creates an editing widget with the given parent for the specified property created by the given manager. The PropertyManager type is a template argument class, and represents the chosen QtAbstractPropertyManager subclass.
This function must be implemented in derived classes: It is recommended to store a pointer to the widget and map it to the given property, since the widget must be updated whenever the associated property's data changes. This is typically done in custom slots responding to the signals emitted by the property's manager, e.g. QtIntPropertyManager::valueChanged() and QtIntPropertyManager::rangeChanged().
See also
connectPropertyManager()
Implements QtAbstractEditorFactory< QtVariantPropertyManager > .
References QtAbstractEditorFactoryBase::createEditor(), QtVariantEditorFactoryPrivate::m_typeToFactory, QtVariantPropertyManager::propertyType(), and wrappedProperty().
QWidget * QtVariantEditorFactory::createEditor (QtProperty * property, QWidget * parent) [protected], [virtual]
Creates an editing widget (with the given parent) for the given property.
This function is reimplemented in QtAbstractEditorFactory template class which also provides a pure virtual convenience overload of this function enabling access to the property's manager.
See also
QtAbstractEditorFactory::createEditor()
Implements QtAbstractEditorFactoryBase .
References QtAbstractEditorFactory< PropertyManager >::createEditor().
void QtVariantEditorFactory::disconnectPropertyManager (QtVariantPropertyManager * manager) [protected], [virtual]
Disconnects this factory from the given manager's signals. The PropertyManager type is a template argument class, and represents the chosen QtAbstractPropertyManager subclass.
This function is used internally by the removePropertyManager() function.
See also
propertyManagers(), connectPropertyManager()
Implements QtAbstractEditorFactory< QtVariantPropertyManager > .
References QtVariantEditorFactoryPrivate::m_charEditorFactory, QtVariantEditorFactoryPrivate::m_checkBoxFactory, QtVariantEditorFactoryPrivate::m_colorEditorFactory, QtVariantEditorFactoryPrivate::m_comboBoxFactory, QtVariantEditorFactoryPrivate::m_cursorEditorFactory, QtVariantEditorFactoryPrivate::m_dateEditFactory, QtVariantEditorFactoryPrivate::m_dateTimeEditFactory, QtVariantEditorFactoryPrivate::m_doubleSpinBoxFactory, QtVariantEditorFactoryPrivate::m_fontEditorFactory, QtVariantEditorFactoryPrivate::m_keySequenceEditorFactory, QtVariantEditorFactoryPrivate::m_lineEditFactory, QtVariantEditorFactoryPrivate::m_spinBoxFactory, QtVariantEditorFactoryPrivate::m_timeEditFactory, QtAbstractEditorFactory< PropertyManager >::removePropertyManager(), QtFontPropertyManager::subBoolPropertyManager(), QtSizePolicyPropertyManager::subEnumPropertyManager(), QtFontPropertyManager::subEnumPropertyManager(), QtSizePolicyPropertyManager::subIntPropertyManager(), QtFontPropertyManager::subIntPropertyManager(), and QtColorPropertyManager::subIntPropertyManager().
The documentation for this class was generated from the following files:
qtvariantproperty.h
qtvariantproperty.cpp