QtIntPropertyManager Class Reference
The QtIntPropertyManager provides and manages int properties.
#include <qtpropertymanager.h>
Public Slots
void setValue (QtProperty *property, int val)
void setMinimum (QtProperty *property, int minVal)
void setMaximum (QtProperty *property, int maxVal)
void setRange (QtProperty *property, int minVal, int maxVal)
void setSingleStep (QtProperty *property, int step)
Signals
void valueChanged (QtProperty *property, int val)
void rangeChanged (QtProperty *property, int minVal, int maxVal)
void singleStepChanged (QtProperty *property, int step)
Public Member Functions
QtIntPropertyManager (QObject *parent=0)
~QtIntPropertyManager ()
int value (const QtProperty *property) const
int minimum (const QtProperty *property) const
int maximum (const QtProperty *property) const
int singleStep (const QtProperty *property) const
Protected Member Functions
QString valueText (const QtProperty *property) const
virtual void initializeProperty (QtProperty *property)
virtual void uninitializeProperty (QtProperty *property)
Detailed Description
An int property has a current value, and a range specifying the valid values. The range is defined by a minimum and a maximum value.
The property's value and range can be retrieved using the value(), minimum() and maximum() functions, and can be set using the setValue(), setMinimum() and setMaximum() slots. Alternatively, the range can be defined in one go using the setRange() slot.
In addition, QtIntPropertyManager provides the valueChanged() signal which is emitted whenever a property created by this manager changes, and the rangeChanged() signal which is emitted whenever such a property changes its range of valid values.
See also
QtAbstractPropertyManager, QtSpinBoxFactory, QtSliderFactory, QtScrollBarFactory
Constructor & Destructor Documentation
QtIntPropertyManager::QtIntPropertyManager (QObject * parent = 0)
Creates a manager with the given parent.
QtIntPropertyManager::~QtIntPropertyManager ()
Destroys this manager, and all the properties it has created.
References QtAbstractPropertyManager::clear().
Member Function Documentation
void QtIntPropertyManager::initializeProperty (QtProperty * property) [protected], [virtual]
Implements QtAbstractPropertyManager .
References QtIntPropertyManagerPrivate::m_values.
int QtIntPropertyManager::maximum (const QtProperty * property) const
Returns the given property's maximum value.
See also
setMaximum(), minimum(), setRange()
References QtIntPropertyManagerPrivate::m_values.
Referenced by QtSpinBoxFactory::createEditor(), QtSliderFactory::createEditor(), and QtScrollBarFactory::createEditor().
int QtIntPropertyManager::minimum (const QtProperty * property) const
Returns the given property's minimum value.
See also
setMinimum(), maximum(), setRange()
References QtIntPropertyManagerPrivate::m_values.
Referenced by QtSpinBoxFactory::createEditor(), QtSliderFactory::createEditor(), and QtScrollBarFactory::createEditor().
void QtIntPropertyManager::rangeChanged (QtProperty * property, int minimum, int maximum) [signal]
This signal is emitted whenever a property created by this manager changes its range of valid values, passing a pointer to the property and the new minimum and maximum values.
See also
setRange()
Referenced by setMaximum(), setMinimum(), and setRange().
void QtIntPropertyManager::setMaximum (QtProperty * property, int maxVal) [slot]
Sets the maximum value for the given property to maxVal.
When setting maximum value, the minimum and current values are adjusted if necessary (ensuring that the range remains valid and that the current value is within the range).
See also
maximum(), setRange(), rangeChanged()
References QtAbstractPropertyManager::propertyChanged(), rangeChanged(), and valueChanged().
void QtIntPropertyManager::setMinimum (QtProperty * property, int minVal) [slot]
Sets the minimum value for the given property to minVal.
When setting the minimum value, the maximum and current values are adjusted if necessary (ensuring that the range remains valid and that the current value is within the range).
See also
minimum(), setRange(), rangeChanged()
References QtAbstractPropertyManager::propertyChanged(), rangeChanged(), and valueChanged().
Referenced by QtSizePropertyManager::initializeProperty(), QtRectPropertyManager::initializeProperty(), and QtFontPropertyManager::initializeProperty().
void QtIntPropertyManager::setRange (QtProperty * property, int minimum, int maximum) [slot]
Sets the range of valid values.
This is a convenience function defining the range of valid values in one go; setting the minimum and maximum values for the given property with a single function call.
When setting a new range, the current value is adjusted if necessary (ensuring that the value remains within range).
See also
setMinimum(), setMaximum(), rangeChanged()
References QtAbstractPropertyManager::propertyChanged(), rangeChanged(), and valueChanged().
Referenced by QtSizePolicyPropertyManager::initializeProperty(), and QtColorPropertyManager::initializeProperty().
void QtIntPropertyManager::setSingleStep (QtProperty * property, int step) [slot]
Sets the step value for the given property to step.
The step is typically used to increment or decrement a property value while pressing an arrow key.
See also
singleStep()
References QtIntPropertyManagerPrivate::m_values, QtIntPropertyManagerPrivate::Data::singleStep, and singleStepChanged().
void QtIntPropertyManager::setValue (QtProperty * property, int value) [slot]
Sets the value of the given property to value.
If the specified value is not valid according to the given property's range, the value is adjusted to the nearest valid value within the range.
See also
value(), setRange(), valueChanged()
References QtAbstractPropertyManager::propertyChanged(), and valueChanged().
Referenced by QtPointPropertyManager::initializeProperty(), QtSizePropertyManager::initializeProperty(), QtRectPropertyManager::initializeProperty(), QtSizePolicyPropertyManager::initializeProperty(), QtFontPropertyManager::initializeProperty(), QtColorPropertyManager::initializeProperty(), QtPointPropertyManager::setValue(), QtRectPropertyManager::setValue(), QtSizePolicyPropertyManager::setValue(), QtFontPropertyManager::setValue(), QtColorPropertyManager::setValue(), QtSpinBoxFactoryPrivate::slotSetValue(), QtSliderFactoryPrivate::slotSetValue(), and QtScrollBarFactoryPrivate::slotSetValue().
int QtIntPropertyManager::singleStep (const QtProperty * property) const
Returns the given property's step value.
The step is typically used to increment or decrement a property value while pressing an arrow key.
See also
setSingleStep()
References QtIntPropertyManagerPrivate::m_values, and QtIntPropertyManagerPrivate::Data::singleStep.
Referenced by QtSpinBoxFactory::createEditor(), QtSliderFactory::createEditor(), and QtScrollBarFactory::createEditor().
void QtIntPropertyManager::singleStepChanged (QtProperty * property, int step) [signal]
This signal is emitted whenever a property created by this manager changes its single step property, passing a pointer to the property and the new step value
See also
setSingleStep()
Referenced by setSingleStep().
void QtIntPropertyManager::uninitializeProperty (QtProperty * property) [protected], [virtual]
Reimplemented from QtAbstractPropertyManager .
References QtIntPropertyManagerPrivate::m_values.
int QtIntPropertyManager::value (const QtProperty * property) const
Returns the given property's value.
If the given property is not managed by this manager, this function returns 0.
See also
setValue()
References QtIntPropertyManagerPrivate::m_values.
Referenced by QtSpinBoxFactory::createEditor(), QtSliderFactory::createEditor(), QtScrollBarFactory::createEditor(), QtSpinBoxFactoryPrivate::slotRangeChanged(), QtSliderFactoryPrivate::slotRangeChanged(), and QtScrollBarFactoryPrivate::slotRangeChanged().
void QtIntPropertyManager::valueChanged (QtProperty * property, int value) [signal]
This signal is emitted whenever a property created by this manager changes its value, passing a pointer to the property and the new value as parameters.
See also
setValue()
Referenced by setMaximum(), setMinimum(), setRange(), and setValue().
QString QtIntPropertyManager::valueText (const QtProperty * property) const [protected], [virtual]
Reimplemented from QtAbstractPropertyManager .
References QtIntPropertyManagerPrivate::m_values.
The documentation for this class was generated from the following files:
qtpropertymanager.h
qtpropertymanager.cpp