PlotGeometryEventListener Class Reference
This is an interface that you can subclass to be notified when the plot rect changes.
#include <plotgeometryeventlistener.h>
Public Member Functions
 PlotGeometryEventListener ()
virtual void plotRectChanged (const QRectF &newRect)=0
pure virtual method that needs to be reimplemented in order to be notified when the plot rect changes
virtual void plotAreaChanged (const QSizeF &area)=0
pure virtual method that needs to be reimplemented in order to be notified when the plot area changes.
virtual void scrollBarChanged (Qt::Orientation orientation, int value)=0
pure virtual method that needs to be reimplemented in order to be notified when the value of one of the two scrollbars changes.
virtual void plotZoomLevelChanged (int level)=0
Detailed Description
Subclass PlotEventListener and implement the plotRectChanged method if you want to be notified when the plot rect changes.
This usually happens when the scene rect changes or the plot area changes.
See also
PlotSceneWidget::installPlotChangeListener
PlotSceneWidget::setPlotAreaPercentage
PlotSceneWidget::setPlotAreaTopLeftPercentage
PlotSceneWidget
Constructor & Destructor Documentation
PlotGeometryEventListener()
PlotGeometryEventListener::PlotGeometryEventListener () [inline]
Member Function Documentation
plotAreaChanged()
virtual void PlotGeometryEventListener::plotAreaChanged (const QSizeF & area) [pure virtual]
Note
The area takes into account the scaling factors currently applied to the view, i.e. m11() and m22() of the current transformation obtained by transform().
Implemented in ExternalScaleWidget , and ScaleItem .
Referenced by PlotSceneWidget::notifyPlotAreaChanged().
plotRectChanged()
virtual void PlotGeometryEventListener::plotRectChanged (const QRectF & newRect) [pure virtual]
Parameters
newRect the new plot rectangle.
See also
PlotSceneWidget::installPlotChangeListener
PlotSceneWidget::setPlotAreaPercentage
PlotSceneWidget::setPlotAreaTopLeftPercentage
PlotSceneWidget
Implemented in ExternalScaleWidget , and ScaleItem .
Referenced by PlotSceneWidget::recalculatePlotRect().
plotZoomLevelChanged()
virtual void PlotGeometryEventListener::plotZoomLevelChanged (int level) [pure virtual]
Implemented in ExternalScaleWidget , and ScaleItem .
scrollBarChanged()
virtual void PlotGeometryEventListener::scrollBarChanged (Qt::Orientation orientation, int value) [pure virtual]
Parameters
orientation one of the two possible Qt::Orientation values: Qt::Horizontal or Qt::Vertical
value the value of the scrollbar
Implemented in ExternalScaleWidget , and ScaleItem .
Referenced by PlotSceneWidget::hScrollBarValueChanged(), and PlotSceneWidget::vScrollBarValueChanged().
The documentation for this class was generated from the following file:
 plotgeometryeventlistener.h