LegendItem Class Reference
A legend item.
#include <legenditem.h>
Public Slots
void setVisible (bool isVisible)
void newCurveAdded (SceneCurve *curve)
void curveRemoved (SceneCurve *c)
void setDrawBoundingRect (bool br)
void setFillBackground (bool fill)
Public Member Functions
 LegendItem (QGraphicsScene *parent=0)
void paint (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget)
bool fillBackground () const
bool drawBoundingRect () const
bool isVisible () const
QRectF boundingRect () const
void setCurveAlias (const QString &realName, const QString &alias)
QString curveAlias (const QString &realName) const
QString curveRealName (const QString &alias) const
void removeCurveAlias (const QString &realName)
QColor getColor (SceneCurve *curve)
Properties
bool isVisible
double zValue
bool fillBackground
bool drawBoundingRect
Detailed Description
This class is created and managed by the PlotSceneWidget.
Configuration
The legend can be configured by changing its zValue (default value is 100), by filling its background and drawing a black bounding rect around (both disabled by default.
Accessing the LegendItem.
Use PlotSceneWidget::legendItem()
Curve aliases.
The legend is able to show an alias instead of the complete source name of the curve. Use setCurveAlias to setup an alias for each curve. setCurveAlias can be invoked before or after TPlotSceneWidget::setSourcesList
Constructor & Destructor Documentation
LegendItem()
LegendItem::LegendItem (QGraphicsScene * parent = 0) [explicit]
References LegendItemPrivate::drawBoundingRect, LegendItemPrivate::fillBackground, LegendItemPrivate::height, and LegendItemPrivate::width.
Member Function Documentation
boundingRect()
QRectF LegendItem::boundingRect () const
References LegendItemPrivate::height, and LegendItemPrivate::width.
curveAlias()
QString LegendItem::curveAlias (const QString & realName) const
References LegendItemPrivate::curveAliases.
curveRealName()
QString LegendItem::curveRealName (const QString & alias) const
References LegendItemPrivate::curveAliases.
curveRemoved
void LegendItem::curveRemoved (SceneCurve * c) [slot]
References SceneCurve::name(), LegendItemPrivate::removeCurve(), and LegendItemPrivate::updateLongestCurveName().
drawBoundingRect()
bool LegendItem::drawBoundingRect () const
References LegendItemPrivate::drawBoundingRect.
fillBackground()
bool LegendItem::fillBackground () const
References LegendItemPrivate::fillBackground.
getColor()
QColor LegendItem::getColor (SceneCurve * curve)
References SceneCurve::curveItem(), CurveItem::itemPainter(), SceneCurve::name(), ItemPainterInterface::pen(), perr, and qstoc.
Referenced by paint().
isVisible()
bool LegendItem::isVisible () const
newCurveAdded
void LegendItem::newCurveAdded (SceneCurve * curve) [slot]
References LegendItemPrivate::addCurve().
paint()
void LegendItem::paint (QPainter * painter, const QStyleOptionGraphicsItem * option, QWidget * widget)
References Elettra::black, LegendItemPrivate::curveAliases, SceneCurve::curveItem(), LegendItemPrivate::curves, LegendItemPrivate::drawBoundingRect, LegendItemPrivate::fillBackground, getColor(), LegendItemPrivate::height, LegendItemPrivate::longestCurveName, SceneCurve::name(), Elettra::white, and LegendItemPrivate::width.
removeCurveAlias()
void LegendItem::removeCurveAlias (const QString & realName)
References LegendItemPrivate::curveAliases.
setCurveAlias()
void LegendItem::setCurveAlias (const QString & realName, const QString & alias)
References LegendItemPrivate::curveAliases, and LegendItemPrivate::updateLongestCurveName().
setDrawBoundingRect
void LegendItem::setDrawBoundingRect (bool br) [slot]
References LegendItemPrivate::drawBoundingRect.
setFillBackground
void LegendItem::setFillBackground (bool fill) [slot]
References LegendItemPrivate::fillBackground.
setVisible
void LegendItem::setVisible (bool isVisible) [slot]
Property Documentation
drawBoundingRect
bool LegendItem::drawBoundingRect [read], [write]
fillBackground
bool LegendItem::fillBackground [read], [write]
isVisible
bool LegendItem::isVisible [read], [write]
zValue
double LegendItem::zValue [read], [write]
The documentation for this class was generated from the following files:
 legenditem.h
 legenditem.cpp