QtAbstractPropertyManager Class Reference
The QtAbstractPropertyManager provides an interface for property managers.
#include <qtpropertybrowser.h>
Signals
void propertyInserted (QtProperty *property, QtProperty *parent, QtProperty *after)
void propertyChanged (QtProperty *property)
void propertyRemoved (QtProperty *property, QtProperty *parent)
void propertyDestroyed (QtProperty *property)
Public Member Functions
QtAbstractPropertyManager (QObject *parent=0)
~QtAbstractPropertyManager ()
QSet< QtProperty * > properties () const
void clear () const
QtProperty * addProperty (const QString &name=QString())
QtProperty * qtProperty (const QString &id) const
Protected Member Functions
virtual bool hasValue (const QtProperty *property) const
virtual QIcon valueIcon (const QtProperty *property) const
virtual QString valueText (const QtProperty *property) const
virtual void initializeProperty (QtProperty *property)=0
virtual void uninitializeProperty (QtProperty *property)
virtual QtProperty * createProperty ()
Friends
class QtProperty
Detailed Description
A manager can create and manage properties of a given type, and is used in conjunction with the QtAbstractPropertyBrowser class.
When using a property browser widget, the properties are created and managed by implementations of the QtAbstractPropertyManager class. To ensure that the properties' values will be displayed using suitable editing widgets, the managers are associated with objects of QtAbstractEditorFactory subclasses. The property browser will use these associations to determine which factories it should use to create the preferred editing widgets.
The QtAbstractPropertyManager class provides common functionality like creating a property using the addProperty() function, and retrieving the properties created by the manager using the properties() function. The class also provides signals that are emitted when the manager's properties change: propertyInserted(), propertyRemoved(), propertyChanged() and propertyDestroyed().
QtAbstractPropertyManager subclasses are supposed to provide their own type specific API. Note that several ready-made implementations are available:
QtBoolPropertyManager QtColorPropertyManager QtDatePropertyManager QtDateTimePropertyManager QtDoublePropertyManager QtEnumPropertyManager QtFlagPropertyManager QtFontPropertyManager QtGroupPropertyManager QtIntPropertyManager QtPointPropertyManager QtRectPropertyManager QtSizePropertyManager QtSizePolicyPropertyManager QtStringPropertyManager QtTimePropertyManager QtVariantPropertyManager
See also
QtAbstractEditorFactoryBase, QtAbstractPropertyBrowser, QtProperty
Constructor & Destructor Documentation
QtAbstractPropertyManager::QtAbstractPropertyManager (QObject * parent = 0) [explicit]
Creates an abstract property manager with the given parent.
QtAbstractPropertyManager::~QtAbstractPropertyManager ()
Destroys the manager. All properties created by the manager are destroyed.
References clear().
Member Function Documentation
QtProperty * QtAbstractPropertyManager::addProperty (const QString & name = QString())
Creates a property with the given name which then is owned by this manager.
Internally, this function calls the createProperty() and initializeProperty() functions.
See also
initializeProperty(), properties()
References createProperty(), initializeProperty(), and QtAbstractPropertyManagerPrivate::m_properties.
Referenced by QtVariantPropertyManager::addProperty(), QtCursorEditorFactory::createEditor(), QtVariantPropertyManager::initializeProperty(), QtLocalePropertyManager::initializeProperty(), QtPointPropertyManager::initializeProperty(), QtPointFPropertyManager::initializeProperty(), QtSizePropertyManager::initializeProperty(), QtSizeFPropertyManager::initializeProperty(), QtRectPropertyManager::initializeProperty(), QtRectFPropertyManager::initializeProperty(), QtSizePolicyPropertyManager::initializeProperty(), QtFontPropertyManager::initializeProperty(), QtColorPropertyManager::initializeProperty(), and QtFlagPropertyManager::setFlagNames().
void QtAbstractPropertyManager::clear () const
Destroys all the properties that this manager has created.
See also
propertyDestroyed(), uninitializeProperty()
References properties().
Referenced by QtVariantPropertyManager::setProperties(), ~QtAbstractPropertyManager(), QtBoolPropertyManager::~QtBoolPropertyManager(), QtCharPropertyManager::~QtCharPropertyManager(), QtColorPropertyManager::~QtColorPropertyManager(), QtCursorPropertyManager::~QtCursorPropertyManager(), QtDatePropertyManager::~QtDatePropertyManager(), QtDateTimePropertyManager::~QtDateTimePropertyManager(), QtDoublePropertyManager::~QtDoublePropertyManager(), QtEnumPropertyManager::~QtEnumPropertyManager(), QtFlagPropertyManager::~QtFlagPropertyManager(), QtFontPropertyManager::~QtFontPropertyManager(), QtIntPropertyManager::~QtIntPropertyManager(), QtKeySequencePropertyManager::~QtKeySequencePropertyManager(), QtLocalePropertyManager::~QtLocalePropertyManager(), QtPointFPropertyManager::~QtPointFPropertyManager(), QtPointPropertyManager::~QtPointPropertyManager(), QtRectFPropertyManager::~QtRectFPropertyManager(), QtRectPropertyManager::~QtRectPropertyManager(), QtSizeFPropertyManager::~QtSizeFPropertyManager(), QtSizePolicyPropertyManager::~QtSizePolicyPropertyManager(), QtSizePropertyManager::~QtSizePropertyManager(), QtStringPropertyManager::~QtStringPropertyManager(), QtTimePropertyManager::~QtTimePropertyManager(), and QtVariantPropertyManager::~QtVariantPropertyManager().
QtProperty * QtAbstractPropertyManager::createProperty () [protected], [virtual]
Creates a property.
The base implementation produce QtProperty instances; Reimplement this function to make this manager produce objects of a QtProperty subclass.
See also
addProperty(), initializeProperty()
Reimplemented in QtVariantPropertyManager .
References QtProperty.
Referenced by addProperty().
bool QtAbstractPropertyManager::hasValue (const QtProperty * property) const [protected], [virtual]
Returns whether the given property has a value.
The default implementation of this function returns true.
See also
QtProperty::hasValue()
Reimplemented in QtVariantPropertyManager , and QtGroupPropertyManager .
void QtAbstractPropertyManager::initializeProperty (QtProperty * property) [protected], [pure virtual]
This function is called whenever a new valid property pointer has been created, passing the pointer as parameter.
The purpose is to let the manager know that the property has been created so that it can provide additional attributes for the new property, e.g. QtIntPropertyManager adds {QtIntPropertyManager::value()}{value}, {QtIntPropertyManager::minimum()}{minimum} and {QtIntPropertyManager::maximum()}{maximum} attributes. Since each manager subclass adds type specific attributes, this function is pure virtual and must be reimplemented when deriving from the QtAbstractPropertyManager class.
See also
addProperty(), createProperty()
Implemented in QtCursorPropertyManager , QtColorPropertyManager , QtFontPropertyManager , QtSizePolicyPropertyManager , QtFlagPropertyManager , QtEnumPropertyManager , QtRectFPropertyManager , QtRectPropertyManager , QtSizeFPropertyManager , QtSizePropertyManager , QtPointFPropertyManager , QtPointPropertyManager , QtLocalePropertyManager , QtCharPropertyManager , QtKeySequencePropertyManager , QtDateTimePropertyManager , QtTimePropertyManager , QtDatePropertyManager , QtStringPropertyManager , QtDoublePropertyManager , QtBoolPropertyManager , QtVariantPropertyManager , QtIntPropertyManager , and QtGroupPropertyManager .
Referenced by addProperty().
QSet< QtProperty * > QtAbstractPropertyManager::properties () const
Returns the set of properties created by this manager.
See also
addProperty()
References QtAbstractPropertyManagerPrivate::m_properties.
Referenced by clear().
void QtAbstractPropertyManager::propertyChanged (QtProperty * property) [signal]
This signal is emitted whenever a property's data changes, passing a pointer to the property as parameter.
Note that signal is only emitted for properties that are created by this manager.
See also
QtAbstractPropertyBrowser::itemChanged()
Referenced by QtRectPropertyManager::setConstraint(), QtRectFPropertyManager::setConstraint(), QtEnumPropertyManager::setEnumIcons(), QtEnumPropertyManager::setEnumNames(), QtFlagPropertyManager::setFlagNames(), QtIntPropertyManager::setMaximum(), QtDoublePropertyManager::setMaximum(), QtDatePropertyManager::setMaximum(), QtSizePropertyManager::setMaximum(), QtSizeFPropertyManager::setMaximum(), QtIntPropertyManager::setMinimum(), QtDoublePropertyManager::setMinimum(), QtDatePropertyManager::setMinimum(), QtSizePropertyManager::setMinimum(), QtSizeFPropertyManager::setMinimum(), QtIntPropertyManager::setRange(), QtDoublePropertyManager::setRange(), QtDatePropertyManager::setRange(), QtSizePropertyManager::setRange(), QtSizeFPropertyManager::setRange(), QtIntPropertyManager::setValue(), QtBoolPropertyManager::setValue(), QtDoublePropertyManager::setValue(), QtStringPropertyManager::setValue(), QtDatePropertyManager::setValue(), QtTimePropertyManager::setValue(), QtDateTimePropertyManager::setValue(), QtKeySequencePropertyManager::setValue(), QtCharPropertyManager::setValue(), QtLocalePropertyManager::setValue(), QtPointPropertyManager::setValue(), QtPointFPropertyManager::setValue(), QtSizePropertyManager::setValue(), QtSizeFPropertyManager::setValue(), QtRectPropertyManager::setValue(), QtRectFPropertyManager::setValue(), QtEnumPropertyManager::setValue(), QtFlagPropertyManager::setValue(), QtSizePolicyPropertyManager::setValue(), QtFontPropertyManager::setValue(), QtColorPropertyManager::setValue(), QtCursorPropertyManager::setValue(), and QtVariantPropertyManagerPrivate::valueChanged().
void QtAbstractPropertyManager::propertyDestroyed (QtProperty * property) [signal]
This signal is emitted when the specified property is about to be destroyed.
Note that signal is only emitted for properties that are created by this manager.
See also
clear(), uninitializeProperty()
Referenced by QtColorPropertyManager::QtColorPropertyManager(), QtFlagPropertyManager::QtFlagPropertyManager(), QtFontPropertyManager::QtFontPropertyManager(), QtLocalePropertyManager::QtLocalePropertyManager(), QtPointFPropertyManager::QtPointFPropertyManager(), QtPointPropertyManager::QtPointPropertyManager(), QtRectFPropertyManager::QtRectFPropertyManager(), QtRectPropertyManager::QtRectPropertyManager(), QtSizeFPropertyManager::QtSizeFPropertyManager(), QtSizePolicyPropertyManager::QtSizePolicyPropertyManager(), and QtSizePropertyManager::QtSizePropertyManager().
void QtAbstractPropertyManager::propertyInserted (QtProperty * newProperty, QtProperty * parentProperty, QtProperty * precedingProperty) [signal]
This signal is emitted when a new subproperty is inserted into an existing property, passing pointers to the newProperty, parentProperty and precedingProperty as parameters.
If precedingProperty is 0, the newProperty was inserted at the beginning of the parentProperty's subproperties list.
Note that signal is emitted only if the parentProperty is created by this manager.
See also
QtAbstractPropertyBrowser::itemInserted()
Referenced by QtVariantPropertyManager::QtVariantPropertyManager().
void QtAbstractPropertyManager::propertyRemoved (QtProperty * property, QtProperty * parent) [signal]
This signal is emitted when a subproperty is removed, passing pointers to the removed property and the parent property as parameters.
Note that signal is emitted only when the parent property is created by this manager.
See also
QtAbstractPropertyBrowser::itemRemoved()
Referenced by QtVariantPropertyManager::QtVariantPropertyManager().
QtProperty * QtAbstractPropertyManager::qtProperty (const QString & id) const
Return the QtProperty object matching id or Null if any.
See also
addProperty(), setPropertyId(const QString&), properties()
References QtAbstractPropertyManagerPrivate::m_properties, and QtProperty::propertyId().
void QtAbstractPropertyManager::uninitializeProperty (QtProperty * property) [protected], [virtual]
This function is called just before the specified property is destroyed.
The purpose is to let the property manager know that the property is being destroyed so that it can remove the property's additional attributes.
See also
clear(), propertyDestroyed()
Reimplemented in QtCursorPropertyManager , QtColorPropertyManager , QtFontPropertyManager , QtSizePolicyPropertyManager , QtFlagPropertyManager , QtEnumPropertyManager , QtRectFPropertyManager , QtRectPropertyManager , QtSizeFPropertyManager , QtSizePropertyManager , QtPointFPropertyManager , QtPointPropertyManager , QtLocalePropertyManager , QtCharPropertyManager , QtKeySequencePropertyManager , QtDateTimePropertyManager , QtTimePropertyManager , QtDatePropertyManager , QtStringPropertyManager , QtDoublePropertyManager , QtBoolPropertyManager , QtVariantPropertyManager , QtIntPropertyManager , and QtGroupPropertyManager .
QIcon QtAbstractPropertyManager::valueIcon (const QtProperty * property) const [protected], [virtual]
Returns an icon representing the current state of the given property.
The default implementation of this function returns an invalid icon.
See also
QtProperty::valueIcon()
Reimplemented in QtCursorPropertyManager , QtColorPropertyManager , QtFontPropertyManager , QtEnumPropertyManager , QtBoolPropertyManager , and QtVariantPropertyManager .
QString QtAbstractPropertyManager::valueText (const QtProperty * property) const [protected], [virtual]
Returns a string representing the current state of the given property.
The default implementation of this function returns an empty string.
See also
QtProperty::valueText()
Reimplemented in QtCursorPropertyManager , QtColorPropertyManager , QtFontPropertyManager , QtSizePolicyPropertyManager , QtFlagPropertyManager , QtEnumPropertyManager , QtRectFPropertyManager , QtRectPropertyManager , QtSizeFPropertyManager , QtSizePropertyManager , QtPointFPropertyManager , QtPointPropertyManager , QtLocalePropertyManager , QtCharPropertyManager , QtKeySequencePropertyManager , QtDateTimePropertyManager , QtTimePropertyManager , QtDatePropertyManager , QtStringPropertyManager , QtDoublePropertyManager , QtBoolPropertyManager , QtVariantPropertyManager , and QtIntPropertyManager .
Friends And Related Function Documentation
friend class QtProperty [friend]
Referenced by createProperty().
The documentation for this class was generated from the following files:
qtpropertybrowser.h
qtpropertybrowser.cpp