QtFontPropertyManager Class Reference
The QtFontPropertyManager provides and manages QFont properties.
#include <qtpropertymanager.h>
Public Slots
void setValue (QtProperty *property, const QFont &val)
Signals
void valueChanged (QtProperty *property, const QFont &val)
Public Member Functions
QtFontPropertyManager (QObject *parent=0)
~QtFontPropertyManager ()
QtIntPropertyManager * subIntPropertyManager () const
QtEnumPropertyManager * subEnumPropertyManager () const
QtBoolPropertyManager * subBoolPropertyManager () const
QFont value (const QtProperty *property) const
Protected Member Functions
QString valueText (const QtProperty *property) const
QIcon valueIcon (const QtProperty *property) const
virtual void initializeProperty (QtProperty *property)
virtual void uninitializeProperty (QtProperty *property)
Detailed Description
A font property has nested family, pointSize, bold, italic, underline, strikeOut and kerning subproperties. The top-level property's value can be retrieved using the value() function, and set using the setValue() slot.
The subproperties are created by QtIntPropertyManager, QtEnumPropertyManager and QtBoolPropertyManager objects. These managers can be retrieved using the corresponding subIntPropertyManager(), subEnumPropertyManager() and subBoolPropertyManager() functions. In order to provide editing widgets for the subproperties in a property browser widget, these managers must be associated with editor factories.
In addition, QtFontPropertyManager provides the valueChanged() signal which is emitted whenever a property created by this manager changes.
See also
QtAbstractPropertyManager, QtEnumPropertyManager, QtIntPropertyManager, QtBoolPropertyManager
Constructor & Destructor Documentation
QtFontPropertyManager::QtFontPropertyManager (QObject * parent = 0)
Creates a manager with the given parent.
References QtFontPropertyManagerPrivate::m_boolPropertyManager, QtFontPropertyManagerPrivate::m_enumPropertyManager, QtFontPropertyManagerPrivate::m_intPropertyManager, QtAbstractPropertyManager::propertyDestroyed(), and valueChanged().
QtFontPropertyManager::~QtFontPropertyManager ()
Destroys this manager, and all the properties it has created.
References QtAbstractPropertyManager::clear().
Member Function Documentation
void QtFontPropertyManager::initializeProperty (QtProperty * property) [protected], [virtual]
Implements QtAbstractPropertyManager .
References QtAbstractPropertyManager::addProperty(), QtProperty::addSubProperty(), QtFontPropertyManagerPrivate::m_boldToProperty, QtFontPropertyManagerPrivate::m_boolPropertyManager, QtFontPropertyManagerPrivate::m_enumPropertyManager, QtFontPropertyManagerPrivate::m_familyNames, QtFontPropertyManagerPrivate::m_familyToProperty, QtFontPropertyManagerPrivate::m_intPropertyManager, QtFontPropertyManagerPrivate::m_italicToProperty, QtFontPropertyManagerPrivate::m_kerningToProperty, QtFontPropertyManagerPrivate::m_pointSizeToProperty, QtFontPropertyManagerPrivate::m_propertyToBold, QtFontPropertyManagerPrivate::m_propertyToFamily, QtFontPropertyManagerPrivate::m_propertyToItalic, QtFontPropertyManagerPrivate::m_propertyToKerning, QtFontPropertyManagerPrivate::m_propertyToPointSize, QtFontPropertyManagerPrivate::m_propertyToStrikeOut, QtFontPropertyManagerPrivate::m_propertyToUnderline, QtFontPropertyManagerPrivate::m_strikeOutToProperty, QtFontPropertyManagerPrivate::m_underlineToProperty, QtFontPropertyManagerPrivate::m_values, QtEnumPropertyManager::setEnumNames(), QtIntPropertyManager::setMinimum(), QtProperty::setPropertyName(), QtIntPropertyManager::setValue(), QtBoolPropertyManager::setValue(), and QtEnumPropertyManager::setValue().
void QtFontPropertyManager::setValue (QtProperty * property, const QFont & value) [slot]
Sets the value of the given property to value. Nested properties are updated automatically.
See also
value(), valueChanged()
References QtFontPropertyManagerPrivate::m_boolPropertyManager, QtFontPropertyManagerPrivate::m_enumPropertyManager, QtFontPropertyManagerPrivate::m_familyNames, QtFontPropertyManagerPrivate::m_intPropertyManager, QtFontPropertyManagerPrivate::m_propertyToBold, QtFontPropertyManagerPrivate::m_propertyToFamily, QtFontPropertyManagerPrivate::m_propertyToItalic, QtFontPropertyManagerPrivate::m_propertyToKerning, QtFontPropertyManagerPrivate::m_propertyToPointSize, QtFontPropertyManagerPrivate::m_propertyToStrikeOut, QtFontPropertyManagerPrivate::m_propertyToUnderline, QtFontPropertyManagerPrivate::m_settingValue, QtFontPropertyManagerPrivate::m_values, QtAbstractPropertyManager::propertyChanged(), QtIntPropertyManager::setValue(), QtBoolPropertyManager::setValue(), QtEnumPropertyManager::setValue(), and valueChanged().
Referenced by QtFontPropertyManagerPrivate::slotBoolChanged(), QtFontPropertyManagerPrivate::slotEnumChanged(), QtFontPropertyManagerPrivate::slotIntChanged(), and QtFontEditorFactoryPrivate::slotSetValue().
QtBoolPropertyManager * QtFontPropertyManager::subBoolPropertyManager () const
Returns the manager that creates the bold, italic, underline, strikeOut and kerning subproperties.
In order to provide editing widgets for the mentioned properties in a property browser widget, this manager must be associated with an editor factory.
See also
QtAbstractPropertyBrowser::setFactoryForManager()
References QtFontPropertyManagerPrivate::m_boolPropertyManager.
Referenced by QtVariantEditorFactory::connectPropertyManager(), QtVariantEditorFactory::disconnectPropertyManager(), and QtVariantPropertyManager::QtVariantPropertyManager().
QtEnumPropertyManager * QtFontPropertyManager::subEnumPropertyManager () const
Returns the manager that create the family subproperty.
In order to provide editing widgets for the family property in a property browser widget, this manager must be associated with an editor factory.
See also
QtAbstractPropertyBrowser::setFactoryForManager()
References QtFontPropertyManagerPrivate::m_enumPropertyManager.
Referenced by QtVariantEditorFactory::connectPropertyManager(), QtVariantEditorFactory::disconnectPropertyManager(), and QtVariantPropertyManager::QtVariantPropertyManager().
QtIntPropertyManager * QtFontPropertyManager::subIntPropertyManager () const
Returns the manager that creates the pointSize subproperty.
In order to provide editing widgets for the pointSize property in a property browser widget, this manager must be associated with an editor factory.
See also
QtAbstractPropertyBrowser::setFactoryForManager()
References QtFontPropertyManagerPrivate::m_intPropertyManager.
Referenced by QtVariantEditorFactory::connectPropertyManager(), QtVariantEditorFactory::disconnectPropertyManager(), and QtVariantPropertyManager::QtVariantPropertyManager().
void QtFontPropertyManager::uninitializeProperty (QtProperty * property) [protected], [virtual]
Reimplemented from QtAbstractPropertyManager .
References QtFontPropertyManagerPrivate::m_boldToProperty, QtFontPropertyManagerPrivate::m_familyToProperty, QtFontPropertyManagerPrivate::m_italicToProperty, QtFontPropertyManagerPrivate::m_kerningToProperty, QtFontPropertyManagerPrivate::m_pointSizeToProperty, QtFontPropertyManagerPrivate::m_propertyToBold, QtFontPropertyManagerPrivate::m_propertyToFamily, QtFontPropertyManagerPrivate::m_propertyToItalic, QtFontPropertyManagerPrivate::m_propertyToKerning, QtFontPropertyManagerPrivate::m_propertyToPointSize, QtFontPropertyManagerPrivate::m_propertyToStrikeOut, QtFontPropertyManagerPrivate::m_propertyToUnderline, QtFontPropertyManagerPrivate::m_strikeOutToProperty, QtFontPropertyManagerPrivate::m_underlineToProperty, and QtFontPropertyManagerPrivate::m_values.
QFont QtFontPropertyManager::value (const QtProperty * property) const
Returns the given property's value.
If the given property is not managed by this manager, this function returns a font object that uses the application's default font.
See also
setValue()
References QtFontPropertyManagerPrivate::m_values.
Referenced by QtFontEditorFactory::createEditor().
void QtFontPropertyManager::valueChanged (QtProperty * property, const QFont & value) [signal]
This signal is emitted whenever a property created by this manager changes its value, passing a pointer to the property and the new value as parameters.
See also
setValue()
Referenced by QtFontPropertyManager(), and setValue().
QIcon QtFontPropertyManager::valueIcon (const QtProperty * property) const [protected], [virtual]
Reimplemented from QtAbstractPropertyManager .
References QtPropertyBrowserUtils::fontValueIcon(), and QtFontPropertyManagerPrivate::m_values.
QString QtFontPropertyManager::valueText (const QtProperty * property) const [protected], [virtual]
Reimplemented from QtAbstractPropertyManager .
References QtPropertyBrowserUtils::fontValueText(), and QtFontPropertyManagerPrivate::m_values.
The documentation for this class was generated from the following files:
qtpropertymanager.h
qtpropertymanager.cpp