QtKeySequencePropertyManager Class Reference
The QtKeySequencePropertyManager provides and manages QKeySequence properties.
#include <qtpropertymanager.h>
Public Slots
void setValue (QtProperty *property, const QKeySequence &val)
Signals
void valueChanged (QtProperty *property, const QKeySequence &val)
Public Member Functions
QtKeySequencePropertyManager (QObject *parent=0)
~QtKeySequencePropertyManager ()
QKeySequence value (const QtProperty *property) const
Protected Member Functions
QString valueText (const QtProperty *property) const
virtual void initializeProperty (QtProperty *property)
virtual void uninitializeProperty (QtProperty *property)
Detailed Description
A key sequence's value can be retrieved using the value() function, and set using the setValue() slot.
In addition, QtKeySequencePropertyManager provides the valueChanged() signal which is emitted whenever a property created by this manager changes.
See also
QtAbstractPropertyManager
Constructor & Destructor Documentation
QtKeySequencePropertyManager::QtKeySequencePropertyManager (QObject * parent = 0)
Creates a manager with the given parent.
QtKeySequencePropertyManager::~QtKeySequencePropertyManager ()
Destroys this manager, and all the properties it has created.
References QtAbstractPropertyManager::clear().
Member Function Documentation
void QtKeySequencePropertyManager::initializeProperty (QtProperty * property) [protected], [virtual]
Implements QtAbstractPropertyManager .
References QtKeySequencePropertyManagerPrivate::m_values.
void QtKeySequencePropertyManager::setValue (QtProperty * property, const QKeySequence & value) [slot]
Sets the value of the given property to value.
See also
value(), valueChanged()
References QtKeySequencePropertyManagerPrivate::m_values, QtAbstractPropertyManager::propertyChanged(), and valueChanged().
Referenced by QtKeySequenceEditorFactoryPrivate::slotSetValue().
void QtKeySequencePropertyManager::uninitializeProperty (QtProperty * property) [protected], [virtual]
Reimplemented from QtAbstractPropertyManager .
References QtKeySequencePropertyManagerPrivate::m_values.
QKeySequence QtKeySequencePropertyManager::value (const QtProperty * property) const
Returns the given property's value.
If the given property is not managed by this manager, this function returns an empty QKeySequence object.
See also
setValue()
References QtKeySequencePropertyManagerPrivate::m_values.
Referenced by QtKeySequenceEditorFactory::createEditor().
void QtKeySequencePropertyManager::valueChanged (QtProperty * property, const QKeySequence & value) [signal]
This signal is emitted whenever a property created by this manager changes its value, passing a pointer to the property and the new value as parameters.
Referenced by setValue().
QString QtKeySequencePropertyManager::valueText (const QtProperty * property) const [protected], [virtual]
Reimplemented from QtAbstractPropertyManager .
References QtKeySequencePropertyManagerPrivate::m_values.
The documentation for this class was generated from the following files:
qtpropertymanager.h
qtpropertymanager.cpp