TreeViewAxes Class Reference
#include <treeviewaxes.h>
Public Types
enum Columns { ColName,
ColYAxis
 }
enum CustomRoles { AxisCntRole = Qt::UserRole + 1
 }
Public Member Functions
TreeViewAxes (QWidget *parent=NULL)
void setAxisCount (int count, ScaleOrientation::Type o)
int axisCount (ScaleOrientation::Type o) const
void addItem (const QString &src)
void removeItem (const QString &src)
QList< CurveOptions > getCurveOptions () const
Member Enumeration Documentation
enum TreeViewAxes::Columns
Enumerator
ColName
ColYAxis
enum TreeViewAxes::CustomRoles
Enumerator
AxisCntRole
Constructor & Destructor Documentation
TreeViewAxes::TreeViewAxes (QWidget * parent = NULL)
References Elettra::blue, ColYAxis, Elettra::cyan, Elettra::darkCyan, Elettra::darkGreen, Elettra::darkRed, Elettra::green, ScaleOrientation::Horizontal, Elettra::red, setAxisCount(), ScaleOrientation::Vertical, and Elettra::yellow.
Member Function Documentation
void TreeViewAxes::addItem (const QString & src)
References axisCount(), AxesDataModel::ColName, AxesDataModel::ColYAxis, ColYAxis, AxesDataModel::data(), AxesDataModel::rowCount(), and AxesDataModel::setData().
Referenced by AxisConfWidget::addItem().
int TreeViewAxes::axisCount (ScaleOrientation::Type o) const
References ColYAxis, and ScaleOrientation::Horizontal.
Referenced by AxisConfWidget::addConfigurableObjects(), addItem(), and AxisConfWidget::axisCount().
QList< CurveOptions > TreeViewAxes::getCurveOptions () const
References AxesDataModel::getData().
Referenced by AxisConfWidget::addConfigurableObjects().
void TreeViewAxes::removeItem (const QString & src)
void TreeViewAxes::setAxisCount (int count, ScaleOrientation::Type o)
References ColYAxis, and ScaleOrientation::Horizontal.
Referenced by AxisConfWidget::addConfigurableObjects(), AxisConfWidget::setAxisCount(), and TreeViewAxes().
The documentation for this class was generated from the following files:
treeviewaxes.h
treeviewaxes.cpp