QtCharEdit Class Reference
Public Slots
void setValue (const QChar &value)
Signals
void valueChanged (const QChar &value)
Public Member Functions
QtCharEdit (QWidget *parent=0)
QChar value () const
bool eventFilter (QObject *o, QEvent *e)
Protected Member Functions
void focusInEvent (QFocusEvent *e)
void focusOutEvent (QFocusEvent *e)
void keyPressEvent (QKeyEvent *e)
void keyReleaseEvent (QKeyEvent *e)
void paintEvent (QPaintEvent *)
bool event (QEvent *e)
Constructor & Destructor Documentation
QtCharEdit::QtCharEdit (QWidget * parent = 0)
Member Function Documentation
bool QtCharEdit::event (QEvent * e) [protected]
bool QtCharEdit::eventFilter (QObject * o, QEvent * e)
References setValue(), and valueChanged().
void QtCharEdit::focusInEvent (QFocusEvent * e) [protected]
void QtCharEdit::focusOutEvent (QFocusEvent * e) [protected]
void QtCharEdit::keyPressEvent (QKeyEvent * e) [protected]
void QtCharEdit::keyReleaseEvent (QKeyEvent * e) [protected]
void QtCharEdit::paintEvent (QPaintEvent *) [protected]
void QtCharEdit::setValue (const QChar & value) [slot]
References value().
Referenced by QtCharEditorFactory::createEditor(), eventFilter(), and QtCharEditorFactoryPrivate::slotPropertyChanged().
QChar QtCharEdit::value () const
Referenced by setValue().
void QtCharEdit::valueChanged (const QChar & value) [signal]
Referenced by eventFilter().
The documentation for this class was generated from the following file:
qteditorfactory.cpp