MarkerItem Class Reference
When a mouse click event takes place into the plot, the closest point on the closest curve is marked by a round circle and the x and y values of the point on the curve are drawn.
#include <markeritem.h>
Public Types
enum { Type = UserType + 201
 }
Public Slots
void setTextColor (const QColor &c)
void setPointColor (const QColor &pointC)
Set or change the point fill color.
void setPointBorderColor (const QColor &bc)
void setBackgroundColor (const QColor &bgc)
void setDecorationEnabled (bool en)
void setDotRadius (double r)
void removeCurve (SceneCurve *c)
void setItemIgnoresTransformations (bool ign)
Public Member Functions
 MarkerItem (QGraphicsObject *parent)
virtual ~MarkerItem ()
virtual void mouseClickEvent (PlotSceneWidget *plot, const QPointF &pos)
virtual void mouseReleaseEvent (PlotSceneWidget *plot, QMouseEvent *e)
virtual void mouseDoubleClickEvent (PlotSceneWidget *, QMouseEvent *)
virtual void paint (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget)
virtual QRectF boundingRect () const
QColor textColor () const
The color of the text. Default is black.
QColor pointColor () const
Returns the color used to fill the point.
QColor pointBorderColor () const
This property holds the color of the point.
QColor backgroundColor () const
This property determines the background color of the text area.
bool decorationEnabled () const
double dotRadius () const
This property describes the dimensions of the point drawn by the marker.
bool itemIgnoresTransformations () const
This property determines if the item ignores the scen transformataions.
Properties
bool decorationEnabled
QColor textColor
QColor pointColor
QColor pointBorderColor
QColor backgroundColor
double dotRadius
bool itemIgnoresTransformations
Detailed Description
The marker is drawn on the point of the curve closest to the point where the mouse click event took place.
Implementation
When the user clicks on a point P1 on the plot, the MarkerItem asks the plot which are the curve and the point closest to P1. A circle is drawn on that point and its position is kept up to date when the y coordinate changes in time. The point is kept drawn on the same x coordinate.
Note
Important note If your application permits removing curves, then you must connect the PlotSceneWidget::curveAboutToBeRemoved signal to the MarkerItem::removeCurve slot. Forgetting to do this will cause the application to crash when a curve on which a marker is placed is removed.
 It is not otherwise possible for the MarkerItem to know when a curve is removed, because the closest x coordinate point and the closest curve are only calculated on the click event and are not updated at each paint event, for performance reasons. You don't need this signal/slot connection if you don't plan to remove curves from the plot at runtime.
MarkerItem is configurable through some Qt properties. If you want to be able to change them at runtime, remember to call PlotSceneWidget::addConfigurableObjects after creating your own MarkerItem.
Example
MarkerItem* marker = new MarkerItem(0);
myPlotSceneWidget->installMouseEventListener(marker);
myPlotSceneWidget->scene()->addItem(marker);
// if you plan to remove a curve from the plot
connect(myPlotSceneWidget, SIGNAL(curveAboutToBeRemoved(SceneCurve *)), marker,
        SLOT(removeCurve(SceneCurve *)));
// if you want to configure the MarkerItem at runtime:
myPlotSceneWidget->addConfigurableObjects("Marker", marker);
If the alias Qt property is set on a scene curve, this is used by the marker to draw the curve identifier instead of its name (SceneCurve::name).
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
Type
Constructor & Destructor Documentation
MarkerItem()
MarkerItem::MarkerItem (QGraphicsObject * parent)
References Elettra::black, KBLUE, KDARKGRAY, KLIGHTGRAY, and KORANGE.
~MarkerItem()
MarkerItem::~MarkerItem () [virtual]
Member Function Documentation
backgroundColor()
QColor MarkerItem::backgroundColor () const
boundingRect()
QRectF MarkerItem::boundingRect () const [virtual]
decorationEnabled()
bool MarkerItem::decorationEnabled () const
dotRadius()
double MarkerItem::dotRadius () const
itemIgnoresTransformations()
bool MarkerItem::itemIgnoresTransformations () const
By default, scene transformations are ignored
mouseClickEvent()
void MarkerItem::mouseClickEvent (PlotSceneWidget * plot, const QPointF & pos) [virtual]
Reimplemented from MouseEventListener .
References PlotSceneWidget::getClosest(), and PlotSceneWidget::getCurves().
mouseDoubleClickEvent()
void MarkerItem::mouseDoubleClickEvent (PlotSceneWidget * plot, QMouseEvent * e) [virtual]
Reimplemented from MouseEventListener .
mouseReleaseEvent()
void MarkerItem::mouseReleaseEvent (PlotSceneWidget * plot, QMouseEvent * e) [virtual]
Reimplemented from MouseEventListener .
paint()
void MarkerItem::paint (QPainter * painter, const QStyleOptionGraphicsItem * option, QWidget * widget) [virtual]
References SceneCurve::data(), SceneCurve::dataSize(), SceneCurve::getXAxis(), SceneCurve::getYAxis(), KDARKGRAY, ScaleItem::label(), SceneCurve::name(), SceneCurve::points(), Elettra::white, Data::xData, and Data::yData.
pointBorderColor()
QColor MarkerItem::pointBorderColor () const
Default: blue
pointColor()
QColor MarkerItem::pointColor () const
If an invalid color is set (the default), then the circle is drawn but not filled
Returns
the color used to fill in the point.
See also
setPointColor
removeCurve
void MarkerItem::removeCurve (SceneCurve * c) [slot]
setBackgroundColor
void MarkerItem::setBackgroundColor (const QColor & bgc) [slot]
setDecorationEnabled
void MarkerItem::setDecorationEnabled (bool en) [slot]
setDotRadius
void MarkerItem::setDotRadius (double r) [slot]
setItemIgnoresTransformations
void MarkerItem::setItemIgnoresTransformations (bool ign) [slot]
setPointBorderColor
void MarkerItem::setPointBorderColor (const QColor & bc) [slot]
setPointColor
void MarkerItem::setPointColor (const QColor & pointC) [slot]
Parameters
pointC the color to use to fill the circle around the marker point.
Note
Unless setPointColor is called, the MarkerItem only draws the circle, without filling it.
setTextColor
void MarkerItem::setTextColor (const QColor & c) [slot]
textColor()
QColor MarkerItem::textColor () const
Property Documentation
backgroundColor
QColor MarkerItem::backgroundColor [read], [write]
decorationEnabled
bool MarkerItem::decorationEnabled [read], [write]
dotRadius
double MarkerItem::dotRadius [read], [write]
itemIgnoresTransformations
bool MarkerItem::itemIgnoresTransformations [read], [write]
pointBorderColor
QColor MarkerItem::pointBorderColor [read], [write]
pointColor
QColor MarkerItem::pointColor [read], [write]
textColor
QColor MarkerItem::textColor [read], [write]
The documentation for this class was generated from the following files:
 markeritem.h
 markeritem.cpp