QtBoolPropertyManager Class Reference
The QtBoolPropertyManager class provides and manages boolean properties.
#include <qtpropertymanager.h>
Public Slots
void setValue (QtProperty *property, bool val)
Signals
void valueChanged (QtProperty *property, bool val)
Public Member Functions
QtBoolPropertyManager (QObject *parent=0)
~QtBoolPropertyManager ()
bool value (const QtProperty *property) const
Protected Member Functions
QString valueText (const QtProperty *property) const
QIcon valueIcon (const QtProperty *property) const
virtual void initializeProperty (QtProperty *property)
virtual void uninitializeProperty (QtProperty *property)
Detailed Description
The property's value can be retrieved using the value() function, and set using the setValue() slot.
In addition, QtBoolPropertyManager provides the valueChanged() signal which is emitted whenever a property created by this manager changes.
See also
QtAbstractPropertyManager, QtCheckBoxFactory
Constructor & Destructor Documentation
QtBoolPropertyManager::QtBoolPropertyManager (QObject * parent = 0)
Creates a manager with the given parent.
QtBoolPropertyManager::~QtBoolPropertyManager ()
Destroys this manager, and all the properties it has created.
References QtAbstractPropertyManager::clear().
Member Function Documentation
void QtBoolPropertyManager::initializeProperty (QtProperty * property) [protected], [virtual]
Implements QtAbstractPropertyManager .
References QtBoolPropertyManagerPrivate::m_values.
void QtBoolPropertyManager::setValue (QtProperty * property, bool value) [slot]
Sets the value of the given property to value.
See also
value()
References QtBoolPropertyManagerPrivate::m_values, QtAbstractPropertyManager::propertyChanged(), and valueChanged().
Referenced by QtFontPropertyManager::initializeProperty(), QtFlagPropertyManager::setValue(), QtFontPropertyManager::setValue(), and QtCheckBoxFactoryPrivate::slotSetValue().
void QtBoolPropertyManager::uninitializeProperty (QtProperty * property) [protected], [virtual]
Reimplemented from QtAbstractPropertyManager .
References QtBoolPropertyManagerPrivate::m_values.
bool QtBoolPropertyManager::value (const QtProperty * property) const
Returns the given property's value.
If the given property is not managed by this manager, this function returns false.
See also
setValue()
References QtBoolPropertyManagerPrivate::m_values.
Referenced by QtCheckBoxFactory::createEditor().
void QtBoolPropertyManager::valueChanged (QtProperty * property, bool value) [signal]
This signal is emitted whenever a property created by this manager changes its value, passing a pointer to the property and the new value as parameters.
Referenced by setValue().
QIcon QtBoolPropertyManager::valueIcon (const QtProperty * property) const [protected], [virtual]
Reimplemented from QtAbstractPropertyManager .
References drawCheckBox(), and QtBoolPropertyManagerPrivate::m_values.
QString QtBoolPropertyManager::valueText (const QtProperty * property) const [protected], [virtual]
Reimplemented from QtAbstractPropertyManager .
References QtBoolPropertyManagerPrivate::m_values.
The documentation for this class was generated from the following files:
qtpropertymanager.h
qtpropertymanager.cpp