PlotSceneWidget Class Reference
#include <plotscenewidget.h>
Public Types
enum Axis {
 xBottom,
 yLeft,
 xTop,
 yRight,
 User = 100
 }
Public Slots
void setXScaleEnabled (bool en)
void setYScaleEnabled (bool en)
void setScaleSceneOnResizeEnabled (bool en)
Changes the scaleSceneOnResizeEnabled property value.
void setMouseZoomEnabled (bool en)
Enables the zoom with the mouse, when the Ctrl key and the left mouse button are pressed.
bool scaleSceneOnResizeEnabled () const
returns the boolean value of the scaleSceneOnResizeEnabled property.
void setSceneRectToWidgetGeometry (bool en)
This property sets the scene rect of the view equal to the widget geometry.
void setScaleSceneOnMouseScroll (bool en)
enable or disable the scene scaling feature when the wheel mouse is scrolled
void setDontSavePainterState (bool dont)
void setDontAdjustForAntialiasing (bool dont)
void setSmoothPixmapTransform (bool enable)
void setCacheBackground (bool cache)
void setModifiedPaintEvent (bool mod)
void resetTransformMatrix ()
void setManualSceneUpdate (bool manual)
This is an important optimization that acts on the QGraphicsView::ViewportUpdateMode that comes into relevance when you have several items that must be fastly drawn.
void setRefreshPeriod (int period)
sets the refresh period of the internal timer used to refresh the scene when manualSceneUpdate is turned on.
void executePropertyDialog ()
virtual void appendData (const QString &curveName, double x, double y)
virtual void appendData (const QString &curveName, const QVector< double > &xData, const QVector< double > &yData)
virtual void setData (const QString &curveName, const QVector< double > &xData, const QVector< double > &yData)
virtual void setData (const QString &curveName, const QVector< double > &yData)
void setPlotAreaTopLeftPercentage (double widthPercent, double heightPercent)
sets the top left point of the rectangle occupied by the plot inside the scene.
void setPlotAreaPercentage (double widthPercent, double heightPercent)
set the plot area rectangle size, in terms of percentage with respect to the scene rect area.
void setPlotAreaPercentageWidth (double widthPercent)
the same as setPlotAreaTopLeftPercentage, sets only width
void setPlotAreaPercentageHeight (double heightPercent)
the same as setPlotAreaTopLeftPercentage, sets only height
void setPlotAreaTopLeftXPercentage (double xPercent)
the same as setPlotAreaTopLeftPercentage, sets only top left x coordinate percentage
void setPlotAreaTopLeftYPercentage (double yPercent)
the same as setPlotAreaTopLeftPercentage, sets only top left y coordinate percentage
void setOriginPosPercentage (ScaleItem *scaleIt, double percent)
sets the position of the origin of the given scale item to the specified percent value, in percentage terms from 0 to 1.0
void setDefaultXAxisOriginPosPercentage (double percent)
Changes the position of the default x axis.
void setDefaultYAxisOriginPosPercentage (double percent)
Changes the position of the default y axis.
void setPainterAntiAlias (bool en)
sets the QGraphicsItem flag QPainter::Antialiasing on the view
void setPainterHQGLAntiAlias (bool en)
sets the QGraphicsItem flag QPainter::HighQualityAntialiasing on the view
void setScrollBarsEnabled (bool en)
void setLegendVisible (bool visible)
void setXAxisLowerBound (double xlb)
Shortcut to access the x axis and set the bound.
void setYAxisLowerBound (double ylb)
Shortcut to access the y axis and set the bound.
void setXAxisUpperBound (double xub)
Shortcut to access the x axis and set the bound.
void setYAxisUpperBound (double yub)
Shortcut to access the y axis and set the bound.
void setXAxisAutoscaleEnabled (bool en)
Shortcut to enable/disable the autoscale on the x axis.
void setYAxisAutoscaleEnabled (bool en)
Shortcut to enable/disable the autoscale on the x axis.
void setXAxisLabelsOutsideCanvas (bool outside)
Tells the plot to draw the axis labels outside the area where the curves are drawn.
void setYAxisLabelsOutsideCanvas (bool outside)
Tells the plot to draw the axis labels outside the area where the curves are drawn.
void setBackgroundColor (const QColor &) const
void scale (qreal sx, qreal sy)
void fitIn ()
void saveData ()
virtual QMenu * createContextMenu ()
Signals
void clicked (const QPointF &pos)
the plot was clicked at the position pos
void plotRectChanged (const QRectF &newRect)
The plot rectangle has changed.
void plotAreaChanged (const QSizeF &newSize)
notifies that the plot area has changed
void curveAboutToBeRemoved (SceneCurve *c)
this signal is emitted when a curve is removed from the plot
void curveAdded (SceneCurve *curve)
This signal notifies that the curve has been added to the plot.
void viewScaleChanged (double dx, double dy)
Notifies that the scale factors have changed.
void viewScaleChanged (double scale)
Notifies that the scale factors have changed. The operations performed by the PlotSceneWidget and its zoomer scale the view by the same factor in order to keep the aspect ratio.
Public Member Functions
 PlotSceneWidget (QWidget *parent=0, bool useOpenGl=false)
PlotSceneWidget is a QGraphicsView with a QGraphicsScene where QGraphicsItem items can be placed and displayed. In particular, PlotSceneWidget is a plot where curves can be drawn.
 PlotSceneWidget (QWidget *parent, bool initDefaultAxes, bool useOpenGl=false)
bool xScaleEnabled () const
bool yScaleEnabled () const
bool scaleSceneOnMouseScroll () const
bool sceneRectToWidgetGeometry () const
bool mouseZoomEnabled () const
returns the mouse zoom enable state
bool modifiedPaintEvent () const
bool smoothPixmapTransform () const
bool legendVisible () const
virtual void boundsChanged ()
void installPlotGeometryChangeListener (PlotGeometryEventListener *l)
void removePlotGeometryChangeListener (PlotGeometryEventListener *l)
void installMouseEventListener (MouseEventListener *l)
void removeMouseEventListener (MouseEventListener *l)
QColor backgroundColor () const
QList< Point * > getPoints () const
 ScaleItem * xScaleItem () const
shortcut to retrieve the x scale item (ScaleItem::xBottom) which is always created by default.
 ScaleItem * yScaleItem () const
shortcut to retrieve the y scale item (ScaleItem::yLeft) which is always created by default.
 ScaleItem * scaleItem (ScaleItem::Id id) const
returns the ScaleItem associated to the argument.
 ScaleItem * associatedAxis (ScaleItem::Id otherAxisId) const
QPair< double, double > associatedOriginPosPercentage (ScaleItem::Id xAxisId, ScaleItem::Id yAxisId, bool *ok) const
void addConfigurableObjects (const QString &title, QObject *object)
add an object which is configurable through its Qt properties.
void removeConfigurableObjects (const QString &title)
removes an object which was previously added with addConfigurableObjects with the given title.
void setSettingsKey (const QString &key)
a key to be used to retrieve the settings for the plot.
QString settingsKey () const
void loadConfigurationProperties ()
QPointF invTransform (const QPointF &pSceneCoord)
transforms a QPointF in scene coordinates into a QPointF containing the x and y values in the x and y axis scale coordinates.
double invTransform (const double xCoord, ScaleItem * scaleItem) const
transforms a double in scene coordinates into a double in scaleItem coordinates
double transform (const double x, ScaleItem * scaleItem) const
transforms a value on the scaleItem axis in axis coordinates into a value in scene coordinates inside the plot rect.
QPointF invTransform (const QPointF &pSceneCoord, ScaleItem * xScaleItem, ScaleItem * yScaleItem) const
void addCurve (SceneCurve *curve)
 SceneCurve * addCurve (const QString &name)
Creates a new curve with the given name and automatically associates it to the x bottom axis and y left axis.
 SceneCurve * addCurve (const QString &name, ScaleItem * xScaleItem, ScaleItem * yScaleItem)
Creates a new curve with the given name and attachs the curve to the specified x and y ScaleItems (axes).
 SceneCurve * findCurve (const QString &name)
finds the curve with the provided name
QList< SceneCurve * > getCurves () const
returns a list of all curves belonging to this plot
 SceneCurve * addLineCurve (const QString &name, ScaleItem * xScaleItem=NULL, ScaleItem * yScaleItem=NULL)
adds and configures a curve with a LinePainter
void curveAboutToBeDestroyed (const QString &name, bool deleteCurve=true)
QList< SceneCurve * > curvesForAxes (ScaleItem::Id axisId, ScaleItem::Orientation orientation) const
returns the list of curves that are attached to the provided axisId with Orientation orientation
 AxesManager * axesManager () const
returns the reference to the AxesManager.
QRectF plotRect () const
double plotAreaPercentageWidth () const
double plotAreaPercentageHeight () const
double plotAreaTopLeftXPercentage () const
double plotAreaTopLeftYPercentage () const
double originPosPercentage (ScaleItem *scaleIt) const
returns the origin position (in percentage between 0.0 and 1.0) of the scale item passed as parameter
double defaultXAxisOriginPosPercentage () const
returns the origin position (in percentage between 0.0 and 1.0) of the default x scale item (the one that the PlotSceneWidget always creates automatically)
double defaultYAxisOriginPosPercentage () const
returns the origin position (in percentage between 0.0 and 1.0) of the default y scale item (the one that the PlotSceneWidget always creates automatically)
bool painterAntiAlias () const
bool painterHQGLAntiAlias () const
bool dontSavePainterState () const
bool dontAdjustForAntialiasing () const
bool cacheBackground () const
double xAxisLowerBound () const
shortcut to get the axis bound from the xScaleItem()
double yAxisLowerBound () const
shortcut to get the axis bound from the yScaleItem()
double xAxisUpperBound () const
shortcut to get the axis bound from the xScaleItem()
double yAxisUpperBound () const
shortcut to get the axis bound from the yScaleItem()
bool xAxisAutoscaleEnabled () const
shortcut to get the axis autoscale mode from the xScaleItem()
bool yAxisAutoscaleEnabled () const
shortcut to get the axis autoscale mode from the yScaleItem()
bool xAxisLabelsOutsideCanvas () const
Shortcut for ScaleItem::axisLabelsOutsideCanvas.
bool yAxisLabelsOutsideCanvas () const
Shortcut for ScaleItem::axisLabelsOutsideCanvas.
int refreshPeriod () const
returns the refresh period of the internal timer used to refresh the scene when manualSceneUpdate is turned on.
bool manualSceneUpdate () const
returns the value of the manualSceneUpdate property
QList< SceneCurve * > getClosest (QPointF &closestPos, int *closestIndex, const QPointF &viewPos)
retrieve the list of curves that are closest to the viewPos point in view coordinates. The closestPos point is the point, in scene coordinates, closest to the viewPos and belonging to the closest curves. The closestIndex is the x axis index coordinate of the closest point.
bool inZoom () const
returns the zoom state
int zoomLevel () const
returns the zoom level of the zoomer.
bool scrollBarsEnabled () const
 LegendItem * legendItem () const
 QGraphicsZoomer * zoomer () const
 ScaleItem * addAxis (ScaleItem::Orientation o, ScaleItem::Id id, ScaleItem * associatedAxis)
void removeAxis (ScaleItem::Id id)
void clearAxes (bool all=false, ScaleItem::Orientation o= ScaleItem::Vertical)
Removes the axes from the plot.
void clear ()
Protected Slots
void curveAboutToBeDestroyed (QObject *crv)
this is a protected slot connected to the destroyed() signal of a SceneCurve
void removeAxis (QObject *axis)
void sceneRectChanged (const QRectF &)
void hScrollBarValueChanged (int value)
notifies PlotChangeListeners that the scrollbar has changed its value
void vScrollBarValueChanged (int value)
notifies PlotChangeListeners that the scrollbar has changed its value
Protected Member Functions
void showEvent (QShowEvent * event)
initializes the scene rect according to the viewport rect which is correctly initialized after the show event.
void mouseMoveEvent (QMouseEvent * event)
void wheelEvent (QWheelEvent * event)
void contextMenuEvent (QContextMenuEvent * event)
void mousePressEvent (QMouseEvent * event)
void mouseReleaseEvent (QMouseEvent * event)
void mouseDoubleClickEvent (QMouseEvent *)
void mSwitchAxesCurvesForeground ()
void recalculatePlotRect ()
Recalculates the plot rect and caches it.
void resizeEvent (QResizeEvent * event)
virtual bool event (QEvent *event)
void notifyPlotAreaChanged ()
void paintEvent (QPaintEvent * event)
Properties
bool xScaleEnabled
bool yScaleEnabled
bool mouseZoomEnabled
bool scaleSceneOnResizeEnabled
double plotAreaPercentageWidth
double plotAreaPercentageHeight
double plotAreaTopLeftXPercentage
double plotAreaTopLeftYPercentage
bool painterAntiAlias
bool painterHQGLAntiAlias
bool smoothPixmapTransform
bool dontSavePainterState
bool dontAdjustForAntialiasing
bool cacheBackground
bool manualSceneUpdate
int refreshPeriod
double defaultXAxisOriginPosPercentage
double defaultYAxisOriginPosPercentage
bool modifiedPaintEvent
bool scrollBarsEnabled
bool legendVisible
QColor backgroundColor
Member Enumeration Documentation
Axis
enum PlotSceneWidget::Axis
Enumerator
xBottom
yLeft
xTop
yRight
User
Constructor & Destructor Documentation
PlotSceneWidget() [1/2]
PlotSceneWidget::PlotSceneWidget (QWidget * parent = 0, bool useOpenGl = false) [explicit]
PlotSceneWidget
PlotSceneWidget is a QGraphicsView with a QGraphicsScene where QGraphicsItem items can be placed and displayed. In particular, PlotSceneWidget is a plot where curves can be drawn.
Axes
A PlotSceneWidget has by default a couple of axes, the x and y axes, and their origin is by default in the center of the scene. If you want to change the axes position, see
PlotSceneWidget::setOriginPosPercentage
PlotSceneWidget::setDefaultXAxisOriginPosPercentage and
PlotSceneWidget::setDefaultYAxisOriginPosPercentage.
Reducing the plot area inside the scene.
It is possible to reduce the area occupied by the plot by means of the plotAreaPercentageWidth, plotAreaPercentageHeight, plotAreaTopLeftXPercentage, plotAreaTopLeftYPercentage properties.
Curves
Each curve is represented by a SceneCurve. A SceneCurve contains the data of the curve. The SceneCurve is not responsible for drawing itself. Each SceneCurve must be given a name and added to the plot by means of PlotSceneWidget::addCurve
 The painting takes place by a CurveItem object instantiated by passing a SceneCurve to its constructor and by an implementation of an ItemPainterInterface which must be installed on a CurveItem. Once a CurveItem is constructed with a SceneCurve, the SceneCurve takes the ownership of the CurveItem, destroying it when the curve is destroyed. Once an ItemPainterInterface implementation instance is installed on a CurveItem, the CurveItem takes the ownership of the item painter destroying it on CurveItem destruction.
LinePainter is an example of an ItemPainterInterface implementation. DotsPainter is another example.
Example. Adding a curve to a PlotSceneWidget
SceneCurve *curve = myPlotSceneWidget->addCurve("Curve Name");
//
// if you want no more than bufsize points on the curve
int bufsize = 1000;
curve->setBufferSize(bufsize);
// Create the effective curve painter!
// Just pass the curve in the constructor
// The SceneCurve curve takes the ownership of curveItem, i.e. CurveItem
// will be destroyed when removeCurve is called on PlotSceneWidget (or,
// equivalently, on SceneCurve destruction)
//
CurveItem *curveItem = new CurveItem(curve);
// add the CurveItem to the Graphics Scene
scene()->addItem(curveItem);
//
// The CurveItem is aimed at calculating the transformations between the curve data
// coordinates and the PlotSceneWidget pixel coordinates.
// The CurveItem delegates the painting to specialized painters, which can be
// line painers, dot painters, histogram painters, and so on.
//
// Let's create a LinePainter to connect points on the plot with lines:
// Pass the curve item as parameter in the LinePainter constructor
// The curveItem takes the ownership of the line painter.
//
LinePainter *linePainter = new LinePainter(curveItem);
linePainter->setLineColor(Qt::green); // colour the lines
// setData on the curve
QVector<double> xData, yData;
// fill the vectors xData and yData as you like, then....
// ...
//
curve->setData(xData, yData);
Why ownership of CurveItem and LinePainter is passed to SceneCurve and CurveItem respectively?
This particular implementation allows you to create the CurveItem and one or more LinePainter objects and forget about their memory management. It is strongly suggested to use addCurve and removeCurve(const QString&) methods to add and remove curves to and from the PlotSceneWidget
See also
addCurve
removeCurve(const QString&) This aspect must be taken into account when your application allows curve deletion at runtime. In other cases, you never want to worry about deleting the objects you create and attach to your plot to add curves or decorate them. This is accomplished by Qt QObject children deletion and careful design of parent-children hierarchy in QGraphicsPlot library.
Some more details about item deletion.
CurveItem is a QGraphicsObject and when it's added to a QGraphicsScene through QGraphicsScene::addItem the ownership is taken by the QGraphicsScene. This means that every CurveItem is deleted on scene deletion, i.e. on PlotSceneWidget deletion, since the plot scene is a child of PlotSceneWidget.
SceneCurve is created by PlotSceneWidget::addCurve as a child of PlotSceneWidget. Each curve is thus deleted on PlotSceneWidget destruction.
LinePainter, as in the example above, must be constructed by passing a CurveItem in its constructor. All ItemPainterInterface implementations, such as LinePainter, must inherit from QObject and the parent must be a CurveItem, as you can see in the LinePainter implementation. In this way, on CurveItem deletion, the LinePainter is automatically deleted, as a child of CurveItem.
Curve removal.
You can remove a SceneCurve at runtime by calling PlotSceneWidget::removeCurve. This method will delete the associated CurveItem (and all its painters, such as LinePainter, for example) and then delete the SceneCurve itself.
See also
removeCurve
addCurve
Using external scales
External scales can be used and they can be useful when the plot is zoomed and the plot internal axes fall out of the zoom area.
See also
ExternalScaleWidget
PlotSceneWidget() [2/2]
PlotSceneWidget::PlotSceneWidget (QWidget * parent, bool initDefaultAxes, bool useOpenGl = false) [explicit]
Member Function Documentation
addAxis()
 ScaleItem * PlotSceneWidget::addAxis (ScaleItem::Orientation o, ScaleItem::Id id, ScaleItem * associatedAxis)
References associatedAxis(), ScaleItem::Horizontal, installPlotGeometryChangeListener(), ScaleItem::orientation(), perr, removeAxis(), scaleItem(), ScaleItem::Vertical, AxisCouple::xAxis, and AxisCouple::yAxis.
addConfigurableObjects()
void PlotSceneWidget::addConfigurableObjects (const QString & title, QObject * object)
Parameters
title in the configuration dialog of the plot the object properties will appear under a tab widget with title as the title page.
object the object whose properties are selected and configurable. May be a widget for example, or a graphics object item.
See also
removeConfigurableObjects
addCurve() [1/3]
 SceneCurve * PlotSceneWidget::addCurve (const QString & name)
Returns
the new curve just created. You can configure its properties using this return value.
Parameters
name the name with which the curve is marked and identified.
References addCurve(), xScaleItem(), and yScaleItem().
addCurve() [2/3]
 SceneCurve * PlotSceneWidget::addCurve (const QString & name, ScaleItem * xScaleItem, ScaleItem * yScaleItem)
Use this method instead of the one provided above to attach the curve to a couple of axes different from the x bottom and y left default axes.
References curveAboutToBeDestroyed(), curveAdded(), ScaleItem::installAxisChangeListener(), perr, xScaleItem(), and yScaleItem().
addCurve() [3/3]
void PlotSceneWidget::addCurve (SceneCurve * curve)
References curveAboutToBeDestroyed(), curveAdded(), SceneCurve::getXAxis(), SceneCurve::getYAxis(), ScaleItem::installAxisChangeListener(), and SceneCurve::name().
Referenced by addCurve().
addLineCurve()
 SceneCurve * PlotSceneWidget::addLineCurve (const QString & name, ScaleItem * xScaleI = NULL, ScaleItem * yScaleI = NULL)
This methods adds a new curve to the plot. The curve is represented in the plot by lines joining its points.
This method is equivalent to the calls to
SceneCurve *c = graphicsPlot->addCurve(name);
CurveItem *curveItem = new CurveItem(c);
graphicsPlot->scene()->addItem(curveItem);
c->installCurveChangeListener(curveItem);
LinePainter *lp = new LinePainter(curveItem);
 The colour is automatically chosen.
References curveAboutToBeDestroyed(), curveAdded(), ColorPalette::getColor(), ScaleItem::installAxisChangeListener(), SceneCurve::installCurveChangeListener(), LinePainter::setLineColor(), xScaleItem(), and yScaleItem().
appendData [1/2]
void PlotSceneWidget::appendData (const QString & curveName, const QVector< double > & xData, const QVector< double > & yData) [virtual], [slot]
References SceneCurve::addPoints(), perr, and qstoc.
appendData [2/2]
void PlotSceneWidget::appendData (const QString & curveName, double x, double y) [virtual], [slot]
References SceneCurve::addPoint(), perr, and qstoc.
associatedAxis()
 ScaleItem * PlotSceneWidget::associatedAxis (ScaleItem::Id otherAxisId) const
Referenced by addAxis().
associatedOriginPosPercentage()
QPair< double, double > PlotSceneWidget::associatedOriginPosPercentage (ScaleItem::Id xAxisId, ScaleItem::Id yAxisId, bool * ok) const
axesManager()
 AxesManager * PlotSceneWidget::axesManager () const
See also
AxesManager
The AxesManager class manages the axes in the plot and their origins.
backgroundColor()
QColor PlotSceneWidget::backgroundColor () const
boundsChanged()
void PlotSceneWidget::boundsChanged () [virtual]
References SceneCurve::invalidateCache(), ScaleItem::redraw(), and scaleItem().
Referenced by setPlotAreaPercentage(), setPlotAreaTopLeftPercentage(), setXScaleEnabled(), setYScaleEnabled(), and showEvent().
cacheBackground()
bool PlotSceneWidget::cacheBackground () const
clear()
void PlotSceneWidget::clear ()
References clearAxes(), getCurves(), and ScaleItem::Vertical.
clearAxes()
void PlotSceneWidget::clearAxes (bool all = false, ScaleItem::Orientation o = ScaleItem::Vertical)
Parameters
all true: all axes (horizontal and vertical) are removed
all false: only the axes with the specified orientation are removed
Referenced by clear().
clicked
void PlotSceneWidget::clicked (const QPointF & pos) [signal]
Parameters
pos the point where the click took place.
Referenced by mouseReleaseEvent().
contextMenuEvent()
void PlotSceneWidget::contextMenuEvent (QContextMenuEvent * event) [protected]
References createContextMenu().
createContextMenu
QMenu * PlotSceneWidget::createContextMenu () [virtual], [slot]
References executePropertyDialog(), fitIn(), resetTransformMatrix(), and saveData().
Referenced by contextMenuEvent().
curveAboutToBeDestroyed() [1/2]
void PlotSceneWidget::curveAboutToBeDestroyed (const QString & name, bool deleteCurve = true)
References curveAboutToBeRemoved(), SceneCurve::curveItem(), SceneCurve::getXAxis(), SceneCurve::getYAxis(), perr, qstoc, and ScaleItem::removeAxisChangeListener().
Referenced by addCurve(), addLineCurve(), and curveAboutToBeDestroyed().
curveAboutToBeDestroyed [2/2]
void PlotSceneWidget::curveAboutToBeDestroyed (QObject * crv) [protected], [slot]
This method is involved when the users calls delete on a SceneCurve instead of using the removeCurve(const QString& name) method of the PlotSceneWidget, which is the recommended way to remove a curve from the plot.
References curveAboutToBeDestroyed(), and SceneCurve::name().
curveAboutToBeRemoved
void PlotSceneWidget::curveAboutToBeRemoved (SceneCurve * c) [signal]
Any class interested in knowing when a curve is removed (e.g. MarkerItem) must be connected to this signal, which is emitted right before the SceneCurve passed as parameter is removed.
Parameters
curve a reference to the curve being removed
Note
When this signal is emitted, the curve axes have not been already detached (they are available) and also the associated CurveItem is still available.
See also
CurveItem
ScaleItem
CurveAddded
Referenced by curveAboutToBeDestroyed().
curveAdded
void PlotSceneWidget::curveAdded (SceneCurve * curve) [signal]
Parameters
curve the new curve
Note
The AxisChangeListener on the x and y axes has been installed on the plot when this signal is emitted. The curve has already been inserted in the internal list of curves. This means it is available through getCurves and findCurve. This does not mean that a CurveItem has already been installed on the curve. Always check for curveItem() returning NULL. If you use addLineCurve, then the curve has a CurveItem already associated when the signal is emitted.
Referenced by addCurve(), and addLineCurve().
curvesForAxes()
QList< SceneCurve * > PlotSceneWidget::curvesForAxes (ScaleItem::Id axisId, ScaleItem::Orientation orientation) const
References SceneCurve::associatedXAxisId(), SceneCurve::associatedYAxisId(), and ScaleItem::Horizontal.
defaultXAxisOriginPosPercentage()
double PlotSceneWidget::defaultXAxisOriginPosPercentage () const
Axes are placed with a position with respect to each other defined by this value, expressed in percentage from 0.0 to 1.0. By default, the axes have both 0.5 as position percentage value, meaning that they intersect in the middle of each other.
See also
originPosPercentage
defaultYAxisOriginPosPercentage
References originPosPercentage(), and xScaleItem().
defaultYAxisOriginPosPercentage()
double PlotSceneWidget::defaultYAxisOriginPosPercentage () const
See also
defaultXAxisOriginPosPercentage
originPosPercentage
References originPosPercentage(), and yScaleItem().
dontAdjustForAntialiasing()
bool PlotSceneWidget::dontAdjustForAntialiasing () const
dontSavePainterState()
bool PlotSceneWidget::dontSavePainterState () const
event()
bool PlotSceneWidget::event (QEvent * event) [protected], [virtual]
Referenced by mouseDoubleClickEvent(), mouseMoveEvent(), mousePressEvent(), mouseReleaseEvent(), paintEvent(), resizeEvent(), and showEvent().
executePropertyDialog
void PlotSceneWidget::executePropertyDialog () [slot]
References PropertyDialog::configureTabs(), PropertyDialog::setSettingsKey(), and PropertyDialog::show().
Referenced by createContextMenu().
findCurve()
 SceneCurve * PlotSceneWidget::findCurve (const QString & name)
Returns
the curve with the given name or NULL if not present
Parameters
name the name to look for
fitIn
void PlotSceneWidget::fitIn () [slot]
References notifyPlotAreaChanged().
Referenced by createContextMenu().
getClosest()
QList< SceneCurve * > PlotSceneWidget::getClosest (QPointF & closestPos, int * closestIndex, const QPointF & viewPos)
The returned list contains more than one curve if they overlap in the same point. Otherwise, the list will contain at most one curve.
Parameters
closestPos the position of the closest point, in scene coordinates.
viewPos the position, in view coordinates, whose curve's closest point must be searched
closestIndex the index with which you can retrieve the data in the data vector of the closest curve(s).
An example can be found in the MarkerItem::mouseClickEvent method
 If no closest curve is found, the returned list is empty, the closestPos is a null point and the closest index is set to -1.
closestPos is passed by reference closestIndex is a pointer to an integer that will point to the index of the data vector associated to the closest point in the closest curve viewPos is the position in view coordinates, it may represent, as in MarkerItem::mouseClickEvent, the point where a click event has taken place in the PlotSceneWidget.
See also
MarkerItem::mouseClickEvent
References SceneCurve::data(), SceneCurve::dataSize(), SceneCurve::points(), Data::size(), Data::xData, and Data::yData.
Referenced by MarkerItem::mouseClickEvent().
getCurves()
QList< SceneCurve * > PlotSceneWidget::getCurves () const
Referenced by clear(), MarkerItem::mouseClickEvent(), and saveData().
getPoints()
QList< Point *> PlotSceneWidget::getPoints () const
hScrollBarValueChanged
void PlotSceneWidget::hScrollBarValueChanged (int value) [protected], [slot]
Parameters
value the value of the scrollbar as provided by the horizontalScrollBar
References PlotGeometryEventListener::scrollBarChanged().
installMouseEventListener()
void PlotSceneWidget::installMouseEventListener (MouseEventListener * l)
installPlotGeometryChangeListener()
void PlotSceneWidget::installPlotGeometryChangeListener (PlotGeometryEventListener * l)
Referenced by addAxis().
invTransform() [1/3]
double PlotSceneWidget::invTransform (const double pt, ScaleItem * scaleItem) const
Parameters
pt the x or y coordinate of the point you want to transform, in scene coordinates
scaleItem the ScaleItem on which to calculate the transformed value.
Returns
the value of the transformed point, in the scaleItem coordinates.
See also
invTransform(const double pt, ScaleItem* scaleItem) const
transform
References ScaleItem::canvasHeight, ScaleItem::canvasWidth, ScaleItem::Horizontal, ScaleItem::lowerBound, ScaleItem::orientation(), perr, scaleItem(), ScaleItem::upperBound, and ScaleItem::Vertical.
invTransform() [2/3]
QPointF PlotSceneWidget::invTransform (const QPointF & pSceneCoord)
This method operates on the default x and y scale items, the ones returned by xScaleItem and yScaleItem. If you want to transform according to other scale items use the invTransform(const double pt, ScaleItem* scaleItem) method instead.
See also
invTransform(const double pt, ScaleItem* scaleItem) const
transform
References perr, xScaleItem(), and yScaleItem().
Referenced by QGraphicsZoomer::zoom().
invTransform() [3/3]
QPointF PlotSceneWidget::invTransform (const QPointF & pSceneCoord, ScaleItem * xScaleItem, ScaleItem * yScaleItem) const
References ScaleItem::canvasHeight, ScaleItem::canvasWidth, ScaleItem::lowerBound, perr, ScaleItem::upperBound, xScaleItem(), and yScaleItem().
inZoom()
bool PlotSceneWidget::inZoom () const
Returns
true the plot is being zoomed
false the plot is not in zoom state
The plot enters the zoom state when the user selects a rectangular area with the left mouse button together with the Maiusc key.
Note
The plot is not in zoom state when the user scrolls the mouse wheel to scale the view.
Referenced by resizeEvent().
legendItem()
 LegendItem * PlotSceneWidget::legendItem () const
legendVisible()
bool PlotSceneWidget::legendVisible () const
loadConfigurationProperties()
void PlotSceneWidget::loadConfigurationProperties ()
References SettingsLoader::loadConfiguration().
manualSceneUpdate()
bool PlotSceneWidget::manualSceneUpdate () const
See also
setManualSceneUpdate
setRefreshPeriod
modifiedPaintEvent()
bool PlotSceneWidget::modifiedPaintEvent () const
mouseDoubleClickEvent()
void PlotSceneWidget::mouseDoubleClickEvent (QMouseEvent * event) [protected]
References event(), and MouseEventListener::mouseDoubleClickEvent().
mouseMoveEvent()
void PlotSceneWidget::mouseMoveEvent (QMouseEvent * event) [protected]
d_ptr->mouseMovingPoint = mapToScene(event->pos());
References event(), and MouseEventListener::mouseMoveEvent().
mousePressEvent()
void PlotSceneWidget::mousePressEvent (QMouseEvent * event) [protected]
References event(), MouseEventListener::mousePressEvent(), and mSwitchAxesCurvesForeground().
mouseReleaseEvent()
void PlotSceneWidget::mouseReleaseEvent (QMouseEvent * event) [protected]
References clicked(), event(), MouseEventListener::mouseClickEvent(), and MouseEventListener::mouseReleaseEvent().
mouseZoomEnabled()
bool PlotSceneWidget::mouseZoomEnabled () const
Returns
true the user is able to zoom with the mouse (while the Control key is simultaneously pressed.
false the mouse zoomer is disabled
See also
setMouseZoomEnabled
mSwitchAxesCurvesForeground()
void PlotSceneWidget::mSwitchAxesCurvesForeground () [protected]
Referenced by mousePressEvent().
notifyPlotAreaChanged()
void PlotSceneWidget::notifyPlotAreaChanged () [protected]
References PlotGeometryEventListener::plotAreaChanged(), plotAreaChanged(), and viewScaleChanged().
Referenced by fitIn(), recalculatePlotRect(), resetTransformMatrix(), scale(), and showEvent().
originPosPercentage()
double PlotSceneWidget::originPosPercentage (ScaleItem * scaleIt) const
Axes are placed with a position with respect to each other defined by this value, expressed in percentage from 0.0 to 1.0. By default, the axes have both 0.5 as position percentage value, meaning that they intersect in the middle of each other.
References ScaleItem::Horizontal, ScaleItem::orientation(), ScaleItem::Vertical, AxisCouple::xAxis, AxisCouple::xOriginPosPercentage, AxisCouple::yAxis, and AxisCouple::yOriginPosPercentage.
Referenced by defaultXAxisOriginPosPercentage(), and defaultYAxisOriginPosPercentage().
painterAntiAlias()
bool PlotSceneWidget::painterAntiAlias () const
painterHQGLAntiAlias()
bool PlotSceneWidget::painterHQGLAntiAlias () const
paintEvent()
void PlotSceneWidget::paintEvent (QPaintEvent * event) [protected]
References event().
plotAreaChanged
void PlotSceneWidget::plotAreaChanged (const QSizeF & newSize) [signal]
Parameters
newSize the new size of the plot area
Note
newSize takes into account the transform() being applied to the view. The area is calculated by scaling the plotRect property according to the m11 and m22 elements of the transform matrix.
Referenced by notifyPlotAreaChanged().
plotAreaPercentageHeight()
double PlotSceneWidget::plotAreaPercentageHeight () const
plotAreaPercentageWidth()
double PlotSceneWidget::plotAreaPercentageWidth () const
plotAreaTopLeftXPercentage()
double PlotSceneWidget::plotAreaTopLeftXPercentage () const
plotAreaTopLeftYPercentage()
double PlotSceneWidget::plotAreaTopLeftYPercentage () const
plotRect()
QRectF PlotSceneWidget::plotRect () const
Referenced by ScaleItem::ScaleItem(), Point::updatePosition(), Point::updateXPos(), Point::updateYPos(), Zoomer::zoom(), and Zoomer::Zoomer().
plotRectChanged
void PlotSceneWidget::plotRectChanged (const QRectF & newRect) [signal]
Parameters
newRect the new rectangle containing the plot.
Plot Rect property.
It takes into account the sceneRect adjusted with the plotAreaPercentageWidth, plotAreaTopLeftXPercentage, plotAreaPercentageHeight and plotAreaTopLeftYPercentage properties. For this, newRect does not always coincide with the scene rect.
Note
The rectangle does not take into account the transform being applied, if any. For that purpose, please see plotAreaChanged
See also
plotAreaChanged
Referenced by recalculatePlotRect().
recalculatePlotRect()
void PlotSceneWidget::recalculatePlotRect () [protected]
The cached plot rect must be recalculated when
the scene rect changes
the top left percent (x or y) values change
the width or height percentage of the plot area change
References notifyPlotAreaChanged(), plotRectChanged(), and PlotGeometryEventListener::plotRectChanged().
Referenced by sceneRectChanged(), setPlotAreaPercentage(), and setPlotAreaTopLeftPercentage().
refreshPeriod()
int PlotSceneWidget::refreshPeriod () const
Returns
the period in milliseconds of the internal timer. -1 is returned if the timer is not active, i.e. manualSceneUpdate is false
See also
setManualSceneUpdate
manualSceneUpdate
setRefreshPeriod
removeAxis [1/2]
void PlotSceneWidget::removeAxis (QObject * axis) [protected], [slot]
References removePlotGeometryChangeListener().
removeAxis() [2/2]
void PlotSceneWidget::removeAxis (ScaleItem::Id id)
Referenced by addAxis().
removeConfigurableObjects()
void PlotSceneWidget::removeConfigurableObjects (const QString & title)
Parameters
title in the configuration dialog of the plot the object properties will appear under a tab widget with title as the title page.
See also
addConfigurableObjects
removeMouseEventListener()
void PlotSceneWidget::removeMouseEventListener (MouseEventListener * l)
removePlotGeometryChangeListener()
void PlotSceneWidget::removePlotGeometryChangeListener (PlotGeometryEventListener * l)
Referenced by removeAxis().
resetTransformMatrix
void PlotSceneWidget::resetTransformMatrix () [slot]
References notifyPlotAreaChanged().
Referenced by createContextMenu().
resizeEvent()
void PlotSceneWidget::resizeEvent (QResizeEvent * event) [protected]
References event(), and inZoom().
saveData
void PlotSceneWidget::saveData () [slot]
References PlotSceneWidgetSaver::errorMessage(), PlotSceneWidgetSaver::fileName(), getCurves(), PlotSceneWidgetSaver::save(), ScaleItem::scaleLabelInterface(), ScaleLabelInterface::TimeScale, ScaleLabelInterface::type(), and xScaleItem().
Referenced by createContextMenu().
scale
void PlotSceneWidget::scale (qreal sx, qreal sy) [slot]
References notifyPlotAreaChanged().
Referenced by Zoomer::unzoom(), wheelEvent(), and Zoomer::zoom().
scaleItem()
 ScaleItem * PlotSceneWidget::scaleItem (ScaleItem::Id id) const
Returns
the ScaleItem associated to the id. The ScaleItem must have previously been programmatically added through the AxesManager.
Returns NULL if the ScaleItem with the provided Id was not added programmatically.
See also
AxesManager::addCouple
Referenced by addAxis(), boundsChanged(), LinePainter::draw(), invTransform(), and transform().
scaleSceneOnMouseScroll()
bool PlotSceneWidget::scaleSceneOnMouseScroll () const
scaleSceneOnResizeEnabled
bool PlotSceneWidget::scaleSceneOnResizeEnabled () const [slot]
If this property is set to true, then the plot is fitted on the view each time the PlotSceneWidget is resized. In other words, the scene rect is set to the viewport rect each time the widget is resized.
Note
The behaviour describe above stops being applied after that the user zooms on the plot or uses the mouse wheel to alter the view transform (scales the view). After a zoom or a manual scaling, the user manages the scaling of the view manually until next application restart.
Note
When part of a QTabWidget, it is recommended that this property is enabled, since the geometry of the QTabWidget children is not correctly provided on the first show event.
Note
By default, this property is enabled in releases following the 2.2.1.
See also
setScaleSceneOnResizeEnabled
sceneRectChanged
void PlotSceneWidget::sceneRectChanged (const QRectF &) [protected], [slot]
References recalculatePlotRect().
sceneRectToWidgetGeometry()
bool PlotSceneWidget::sceneRectToWidgetGeometry () const
scrollBarsEnabled()
bool PlotSceneWidget::scrollBarsEnabled () const
setBackgroundColor
void PlotSceneWidget::setBackgroundColor (const QColor & c) const [slot]
setCacheBackground
void PlotSceneWidget::setCacheBackground (bool cache) [slot]
setData [1/2]
void PlotSceneWidget::setData (const QString & curveName, const QVector< double > & xData, const QVector< double > & yData) [virtual], [slot]
References perr, qstoc, and SceneCurve::setData().
setData [2/2]
void PlotSceneWidget::setData (const QString & curveName, const QVector< double > & yData) [virtual], [slot]
References perr, qstoc, and SceneCurve::setData().
setDefaultXAxisOriginPosPercentage
void PlotSceneWidget::setDefaultXAxisOriginPosPercentage (double percent) [slot]
The default x axis is the axis that PlotSceneWidget always creates for you and places at the position 0.5 by default.
Parameters
percent the value of the new position for the default x axis
See also
setOriginPosPercentage
setDefaultYAxisOriginPosPercentage
If you added custom axes, then use the setOriginPosPercentage method instead.
References setOriginPosPercentage(), and xScaleItem().
setDefaultYAxisOriginPosPercentage
void PlotSceneWidget::setDefaultYAxisOriginPosPercentage (double percent) [slot]
The default y axis is the axis that PlotSceneWidget always creates for you and places at the position 0.5 by default.
Parameters
percent the value of the new position for the default y axis
See also
setOriginPosPercentage
setDefaultXAxisOriginPosPercentage
If you added custom axes, then use the setOriginPosPercentage method instead.
References setOriginPosPercentage(), and yScaleItem().
setDontAdjustForAntialiasing
void PlotSceneWidget::setDontAdjustForAntialiasing (bool dont) [slot]
setDontSavePainterState
void PlotSceneWidget::setDontSavePainterState (bool dont) [slot]
setLegendVisible
void PlotSceneWidget::setLegendVisible (bool visible) [slot]
setManualSceneUpdate
void PlotSceneWidget::setManualSceneUpdate (bool manual) [slot]
This property sets the ViewportUpdateMode to QGraphicsView::NoViewportUpdate meaning that QGraphicsView will never update its viewport when the scene changes; the user is expected to control all updates. This mode disables all (potentially slow) item visibility testing in QGraphicsView, and is suitable for scenes that either require a fixed frame rate, or where the viewport is otherwise updated externally.
Note
When you enable manual scene update, then you must call setRefreshPeriod with the desired refresh period of the scene, which typically must be equal to the fastest refresh rate needed by the fastest item.
 Calling setManualSceneUpdate with a false parameter, restores QGraphicsScene default ViewportUpdateMode, which is QGraphicsView::MinimalViewportUpdate, according to the Qt documentation.
Parameters
manual true update is managed by an internal timer. setRefreshPeriod must be called with a greater than zero value in order to activate the timer and have the scene refreshed with that interval.
manual false the update is set to QGraphicsView::MinimalViewportUpdate, the default Qt setting for the ViewportUpdateMode property. The internal refresh timer, if previously activated and started with a valid setRefreshPeriod method call is automatically stopped for you. The timer is not deleted, it is just stopped, so that a subsequent call to setManualSceneUpdate with a true parameter automatically restarts the timer with the timeout previously set with setRefreshPeriod. In this way, a second manual mode activation does not need another call to setRefreshPeriod. A call to setRefreshPeriod with zero or a negative value instead produces the destruction of the timer.
See also
setRefreshPeriod
refreshPeriod
manualSceneUpdate
setModifiedPaintEvent
void PlotSceneWidget::setModifiedPaintEvent (bool mod) [slot]
setMouseZoomEnabled
void PlotSceneWidget::setMouseZoomEnabled (bool en) [slot]
Parameters
en the Ctrl+Left mouse button zoomes the area drawn by the mouse
false the mouse zoomer is disabled.
See also
mouseZoomEnabled
setOriginPosPercentage
void PlotSceneWidget::setOriginPosPercentage (ScaleItem * scaleIt, double percent) [slot]
Parameters
scaleIt the scale item whose position you want to change
percent the value of the position, from 0 to 1.0.
If you did not add additional axes by yourself, then you might want to use the shortcut methods setDefaultXAxisOriginPosPercentage and setDefaultYAxisOriginPosPercentage.
See also
setDefaultXAxisOriginPosPercentage
setDefaultYAxisOriginPosPercentage
References ScaleItem::Horizontal, ScaleItem::orientation(), ScaleItem::updateLabelsCache(), and ScaleItem::Vertical.
Referenced by setDefaultXAxisOriginPosPercentage(), and setDefaultYAxisOriginPosPercentage().
setPainterAntiAlias
void PlotSceneWidget::setPainterAntiAlias (bool en) [slot]
Parameters
en true: anti alias painting enabled
en false: anti alias painting not enabled
The default is true. This might affect performance.
setPainterHQGLAntiAlias
void PlotSceneWidget::setPainterHQGLAntiAlias (bool en) [slot]
Parameters
en true: anti alias painting enabled
en false: anti alias painting not enabled
The default is QGraphicsView's default. This is an OpenGL-specific rendering hint indicating that the engine should use fragment programs and offscreen rendering for antialiasing.
setPlotAreaPercentage
void PlotSceneWidget::setPlotAreaPercentage (double widthPercent, double heightPercent) [slot]
Parameters
widthPercent a number between 0 and 1 representing the percentage of the scene rect width to be considered in order to calculate the width of the rectangular plot area.
In other words the plot area width will be equal to scene->sceneRect().width() * widthPercent
heightPercent a number between 0 and 1 with the same meaning of widthPercent, but referred to the scene rect height
See also
setPlotAreaSTopLeftPercentage
The default values are 1.0 for both arguments, so that the plot area coincides with the scene()->sceneRect() rectangle.
References boundsChanged(), perr, and recalculatePlotRect().
Referenced by setPlotAreaPercentageHeight(), and setPlotAreaPercentageWidth().
setPlotAreaPercentageHeight
void PlotSceneWidget::setPlotAreaPercentageHeight (double heightPercent) [slot]
References setPlotAreaPercentage().
setPlotAreaPercentageWidth
void PlotSceneWidget::setPlotAreaPercentageWidth (double widthPercent) [slot]
References setPlotAreaPercentage().
setPlotAreaTopLeftPercentage
void PlotSceneWidget::setPlotAreaTopLeftPercentage (double widthPercent, double heightPercent) [slot]
One may want the plot to occupy only a portion of the scene, in order to place other elements or drawings in the same scene. With this method you configure the top left of the rectangle containing the plot. The widthPercent and heightPercent parameters are floating point values between 0 and 1 and represent the percentage of the width and height of the sceneRect to be considered in order to place the top left point of the plot rectangle.
If the sceneRect width is 200 and widthPercent is 0.1, then the top left x coordinate will be 20.
Parameters
widthPercent a number between 0 and 1 representing the percentage of the scene rect width to be considered in order to place the x coordinate of the top left point of the plot area.
heightPercent a number between 0 and 1 with the same meaning of widthPercent, but referred to the scene rect height
See also
setPlotAreaPercentage
The default values are 0.0 for both arguments, so that the plot area coincides with the scene()->sceneRect() rectangle.
References boundsChanged(), perr, and recalculatePlotRect().
Referenced by setPlotAreaTopLeftXPercentage(), and setPlotAreaTopLeftYPercentage().
setPlotAreaTopLeftXPercentage
void PlotSceneWidget::setPlotAreaTopLeftXPercentage (double xPercent) [slot]
References setPlotAreaTopLeftPercentage().
setPlotAreaTopLeftYPercentage
void PlotSceneWidget::setPlotAreaTopLeftYPercentage (double yPercent) [slot]
References setPlotAreaTopLeftPercentage().
setRefreshPeriod
void PlotSceneWidget::setRefreshPeriod (int period) [slot]
Parameters
period the interval, in milliseconds of the internal timer.
The period must be greater than 0. If zero or a negative value is passed, then the internal timer is stopped and destroyed. When invoked with a value greater than zero, an internal refresh timer is created, with objectName `refreshTimer`, its interval is set to period and the timer is started. At each timeout, the scene is refreshed. The period must be as fast as to ensure that the fastest item in the scene is updated in time.
See also
setManualSceneUpdate
manualSceneUpdate
refreshPeriod
setScaleSceneOnMouseScroll
void PlotSceneWidget::setScaleSceneOnMouseScroll (bool en) [slot]
Parameters
en true enable scene scaling
en false disable scene scaling
setScaleSceneOnResizeEnabled
void PlotSceneWidget::setScaleSceneOnResizeEnabled (bool en) [slot]
Read setScaleSceneOnResizeEnabled documentation for details.
Parameters
en true the scene is resized when the PlotSceneWidget is resized, until the user scrolls on the plot to scale the scene or the scene is scaled programmatically.
en false the scene is not fitted in the view when the view (i.e. PlotSceneWidget) is resized.
See also
scaleSceneOnResizeEnabled
setSceneRectToWidgetGeometry
void PlotSceneWidget::setSceneRectToWidgetGeometry (bool en) [slot]
The default is enabled. On first show event the scene rect is initialized to the viewport rect. The scene rect can be changed later. This property is read only at the first show event: it must be changed before first show event (i.e. right after object construction).
See also
sceneRectToWidgetGeometry
setScrollBarsEnabled
void PlotSceneWidget::setScrollBarsEnabled (bool en) [slot]
setSettingsKey()
void PlotSceneWidget::setSettingsKey (const QString & key)
For instance, it may be the associated device name or attribute or anything else needed to distinguish this particular plot from the other plots which may be present in the same application or another one.
setSmoothPixmapTransform
void PlotSceneWidget::setSmoothPixmapTransform (bool enable) [slot]
settingsKey()
QString PlotSceneWidget::settingsKey () const
setXAxisAutoscaleEnabled
void PlotSceneWidget::setXAxisAutoscaleEnabled (bool en) [slot]
calls xScaleItem()->setAxisAutoscaleEnabled(en)
References ScaleItem::setAxisAutoscaleEnabled(), and xScaleItem().
setXAxisLabelsOutsideCanvas
void PlotSceneWidget::setXAxisLabelsOutsideCanvas (bool outside) [slot]
This is useful when the x axis is placed at the bottom.
References ScaleItem::setAxisLabelsOutsideCanvas(), and xScaleItem().
setXAxisLowerBound
void PlotSceneWidget::setXAxisLowerBound (double xlb) [slot]
References ScaleItem::setLowerBound(), and xScaleItem().
setXAxisUpperBound
void PlotSceneWidget::setXAxisUpperBound (double xub) [slot]
References ScaleItem::setUpperBound(), and xScaleItem().
setXScaleEnabled
void PlotSceneWidget::setXScaleEnabled (bool en) [slot]
References boundsChanged(), and ScaleItem::xBottom.
setYAxisAutoscaleEnabled
void PlotSceneWidget::setYAxisAutoscaleEnabled (bool en) [slot]
calls xScaleItem()->setAxisAutoscaleEnabled(en)
References ScaleItem::setAxisAutoscaleEnabled(), and yScaleItem().
setYAxisLabelsOutsideCanvas
void PlotSceneWidget::setYAxisLabelsOutsideCanvas (bool outside) [slot]
This is useful when the y axis is placed at the left.
References ScaleItem::setAxisLabelsOutsideCanvas(), and yScaleItem().
setYAxisLowerBound
void PlotSceneWidget::setYAxisLowerBound (double ylb) [slot]
References ScaleItem::setLowerBound(), and yScaleItem().
setYAxisUpperBound
void PlotSceneWidget::setYAxisUpperBound (double yub) [slot]
References ScaleItem::setUpperBound(), and yScaleItem().
setYScaleEnabled
void PlotSceneWidget::setYScaleEnabled (bool en) [slot]
References boundsChanged(), and ScaleItem::yLeft.
showEvent()
void PlotSceneWidget::showEvent (QShowEvent * event) [protected]
References boundsChanged(), event(), and notifyPlotAreaChanged().
smoothPixmapTransform()
bool PlotSceneWidget::smoothPixmapTransform () const
transform()
double PlotSceneWidget::transform (const double x, ScaleItem * scaleItem) const
Parameters
x the value of the point on the ScaleItem axis
scaleItem the axis on which to make the calculation.
Returns
a coordinate in scene coordinates, representing the x axis point mapped into a point in the scene coordinate
References ScaleItem::canvasHeight, ScaleItem::canvasWidth, ScaleItem::Horizontal, ScaleItem::lowerBound, ScaleItem::orientation(), perr, scaleItem(), and ScaleItem::upperBound.
Referenced by DotsPainter::draw(), HistogramPainter::draw(), LinePainter::draw(), and StepsPainter::draw().
viewScaleChanged [1/2]
void PlotSceneWidget::viewScaleChanged (double dx, double dy) [signal]
Signal notifying that the scale factors of the view have changed
Parameters
dx the m11 transform matrix value
dy the m22 transform matrix value
Referenced by notifyPlotAreaChanged().
viewScaleChanged [2/2]
void PlotSceneWidget::viewScaleChanged (double scale) [signal]
Notifies that the scale factors have changed. The operations performed by the PlotSceneWidget and its zoomer scale the view by the same factor in order to keep the aspect ratio. So this method is provided, with a single scale parameter.
Note
If m11 differs from m22, then their mean is calculated and the mean value is emitted.
vScrollBarValueChanged
void PlotSceneWidget::vScrollBarValueChanged (int value) [protected], [slot]
Parameters
value the value of the scrollbar as provided by the verticalScrollBar
References PlotGeometryEventListener::scrollBarChanged().
wheelEvent()
void PlotSceneWidget::wheelEvent (QWheelEvent * event) [protected]
References scale().
xAxisAutoscaleEnabled()
bool PlotSceneWidget::xAxisAutoscaleEnabled () const
Returns
xScaleItem()->axisAutoscaleEnabled()
References ScaleItem::axisAutoscaleEnabled, and xScaleItem().
xAxisLabelsOutsideCanvas()
bool PlotSceneWidget::xAxisLabelsOutsideCanvas () const
If set to true, draws the axis labels outside the rectangle where the curves are drawn.
References ScaleItem::axisLabelsOutsideCanvas, and xScaleItem().
xAxisLowerBound()
double PlotSceneWidget::xAxisLowerBound () const
Returns
xScaleItem->lowerBound
References ScaleItem::lowerBound, and xScaleItem().
xAxisUpperBound()
double PlotSceneWidget::xAxisUpperBound () const
Returns
xScaleItem->upperBound
References ScaleItem::upperBound, and xScaleItem().
xScaleEnabled()
bool PlotSceneWidget::xScaleEnabled () const
References ScaleItem::xBottom.
xScaleItem()
 ScaleItem * PlotSceneWidget::xScaleItem () const
Returns
the x bottom scale item, if not removed programmatically, NULL otherwise.
References ScaleItem::xBottom.
Referenced by addCurve(), addLineCurve(), defaultXAxisOriginPosPercentage(), DotsPainter::draw(), HistogramPainter::draw(), StepsPainter::draw(), invTransform(), saveData(), setDefaultXAxisOriginPosPercentage(), setXAxisAutoscaleEnabled(), setXAxisLabelsOutsideCanvas(), setXAxisLowerBound(), setXAxisUpperBound(), xAxisAutoscaleEnabled(), xAxisLabelsOutsideCanvas(), xAxisLowerBound(), and xAxisUpperBound().
yAxisAutoscaleEnabled()
bool PlotSceneWidget::yAxisAutoscaleEnabled () const
Returns
yScaleItem()->axisAutoscaleEnabled()
References ScaleItem::axisAutoscaleEnabled, and yScaleItem().
yAxisLabelsOutsideCanvas()
bool PlotSceneWidget::yAxisLabelsOutsideCanvas () const
If set to true, draws the axis labels outside the rectangle where the curves are drawn.
References ScaleItem::axisLabelsOutsideCanvas, and yScaleItem().
yAxisLowerBound()
double PlotSceneWidget::yAxisLowerBound () const
Returns
yScaleItem->lowerBound
References ScaleItem::lowerBound, and yScaleItem().
yAxisUpperBound()
double PlotSceneWidget::yAxisUpperBound () const
Returns
yScaleItem->upperBound
References ScaleItem::upperBound, and yScaleItem().
yScaleEnabled()
bool PlotSceneWidget::yScaleEnabled () const
References ScaleItem::yLeft.
yScaleItem()
 ScaleItem * PlotSceneWidget::yScaleItem () const
Returns
the y left scale item, if not removed programmatically, NULL otherwise.
References ScaleItem::yLeft.
Referenced by addCurve(), addLineCurve(), defaultYAxisOriginPosPercentage(), HistogramPainter::draw(), invTransform(), setDefaultYAxisOriginPosPercentage(), setYAxisAutoscaleEnabled(), setYAxisLabelsOutsideCanvas(), setYAxisLowerBound(), setYAxisUpperBound(), yAxisAutoscaleEnabled(), yAxisLabelsOutsideCanvas(), yAxisLowerBound(), and yAxisUpperBound().
zoomer()
 QGraphicsZoomer * PlotSceneWidget::zoomer () const
zoomLevel()
int PlotSceneWidget::zoomLevel () const
The minimum value returned by this call is 1 and it means that no zoom is currently applied. A value of 2 means that the plot has been zoomed 1 time, a value of 3 means that the plot has been zoomed 2 times and so on.
Returns
the zoom level: 1 means no zoom, 2 means zoomed once and so on...
Property Documentation
backgroundColor
QColor PlotSceneWidget::backgroundColor [read], [write]
cacheBackground
bool PlotSceneWidget::cacheBackground [read], [write]
defaultXAxisOriginPosPercentage
double PlotSceneWidget::defaultXAxisOriginPosPercentage [read], [write]
defaultYAxisOriginPosPercentage
double PlotSceneWidget::defaultYAxisOriginPosPercentage [read], [write]
dontAdjustForAntialiasing
bool PlotSceneWidget::dontAdjustForAntialiasing [read], [write]
dontSavePainterState
bool PlotSceneWidget::dontSavePainterState [read], [write]
legendVisible
bool PlotSceneWidget::legendVisible [read], [write]
manualSceneUpdate
bool PlotSceneWidget::manualSceneUpdate [read], [write]
modifiedPaintEvent
bool PlotSceneWidget::modifiedPaintEvent [read], [write]
mouseZoomEnabled
bool PlotSceneWidget::mouseZoomEnabled [read], [write]
painterAntiAlias
bool PlotSceneWidget::painterAntiAlias [read], [write]
painterHQGLAntiAlias
bool PlotSceneWidget::painterHQGLAntiAlias [read], [write]
plotAreaPercentageHeight
double PlotSceneWidget::plotAreaPercentageHeight [read], [write]
plotAreaPercentageWidth
double PlotSceneWidget::plotAreaPercentageWidth [read], [write]
plotAreaTopLeftXPercentage
double PlotSceneWidget::plotAreaTopLeftXPercentage [read], [write]
plotAreaTopLeftYPercentage
double PlotSceneWidget::plotAreaTopLeftYPercentage [read], [write]
refreshPeriod
int PlotSceneWidget::refreshPeriod [read], [write]
scaleSceneOnResizeEnabled
bool PlotSceneWidget::scaleSceneOnResizeEnabled [read], [write]
scrollBarsEnabled
bool PlotSceneWidget::scrollBarsEnabled [read], [write]
smoothPixmapTransform
bool PlotSceneWidget::smoothPixmapTransform [read], [write]
xScaleEnabled
bool PlotSceneWidget::xScaleEnabled [read], [write]
yScaleEnabled
bool PlotSceneWidget::yScaleEnabled [read], [write]
The documentation for this class was generated from the following files:
 plotscenewidget.h
 moc_plotscenewidget.cpp
 plotscenewidget.cpp