AxesDataModel Class Reference
#include <axesdatamodel.h>
Public Types
enum Columns { ColName = 0,
ColYAxis,
ColumnCount
 }
Public Member Functions
AxesDataModel (QObject *parent)
int rowCount (const QModelIndex &parent) const
int columnCount (const QModelIndex &parent) const
QVariant data (const QModelIndex &index, int role) const
bool setData (const QModelIndex &index, const QVariant &value, int role)
QVariant headerData (int section, Qt::Orientation orientation, int role) const
bool insertRows (int row, int count, const QModelIndex &parent=QModelIndex())
Qt::ItemFlags flags (const QModelIndex &index) const
QList< CurveOptions > getData () const
Member Enumeration Documentation
enum AxesDataModel::Columns
Enumerator
ColName
ColYAxis
ColumnCount
Constructor & Destructor Documentation
AxesDataModel::AxesDataModel (QObject * parent)
Member Function Documentation
int AxesDataModel::columnCount (const QModelIndex & parent) const
References ColumnCount.
QVariant AxesDataModel::data (const QModelIndex & index, int role) const
References ColName, ColYAxis, CurveOptions::name, CurveOptions::shortName(), and CurveOptions::yAxisName.
Referenced by TreeViewAxes::addItem().
Qt::ItemFlags AxesDataModel::flags (const QModelIndex & index) const
QList< CurveOptions > AxesDataModel::getData () const
Referenced by TreeViewAxes::getCurveOptions().
QVariant AxesDataModel::headerData (int section, Qt::Orientation orientation, int role) const
bool AxesDataModel::insertRows (int row, int count, const QModelIndex & parent = QModelIndex())
int AxesDataModel::rowCount (const QModelIndex & parent) const
Referenced by TreeViewAxes::addItem().
bool AxesDataModel::setData (const QModelIndex & index, const QVariant & value, int role)
References ColName, ColYAxis, CurveOptions::name, perr, and CurveOptions::yAxisName.
Referenced by TreeViewAxes::addItem().
The documentation for this class was generated from the following files:
axesdatamodel.h
axesdatamodel.cpp