AxisConfWidget Class Reference
#include <axisconfwidget.h>
Signals
void addScale (ScaleWidget::Position pos)
void removeScale (const QString &name)
void applyOptionsSignal (const QList< CurveOptions > &)
Public Member Functions
AxisConfWidget (QWidget *parent=0)
void setAxisCount (int c, ScaleOrientation::Type o=ScaleOrientation::Vertical)
int axisCount (ScaleOrientation::Type o=ScaleOrientation::Vertical) const
void addItem (const QString &src)
void addConfigurableObjects (const QString &groupName, const QList< QObject * >o)
Constructor & Destructor Documentation
AxisConfWidget::AxisConfWidget (QWidget * parent = 0) [explicit]
References addScale(), removeScale(), and AxisConfWidgetPrivate::tvAxes.
Member Function Documentation
void AxisConfWidget::addConfigurableObjects (const QString & groupName, const QList< QObject * > o)
References QtAbstractPropertyBrowser::addProperty(), addScale(), applyOptionsSignal(), TreeViewAxes::axisCount(), ScaleWidget::Bottom, TreeViewAxes::ColYAxis, TreeViewAxes::getCurveOptions(), ScaleOrientation::Horizontal, ScaleWidget::Left, removeScale(), ScaleWidget::Right, TreeViewAxes::setAxisCount(), QtTreePropertyBrowser::setExpanded(), QtAbstractPropertyBrowser::setFactoryForManager(), ObjectPropertyManager::setObjects(), ScaleWidget::Top, QtAbstractPropertyBrowser::topLevelItems(), AxisConfWidgetPrivate::tvAxes, and ScaleOrientation::Vertical.
Referenced by ExtScalePlotSceneWidget::addScale(), and ExtScalePlotSceneWidget::onDataMinMaxChanged().
void AxisConfWidget::addItem (const QString & src)
References TreeViewAxes::addItem(), and AxisConfWidgetPrivate::tvAxes.
Referenced by ExtScalePlotSceneWidget::onDataMinMaxChanged().
void AxisConfWidget::addScale (ScaleWidget::Position pos) [signal]
Referenced by addConfigurableObjects(), and AxisConfWidget().
void AxisConfWidget::applyOptionsSignal (const QList< CurveOptions > &) [signal]
Referenced by addConfigurableObjects().
int AxisConfWidget::axisCount (ScaleOrientation::Type o = ScaleOrientation::Vertical) const
References TreeViewAxes::axisCount(), and AxisConfWidgetPrivate::tvAxes.
void AxisConfWidget::removeScale (const QString & name) [signal]
Referenced by addConfigurableObjects(), and AxisConfWidget().
void AxisConfWidget::setAxisCount (int c, ScaleOrientation::Type o = ScaleOrientation::Vertical)
References TreeViewAxes::setAxisCount(), and AxisConfWidgetPrivate::tvAxes.
Referenced by ExtScalePlotSceneWidget::onDataMinMaxChanged().
The documentation for this class was generated from the following files:
axisconfwidget.h
axisconfwidget.cpp