QtVariantProperty Class Reference
The QtVariantProperty class is a convenience class handling QVariant based properties.
#include <qtvariantproperty.h>
Public Member Functions
~QtVariantProperty ()
QVariant value () const
QVariant attributeValue (const QString &attribute) const
int valueType () const
int propertyType () const
virtual bool compare (QtProperty *otherProperty) const
void setValue (const QVariant &value)
void setAttribute (const QString &attribute, const QVariant &value)
Protected Member Functions
QtVariantProperty (QtVariantPropertyManager *manager)
Friends
class QtVariantPropertyManager
Detailed Description
QtVariantProperty provides additional API: A property's type, value type, attribute values and current value can easily be retrieved using the propertyType(), valueType(), attributeValue() and value() functions respectively. In addition, the attribute values and the current value can be set using the corresponding setValue() and setAttribute() functions.
For example, instead of writing:
QtVariantPropertyManager *variantPropertyManager;
QtProperty *property;
variantPropertyManager->setValue(property, 10);
you can write:
QtVariantPropertyManager *variantPropertyManager;
QtVariantProperty *property;
property->setValue(10);
QtVariantProperty instances can only be created by the QtVariantPropertyManager class.
See also
QtProperty, QtVariantPropertyManager, QtVariantEditorFactory
Constructor & Destructor Documentation
QtVariantProperty::~QtVariantProperty ()
Destroys this property.
See also
QtProperty::~QtProperty()
QtVariantProperty::QtVariantProperty (QtVariantPropertyManager * manager) [protected]
Creates a variant property using the given manager.
Do not use this constructor to create variant property instances; use the QtVariantPropertyManager::addProperty() function instead. This constructor is used internally by the QtVariantPropertyManager::createProperty() function.
See also
QtVariantPropertyManager
Member Function Documentation
QVariant QtVariantProperty::attributeValue (const QString & attribute) const
Returns this property's value for the specified attribute.
QtVariantPropertyManager provides a couple of related functions: {QtVariantPropertyManager::attributes()}{attributes()} and {QtVariantPropertyManager::attributeType()}{attributeType()}.
See also
setAttribute()
References QtVariantPropertyManager::attributeValue(), and QtVariantPropertyPrivate::manager.
Referenced by QtVariantPropertyManager::addProperty().
bool QtVariantProperty::compare (QtProperty * otherProperty) const [virtual]
Returns True if this property is equal to otherProperty
The list of parent or sub properties are not considered in the comparison.
Reimplemented from QtProperty .
References QtProperty::compare(), value(), and valueType().
int QtVariantProperty::propertyType () const
Returns this property's type.
QtVariantPropertyManager provides several related functions: {QtVariantPropertyManager::enumTypeId()}{enumTypeId()}, {QtVariantPropertyManager::flagTypeId()}{flagTypeId()} and {QtVariantPropertyManager::groupTypeId()}{groupTypeId()}.
See also
valueType()
References QtVariantPropertyPrivate::manager, and QtVariantPropertyManager::propertyType().
Referenced by QtVariantPropertyManager::addProperty().
void QtVariantProperty::setAttribute (const QString & attribute, const QVariant & value)
Sets the attribute of property to value.
QtVariantPropertyManager provides the related {QtVariantPropertyManager::setAttribute()}{setAttribute()} function.
See also
attributeValue()
References QtVariantPropertyPrivate::manager, and QtVariantPropertyManager::setAttribute().
void QtVariantProperty::setValue (const QVariant & value)
Sets the value of this property to value.
The specified value must be of the type returned by valueType(), or of a type that can be converted to valueType() using the QVariant::canConvert() function; otherwise this function does nothing.
See also
value()
References QtVariantPropertyPrivate::manager, and QtVariantPropertyManager::setValue().
Referenced by ObjectPropertyManager::setObjects().
QVariant QtVariantProperty::value () const
Returns the property's current value.
See also
valueType(), setValue()
References QtVariantPropertyPrivate::manager, and QtVariantPropertyManager::value().
Referenced by QtVariantPropertyManager::addProperty(), and compare().
int QtVariantProperty::valueType () const
Returns the type of this property's value.
See also
propertyType()
References QtVariantPropertyPrivate::manager, and QtVariantPropertyManager::valueType().
Referenced by compare().
Friends And Related Function Documentation
friend class QtVariantPropertyManager [friend]
The documentation for this class was generated from the following files:
qtvariantproperty.h
qtvariantproperty.cpp