QtCursorEditorFactory Class Reference
The QtCursorEditorFactory class provides QComboBox widgets for properties created by QtCursorPropertyManager objects.
#include <qteditorfactory.h>
Public Member Functions
QtCursorEditorFactory (QObject *parent=0)
~QtCursorEditorFactory ()
Protected Member Functions
void connectPropertyManager (QtCursorPropertyManager *manager)
QWidget * createEditor (QtCursorPropertyManager *manager, QtProperty *property, QWidget *parent)
void disconnectPropertyManager (QtCursorPropertyManager *manager)
Additional Inherited Members
Detailed Description
See also
QtAbstractEditorFactory, QtCursorPropertyManager
Constructor & Destructor Documentation
QtCursorEditorFactory::QtCursorEditorFactory (QObject * parent = 0)
Creates a factory with the given parent.
References QtAbstractEditorFactory< PropertyManager >::addPropertyManager(), QtCursorEditorFactoryPrivate::m_enumEditorFactory, and QtCursorEditorFactoryPrivate::m_enumPropertyManager.
QtCursorEditorFactory::~QtCursorEditorFactory ()
Destroys this factory, and all the widgets it has created.
Member Function Documentation
void QtCursorEditorFactory::connectPropertyManager (QtCursorPropertyManager * manager) [protected], [virtual]
Connects this factory to the given manager's signals. The PropertyManager type is a template argument class, and represents the chosen QtAbstractPropertyManager subclass.
This function is used internally by the addPropertyManager() function, and makes it possible to update an editing widget when the associated property's data changes. This is typically done in custom slots responding to the signals emitted by the property's manager, e.g. QtIntPropertyManager::valueChanged() and QtIntPropertyManager::rangeChanged().
See also
propertyManagers(), disconnectPropertyManager()
Implements QtAbstractEditorFactory< QtCursorPropertyManager > .
QWidget * QtCursorEditorFactory::createEditor (QtCursorPropertyManager * manager, QtProperty * property, QWidget * parent) [protected], [virtual]
Creates an editing widget with the given parent for the specified property created by the given manager. The PropertyManager type is a template argument class, and represents the chosen QtAbstractPropertyManager subclass.
This function must be implemented in derived classes: It is recommended to store a pointer to the widget and map it to the given property, since the widget must be updated whenever the associated property's data changes. This is typically done in custom slots responding to the signals emitted by the property's manager, e.g. QtIntPropertyManager::valueChanged() and QtIntPropertyManager::rangeChanged().
See also
connectPropertyManager()
Implements QtAbstractEditorFactory< QtCursorPropertyManager > .
References QtAbstractPropertyManager::addProperty(), QtAbstractEditorFactoryBase::createEditor(), QtCursorEditorFactoryPrivate::m_editorToEnum, QtCursorEditorFactoryPrivate::m_enumEditorFactory, QtCursorEditorFactoryPrivate::m_enumPropertyManager, QtCursorEditorFactoryPrivate::m_enumToEditors, QtCursorEditorFactoryPrivate::m_enumToProperty, QtCursorEditorFactoryPrivate::m_propertyToEnum, QtProperty::propertyName(), QtEnumPropertyManager::setEnumIcons(), QtEnumPropertyManager::setEnumNames(), QtEnumPropertyManager::setValue(), and QtCursorPropertyManager::value().
void QtCursorEditorFactory::disconnectPropertyManager (QtCursorPropertyManager * manager) [protected], [virtual]
Disconnects this factory from the given manager's signals. The PropertyManager type is a template argument class, and represents the chosen QtAbstractPropertyManager subclass.
This function is used internally by the removePropertyManager() function.
See also
propertyManagers(), connectPropertyManager()
Implements QtAbstractEditorFactory< QtCursorPropertyManager > .
The documentation for this class was generated from the following files:
qteditorfactory.h
qteditorfactory.cpp