QtFontEditWidget Class Reference
Public Slots
void setValue (const QFont &value)
Signals
void valueChanged (const QFont &value)
Public Member Functions
QtFontEditWidget (QWidget *parent)
bool eventFilter (QObject *obj, QEvent *ev)
Protected Member Functions
void paintEvent (QPaintEvent *)
Constructor & Destructor Documentation
QtFontEditWidget::QtFontEditWidget (QWidget * parent)
References QtPropertyBrowserUtils::fontValuePixmap(), QtPropertyBrowserUtils::fontValueText(), and setupTreeViewEditorMargin().
Member Function Documentation
bool QtFontEditWidget::eventFilter (QObject * obj, QEvent * ev)
void QtFontEditWidget::paintEvent (QPaintEvent *) [protected]
void QtFontEditWidget::setValue (const QFont & value) [slot]
References QtPropertyBrowserUtils::fontValuePixmap(), QtPropertyBrowserUtils::fontValueText(), and valueChanged().
Referenced by QtFontEditorFactory::createEditor().
void QtFontEditWidget::valueChanged (const QFont & value) [signal]
Referenced by setValue().
The documentation for this class was generated from the following file:
qteditorfactory.cpp