CurveConfigurator Class Reference
#include <curveconfigurator.h>
Public Member Functions
CurveConfigurator ()
void configure (SceneCurve *c, const CurveOptions &options)
CurveOptions getOptions (const SceneCurve *c) const
This method returns a CurveOptions structure initialized from the current curve.
Constructor & Destructor Documentation
CurveConfigurator::CurveConfigurator ()
Member Function Documentation
void CurveConfigurator::configure (SceneCurve * c, const CurveOptions & options)
References ItemPainterInterface::color(), SceneCurve::curveItem(), SceneCurve::Dot, SceneCurve::Histogram, CurveItem::installItemPainterInterface(), CurveItem::itemPainter(), SceneCurve::Line, CurveOptions::pen, perr, CurveItem::removeItemPainterInterface(), ItemPainterInterface::setColor(), ItemPainterInterface::setWidth(), SceneCurve::Step, CurveOptions::style, ItemPainterInterface::style(), and ItemPainterInterface::width().
Referenced by SceneCurve::setColor(), SceneCurve::setType(), and SceneCurve::setWidth().
CurveOptions CurveConfigurator::getOptions (const SceneCurve * c) const
Returns
a CurveOptions initialized from the curve used in the CurveConfigurator constructor.
References ItemPainterInterface::color(), SceneCurve::curveItem(), SceneCurve::name(), ItemPainterInterface::pen(), ItemPainterInterface::style(), and ItemPainterInterface::width().
Referenced by SceneCurve::color(), SceneCurve::setColor(), SceneCurve::setType(), and SceneCurve::setWidth().
The documentation for this class was generated from the following files:
curveconfigurator.h
curveconfigurator.cpp