qrc_qgraphicsplotplugin.cpp File Reference
Macros
#define QT_RCC_PREPEND_NAMESPACE(name) name
#define QT_RCC_MANGLE_NAMESPACE(name) name
Functions
bool qRegisterResourceData (int, const unsigned char *, const unsigned char *, const unsigned char *)
bool qUnregisterResourceData (int, const unsigned char *, const unsigned char *, const unsigned char *)
int QT_RCC_MANGLE_NAMESPACE() qInitResources_qgraphicsplotplugin ()
int QT_RCC_MANGLE_NAMESPACE() qCleanupResources_qgraphicsplotplugin ()
Variables
static const unsigned char qt_resource_data []
static const unsigned char qt_resource_name []
static const unsigned char qt_resource_struct []
Macro Definition Documentation
QT_RCC_MANGLE_NAMESPACE
#define QT_RCC_MANGLE_NAMESPACE(name) name
QT_RCC_PREPEND_NAMESPACE
#define QT_RCC_PREPEND_NAMESPACE(name) name
Function Documentation
qCleanupResources_qgraphicsplotplugin()
int QT_RCC_MANGLE_NAMESPACE() qCleanupResources_qgraphicsplotplugin ()
References QT_RCC_PREPEND_NAMESPACE, qt_resource_data, qt_resource_name, qt_resource_struct, and qUnregisterResourceData().
qInitResources_qgraphicsplotplugin()
int QT_RCC_MANGLE_NAMESPACE() qInitResources_qgraphicsplotplugin ()
References qRegisterResourceData(), QT_RCC_PREPEND_NAMESPACE, qt_resource_data, qt_resource_name, and qt_resource_struct.
qRegisterResourceData()
bool qRegisterResourceData (int , const unsigned char * , const unsigned char * , const unsigned char *)
Referenced by qInitResources_qgraphicsplotplugin().
qUnregisterResourceData()
bool qUnregisterResourceData (int , const unsigned char * , const unsigned char * , const unsigned char *)
Referenced by qCleanupResources_qgraphicsplotplugin().
Variable Documentation
qt_resource_data
const unsigned char qt_resource_data[] [static]
Referenced by qCleanupResources_qgraphicsplotplugin(), and qInitResources_qgraphicsplotplugin().
qt_resource_name
const unsigned char qt_resource_name[] [static]
Initial value:
= {
  
  0x0,0x7,
  0x7,0xf,0x38,0x93,
  0x0,0x70,
  0x0,0x69,0x0,0x78,0x0,0x6d,0x0,0x61,0x0,0x70,0x0,0x73,
    
  0x0,0x11,
  0xa,0xc7,0x2,0xc7,
  0x0,0x76,
  0x0,0x65,0x0,0x72,0x0,0x74,0x0,0x69,0x0,0x63,0x0,0x61,0x0,0x6c,0x0,0x73,0x0,0x63,0x0,0x61,0x0,0x6c,0x0,0x65,0x0,0x2e,0x0,0x70,0x0,0x6e,0x0,0x67,
  
    
  0x0,0x12,
  0x6,0x7a,0x38,0xa7,
  0x0,0x71,
  0x0,0x67,0x0,0x72,0x0,0x61,0x0,0x70,0x0,0x68,0x0,0x69,0x0,0x63,0x0,0x73,0x0,0x70,0x0,0x6c,0x0,0x6f,0x0,0x74,0x0,0x32,0x0,0x2e,0x0,0x70,0x0,0x6e,
  0x0,0x67,
    
  0x0,0x13,
  0x2,0xcc,0x62,0x87,
  0x0,0x68,
  0x0,0x6f,0x0,0x72,0x0,0x69,0x0,0x7a,0x0,0x6f,0x0,0x6e,0x0,0x74,0x0,0x61,0x0,0x6c,0x0,0x73,0x0,0x63,0x0,0x61,0x0,0x6c,0x0,0x65,0x0,0x2e,0x0,0x70,
  0x0,0x6e,0x0,0x67,
  
}
Referenced by qCleanupResources_qgraphicsplotplugin(), and qInitResources_qgraphicsplotplugin().
qt_resource_struct
const unsigned char qt_resource_struct[] [static]
Initial value:
= {
  
  0x0,0x0,0x0,0x0,0x0,0x2,0x0,0x0,0x0,0x1,0x0,0x0,0x0,0x1,
  
  0x0,0x0,0x0,0x0,0x0,0x2,0x0,0x0,0x0,0x3,0x0,0x0,0x0,0x2,
  
  0x0,0x0,0x0,0x66,0x0,0x0,0x0,0x0,0x0,0x1,0x0,0x0,0x2f,0x4f,
  
  0x0,0x0,0x0,0x3c,0x0,0x0,0x0,0x0,0x0,0x1,0x0,0x0,0x5,0x70,
  
  0x0,0x0,0x0,0x14,0x0,0x0,0x0,0x0,0x0,0x1,0x0,0x0,0x0,0x0,
}
Referenced by qCleanupResources_qgraphicsplotplugin(), and qInitResources_qgraphicsplotplugin().