qtpropertymanager.cpp File Reference
#include `qtpropertymanager.h`
*
#include `qtpropertybrowserutils_p.h`
*
#include <QtCore/QDateTime>
*
#include <QtCore/QLocale>
*
#include <QtCore/QMap>
*
#include <QtCore/QTimer>
*
#include <QIcon>
*
#include <QtCore/QMetaEnum>
*
#include <QFontDatabase>
*
#include <QStyleOption>
*
#include <QStyle>
*
#include <QApplication>
*
#include <QPainter>
*
#include <QLabel>
*
#include <QCheckBox>
*
#include <limits.h>
*
#include <float.h>
*
#include `moc_qtpropertymanager.cpp`
*
#include `qtpropertymanager.moc`
*
Classes
class QtMetaEnumWrapper
class QtMetaEnumProvider
class QtIntPropertyManagerPrivate
struct QtIntPropertyManagerPrivate::Data
class QtDoublePropertyManagerPrivate
struct QtDoublePropertyManagerPrivate::Data
class QtStringPropertyManagerPrivate
struct QtStringPropertyManagerPrivate::Data
class QtBoolPropertyManagerPrivate
class QtDatePropertyManagerPrivate
struct QtDatePropertyManagerPrivate::Data
class QtTimePropertyManagerPrivate
class QtDateTimePropertyManagerPrivate
class QtKeySequencePropertyManagerPrivate
class QtCharPropertyManagerPrivate
class QtLocalePropertyManagerPrivate
class QtPointPropertyManagerPrivate
class QtPointFPropertyManagerPrivate
struct QtPointFPropertyManagerPrivate::Data
class QtSizePropertyManagerPrivate
struct QtSizePropertyManagerPrivate::Data
class QtSizeFPropertyManagerPrivate
struct QtSizeFPropertyManagerPrivate::Data
class QtRectPropertyManagerPrivate
struct QtRectPropertyManagerPrivate::Data
class QtRectFPropertyManagerPrivate
struct QtRectFPropertyManagerPrivate::Data
class QtEnumPropertyManagerPrivate
struct QtEnumPropertyManagerPrivate::Data
class QtFlagPropertyManagerPrivate
struct QtFlagPropertyManagerPrivate::Data
class QtSizePolicyPropertyManagerPrivate
class QtFontPropertyManagerPrivate
class QtColorPropertyManagerPrivate
class QtCursorPropertyManagerPrivate
Functions
template<class PrivateData , class Value >
static void setSimpleMinimumData (PrivateData *data, const Value &minVal)
template<class PrivateData , class Value >
static void setSimpleMaximumData (PrivateData *data, const Value &maxVal)
template<class PrivateData , class Value >
static void setSizeMinimumData (PrivateData *data, const Value &newMinVal)
template<class PrivateData , class Value >
static void setSizeMaximumData (PrivateData *data, const Value &newMaxVal)
template<class SizeValue >
static SizeValue qBoundSize (const SizeValue &minVal, const SizeValue &val, const SizeValue &maxVal)
QSize qBound (QSize minVal, QSize val, QSize maxVal)
QSizeF qBound (QSizeF minVal, QSizeF val, QSizeF maxVal)
template<class Value , class PrivateData >
static Value getData (const QMap< const QtProperty *, PrivateData > &propertyMap, Value PrivateData::*data, const QtProperty *property, const Value &defaultValue=Value())
template<class Value , class PrivateData >
static Value getValue (const QMap< const QtProperty *, PrivateData > &propertyMap, const QtProperty *property, const Value &defaultValue=Value())
template<class Value , class PrivateData >
static Value getMinimum (const QMap< const QtProperty *, PrivateData > &propertyMap, const QtProperty *property, const Value &defaultValue=Value())
template<class Value , class PrivateData >
static Value getMaximum (const QMap< const QtProperty *, PrivateData > &propertyMap, const QtProperty *property, const Value &defaultValue=Value())
template<class ValueChangeParameter , class Value , class PropertyManager >
static void setSimpleValue (QMap< const QtProperty *, Value > &propertyMap, PropertyManager *manager, void(PropertyManager::*propertyChangedSignal)(QtProperty *), void(PropertyManager::*valueChangedSignal)(QtProperty *, ValueChangeParameter), QtProperty *property, const Value &val)
template<class ValueChangeParameter , class PropertyManagerPrivate , class PropertyManager , class Value >
static void setValueInRange (PropertyManager *manager, PropertyManagerPrivate *managerPrivate, void(PropertyManager::*propertyChangedSignal)(QtProperty *), void(PropertyManager::*valueChangedSignal)(QtProperty *, ValueChangeParameter), QtProperty *property, const Value &val, void(PropertyManagerPrivate::*setSubPropertyValue)(QtProperty *, ValueChangeParameter))
template<class ValueChangeParameter , class PropertyManagerPrivate , class PropertyManager , class Value >
static void setBorderValues (PropertyManager *manager, PropertyManagerPrivate *managerPrivate, void(PropertyManager::*propertyChangedSignal)(QtProperty *), void(PropertyManager::*valueChangedSignal)(QtProperty *, ValueChangeParameter), void(PropertyManager::*rangeChangedSignal)(QtProperty *, ValueChangeParameter, ValueChangeParameter), QtProperty *property, const Value &minVal, const Value &maxVal, void(PropertyManagerPrivate::*setSubPropertyRange)(QtProperty *, ValueChangeParameter, ValueChangeParameter, ValueChangeParameter))
template<class ValueChangeParameter , class PropertyManagerPrivate , class PropertyManager , class Value , class PrivateData >
static void setBorderValue (PropertyManager *manager, PropertyManagerPrivate *managerPrivate, void(PropertyManager::*propertyChangedSignal)(QtProperty *), void(PropertyManager::*valueChangedSignal)(QtProperty *, ValueChangeParameter), void(PropertyManager::*rangeChangedSignal)(QtProperty *, ValueChangeParameter, ValueChangeParameter), QtProperty *property, Value(PrivateData::*getRangeVal)() const, void(PrivateData::*setRangeVal)(ValueChangeParameter), const Value &borderVal, void(PropertyManagerPrivate::*setSubPropertyRange)(QtProperty *, ValueChangeParameter, ValueChangeParameter, ValueChangeParameter))
template<class ValueChangeParameter , class PropertyManagerPrivate , class PropertyManager , class Value , class PrivateData >
static void setMinimumValue (PropertyManager *manager, PropertyManagerPrivate *managerPrivate, void(PropertyManager::*propertyChangedSignal)(QtProperty *), void(PropertyManager::*valueChangedSignal)(QtProperty *, ValueChangeParameter), void(PropertyManager::*rangeChangedSignal)(QtProperty *, ValueChangeParameter, ValueChangeParameter), QtProperty *property, const Value &minVal)
template<class ValueChangeParameter , class PropertyManagerPrivate , class PropertyManager , class Value , class PrivateData >
static void setMaximumValue (PropertyManager *manager, PropertyManagerPrivate *managerPrivate, void(PropertyManager::*propertyChangedSignal)(QtProperty *), void(PropertyManager::*valueChangedSignal)(QtProperty *, ValueChangeParameter), void(PropertyManager::*rangeChangedSignal)(QtProperty *, ValueChangeParameter, ValueChangeParameter), QtProperty *property, const Value &maxVal)
static QList< QLocale::Country > countriesForLanguage (QLocale::Language language)
static QList< QLocale::Country > sortCountries (const QList< QLocale::Country > &countries)
static QIcon drawCheckBox (bool value)
Function Documentation
static QList<QLocale::Country> countriesForLanguage (QLocale::Language language) [static]
Referenced by sortCountries().
static QIcon drawCheckBox (bool value) [static]
Referenced by QtBoolPropertyManager::valueIcon().
template<class Value , class PrivateData > static Value getData (const QMap< const QtProperty *, PrivateData > & propertyMap, Value PrivateData::* data, const QtProperty * property, const Value & defaultValue = Value()) [static]
template<class Value , class PrivateData > static Value getMaximum (const QMap< const QtProperty *, PrivateData > & propertyMap, const QtProperty * property, const Value & defaultValue = Value()) [static]
template<class Value , class PrivateData > static Value getMinimum (const QMap< const QtProperty *, PrivateData > & propertyMap, const QtProperty * property, const Value & defaultValue = Value()) [static]
template<class Value , class PrivateData > static Value getValue (const QMap< const QtProperty *, PrivateData > & propertyMap, const QtProperty * property, const Value & defaultValue = Value()) [static]
QSize qBound (QSize minVal, QSize val, QSize maxVal)
References qBoundSize().
Referenced by setValueInRange().
QSizeF qBound (QSizeF minVal, QSizeF val, QSizeF maxVal)
References qBoundSize().
template<class SizeValue > static SizeValue qBoundSize (const SizeValue & minVal, const SizeValue & val, const SizeValue & maxVal) [static]
Referenced by qBound().
[setBorderValue(PropertyManager *manager, PropertyManagerPrivate *managerPrivate, void(PropertyManager::*propertyChangedSignal)(QtProperty *), void(PropertyManager::*valueChangedSignal)(QtProperty *, ValueChangeParameter), void(PropertyManager::*rangeChangedSignal)(QtProperty *, ValueChangeParameter, ValueChangeParameter), QtProperty *property, Value(PrivateData::*getRangeVal)() const, void(PrivateData::*setRangeVal)(ValueChangeParameter), const Value &borderVal, void(PropertyManagerPrivate::*setSubPropertyRange)(QtProperty *, ValueChangeParameter, ValueChangeParameter, ValueChangeParameter))]template<class ValueChangeParameter , class PropertyManagerPrivate , class PropertyManager , class Value , class PrivateData > static void setBorderValue (PropertyManager * manager, PropertyManagerPrivate * managerPrivate, void(PropertyManager::*)(QtProperty *) propertyChangedSignal, void(PropertyManager::*)(QtProperty *, ValueChangeParameter) valueChangedSignal, void(PropertyManager::*)(QtProperty *, ValueChangeParameter, ValueChangeParameter) rangeChangedSignal, QtProperty * property, Value(PrivateData::*)() const getRangeVal, void(PrivateData::*)(ValueChangeParameter) setRangeVal, const Value & borderVal, void(PropertyManagerPrivate::*)(QtProperty *, ValueChangeParameter, ValueChangeParameter, ValueChangeParameter) setSubPropertyRange) [static]
[setBorderValues(PropertyManager *manager, PropertyManagerPrivate *managerPrivate, void(PropertyManager::*propertyChangedSignal)(QtProperty *), void(PropertyManager::*valueChangedSignal)(QtProperty *, ValueChangeParameter), void(PropertyManager::*rangeChangedSignal)(QtProperty *, ValueChangeParameter, ValueChangeParameter), QtProperty *property, const Value &minVal, const Value &maxVal, void(PropertyManagerPrivate::*setSubPropertyRange)(QtProperty *, ValueChangeParameter, ValueChangeParameter, ValueChangeParameter))]template<class ValueChangeParameter , class PropertyManagerPrivate , class PropertyManager , class Value > static void setBorderValues (PropertyManager * manager, PropertyManagerPrivate * managerPrivate, void(PropertyManager::*)(QtProperty *) propertyChangedSignal, void(PropertyManager::*)(QtProperty *, ValueChangeParameter) valueChangedSignal, void(PropertyManager::*)(QtProperty *, ValueChangeParameter, ValueChangeParameter) rangeChangedSignal, QtProperty * property, const Value & minVal, const Value & maxVal, void(PropertyManagerPrivate::*)(QtProperty *, ValueChangeParameter, ValueChangeParameter, ValueChangeParameter) setSubPropertyRange) [static]
template<class ValueChangeParameter , class PropertyManagerPrivate , class PropertyManager , class Value , class PrivateData > static void setMaximumValue (PropertyManager * manager, PropertyManagerPrivate * managerPrivate, void(PropertyManager::*)(QtProperty *) propertyChangedSignal, void(PropertyManager::*)(QtProperty *, ValueChangeParameter) valueChangedSignal, void(PropertyManager::*)(QtProperty *, ValueChangeParameter, ValueChangeParameter) rangeChangedSignal, QtProperty * property, const Value & maxVal) [static]
template<class ValueChangeParameter , class PropertyManagerPrivate , class PropertyManager , class Value , class PrivateData > static void setMinimumValue (PropertyManager * manager, PropertyManagerPrivate * managerPrivate, void(PropertyManager::*)(QtProperty *) propertyChangedSignal, void(PropertyManager::*)(QtProperty *, ValueChangeParameter) valueChangedSignal, void(PropertyManager::*)(QtProperty *, ValueChangeParameter, ValueChangeParameter) rangeChangedSignal, QtProperty * property, const Value & minVal) [static]
template<class PrivateData , class Value > static void setSimpleMaximumData (PrivateData * data, const Value & maxVal) [static]
Referenced by QtIntPropertyManagerPrivate::Data::setMaximumValue(), QtDoublePropertyManagerPrivate::Data::setMaximumValue(), and QtDatePropertyManagerPrivate::Data::setMaximumValue().
template<class PrivateData , class Value > static void setSimpleMinimumData (PrivateData * data, const Value & minVal) [static]
Referenced by QtIntPropertyManagerPrivate::Data::setMinimumValue(), QtDoublePropertyManagerPrivate::Data::setMinimumValue(), and QtDatePropertyManagerPrivate::Data::setMinimumValue().
template<class ValueChangeParameter , class Value , class PropertyManager > static void setSimpleValue (QMap< const QtProperty *, Value > & propertyMap, PropertyManager * manager, void(PropertyManager::*)(QtProperty *) propertyChangedSignal, void(PropertyManager::*)(QtProperty *, ValueChangeParameter) valueChangedSignal, QtProperty * property, const Value & val) [static]
template<class PrivateData , class Value > static void setSizeMaximumData (PrivateData * data, const Value & newMaxVal) [static]
Referenced by QtSizePropertyManagerPrivate::Data::setMaximumValue(), and QtSizeFPropertyManagerPrivate::Data::setMaximumValue().
template<class PrivateData , class Value > static void setSizeMinimumData (PrivateData * data, const Value & newMinVal) [static]
Referenced by QtSizePropertyManagerPrivate::Data::setMinimumValue(), and QtSizeFPropertyManagerPrivate::Data::setMinimumValue().
template<class ValueChangeParameter , class PropertyManagerPrivate , class PropertyManager , class Value > static void setValueInRange (PropertyManager * manager, PropertyManagerPrivate * managerPrivate, void(PropertyManager::*)(QtProperty *) propertyChangedSignal, void(PropertyManager::*)(QtProperty *, ValueChangeParameter) valueChangedSignal, QtProperty * property, const Value & val, void(PropertyManagerPrivate::*)(QtProperty *, ValueChangeParameter) setSubPropertyValue) [static]
References qBound().
static QList<QLocale::Country> sortCountries (const QList< QLocale::Country > & countries) [static]
References countriesForLanguage().