QtSizePropertyManagerPrivate::Data Struct Reference
Public Member Functions
Data ()
QSize minimumValue () const
QSize maximumValue () const
void setMinimumValue (const QSize &newMinVal)
void setMaximumValue (const QSize &newMaxVal)
Public Attributes
QSize val
QSize minVal
QSize maxVal
Constructor & Destructor Documentation
QtSizePropertyManagerPrivate::Data::Data () [inline]
Member Function Documentation
QSize QtSizePropertyManagerPrivate::Data::maximumValue () const [inline]
Referenced by QtSizePropertyManager::setMaximum().
QSize QtSizePropertyManagerPrivate::Data::minimumValue () const [inline]
Referenced by QtSizePropertyManager::setMinimum().
void QtSizePropertyManagerPrivate::Data::setMaximumValue (const QSize & newMaxVal) [inline]
References setSizeMaximumData().
Referenced by QtSizePropertyManager::setMaximum().
void QtSizePropertyManagerPrivate::Data::setMinimumValue (const QSize & newMinVal) [inline]
References setSizeMinimumData().
Referenced by QtSizePropertyManager::setMinimum().
Member Data Documentation
QSize QtSizePropertyManagerPrivate::Data::maxVal
QSize QtSizePropertyManagerPrivate::Data::minVal
QSize QtSizePropertyManagerPrivate::Data::val
The documentation for this struct was generated from the following file:
qtpropertymanager.cpp