QtSizeFPropertyManagerPrivate::Data Struct Reference
Public Member Functions
Data ()
QSizeF minimumValue () const
QSizeF maximumValue () const
void setMinimumValue (const QSizeF &newMinVal)
void setMaximumValue (const QSizeF &newMaxVal)
Public Attributes
QSizeF val
QSizeF minVal
QSizeF maxVal
int decimals
Constructor & Destructor Documentation
QtSizeFPropertyManagerPrivate::Data::Data () [inline]
Member Function Documentation
QSizeF QtSizeFPropertyManagerPrivate::Data::maximumValue () const [inline]
Referenced by QtSizeFPropertyManager::setMaximum().
QSizeF QtSizeFPropertyManagerPrivate::Data::minimumValue () const [inline]
Referenced by QtSizeFPropertyManager::setMinimum().
void QtSizeFPropertyManagerPrivate::Data::setMaximumValue (const QSizeF & newMaxVal) [inline]
References setSizeMaximumData().
Referenced by QtSizeFPropertyManager::setMaximum().
void QtSizeFPropertyManagerPrivate::Data::setMinimumValue (const QSizeF & newMinVal) [inline]
References setSizeMinimumData().
Referenced by QtSizeFPropertyManager::setMinimum().
Member Data Documentation
int QtSizeFPropertyManagerPrivate::Data::decimals
Referenced by QtSizeFPropertyManager::decimals(), and QtSizeFPropertyManager::setDecimals().
QSizeF QtSizeFPropertyManagerPrivate::Data::maxVal
QSizeF QtSizeFPropertyManagerPrivate::Data::minVal
QSizeF QtSizeFPropertyManagerPrivate::Data::val
The documentation for this struct was generated from the following file:
qtpropertymanager.cpp