######################################################################
# Automatically generated by qmake (2.01a) Fri Mar 16 11:25:33 2012
######################################################################

include(/runtime/include/qtango4/qtango.pri)

DEFINES -= QT_NO_DEBUG_OUTPUT

TARGET = scalarqwt

# Input
HEADERS += \
    qwtplotw.h
FORMS += \
    qwtplotw.ui
SOURCES += main.cpp \
    qwtplotw.cpp

