######################################################################
# Automatically generated by qmake (2.01a) Fri Mar 16 11:25:33 2012
######################################################################

include(../examples.pro)

CONFIG += debug

QT += widgets

TEMPLATE = app
TARGET = scalar
DEPENDPATH += .

QMAKE_CXXFLAGS += -O2

# Input
HEADERS += \
    scalar.h
FORMS += \
    scalar.ui
SOURCES += main.cpp \
    scalar.cpp

LIBS += -L../.. -lqgraphicsplot$${VER_SUFFIX}
