######################################################################
# Automatically generated by qmake (2.01a) Fri Mar 16 11:25:33 2012
######################################################################

include(../examples.pro)

TEMPLATE = app
CONFIG += debug
TARGET = spectrum
DEPENDPATH += .
INCLUDEPATH += . ../../src ../../src/curve ../../src/axes

QMAKE_CXXFLAGS += -O2

# Input
HEADERS += xygscene.h
FORMS += xygscene.ui
SOURCES += main.cpp xygscene.cpp


